force-app/main/default/objects/ServiceTicket__c/ServiceTicket__c.object-meta.xml
<CustomObject>
    <label>Senha</label>
    <nameField>
        <displayFormat>{YY}{MM}-{000000}</displayFormat>
        <label>Nome do Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Senhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceTicket__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <description>Atividade</description>
    <label>Atividade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ActivityPriority__c.field-meta.xml
<CustomField>
    <fullName>ActivityPriority__c</fullName>
    <description>Prioridade da Atividade</description>
    <label>Prioridade da Atividade</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>Apelido do Cliente</description>
    <label>Apelido</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>Nome do Cliente</description>
    <label>Cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <description>CPF</description>
    <label>CPF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>ID Externo para Identificação do Registro na Base de Dados de Origem</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/GeographicAreaCode__c.field-meta.xml
<CustomField>
    <fullName>GeographicAreaCode__c</fullName>
    <description>Código da Área Geográfica - DDD</description>
    <label>DDD</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/InteractionID__c.field-meta.xml
<CustomField>
    <fullName>InteractionID__c</fullName>
    <description>ID da Interação (Serviço) do Cliente</description>
    <label>ID do Serviço</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/InteractionName__c.field-meta.xml
<CustomField>
    <fullName>InteractionName__c</fullName>
    <description>Nome da Interação (Serviço) do Cliente</description>
    <label>Serviço</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/NetworkNumber__c.field-meta.xml
<CustomField>
    <fullName>NetworkNumber__c</fullName>
    <description>Número do Celular</description>
    <label>Celular</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Prioridade de Atendimento</description>
    <label>Prioridade</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SegmentID__c.field-meta.xml
<CustomField>
    <fullName>SegmentID__c</fullName>
    <description>ID da Segmentação do Cliente</description>
    <label>ID da Segmentação</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SegmentName__c.field-meta.xml
<CustomField>
    <fullName>SegmentName__c</fullName>
    <description>Nome da Segmentação do Cliente</description>
    <label>Segmentação</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SpecialNeeds__c.field-meta.xml
<CustomField>
    <fullName>SpecialNeeds__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Necessidades Especiais</description>
    <label>Necessidades Especiais</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>Em Espera</label>
            </value>
            <value>
                <fullName>In Service</fullName>
                <label>Em Atendimento</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <description>Código da Loja</description>
    <label>Loja</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/TicketId__c.field-meta.xml
<CustomField>
    <fullName>TicketId__c</fullName>
    <description>Número da Senha</description>
    <label>Senha</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Loja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Código da Loja</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSMTicketsEngine.cls
/*
    ---------------------------------------------------
    @author - Márcio Las
    @company - Telefonica  
    @date - 28/03/2022
    @description - Class Engine for SSMTickets

    @PTI3946-120 - 06/11/2023 - Márcio Las
    @description - Recuperação das Senhas de Atendimento | Salesforce x GSS
    ---------------------------------------------------
*/
public with sharing class SSMTicketsEngine {
    private static final Integer GENERIC_ERROR_MESSAGE = 699;
    private static final String CUSTOM_SETTING_NAME = 'SSMUseServiceTicketObject';
    
    public static Map<String, Object> getPointOfServiceTitckets() {
        
        Map<String, Object> mapResponse = new Map<String, Object>();

        List<StoreServiceManagerTO.ServiceTicket> ltServiceTickets = new List<StoreServiceManagerTO.ServiceTicket>();
        
        if(FeatureFlagEngine.applicationIsActive(CUSTOM_SETTING_NAME)){

            User attendant = UserDAO.getById(UserInfo.getUserId());
            List<ServiceTicket__c> ltTickets = ServiceTicketDAO.getGSSOnHoldByStore(attendant.StoreCode__c);

            if (ltTickets != null && ltTickets.size() > 0) {
                for (ServiceTicket__c ticket : ltTickets) {
                    ltServiceTickets.add(createTicket(null, ticket));
                }
            }

            if (ltServiceTickets.size() > 0) {
                mapResponse.put('success', ltServiceTickets);

            } else {
                mapResponse.put('error', System.Label.StoreServiceManagerTicketsListIsEmpty);
            }

        }else{
            try {
                Map<String, Object> mapResponseCallout = PointOfServiceTicketsCallout.execute();
    
                if (mapResponseCallout.get('success') != null) {
                    String jsonResponse = (String) mapResponseCallout.get('success');
    
                    List<StoreServiceManagerResponse.Ticket> ltTickets = (List<StoreServiceManagerResponse.Ticket>) 
                        JSON.deserialize(jsonResponse, List<StoreServiceManagerResponse.Ticket>.class);
    
                    if (ltTickets != null && ltTickets.size() > 0) {
                        ltServiceTickets = new List<StoreServiceManagerTO.ServiceTicket>();
    
                        for (StoreServiceManagerResponse.Ticket ticket : ltTickets) {
                            ltServiceTickets.add(createTicket(ticket, null));
                        }
                    }
                }
    
                if (ltServiceTickets != null) {
                    mapResponse.put('success', ltServiceTickets);
    
                } else {
                    mapResponse.put('error', mapResponseCallout.get('error'));
                }
    
            } catch (Exception e) {
                mapResponse.clear();
        
                mapResponse.put('error', GENERIC_ERROR_MESSAGE);
            }
        }
        

        return (mapResponse);
    }

    //Criar dois métodos um para cada tipo de objeto.
    private static StoreServiceManagerTO.ServiceTicket createTicket(StoreServiceManagerResponse.Ticket ticket, ServiceTicket__c objectTicket){
        StoreServiceManagerTO.ServiceTicket serviceTicket = new StoreServiceManagerTO.ServiceTicket();
        String customerCellPhone;
        String geographicAreaCode;
        String networkNumber;

        if(ticket != null){
            geographicAreaCode = ((ticket.geographicArea != null && ticket.geographicArea.code != null) ? ticket.geographicArea.code.replaceAll('[a-zA-Z .]{1,}|\\-', '') : '');
            networkNumber = ((ticket.network != null && ticket.network.networkNumber != null) ? ticket.network.networkNumber.replaceAll('[a-zA-Z .]{1,}|\\-', '') : '');

            try {
                customerCellPhone = (
                    geographicAreaCode + 
                    ((!String.isBlank(geographicAreaCode) && !String.isBlank(networkNumber)) 
                        ? ' ' + networkNumber.substring(0, 5) + '-' + networkNumber.substring(5)
                        : ''
                    ) 
                );

            } catch (Exception e) {
                customerCellPhone = '';
            }


            serviceTicket.type = '';
            serviceTicket.view = '';
            serviceTicket.workPositionId = '';
            serviceTicket.displayAlert = false;
            serviceTicket.ticketId = ticket.id;
            serviceTicket.customerSpecialNeeds = ((ticket.customer != null && ticket.customer.specialNeeds != null) ? ticket.customer.specialNeeds : false);
            serviceTicket.customerPriority  = ((ticket.customer != null && ticket.customer.priority != null) ? ticket.customer.priority : 2);
            serviceTicket.customerId = '';
            serviceTicket.customerName = ((ticket.customer != null && ticket.customer.name != null) ? ticket.customer.name : '');
            serviceTicket.customerAlias = serviceTicket.customerName;
            serviceTicket.customerDocument = ((ticket.customer != null && ticket.customer.individualIdentification != null && !String.isBlank(ticket.customer.individualIdentification.nationalIdentilyCardNr)) ? ticket.customer.individualIdentification.nationalIdentilyCardNr : '');
            serviceTicket.customerCellPhone = customerCellPhone;
            serviceTicket.segmentation = ((ticket.customer != null && ticket.customer.segment.id != null) ? ticket.customer.segment.id : '');
            serviceTicket.segmentationName = ((ticket.customer != null && ticket.customer.segment != null && ticket.customer.segment.name != null) ? ticket.customer.segment.name : '');
            serviceTicket.activity = '';
            serviceTicket.protocol = '';
            serviceTicket.startTime = '';
            serviceTicket.finalTime = '';
            serviceTicket.duration = '';
            serviceTicket.service = ((ticket.interaction != null && ticket.interaction.id != null) ? ticket.interaction.id : '');
            serviceTicket.serviceName = ((ticket.interaction != null && ticket.interaction.name != null) ? ticket.interaction.name : '');
            serviceTicket.category = '';
            serviceTicket.categoryName = '';
            serviceTicket.mainDocumentType = '';
            serviceTicket.documentNumber = '';
            serviceTicket.giveUpReason = '';
            serviceTicket.activities = '';
            serviceTicket.notes = '';

            try {
                serviceTicket.waitTime = ((ticket.duration != null && ticket.duration.amount != null) ? ticket.duration.amount.substring(11) : '');
            
            } catch (Exception e) {
                serviceTicket.waitTime = '';
            } 

        }else if(objectTicket != null){
            geographicAreaCode = ((!String.isBlank(objectTicket.GeographicAreaCode__c)) ? objectTicket.GeographicAreaCode__c.replaceAll('[a-zA-Z .]{1,}|\\-', '') : '');
            networkNumber = ((!String.isBlank(objectTicket.NetworkNumber__c)) ? objectTicket.NetworkNumber__c.replaceAll('[a-zA-Z .]{1,}|\\-', '') : '');

            try {
                customerCellPhone = (
                    geographicAreaCode + 
                    ((!String.isBlank(networkNumber)) 
                        ? (networkNumber.substring(0, 5) + '-' + networkNumber.substring(5))
                        : ''
                    )
                );

            } catch (Exception e) {
                customerCellPhone = '';
            }

            String createdDateTime = (DateTime.valueOf(objectTicket.CreatedDate)).formatGmt('YYYY-MM-dd HH:mm:ss');
            String currentDateTime = (DateTime.now()).formatGmt('YYYY-MM-dd HH:mm:ss');
            
            serviceTicket.waitTime = StoreServiceManagerService.calculateElapsedTime(createdDateTime, currentDateTime);
            
            serviceTicket.id = objectTicket.Id;
            serviceTicket.createdDateTime = createdDateTime;
            serviceTicket.type = '';
            serviceTicket.view = '';
            serviceTicket.store = objectTicket.Store__c;
            serviceTicket.workPositionId = '';
            serviceTicket.displayAlert = false;
            serviceTicket.ticketId = objectTicket.TicketId__c;
            serviceTicket.externalId = objectTicket.ExternalID__c;
            serviceTicket.customerSpecialNeeds = ((objectTicket.SpecialNeeds__c != null) ? objectTicket.SpecialNeeds__c : false);
            serviceTicket.customerPriority = ((objectTicket.Priority__c != null) ? Integer.valueOf(objectTicket.Priority__c) : 2);
            serviceTicket.customerInteractionId = '';
            serviceTicket.customerId = '';
            serviceTicket.customerName = ((!String.isBlank(objectTicket.CustomerName__c)) ? objectTicket.CustomerName__c : '');
            serviceTicket.customerAlias = ((!String.isBlank(objectTicket.Alias__c)) ? objectTicket.Alias__c : serviceTicket.customerName);
            serviceTicket.customerDocument = ((!String.isBlank(objectTicket.Document__c)) ? objectTicket.Document__c : '');
            serviceTicket.geographicAreaCode = geographicAreaCode;
            serviceTicket.networkNumber = networkNumber;
            serviceTicket.customerCellPhone = customerCellPhone;
            serviceTicket.segmentation = ((!String.isBlank(objectTicket.SegmentID__c)) ? objectTicket.SegmentID__c : '');
            serviceTicket.segmentationName = ((!String.isBlank(objectTicket.SegmentName__c)) ? objectTicket.SegmentName__c : '');
            serviceTicket.activity = ((!String.isBlank(objectTicket.Activity__c)) ? objectTicket.Activity__c : '');
            serviceTicket.protocol = ((!String.isBlank(objectTicket.Protocol__c)) ? objectTicket.Protocol__c : '');
            serviceTicket.status = objectTicket.Status__c;
            serviceTicket.userLogin = '';
            serviceTicket.startTime = '';
            serviceTicket.finalTime = '';
            serviceTicket.duration = '';
            serviceTicket.service = ((!String.isBlank(objectTicket.InteractionID__c)) ? objectTicket.InteractionID__c : '');
            serviceTicket.serviceName = ((!String.isBlank(objectTicket.InteractionName__c)) ? objectTicket.InteractionName__c : '');
            serviceTicket.activityPriority = ((objectTicket.ActivityPriority__c != null) ? Integer.valueOf(objectTicket.ActivityPriority__c) : 1);
            serviceTicket.category = '';
            serviceTicket.categoryName = '';
            serviceTicket.mainDocumentType = '';
            serviceTicket.mainDocumentTypeName = '';
            serviceTicket.documentNumber = '';
            serviceTicket.giveUpReason = '';
            serviceTicket.activities = '';
            serviceTicket.notes = '';
        }

        return serviceTicket;
    }
}