force-app/main/default/objects/ServiceTicket__c/ServiceTicket__c.object-meta.xml
<CustomObject>
    <label>Senha</label>
    <nameField>
        <displayFormat>{YY}{MM}-{000000}</displayFormat>
        <label>Nome do Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Senhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceTicket__c/fields/ActivityPriority__c.field-meta.xml
<CustomField>
    <fullName>ActivityPriority__c</fullName>
    <description>Prioridade da Atividade</description>
    <label>Prioridade da Atividade</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>ID Externo para Identificação do Registro na Base de Dados de Origem</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/GeographicAreaCode__c.field-meta.xml
<CustomField>
    <fullName>GeographicAreaCode__c</fullName>
    <description>Código da Área Geográfica - DDD</description>
    <label>DDD</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <description>Login de Rede do Atendente que Realizou o Atendimento</description>
    <label>Atendente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/NetworkNumber__c.field-meta.xml
<CustomField>
    <fullName>NetworkNumber__c</fullName>
    <description>Número do Celular</description>
    <label>Celular</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Prioridade de Atendimento</description>
    <label>Prioridade</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ServiceStart__c.field-meta.xml
<CustomField>
    <fullName>ServiceStart__c</fullName>
    <description>Data e Hora do Início do Atendimento</description>
    <label>Início do Atendimento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SpecialNeeds__c.field-meta.xml
<CustomField>
    <fullName>SpecialNeeds__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Necessidades Especiais</description>
    <label>Necessidades Especiais</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>Em Espera</label>
            </value>
            <value>
                <fullName>In Service</fullName>
                <label>Em Atendimento</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <description>Código da Loja</description>
    <label>Loja</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/TicketId__c.field-meta.xml
<CustomField>
    <fullName>TicketId__c</fullName>
    <description>Número da Senha</description>
    <label>Senha</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/WaitTime__c.field-meta.xml
<CustomField>
    <fullName>WaitTime__c</fullName>
    <description>Tempo de Espera</description>
    <label>Tempo de Espera</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login de rede</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Loja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Código da Loja</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSMManualServiceDialogEngine.cls
/*
    ---------------------------------------------------
    @author - Márcio Las
    @company - Telefonica  
    @date - 14/04/2022
    @description - Class Engine for SSMManualServiceDialog
    ---------------------------------------------------
*/
public with sharing class SSMManualServiceDialogEngine {
    private static final String MANUAL_ATTENDANCE = 'MANUAL';

    private static final Integer GENERIC_ERROR_MESSAGE = 699;

    public static Map<String, Object> generateTicket(String workPositionId, Boolean displayAlert, String scheduleTime, String cellPhone) {
        Map<String, Object> mapResponse = new Map<String, Object>();

        try {
            String cellPhoneNumbers = cellPhone.replaceAll('[a-zA-Z .]{1,}|\\-', '');

            Map<String, Object> mapResponseCallout = PointOfServiceTicketsCallout.execute(scheduleTime, cellPhoneNumbers);

            if (mapResponseCallout.get('success') != null) {
                User attendant = UserDAO.getById(UserInfo.getUserId());

                String jsonTicket = (String) mapResponseCallout.get('success');

                StoreServiceManagerResponse.Ticket generatedTicket = (StoreServiceManagerResponse.Ticket) 
                    JSON.deserialize(jsonTicket, StoreServiceManagerResponse.Ticket.class);

                String geographicAreaCode = cellPhoneNumbers.substring(0, 2);
                String networkNumber = cellPhoneNumbers.substring(2);
                String createdDateTime = (DateTime.now()).formatGmt('YYYY-MM-dd HH:mm:ss');
                String externalId = createdDateTime.replaceAll('[- :]', '');

                StoreServiceManagerTO.ServiceTicket serviceTicket = new StoreServiceManagerTO.ServiceTicket();

                serviceTicket.createdDateTime = createdDateTime;
                serviceTicket.type = MANUAL_ATTENDANCE;
                serviceTicket.view = '';
                serviceTicket.store = attendant.StoreCode__c;
                serviceTicket.workPositionId = workPositionId;
                serviceTicket.displayAlert = displayAlert;
                serviceTicket.ticketId = generatedTicket.id;
                serviceTicket.externalId = ('SF' + serviceTicket.type + generatedTicket.id + externalId);
                serviceTicket.customerSpecialNeeds = false;
                serviceTicket.customerPriority = 2;
                serviceTicket.customerInteractionId = '';
                serviceTicket.customerId = '';
                serviceTicket.customerName = '';
                serviceTicket.customerAlias = '';
                serviceTicket.customerDocument = '';
                serviceTicket.geographicAreaCode = geographicAreaCode;
                serviceTicket.networkNumber = networkNumber;
                serviceTicket.customerCellPhone = cellPhone;
                serviceTicket.segmentation = '';
                serviceTicket.segmentationName = '';
                serviceTicket.activity = '';
                serviceTicket.protocol = '';
                serviceTicket.waitTime = '00:00:00';
                serviceTicket.status = ServiceTicketDAO.GSS_STATUS_IN_SERVICE;
                serviceTicket.userLogin = attendant.Login__c;
                serviceTicket.startTime = createdDateTime;
                serviceTicket.finalTime = '';
                serviceTicket.duration = '';
                serviceTicket.service = '';
                serviceTicket.serviceName = '';
                serviceTicket.activityPriority = 1;
                serviceTicket.category = '';
                serviceTicket.categoryName = '';
                serviceTicket.mainDocumentType = '';
                serviceTicket.mainDocumentTypeName = '';
                serviceTicket.documentNumber = '';
                serviceTicket.giveUpReason = '';
                serviceTicket.activities = '';
                serviceTicket.notes = '';

                Id newTicketId = registerServiceTicket(serviceTicket);

                serviceTicket.Id = newTicketId;

                mapResponse.put('success', serviceTicket);

            } else {
                mapResponse.put('error', mapResponseCallout.get('error'));
            }

        } catch (Exception e) {
            mapResponse.clear();
    
            mapResponse.put('error', GENERIC_ERROR_MESSAGE);
        }

        return (mapResponse);
    }

    private static Id registerServiceTicket(StoreServiceManagerTO.ServiceTicket serviceTicket) {
        ServiceTicket__c ticket = new ServiceTicket__c(
            RecordTypeId = ServiceTicketDAO.GSS_RECORD_TYPE_ID, 
            Store__c = serviceTicket.store, 
            TicketId__c = serviceTicket.ticketId, 
            ExternalID__c = serviceTicket.externalId, 
            SpecialNeeds__c = serviceTicket.customerSpecialNeeds, 
            Priority__c = serviceTicket.customerPriority, 
            GeographicAreaCode__c = serviceTicket.geographicAreaCode, 
            NetworkNumber__c = serviceTicket.networkNumber, 
            Status__c = serviceTicket.status, 
            Login__c = serviceTicket.userLogin, 
            ServiceStart__c = DateTime.valueOfGmt(serviceTicket.startTime), 
            WaitTime__c = serviceTicket.waitTime, 
            ActivityPriority__c = serviceTicket.activityPriority
        );

        insert ticket;

        return (ticket.Id);
    }
}