force-app/main/default/objects/ServiceTicket__c/ServiceTicket__c.object-meta.xml
<CustomObject>
    <label>Senha</label>
    <nameField>
        <displayFormat>{YY}{MM}-{000000}</displayFormat>
        <label>Nome do Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Senhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceTicket__c/fields/Activities__c.field-meta.xml
<CustomField>
    <fullName>Activities__c</fullName>
    <description>Atividades Selecionadas</description>
    <label>Atividades</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>Apelido do Cliente</description>
    <label>Apelido</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/BusinessLineID__c.field-meta.xml
<CustomField>
    <fullName>BusinessLineID__c</fullName>
    <description>ID da Categoria</description>
    <label>ID da Categoria</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/BusinessLineName__c.field-meta.xml
<CustomField>
    <fullName>BusinessLineName__c</fullName>
    <description>Nome da Categoria</description>
    <label>Categoria</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>Nome do Cliente</description>
    <label>Cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Número do Documento</description>
    <label>Nº Documento</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duração do Atendimento</description>
    <label>Duração do Atendimento</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/GeographicAreaCode__c.field-meta.xml
<CustomField>
    <fullName>GeographicAreaCode__c</fullName>
    <description>Código da Área Geográfica - DDD</description>
    <label>DDD</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <description>Login de Rede do Atendente que Realizou o Atendimento</description>
    <label>Atendente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/MainDocumentTypeID__c.field-meta.xml
<CustomField>
    <fullName>MainDocumentTypeID__c</fullName>
    <description>ID do Tipo Documento Principal</description>
    <label>ID do Tipo Documento Principal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/MainDocumentTypeName__c.field-meta.xml
<CustomField>
    <fullName>MainDocumentTypeName__c</fullName>
    <description>Nome do Tipo Documento Principal</description>
    <label>Tipo Documento Principal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/NetworkNumber__c.field-meta.xml
<CustomField>
    <fullName>NetworkNumber__c</fullName>
    <description>Número do Celular</description>
    <label>Celular</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Notas</description>
    <label>Notas</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ServiceEnd__c.field-meta.xml
<CustomField>
    <fullName>ServiceEnd__c</fullName>
    <description>Data e Hora do Término do Atendimento</description>
    <label>Término do Atendimento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ServiceStart__c.field-meta.xml
<CustomField>
    <fullName>ServiceStart__c</fullName>
    <description>Data e Hora do Início do Atendimento</description>
    <label>Início do Atendimento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>Em Espera</label>
            </value>
            <value>
                <fullName>In Service</fullName>
                <label>Em Atendimento</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/WaitTime__c.field-meta.xml
<CustomField>
    <fullName>WaitTime__c</fullName>
    <description>Tempo de Espera</description>
    <label>Tempo de Espera</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/CallerPhone__c.field-meta.xml
<CustomField>
    <fullName>CallerPhone__c</fullName>
    <description>Telefone chamador registrado na URA.</description>
    <label>Telefone Chamador</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/InteractionNumber__c.field-meta.xml
<CustomField>
    <fullName>InteractionNumber__c</fullName>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WDE</fullName>
            </value>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteractionTopic__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>GPS</fullName>
            </value>
            <value>
                <fullName>GPS Pré</fullName>
            </value>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>Hybris</fullName>
            </value>
            <value>
                <fullName>NEXT</fullName>
                <isActive>false</isActive>
                <label>NEXT</label>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SFA Script - Next</fullName>
            </value>
            <value>
                <fullName>VIVO/NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteractionTopic__c/fields/remarkup__c.field-meta.xml
<CustomField>
    <fullName>remarkup__c</fullName>
    <description>Remark Up from user when create Relationship Topic</description>
    <label>Comentário</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteractionTopic__c/fields/TopicName__c.field-meta.xml
<CustomField>
    <fullName>TopicName__c</fullName>
    <description>Complete Topic Name from tree (path)</description>
    <label>Palito</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteractionTopic__c/fields/vlocity_cmt__Reason__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Reason__c</fullName>
    <description>Records the reason of the outcome.</description>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cross Order Validation</fullName>
            </value>
            <value>
                <fullName>Subscription Suspended</fullName>
            </value>
            <value>
                <fullName>Suspension Reason Mismatch</fullName>
            </value>
            <value>
                <fullName>Eligibility Check</fullName>
            </value>
            <value>
                <fullName>Report Fraud</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subscription Validation</fullName>
            </value>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Top-Up</fullName>
            </value>
            <value>
                <fullName>Voucher Code Validation</fullName>
            </value>
            <value>
                <fullName>Provide PUK</fullName>
            </value>
            <value>
                <fullName>ICCID Validation</fullName>
            </value>
            <value>
                <fullName>Change Feature</fullName>
            </value>
            <value>
                <fullName>Credit Check Declined</fullName>
            </value>
            <value>
                <fullName>Palitagem Fixa</fullName>
            </value>
            <value>
                <fullName>Palitagem Móvel</fullName>
            </value>
            <value>
                <fullName>Palitagem Pré</fullName>
            </value>
            <value>
                <fullName>Atendimento - GSS</fullName>
            </value>
            <value>
                <fullName>Contestação de Fatura - Móvel</fullName>
            </value>
            <value>
                <fullName>Palitagem Outros Produtos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SSMAttendanceOperationsEngine.cls
/*
    ---------------------------------------------------
    @author - Márcio Las
    @company - Telefonica  
    @date - 08/04/2022
    @description - Class Engine for SSMAttendanceOperations
    ---------------------------------------------------
*/
public with sharing class SSMAttendanceOperationsEngine {
    private static final Integer GENERIC_ERROR_MESSAGE = 699;

    public static Map<String, Object> recallTicket(StoreServiceManagerTO.ServiceTicket serviceTicket) {
        Map<String, Object> mapResponse = new Map<String, Object>();

        try {
            serviceTicket.startTime = (DateTime.now()).formatGmt('YYYY-MM-dd HH:mm:ss');
            serviceTicket.waitTime = StoreServiceManagerService.calculateElapsedTime(serviceTicket.createdDateTime, serviceTicket.startTime);

            mapResponse = PointOfServiceAttendanceCallout.execute(serviceTicket, 'Recall');

            if (mapResponse.get('success') != null) {
                updateServiceTicket(serviceTicket);

                mapResponse.clear();
                
                mapResponse.put('success', serviceTicket.startTime);
            }

        } catch (Exception e) {
            mapResponse.clear();

            mapResponse.put('error', GENERIC_ERROR_MESSAGE);
        }

        return (mapResponse);
    }

    public static Map<String, Object> returnToHome(StoreServiceManagerTO.ServiceTicket serviceTicket) {
        Map<String, Object> mapResponse = new Map<String, Object>();

        try {
            serviceTicket.status = ServiceTicketDAO.GSS_STATUS_ON_HOLD;
            serviceTicket.userLogin = '';
            serviceTicket.startTime = '';
            serviceTicket.category = '';
            serviceTicket.categoryName = '';
            serviceTicket.mainDocumentType = '';
            serviceTicket.mainDocumentTypeName = '';
            serviceTicket.documentNumber = '';
            serviceTicket.giveUpReason = '';
            serviceTicket.activities = '';
            serviceTicket.notes = '';

            mapResponse = PointOfServiceAttendanceCallout.execute(serviceTicket, 'Return');

            if (mapResponse.get('success') != null) {
                updateServiceTicket(serviceTicket);
            }

        } catch (Exception e) {
            mapResponse.clear();

            mapResponse.put('error', GENERIC_ERROR_MESSAGE);
        }

        return (mapResponse);
    }

    public static Map<String, Object> giveUp(StoreServiceManagerTO.ServiceTicket serviceTicket) {
        Map<String, Object> mapResponse = new Map<String, Object>();
        
        try {
            serviceTicket.status = ServiceTicketDAO.GSS_STATUS_CANCELED;
            serviceTicket.category = '';
            serviceTicket.categoryName = '';
            serviceTicket.mainDocumentType = '';
            serviceTicket.mainDocumentTypeName = '';
            serviceTicket.documentNumber = '';
            serviceTicket.activities = serviceTicket.giveUpReason;
            serviceTicket.notes = '';
            
            mapResponse = PointOfServiceAttendanceCallout.execute(serviceTicket, 'Canceled');

            if (mapResponse.get('success') != null) {
                updateServiceTicket(serviceTicket);
            
                if (!String.isBlank(serviceTicket.customerId)) {
                    Map<String, Object> mapCase = createAttendanceCase(serviceTicket);
            
                    if (mapCase.get('success') != null) {
                        mapResponse.clear();

                        mapResponse.put('success', mapCase.get('success'));
                    }
                }
            }

        } catch (Exception e) {
            mapResponse.clear();

            mapResponse.put('error', GENERIC_ERROR_MESSAGE);
        }

        return (mapResponse);
    }

    public static Map<String, Object> confirmService(StoreServiceManagerTO.ServiceTicket serviceTicket) {
        Map<String, Object> mapResponse = new Map<String, Object>();

        try {
            String customerCellPhone = serviceTicket.customerCellPhone.replaceAll('[a-zA-Z .]{1,}|\\-', '');

            serviceTicket.geographicAreaCode = customerCellPhone.substring(0, 2);
            serviceTicket.networkNumber = customerCellPhone.substring(2);
            serviceTicket.status = ServiceTicketDAO.GSS_STATUS_CLOSED;
            serviceTicket.finalTime = (DateTime.now()).formatGmt('YYYY-MM-dd HH:mm:ss');
            serviceTicket.duration = StoreServiceManagerService.calculateElapsedTime(serviceTicket.startTime, serviceTicket.finalTime);

            mapResponse = PointOfServiceAttendanceCallout.execute(serviceTicket, 'Closed');

            if (mapResponse.get('success') != null) {
                updateServiceTicket(serviceTicket);

                if (!String.isBlank(serviceTicket.customerId)) {
                    Map<String, Object> mapCase = createAttendanceCase(serviceTicket);

                    if (mapCase.get('success') != null) {
                        mapResponse.clear();

                        mapResponse.put('success', mapCase.get('success'));
                    }
                }
            }
            
        } catch (Exception e) {
            mapResponse.clear();
            
            mapResponse.put('error', GENERIC_ERROR_MESSAGE);
        }

        return (mapResponse);
    }

    private static Map<String, Object> createAttendanceCase(StoreServiceManagerTO.ServiceTicket serviceTicket) {
        Map<String, Object> mapResponse = new Map<String, Object>();
        
        String description = '';

        if (!String.isBlank(serviceTicket.giveUpReason)) {
            StoreServiceManagerTO.ItemPicklistValue giveUpReason = (StoreServiceManagerTO.ItemPicklistValue)
                JSON.deserialize(serviceTicket.giveUpReason, StoreServiceManagerTO.ItemPicklistValue.class);

            description = giveUpReason.label;

        } else {
            List<StoreServiceManagerTO.ItemPicklistValue> ltActivities = (List<StoreServiceManagerTO.ItemPicklistValue>)
                JSON.deserialize(serviceTicket.activities, List<StoreServiceManagerTO.ItemPicklistValue>.class);

            for (StoreServiceManagerTO.ItemPicklistValue activity : ltActivities) {
                description += (((String.isBlank(description)) ? '' : ', ') + activity.label);
            }
        }

        try {
            vlocity_cmt__CustomerInteractionTopic__c ssmvlCIT = new vlocity_cmt__CustomerInteractionTopic__c();
            
            ssmvlCIT.vlocity_cmt__CustomerInteractionId__c = serviceTicket.customerInteractionId;
            ssmvlCIT.vlocity_cmt__Reason__c = 'Atendimento - GSS';
            ssmvlCIT.Origin__c = 'GSS';            
            ssmvlCIT.TopicName__c = description;
            ssmvlCIT.remarkup__c = serviceTicket.notes;
            ssmvlCIT.vlocity_cmt__AccountId__c = serviceTicket.customerId;
            
            insert ssmvlCIT;
            
            mapResponse.put('success', ssmvlCIT.Id);
                        
            if (ssmvlCIT.Id != null) {
                vlocity_cmt__CustomerInteraction__c ssmvlCI = new vlocity_cmt__CustomerInteraction__c();

                ssmvlCI.Id = serviceTicket.customerInteractionId;
                ssmvlCI.InteractionNumber__c = serviceTicket.protocol;
                ssmvlCI.CallerPhone__c = serviceTicket.customerCellPhone;

                update ssmvlCI;

                mapResponse.put('success', ssmvlCI.Id);
            }            

        } catch (Exception e) {
            mapResponse.put('error', GENERIC_ERROR_MESSAGE);
        }

        return (mapResponse);
    }

    private static void updateServiceTicket(StoreServiceManagerTO.ServiceTicket serviceTicket) {
        ServiceTicket__c ticket = new ServiceTicket__c(
            Id = serviceTicket.Id, 
            CustomerName__c = serviceTicket.customerName, 
            Alias__c = serviceTicket.customerAlias, 
            GeographicAreaCode__c = serviceTicket.geographicAreaCode, 
            NetworkNumber__c = serviceTicket.networkNumber, 
            Status__c = serviceTicket.status, 
            Login__c = serviceTicket.userLogin, 
            WaitTime__c = serviceTicket.waitTime, 
            ServiceStart__c = (String.isBlank(serviceTicket.startTime) ? null : DateTime.valueOfGmt(serviceTicket.startTime)), 
            ServiceEnd__c = (String.isBlank(serviceTicket.finalTime) ? null : DateTime.valueOfGmt(serviceTicket.finalTime)), 
            Duration__c = serviceTicket.duration, 
            BusinessLineID__c = serviceTicket.category, 
            BusinessLineName__c = serviceTicket.categoryName, 
            MainDocumentTypeID__c = serviceTicket.mainDocumentType, 
            MainDocumentTypeName__c = serviceTicket.mainDocumentTypeName, 
            DocumentNumber__c = serviceTicket.documentNumber, 
            Activities__c = serviceTicket.activities, 
            Notes__c = serviceTicket.notes
        );

        update ticket;
    }
}