force-app/main/default/objects/GenericOptionsLists__c/GenericOptionsLists__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Listas de opções genericas para ser utilizadas nos projetos</description>
    <label>Listas de Opções Generica</label>
</CustomObject>

force-app/main/default/objects/GenericOptionsLists__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Código</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description2__c.field-meta.xml
<CustomField>
    <fullName>Description2__c</fullName>
    <label>Descrição 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrição</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSMAttendanceEndServiceEngine.cls
/*
    ---------------------------------------------------
    @author - Márcio Las
    @company - Telefonica  
    @date - 05/05/2022
    @description - Class Engine for SSMAttendanceEndService
    ---------------------------------------------------
*/
public with sharing class SSMAttendanceEndServiceEngine {
    private static final String OPERATIONAL_INFORMATIONS = 'OperationalInformations';
    private static final String INTERACTIONS = 'Interactions';

    private static final Integer ERROR_LOADING_COMPONENT = 601;

    public static Map<String, Object> loadSSMAttendanceEndService() {
        Map<String, Object> mapResponse = new Map<String, Object>();

        List<StoreServiceManagerTO.ItemPicklistValue> ltActivities = 
            new List<StoreServiceManagerTO.ItemPicklistValue>();

        List<GenericOptionsLists__c> ltInteractions = 
            GenericOptionsListsDAO.getByAPINameUsedInActive(OPERATIONAL_INFORMATIONS, INTERACTIONS);

        if (ltInteractions != null && ltInteractions.size() > 0) {
            for (GenericOptionsLists__c interaction : ltInteractions) {
                StoreServiceManagerTO.ItemPicklistValue activity = 
                    new StoreServiceManagerTO.ItemPicklistValue();

                activity.label = interaction.Description__c;
                activity.value = interaction.Code__c;
                activity.instruction = interaction.description2__c;

                ltActivities.add(activity);
            }
        }
        
        if (ltActivities.size() > 0) {
            mapResponse.put('success', ltActivities);

        } else {
            mapResponse.put('error', ERROR_LOADING_COMPONENT);
        }

        return (mapResponse);
    }
}