force-app/main/default/objects/GenericOptionsLists__c/GenericOptionsLists__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Listas de opções genericas para ser utilizadas nos projetos</description>
    <label>Listas de Opções Generica</label>
</CustomObject>

force-app/main/default/objects/GenericOptionsLists__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/APIDateTime__c.field-meta.xml
<CustomField>
    <fullName>APIDateTime__c</fullName>
    <label>Data/Hora</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>Nome da API</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Código</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description2__c.field-meta.xml
<CustomField>
    <fullName>Description2__c</fullName>
    <label>Descrição 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrição</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/UsedIn__c.field-meta.xml
<CustomField>
    <fullName>UsedIn__c</fullName>
    <label>Usado em</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenericOptionsListsDAO.cls
public with sharing class GenericOptionsListsDAO {
    public static List<GenericOptionsLists__c> getByAPIName(String apiName) {
        return (
            [
                SELECT 
                    Id, 
                    Name, 
                    Code__c, 
                    Description__c, 
                    Description2__c, 
                    APIName__c, 
                    APIDateTime__c,
                    UsedIn__c, 
                    Active__c 
                FROM 
                    GenericOptionsLists__c
                WHERE 
                    APIName__c = :apiName 
            ]
        );
    }

    public static List<GenericOptionsLists__c> getByAPINameUsedIn(String apiName, String usedIn) {
        return (
            [
                SELECT 
                    Id, 
                    Name, 
                    Code__c, 
                    Description__c, 
                    Description2__c, 
                    APIName__c, 
                    APIDateTime__c,
                    UsedIn__c, 
                    Active__c 
                FROM 
                    GenericOptionsLists__c
                WHERE 
                    APIName__c = :apiName AND 
                    UsedIn__c = :usedIn
            ]
        );
    }

    public static List<GenericOptionsLists__c> getByAPINameUsedInActive(String apiName, String usedIn) {
        return (getByAPINameUsedInActive(new Set<String>{apiName}, new Set<String>{usedIn}));
    }

    public static List<GenericOptionsLists__c> getByAPINameUsedInActive(Set<String> apiName, Set<String> usedIn) {
            return (
            [
                SELECT 
                    Id, 
                    Name, 
                    Code__c, 
                    Description__c, 
                    Description2__c, 
                    APIName__c, 
                    APIDateTime__c,
                    UsedIn__c, 
                    Active__c 
                FROM 
                    GenericOptionsLists__c
                WHERE 
                    APIName__c IN :apiName AND 
                    UsedIn__c IN :usedIn AND
                    Active__c = true
            ]
        );
    }

    public static List<GenericOptionsLists__c> getByAPINameUsedInCode(String apiName, String usedIn, String code) {
        return (
            [
                SELECT 
                    Id, 
                    Name, 
                    Code__c, 
                    Description__c, 
                    Description2__c, 
                    APIName__c, 
                    APIDateTime__c,
                    UsedIn__c, 
                    Active__c 
                FROM 
                    GenericOptionsLists__c
                WHERE 
                    APIName__c = :apiName AND 
                    UsedIn__c = :usedIn AND
                    Code__c = :code
            ]
        );
    }

    public static List<GenericOptionsLists__c> getByAPINameUsedInName(String apiName, String usedIn, String name) {
        return (
            [
                SELECT 
                    Id, 
                    Name, 
                    Code__c, 
                    Description__c, 
                    Description2__c, 
                    APIName__c, 
                    APIDateTime__c,
                    UsedIn__c, 
                    Active__c 
                FROM 
                    GenericOptionsLists__c
                WHERE 
                    APIName__c = :apiName AND 
                    UsedIn__c = :usedIn AND
                    Name = :name
            ]
        );
    }
    
    public static List<GenericOptionsLists__c> getByAPINameUsedInDescription(String apiName, String usedIn, String description) {
        return (
            [
                SELECT 
                    Id, 
                    Name, 
                    Code__c, 
                    Description__c, 
                    Description2__c, 
                    APIName__c, 
                    APIDateTime__c,
                    UsedIn__c, 
                    Active__c 
                FROM 
                    GenericOptionsLists__c
                WHERE 
                    APIName__c = :apiName AND 
                    UsedIn__c = :usedIn AND
                    Description__c = :description
            ]
        );
    }
    
    public static List<GenericOptionsLists__c> getByAPINameUsedInDescription2(String apiName, String usedIn, String description2) {
        return (
            [
                SELECT 
                    Id, 
                    Name, 
                    Code__c, 
                    Description__c, 
                    Description2__c, 
                    APIName__c, 
                    APIDateTime__c,
                    UsedIn__c, 
                    Active__c 
                FROM 
                    GenericOptionsLists__c
                WHERE 
                    APIName__c = :apiName AND 
                    UsedIn__c = :usedIn AND
                    Description2__c = :description2
            ]
        );
    }
}