force-app/main/default/objects/GenericOptionsLists__c/GenericOptionsLists__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Listas de opções genericas para ser utilizadas nos projetos</description>
    <label>Listas de Opções Generica</label>
</CustomObject>

force-app/main/default/objects/GenericOptionsLists__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/APIDateTime__c.field-meta.xml
<CustomField>
    <fullName>APIDateTime__c</fullName>
    <label>Data/Hora</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>Nome da API</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Código</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description2__c.field-meta.xml
<CustomField>
    <fullName>Description2__c</fullName>
    <label>Descrição 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrição</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/UsedIn__c.field-meta.xml
<CustomField>
    <fullName>UsedIn__c</fullName>
    <label>Usado em</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSMAttendanceEndServiceControllerTest.cls
@IsTest
public with sharing class SSMAttendanceEndServiceControllerTest {
    private static final String DOCUMENT_TYPES = 'DocumentTypes';

    @TestSetup
    public static void setup() {
        GenericOptionsLists__c newInteraction = new GenericOptionsLists__c();

        newInteraction.Name = 'Interactions705';
        newInteraction.Code__c = '705';
        newInteraction.Description__c = 'Alteração Cadastral - TV';
        newInteraction.Description2__c = '';
        newInteraction.APIName__c = 'OperationalInformations';
        newInteraction.APIDateTime__c = Date.today();
        newInteraction.UsedIn__c = 'Interactions';
        newInteraction.Active__c = true;

        Database.insert(newInteraction);
    }

    @IsTest
    public static void  loadSSMAttendanceEndServiceTest() {
        Test.startTest();
            Map<String, Object> mapTest = SSMAttendanceEndServiceController.loadSSMAttendanceEndService();
        Test.stopTest();

        System.assertNotEquals(null, mapTest.get('success'));
    }
}