force-app/main/default/objects/GenericOptionsLists__c/GenericOptionsLists__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Listas de opções genericas para ser utilizadas nos projetos</description>
    <label>Listas de Opções Generica</label>
</CustomObject>

force-app/main/default/objects/GenericOptionsLists__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/APIDateTime__c.field-meta.xml
<CustomField>
    <fullName>APIDateTime__c</fullName>
    <label>Data/Hora</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>Nome da API</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Código</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description2__c.field-meta.xml
<CustomField>
    <fullName>Description2__c</fullName>
    <label>Descrição 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrição</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/UsedIn__c.field-meta.xml
<CustomField>
    <fullName>UsedIn__c</fullName>
    <label>Usado em</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSMAttendanceCustomerDataControllerTest.cls
@IsTest
public with sharing class SSMAttendanceCustomerDataControllerTest {
    @TestSetup
    public static void setup() {
        GenericOptionsLists__c newBusinessLine = new GenericOptionsLists__c();

        newBusinessLine.Name = 'BusinessLines2';
        newBusinessLine.Code__c = '2';
        newBusinessLine.Description__c = 'Fixa';
        newBusinessLine.Description2__c = 'FIXA';
        newBusinessLine.APIName__c = 'OperationalInformations';
        newBusinessLine.APIDateTime__c = Date.today();
        newBusinessLine.UsedIn__c = 'BusinessLines';
        newBusinessLine.Active__c = true;

        Database.insert(newBusinessLine);

        GenericOptionsLists__c newDocumentType = new GenericOptionsLists__c();

        newDocumentType.Name = 'DocumentTypesCPF';
        newDocumentType.Code__c = 'CPF';
        newDocumentType.Description__c = 'CPF';
        newDocumentType.Description2__c = '';
        newDocumentType.APIName__c = 'DocumentTypes';
        newDocumentType.APIDateTime__c = Date.today();
        newDocumentType.UsedIn__c = 'DocumentTypes';
        newDocumentType.Active__c = true;

        Database.insert(newDocumentType);
    }

    @IsTest
    public static void  loadSSMAttendanceCustomerDataTest() {
        Test.startTest();
            Map<String, Object> mapTest = SSMAttendanceCustomerDataController.loadSSMAttendanceCustomerData();
        Test.stopTest();

        System.assertNotEquals(null, mapTest.get('categories'));
        System.assertNotEquals(null, mapTest.get('documentTypes'));
    }
}