force-app/main/default/objects/CartOffer__c/CartOffer__c.object-meta.xml
<CustomObject>
    <label>Produto do Carrinho</label>
    <nameField>
        <displayFormat>Produto-{000000}</displayFormat>
        <label>Produto do Carrinho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do Carrinho</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CartOffer__c/fields/OfferId__c.field-meta.xml
<CustomField>
    <fullName>OfferId__c</fullName>
    <label>Oferta</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Ofertas do Carrinho</relationshipLabel>
    <relationshipName>CartOffer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OfferBO.cls
public class OfferBO {
    
    public static void validateActiveCartOffer(List<Offer__c> lstOffer){
        Set<Id> setIdOffer = new Set<Id>();
        List<CartOffer__c> lstCartOffer = new List<CartOffer__c>();
        Map<Id, CartOffer__c> mapCartOffer = new Map<Id, CartOffer__c>();

        for(Offer__c offer : lstOffer){
            setIdOffer.add(offer.Id);
        }

        lstCartOffer = CartOfferDAO.getCartOfferByOfferId(setIdOffer);
        
        for(CartOffer__c cartOffer : lstCartOffer){
            mapCartOffer.put(cartOffer.OfferId__c, cartOffer);
        }

        for(Offer__c offer : lstOffer){
            CartOffer__c cartOffer = new CartOffer__c();
            cartOffer = mapCartOffer.get(offer.Id);

            if(cartOffer != null){
                offer.addError(System.Label.DeleteActiveOfferCartValidation);
            }
        }
    }
}