force-app/main/default/objects/CartOffer__c/CartOffer__c.object-meta.xml
<CustomObject>
    <label>Produto do Carrinho</label>
    <nameField>
        <displayFormat>Produto-{000000}</displayFormat>
        <label>Produto do Carrinho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do Carrinho</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CartOffer__c/fields/CartId__c.field-meta.xml
<CustomField>
    <fullName>CartId__c</fullName>
    <label>Carrinho</label>
    <referenceTo>CartAccount__c</referenceTo>
    <relationshipLabel>Produtos do Carrinho</relationshipLabel>
    <relationshipName>CartOffer</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CartOffer__c/fields/OfferId__c.field-meta.xml
<CustomField>
    <fullName>OfferId__c</fullName>
    <label>Oferta</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Ofertas do Carrinho</relationshipLabel>
    <relationshipName>CartOffer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CartOfferDAO.cls
public with sharing class CartOfferDAO {
    public static List<CartOffer__c> getCartOfferByOfferId(Set<Id> setIdOffer){
        return [
            SELECT    
                Id, 
                OfferId__c 
            FROM 
                CartOffer__c 
            WHERE 
                OfferId__c IN: setIdOffer
            AND Active__c = true
        ];
    }
    public static List<CartOffer__c> getCartOfferByCartId(Set<Id> setIdCartId){
        return [
            SELECT    
                Id, 
                CartId__c 
            FROM 
                CartOffer__c 
            WHERE 
            CartId__c IN: setIdCartId
        ];
    }
}