force-app/main/default/objects/Case/fields/CallerDDD__c.field-meta.xml
<CustomField>
    <fullName>CallerDDD__c</fullName>
    <description>DDD chamador do telefone de origem na URA.</description>
    <label>DDD Chamador</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallerPhone__c.field-meta.xml
<CustomField>
    <fullName>CallerPhone__c</fullName>
    <description>Telefone chamador registrado na URA.</description>
    <label>Telefone Chamador</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Closure__c.field-meta.xml
<CustomField>
    <fullName>Closure__c</fullName>
    <label>Fechamento</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Observação</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ProtocolURA__c.field-meta.xml
<CustomField>
    <fullName>ProtocolURA__c</fullName>
    <label>Protocolo URA</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Campo utilizado na parametrização de casos de alta complexidade e críticos no custom metadata HDE DE-PARA, para dependencias de campos e para campos fórmula no objeto. ex: visão</description>
    <label>Grupo de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
                <label>Revendas</label>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>VPR Lojas</fullName>
            </value>
            <value>
                <fullName>V</fullName>
                <isActive>false</isActive>
                <label>V</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceNumber__c.field-meta.xml
<CustomField>
    <fullName>ServiceNumber__c</fullName>
    <label>Número de Atendimento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceQualificationMobile__c.field-meta.xml
<CustomField>
    <fullName>ServiceQualificationMobile__c</fullName>
    <label>Qualificação de Atendimento</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceRequestId__c.field-meta.xml
<CustomField>
    <fullName>ServiceRequestId__c</fullName>
    <label>Número da SS</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TransferObservation__c.field-meta.xml
<CustomField>
    <fullName>TransferObservation__c</fullName>
    <label>Observação da Transferência</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FixedServiceQualification.recordType-meta.xml
<RecordType>
    <fullName>FixedServiceQualification</fullName>
    <active>true</active>
    <businessProcess>FixedServiceQualification</businessProcess>
    <label>Palitagem de Atendimento Fixa</label>
</RecordType>

force-app/main/default/classes/CaseDAO.cls
public without sharing class CaseDAO {
    public static List<Case> getCaseByParentId(String parentId, String accountId) {
        return  [
            SELECT 
                Id
        FROM 
            Case 
        WHERE 
            ParentId  = :parentId
        AND AccountId = :accountId 
        AND Status    = 'InTransfer'];
    }

    public static Case getCasebyId(String caseId){
        return[
            SELECT
                Id,
                Origin,
                Status,
                Segment__c,
                ServiceRequestId__c,
                ServiceNumber__c,
                ParentId,
                CaseNumber,
                Protocol__c,
                RecordTypeId,
                ProtocolURA__c,
                CallerDDD__c,
                CallerPhone__c,
                Comment__c,
                AccountId,
               // ServiceQualificationMobile__c,
                Closure__c,
                TransferObservation__c
            FROM
                Case
            WHERE
                Id = :caseId
            LIMIT 1
        ];
    }

    public static List<Case> getOpenCaseFixa(String accountId, String userId){
        Id recordTypeIdCaseFixa = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('FixedServiceQualification').getrecordTypeId();
        DateTime expirationDate = System.now().addMinutes(-30);
        return [
            SELECT 
                Id,
                Origin,
                Status,
                Segment__c,
                ServiceRequestId__c,
                ParentId,
                CaseNumber,
                Protocol__c,
                RecordTypeId,
                ProtocolURA__c,
                CallerDDD__c,
                CallerPhone__c,
                Comment__c,
                AccountId,
               // ServiceQualificationMobile__c,
                Closure__c,
                TransferObservation__c
            FROM CASE 
            WHERE
                Status       = 'Em Atendimento' AND 
                AccountId    = :accountId AND 
                OwnerId      = :userId AND
                RecordTypeId = :recordTypeIdCaseFixa AND
                CreatedDate >= :expirationDate
            ORDER BY 
                CreatedDate 
            DESC
        ];
    }
	//Kaiser - criado método para retornar um caso aberto de gps pre
    public static List<Case> getOpenCasePre(String accountId, String userId){
        Id recordTypeIdCasePre = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PreDefectAndRepair').getrecordTypeId();
        DateTime expirationDate = System.now().addMinutes(-30);
        return [
            SELECT 
                Id,
                Origin,
                Status,
                Segment__c,
                ServiceNumber__c,
                ParentId,
                CaseNumber,
                Protocol__c,
                RecordTypeId,
                ProtocolURA__c,
                CallerDDD__c,
                CallerPhone__c,
                Comment__c,
                AccountId,
               // ServiceQualificationMobile__c,
                Closure__c,
                TransferObservation__c
            FROM CASE 
            WHERE
                Status       = 'Em Atendimento' AND 
                AccountId    = :accountId AND 
                OwnerId      = :userId AND
                RecordTypeId = :recordTypeIdCasePre AND
                CreatedDate >= :expirationDate
            ORDER BY 
                CreatedDate 
            DESC
        ];
    }    

}