force-app/main/default/objects/Case/fields/CaseOwnerFormula__c.field-meta.xml
<CustomField>
    <fullName>CaseOwnerFormula__c</fullName>
    <formula>IF(ISBLANK(Owner:User.Id), Owner:Queue.QueueName , Owner:User.FirstName &amp; &quot; &quot; &amp;  Owner:User.LastName &amp; &quot; - &quot; &amp; Owner:User.Alias)</formula>
    <label>Proprietário do chamado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Campo utilizado na parametrização de casos de alta complexidade e críticos no custom metadata HDE DE-PARA, para dependencias de campos e para campos fórmula no objeto. ex: visão</description>
    <label>Grupo de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
                <label>Revendas</label>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>VPR Lojas</fullName>
            </value>
            <value>
                <fullName>V</fullName>
                <isActive>false</isActive>
                <label>V</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/FromToMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para ser utilizado para inclusão de de/para que serão utilizados na Org.</description>
    <label>Mapeamento DePara</label>
    <pluralLabel>Mapeamento DePara</pluralLabel>
</CustomObject>

force-app/main/default/objects/FromToMapping__mdt/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <description>Segmento do operador utilizado no de-para do componente de atendimento.</description>
    <label>Segmento do Operador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
                <default>true</default>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Omnichannel</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>Revenda</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
            </value>
            <value>
                <fullName>Suporte a Lojas</fullName>
            </value>
            <value>
                <fullName>Televendas</fullName>
            </value>
            <value>
                <fullName>Atendimento</fullName>
            </value>
            <value>
                <fullName>Backoffice</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Retencao</fullName>
            </value>
            <value>
                <fullName>Purpura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/fields/OriginApiName__c.field-meta.xml
<CustomField>
    <fullName>OriginApiName__c</fullName>
    <description>ApiName do campo desejado origem</description>
    <label>ApiName do campo Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PartnerGroup__c.field-meta.xml
<CustomField>
    <fullName>PartnerGroup__c</fullName>
    <label>Grupo do Aliado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VendasAliado</fullName>
                <label>Vendas Aliado</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPConsultor</fullName>
                <label>Vendas Aliado PaP Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPGerente</fullName>
                <label>Vendas Aliado PaP Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaConsultor</fullName>
                <label>Vendas Aliado Revenda Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaGerente</fullName>
                <label>Vendas Aliado Revenda Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasGerente</fullName>
                <label>Vendas Aliado Televendas Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPSupervisor</fullName>
                <label>Vendas Aliado PaP Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasCoordenador</fullName>
                <label>Vendas Aliado Televendas Coordenador</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasSupervisor</fullName>
                <label>Vendas Aliado Televendas Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasConsultor</fullName>
                <label>Vendas Aliado Televendas Consultor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeOperador</fullName>
                <label>Atendimento Aliado Backoffice Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoOp</fullName>
                <label>Atendimento Aliado Backoffice Retencao Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoSup</fullName>
                <label>Atendimento Aliado Backoffice Retencao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeSupervisor</fullName>
                <label>Atendimento Aliado Backoffice Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Ativo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Ativo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaOperador</fullName>
                <label>Atendimento Aliado Ouvidoria Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaSupervisor</fullName>
                <label>Atendimento Aliado Ouvidoria Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingOp</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingSup</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Supervisor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HDECasesService.cls
public with sharing class HDECasesService {
    public static void validateNewOwnerSegment(List<Case> lstCases) {
        User currentUser = UserDAO.getById(UserInfo.getUserId());
        if (hasHDEPermission() && currentUser.Profile.UserLicense.name != 'Partner Community') {
            List<Case> lstChangedCase = new List<Case>();
            Set<Id> setOwnerId = new Set<Id>();
            for (Case iCase : lstCases) {
                if (iCase.Origin == 'HDE' && TriggerHelper.changedField(iCase, new Set<String>{'CaseOwnerFormula__c'})) {
                    lstChangedCase.add(iCase);
                    setOwnerId.add(iCase.OwnerId);
                }
            }

            if (!lstChangedCase.isEmpty()) {

                List<User> lstAllOwnersUsers = UserDAO.getById(setOwnerId);
                Set<String> setOwnersPartnerGroups = new Set<String>{currentUser.UserRole.DeveloperName};

                for (User iUser : lstAllOwnersUsers) {
                    setOwnersPartnerGroups.add(iUser.PartnerGroup__c);
                }

                List<FromToMapping__mdt> lstSegmentsAvailable = FromToMappingDAO.getLstByUsersRole(setOwnersPartnerGroups);

                if (lstSegmentsAvailable.isEmpty()) {
                    for (Case iCase : lstChangedCase) {
                        iCase.addError('Papel está sem o segmento cadastrado no De/Para');
                    }
                }
                setOwnersPartnerGroups.clear();
                
                String currentUserSegment;
                for(FromToMapping__mdt role : lstSegmentsAvailable){
                    if (role.OperatorSegment__c != null && role.OriginApiName__c == currentUser.UserRole.DeveloperName) {
                        currentUserSegment = role.OperatorSegment__c;
                    }

                    setOwnersPartnerGroups.add(role.OriginApiName__c);
                }

                List<User> lstAllUserWithSegment = UserDAO.getUserByRole(setOwnersPartnerGroups);
                Map<String, List<Id>> mapUserSegment = new Map<String, List<Id>>();

                fillMapWithAvailableSegments(mapUserSegment, lstSegmentsAvailable, lstAllUserWithSegment);

                for (Case iCase : lstChangedCase) {
                    if (currentUserSegment != iCase.Segment__c) {
                        iCase.addError('Este usuário não pode alterar o proprietário para outro se não estiver no mesmo segmento do caso');
                    } else if(!mapUserSegment.containsKey(iCase.Segment__c)){
                        iCase.addError('Não pode alterar o proprietário para outro se usuário destino não estiver no mesmo segmento do caso');
                    }
                }
            }
        }
    }

    public static Boolean hasHDEPermission() {
        List<PermissionSetAssignment> lstPermissionsAssigments = PermissionSetDAO.getAllPermissionSetByUserId(UserInfo.getUserId());
        Pattern regexPatternPerformance = Pattern.compile('\\b.*Performance.*\\b'); 
        Pattern regexPatternProcess = Pattern.compile('\\bHDE.*Processos.*Escalonamento\\b'); 
        Boolean hasAtLeastAHDEPermission = false;
        Boolean hasAtLeastPerfomancePermission = false;
        for(PermissionSetAssignment iPerm : lstPermissionsAssigments){
            Matcher matcherProcess = regexPatternProcess.matcher(iPerm.PermissionSet.Label); //Regex para validar se tem as palavras 'HDE' e 'Processos' e 'Escalonamento' na permission Set 
            Matcher matcherPerformance = regexPatternPerformance.matcher(iPerm.PermissionSet.Label); //Regex para validar se tem a palavra 'Perfomance' na permission Set 
            if (matcherProcess.find()) {
                hasAtLeastAHDEPermission = true;
            } else if (matcherPerformance.find()){
                hasAtLeastPerfomancePermission = true;
            }
        }

        return hasAtLeastPerfomancePermission && hasAtLeastAHDEPermission;
    }

    public static void fillMapWithAvailableSegments(Map<String, List<Id>> mapUserSegment, List<FromToMapping__mdt> lstSegmentsAvailable, List<User> lstAllUserWithSegment) {
        for (FromToMapping__mdt iFromMdt : lstSegmentsAvailable) {
            for (Integer i = 0; i < lstAllUserWithSegment.size(); i++) {
                if (iFromMdt.OriginApiName__c == lstAllUserWithSegment[i].PartnerGroup__c) {
                    if (mapUserSegment.containsKey(iFromMdt.OperatorSegment__c)) {
                        List<Id> lstUserTemp = mapUserSegment.get(iFromMdt.OperatorSegment__c);
                        lstUserTemp.add(lstAllUserWithSegment[i].Id);
                        mapUserSegment.put(iFromMdt.OperatorSegment__c, lstUserTemp);
                    } else{
                        mapUserSegment.put(iFromMdt.OperatorSegment__c, new List<Id> {lstAllUserWithSegment[i].Id});
                    }
                    lstAllUserWithSegment.remove(i);
                }
            }
        }
    }
}