force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Origem do caso, pode ser via App Vivo, Call Center ou Lojas</description>
    <label>Canal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerInteractionTopicTree__c.field-meta.xml
<CustomField>
    <fullName>CustomerInteractionTopicTree__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Árvore de Palitagem</label>
    <referenceTo>CustomerInteractionTopicTree__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/CustomerInteractionTopicTree__c.object-meta.xml
<CustomObject>
    <label>Árvore de Palitagem</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Árvore de Palitagem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ParentTopicId__c.field-meta.xml
<CustomField>
    <fullName>ParentTopicId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Topic Id</description>
    <label>Palito Pai</label>
    <referenceTo>CustomerInteractionTopicTree__c</referenceTo>
    <relationshipLabel>Palitos Filhos</relationshipLabel>
    <relationshipName>ParentTopic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
                <label>Pós/Controle</label>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <label>Fixa</label>
            </value>
            <value>
                <fullName>Pre</fullName>
                <label>Pré</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ServiceTree__c.field-meta.xml
<CustomField>
    <fullName>ServiceTree__c</fullName>
    <label>Árvore de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
                <label>Atendimento</label>
            </value>
            <value>
                <fullName>DigitalChannels</fullName>
                <label>Canais Digitais</label>
            </value>
            <value>
                <fullName>Retention</fullName>
                <label>Retenção</label>
            </value>
            <value>
                <fullName>Hybrid</fullName>
                <label>Híbrido</label>
            </value>
            <value>
                <fullName>Ombudsman</fullName>
                <label>Ouvidoria</label>
            </value>
            <value>
                <fullName>Store</fullName>
                <label>Loja</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Campo criado para desenvolvimento de POC</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pasta</fullName>
            </value>
            <value>
                <fullName>Palito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TopicsAuto__c/TopicsAuto__c.object-meta.xml
<CustomObject>
    <label>Palitagem Automática</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Palitagens Automáticas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TopicsAuto__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lojas Próprias</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Revenda</fullName>
            </value>
            <value>
                <fullName>Integração</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TopicsAuto__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Data Inativação</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TopicsAuto__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <label>Ponto de Palitagem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agendamento Extrato Recorrente</fullName>
            </value>
            <value>
                <fullName>Ajuste de Saldo</fullName>
            </value>
            <value>
                <fullName>Alteração Dados Contatos</fullName>
            </value>
            <value>
                <fullName>Alteração Dados do Contato Principal</fullName>
            </value>
            <value>
                <fullName>Alteração Dados Pessoais</fullName>
            </value>
            <value>
                <fullName>Alteração das Permissões de Contato</fullName>
            </value>
            <value>
                <fullName>Alteração de Endereço da Linha</fullName>
            </value>
            <value>
                <fullName>Antecipação da Promoção</fullName>
                <isActive>false</isActive>
                <label>Antecipação da Promoção</label>
            </value>
            <value>
                <fullName>Antecipação de Promoção</fullName>
            </value>
            <value>
                <fullName>Associação de cadastro</fullName>
            </value>
            <value>
                <fullName>Ativação de Serviços Avançados</fullName>
            </value>
            <value>
                <fullName>Ativação do Crédito Antecipado</fullName>
            </value>
            <value>
                <fullName>Ativar / Desativar Promoção</fullName>
            </value>
            <value>
                <fullName>Autorizar doação Estorno de Port In</fullName>
            </value>
            <value>
                <fullName>Bloqueio a Pedido</fullName>
            </value>
            <value>
                <fullName>Bloqueio Perda e Roubo</fullName>
            </value>
            <value>
                <fullName>Cadastrar Cliente</fullName>
            </value>
            <value>
                <fullName>Cadastro Linha Sem Cadastro</fullName>
            </value>
            <value>
                <fullName>Cancelamento de Linha</fullName>
            </value>
            <value>
                <fullName>Cancelamento Extrato Recorrente</fullName>
            </value>
            <value>
                <fullName>Consulta de Antecipação de Crédito</fullName>
            </value>
            <value>
                <fullName>Consulta de Compartilhamento de Dados</fullName>
            </value>
            <value>
                <fullName>Consulta de Notas Fiscais</fullName>
            </value>
            <value>
                <fullName>Consulta de Notificações</fullName>
            </value>
            <value>
                <fullName>Consulta Histórico de Eventos</fullName>
            </value>
            <value>
                <fullName>Consulta Histórico de Operações</fullName>
            </value>
            <value>
                <fullName>Consulta Histórico de Promoções</fullName>
            </value>
            <value>
                <fullName>Consulta PUK</fullName>
            </value>
            <value>
                <fullName>Consultar Consumo de Mensagens, Voz, Bonus</fullName>
            </value>
            <value>
                <fullName>Desativação de Serviços Avançados</fullName>
            </value>
            <value>
                <fullName>Tranferência de Titularidade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TopicsAuto__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Ativação</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TopicsAuto__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Palito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TopicsAuto__c/fields/TopicId__c.field-meta.xml
<CustomField>
    <fullName>TopicId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Palito Id</label>
    <referenceTo>CustomerInteractionTopicTree__c</referenceTo>
    <relationshipName>Palito</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TopicsAuto__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Topic-Utilizado para a criação de palitagem automática e interação.
Case-Utilizado para a criação de um caso com palitagem automática e interação.
API-Utilizado para a criação de um caso sem interação, somente com mapeamento de palitagem.</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topic</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateTopicsAutoReleaseSetembro2024.cls
/* -------------------------------------------------------------------------
* Autor....: Guilherme Kaiser - Deloitte
* Projeto..: Vivo - VALENTINA
* Descrição: script criado para criar palitos automáticos RELEASE SETEMBRO 2024
* Data.....: 27/05/2024
* --------------------------------------------------------------------------
* A T E N Ç Ã O : ESTE SCRIPT É APENAS PARA INCLUSÃO DE REGISTROS NA TABELA TOPICSAUTO__C - EXECUTAR APENAS 1 VEZ
* --------------------------------------------------------------------------
* Definição de valores de campo:
* Process__c   -> Nome do Ponto de palitagem a ser utilizado(funcionalidade)
* Channel__c   -> {Lojas Próprias, Revenda, Call Center, Integração}
* Status__c    -> {Ativo, Inativo}
* Topic__c     -> path completo do palito na árvore de palitagem (palito já deve estar cadastrado)
* Type__c      -> {Topic, API, Case}
* StartDate__c -> Data e hora criação
* EndDate__c   -> Data e hora desativação (quando criar sempre passar nulo)
* TopicId__c   -> Id do palito na árvore (CustomerInteractionTopicTree__c.Id). Preenchido automáticamente por esse script.
* --------------------------------------------------------------------------
* Alterações
*  -------------------------------------------------------------------------
* Data: 27/05/2024
* Palitos (Processo): Ajuste de Saldo - Atendimento, Ajuste de Saldo - Lojas/Revendas
* Bloco/Jornada/US: Bloco 15/J65/US1234 - Ressarcimento
*  -------------------------------------------------------------------------
* Data:   /  /2024
* Palitos (Processo): ..., ..., ...
* Bloco/Jornada/US: Bloco 99/J99/US1234 - nome jornada
*  -------------------------------------------------------------------------
*
*/

public class CreateTopicsAutoReleaseSetembro2024 {   
    //
    public CreateTopicsAutoReleaseSetembro2024() {
    //
    // Create a list of TopicsAuto__c to add
    //
    List<TopicsAuto__c> topicsAutoList = new List<TopicsAuto__c> {
         new TopicsAuto__c(Process__c= 'Ajuste de Saldo'                   ,Channel__c= 'Lojas Próprias',Status__c= 'Ativo',StartDate__c= datetime.now(),EndDate__c=  null,Topic__c= 'Início > Incidências > Créditos > Cartão Pré Pago > Divergência de Saldo',Type__c= 'Case')
        ,new TopicsAuto__c(Process__c= 'Ajuste de Saldo'                   ,Channel__c= 'Revenda'       ,Status__c= 'Ativo',StartDate__c= datetime.now(),EndDate__c=  null,Topic__c= 'Início > Incidências > Créditos > Cartão Pré Pago > Divergência de Saldo',Type__c= 'Case')
        ,new TopicsAuto__c(Process__c= 'Ajuste de Saldo'                   ,Channel__c= 'Call Center'   ,Status__c= 'Ativo',StartDate__c= datetime.now(),EndDate__c=  null,Topic__c= 'Início > Incidências > Créditos > Saldo > Saldo Divergente',Type__c= 'Case')
        ,new TopicsAuto__c(Process__c= 'Tranferência de Titularidade'      ,Channel__c= 'Lojas Próprias',Status__c= 'Ativo',StartDate__c= datetime.now(),EndDate__c=  null,Topic__c= 'Início > Serviços Loja > Transferência de Titularidade',Type__c= 'Topic')
        ,new TopicsAuto__c(Process__c= 'Tranferência de Titularidade'      ,Channel__c= 'Revenda'       ,Status__c= 'Ativo',StartDate__c= datetime.now(),EndDate__c=  null,Topic__c= 'Início > Serviços Loja > Transferência de Titularidade',Type__c= 'Topic')
        ,new TopicsAuto__c(Process__c= 'Tranferência de Titularidade'      ,Channel__c= 'Call Center'   ,Status__c= 'Ativo',StartDate__c= datetime.now(),EndDate__c=  null,Topic__c= 'Início > Serviços > Cadastro > Transferência de Titularidade',Type__c= 'Topic')
//      ,new TopicsAuto__c(Process__c= 'Recusa de xxxxxxxxxxxxxxxxx',Channel__c= 'Integração',Status__c= 'Ativo',StartDate__c= datetime.now(),EndDate__c=  null,Topic__c= 'Início > Incidências > Portabilidade Numérica > Status > Erros',Type__c= 'API')

    };
                
    String key;
    String serviceTree;
    String channel='';
    
    Map<String, CustomerInteractionTopicTree__c> mapTree = new Map<String, CustomerInteractionTopicTree__c>(); 
    List<CustomerInteractionTopicTree__c> lstTree =[select Id, Name, ParentTopicId__c, Type__c, ServiceTree__c from CustomerInteractionTopicTree__c where  (ProductType__c= 'Pre' and Active__c= true) or (name='Início' and ParentTopicId__c =null)];
    List<TopicsAuto__c> newLstTree = new List<TopicsAuto__c>();
    
    for(CustomerInteractionTopicTree__c topic : lstTree) {
        if(topic.name.Trim()=='Início'){
        	key = 'ParentTopicId__c='+topic.ParentTopicId__c+'|name='+topic.name+'|type__c='+topic.type__c;
        } else{
        	key = 'ParentTopicId__c='+topic.ParentTopicId__c+'|name='+topic.name+'|type__c='+topic.type__c+'|serviceTree__c='+topic.serviceTree__c;
        }
        mapTree.put(key, topic);
    }

    for(TopicsAuto__c obj : topicsAutoList) {
    
        Integer sizelstAlpha;
        Integer idxCurrent =0;
        String source;
        
        List<String> lstAlpha = obj.Topic__c.split('>');
        sizelstAlpha = lstAlpha.Size();
       
        switch on obj.Channel__c {
            when 'Lojas Próprias'
            {Channel='Lojas Proprias';serviceTree='Store';}
            when 'Revenda'
            {Channel='Lojas Revendas';serviceTree='Store';}            
            when 'Call Center'        
            {Channel='Call Center';serviceTree='Service';}
        }
       
        for(String topicItem : lstAlpha){
            idxCurrent++;
            String type = idxCurrent!=sizelstAlpha ? 'Pasta' : 'Palito';
                
            
            if(topicItem.Trim()=='Início' &&idxCurrent==1){
                key = 'ParentTopicId__c='+source+'|name='+topicItem.Trim()+'|type__c='+type;
            }else{
                key = 'ParentTopicId__c='+source+'|name='+topicItem.Trim()+'|type__c='+type+'|serviceTree__c='+serviceTree;
            }
            
            if(mapTree.containsKey(key)){
                CustomerInteractionTopicTree__c recordTree = mapTree.get(key);
                source = (String) recordTree.get('Id');
                if(type=='Palito'){
                    obj.TopicId__c=source;
                    newLstTree.Add(obj);
                }
            }
        }
    }
    // Bulk update all TopicsAuto__c with one DML call
    Database.insert(newLstTree);
    }
}