force-app/main/default/objects/Case/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Observação</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CaseComment__c/CaseComment__c.object-meta.xml
<CustomObject>
    <description>This object corresponds to the &quot;Chat App Vivo&quot;, which records a conversation between the service operator and the b2c customer. It is displayed on the Cases screen in the &quot;Minhas Solicitações&quot; flow: Ajuda com cobrança, Ajuda com fatura ou cobrança, Ajuda com o Pedido, Mudança do Endereço de Instalação, Problema com Portabilidade, Problemas com Recarga.</description>
    <label>Comentário do Caso</label>
    <nameField>
        <displayFormat>CC-{000000000}</displayFormat>
        <label>Número do Comentário do Caso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CaseComments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseComment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CaseComment__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <defaultValue>(&quot;App Vivo&quot;)</defaultValue>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>App Vivo</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseComment__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentId</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>CaseComment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseCommetTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CaseCommetTriggerHandlerTest {

    @isTest
    static void updateParentCasesTest() {
        Case caseObj = new Case();
        caseObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(CasesMyRequestsB2C.CHARGE_OF_ADDRESS_RECORD_TYPE_API_NAME).getrecordTypeId();
        caseObj.Status = 'Aguardando informação';
        insert caseObj;

        CaseComment__c caseCommetObj = new CaseComment__c();
        caseCommetObj.ParentId__c = caseObj.Id;
        caseCommetObj.Comment__c = 'Message from customer';
        caseCommetObj.Origin__c = 'App Vivo';
        insert caseCommetObj;

        Case updatedCaseObj = [SELECT Id, Status, OwnerId FROM Case WHERE Id =: caseObj.Id];
        String waitingforRoutingQueueId = CasesMyRequestsB2CService.getWaitingForRoutingQueueId();

        Assert.areEqual('Em fila', updatedCaseObj.Status);
        Assert.areEqual(waitingforRoutingQueueId, updatedCaseObj.OwnerId);
    }
}