force-app/main/default/objects/Case/fields/ComplainedAsset__c.field-meta.xml
<CustomField>
    <fullName>ComplainedAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Para uso do HDE</description>
    <inlineHelpText>Terminal, TV ou Banda Larga</inlineHelpText>
    <label>Produto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O produto adicionado está incorreto ou não está relacionado ao cliente.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Asset.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerInteractionTopicTree__c.field-meta.xml
<CustomField>
    <fullName>CustomerInteractionTopicTree__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Árvore de Palitagem</label>
    <referenceTo>CustomerInteractionTopicTree__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseDetail__c/CaseDetail__c.object-meta.xml
<CustomObject>
    <description>Objeto auxiliar ao objeto Caso (Case), que armazena os campos das jornadas de minhas solicitações recebidos através do fluxo do App Vivo. Projeto Minhas Solicitações PTI4728</description>
    <label>Detalhe do Caso</label>
    <nameField>
        <displayFormat>DC - {00000000}</displayFormat>
        <label>Número do Detalhe do Caso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalhes dos Casos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseDetail__c/fields/LastSourceSystemAgent__c.field-meta.xml
<CustomField>
    <fullName>LastSourceSystemAgent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo indica quem foi o último atendente a trabalhar no seu caso. Ao registrar essa informação, conseguimos acompanhar melhor o histórico de atendimento.</description>
    <label>Último agente do sistema origem</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CaseDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/CustomerInteractionTopicTree__c.object-meta.xml
<CustomObject>
    <label>Árvore de Palitagem</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Árvore de Palitagem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CasesMyRequestsB2CService.cls
public with sharing class CasesMyRequestsB2CService
{
    public static void validateDuplicates(List<Case> newCases)
    {
        Set<String> newCasesSignatures = new Set<String>();
        Set<Id> accountsIds = new Set<Id>();
        Set<Id> assetsIds = new Set<Id>();
        Set<Id> topicTreeIds = new Set<Id>();

        for (Case newCase: newCases)
        {
            String newCaseSignature = CasesMyRequestsB2CService.generateCaseSignature(newCase);
            newCasesSignatures.add(newCaseSignature);
            accountsIds.add(newCase.AccountId);
            assetsIds.add(newCase.ComplainedAsset__c);
            topicTreeIds.add(newCase.CustomerInteractionTopicTree__c);
        }

        Set<String> exceptStatuses = new Set<String>{'Cancelado', 'Expirado', 'Closed'};

        List<Case> existingActiveCases = CaseDAO.getBy(accountsIds, assetsIds, topicTreeIds, exceptStatuses);
        
        for (Case existingActiveCase : existingActiveCases)
        {
            String existingActiveCaseSignature = CasesMyRequestsB2CService.generateCaseSignature(existingActiveCase);
            if (newCasesSignatures.contains(existingActiveCaseSignature))
            {
                for (Case newCase : newCases)
                {
                    String newCaseSignature = CasesMyRequestsB2CService.generateCaseSignature(newCase);
                    if (newCaseSignature == existingActiveCaseSignature)
                    {
                        newCase.addError('Existe um Caso semelhante ativo com ID: ' + existingActiveCase.Id);
                        break;
                    }
                }
            }
        }
    }

    // Método para gerar uma assinatura do caso
    private static String generateCaseSignature(Case c)
    {
        String signature = '';
        String emptyString = '';
        signature += c.AccountId != null ? (String) c.AccountId : emptyString;
        signature += c.ComplainedAsset__c != null ? (String) c.ComplainedAsset__c : emptyString;
        signature += c.CustomerInteractionTopicTree__c != null ? (String) c.CustomerInteractionTopicTree__c : emptyString;
        return signature;
    }

    public static List<Case> getNewCases(List<Case> newCases, Map<Id, Case> oldCases)
    {
        List<Case> confirmedNewCases = new List<Case>();
        for (Case caseRec : newCases)
        {
            Case oldCaseRec = oldCases.get(caseRec.Id);
            if (oldCaseRec != null) { continue; }
            confirmedNewCases.add(caseRec);
        }
        return confirmedNewCases;
    }

    public static List<Case> getCasesWithUpdatedStatus(List<Case> newCases, Map<Id,Case> oldCases)
    {
        List<Case> casesWithUpdatedStatus = new List<Case>();
        for (Case newCase : newCases)
        {
            Case oldCase = oldCases.get(newCase.Id);
            if (isSameRecord(newCase, oldCase) && isStatusChanged(newCase, oldCase))
            {
                casesWithUpdatedStatus.add(newCase);
            } 
        }
        return casesWithUpdatedStatus;
    }

    private static Boolean isStatusChanged(Case newCase, Case oldCase)
    {
        return newCase.Status != oldCase.Status;
    }

    private static Boolean isSameRecord(Case newCase, Case oldCase)
    {
        return newCase.Id == oldCase.Id;
    }
 
    public static String determineTemplateId(String status)
    {
        String templateId;
        switch on status {
            when 'Expirado' {
                templateId = 'EMAIL_MS_SOLICITACAO_EXPIRADA';
            }
            when 'New' {
                templateId = 'EMAIL_MS_SOLICITACAO_ABERTA';
            }
            when 'Aguardando informação' {
                templateId = 'EMAIL_MS_SOLICITACAO_AGUARDANDO_RESPOSTA';
            }
            when 'Closed' {
                templateId = 'EMAIL_MS_SOLICITACAO_CONCLUIDA';
            }
        }
        return templateId;
    }

    public static String getWaitingForRoutingQueueId() {
        return GroupDAO.getQueueByName('WaitingforRouting').get(0).Id;
    }

    public static boolean isCaseStatusValidForQueue(String status) {
        return status.equals('Em fila') 
            || status.equals('Aguardando informação')
            || status.equals('Escalated')
            || status.equals('Cancelamento solicitado');
    }

    public static boolean isCaseOwnerValidForQueue(Case newCaseObj, Case oldCase) {
        return newCaseObj.OwnerId == oldCase.OwnerId;
    }

    public static boolean isCaseStatusValidForRouting(String status) {
        return status.equals('Em fila') || status.equals('Cancelamento solicitado');
    }

    public static void changeCaseOwner(Case caseObj, String  queueId) {
        caseObj.OwnerId = queueId;
    }

    public static void putTheCaseInTheRouting(Case caseObj, String  queueId) {
        caseObj.Status = 'Em fila';
    }

    public static Boolean theCaseHasAlreadyBeenHandledByAnAgent(CaseDetail__c caseDetailRec) {
        return caseDetailRec?.LastSourceSystemAgent__c != null;
    }
}