force-app/main/default/objects/Case/fields/ContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ContactPhone__c</fullName>
    <label>Telefone de Contato</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/AltEndpoint__c.field-meta.xml
<CustomField>
    <fullName>AltEndpoint__c</fullName>
    <label>AltEndpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/AppKey__c.field-meta.xml
<CustomField>
    <fullName>AppKey__c</fullName>
    <label>App Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Aplicação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/AsyncLogServiceTransaction__c.field-meta.xml
<CustomField>
    <fullName>AsyncLogServiceTransaction__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Caso o campo esteja marcado, o log na Service Transaction será feito de maneira assíncrona.</description>
    <label>Log assíncrono na service transaction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <label>Certificado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/CommitTransactionsList__c.field-meta.xml
<CustomField>
    <fullName>CommitTransactionsList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salvar logs em lista</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ExpireIn__c.field-meta.xml
<CustomField>
    <fullName>ExpireIn__c</fullName>
    <label>Expire In</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/HasAuthToken__c.field-meta.xml
<CustomField>
    <fullName>HasAuthToken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui Token de Autenticação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/HasJWT__c.field-meta.xml
<CustomField>
    <fullName>HasJWT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui JWT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/LogServiceTransaction__c.field-meta.xml
<CustomField>
    <fullName>LogServiceTransaction__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caso esse campo esteja marcado como true, será salvo o log da operação na Service Transaction.</description>
    <label>Salvar log de service transaction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceAccountUser__c.field-meta.xml
<CustomField>
    <fullName>ServiceAccountUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Account User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>Nome do Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceOperation__c.field-meta.xml
<CustomField>
    <fullName>ServiceOperation__c</fullName>
    <label>Operação de Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>ServiceProvider__c</fullName>
    <label>Provedor de serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <label>Validade dos dados da consulta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Versão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NotificadorPushSMS.cls
public with sharing class NotificadorPushSMS implements Queueable, Database.AllowsCallouts {

    private static final String WEBSERVICE_NAME = 'KafkaEvents';
    private String selectedCaseId;
    @TestVisible
    private static String requestBody;

    public NotificadorPushSMS(String selectedCaseId) {
        this.selectedCaseId = selectedCaseId;
    }

    public NotificadorPushSMS() {}

    public static String buildRequestBody(String selectedCaseId) {
        Case selectedCase = [SELECT Id, Account.Name, Status, AccountId, Document__c, CreatedDate, ContactPhone__c, RecordType.DeveloperName, RecordType.Name, Protocol__c 
                             FROM Case WHERE Id =: selectedCaseId];

        if (String.isBlank(selectedCase.ContactPhone__c))
            throw new MyRequestNotificationException('Caso não possui contato cadastrado');

        NotificadorPushSMS.RequestWrapper requestBody = new NotificadorPushSMS.RequestWrapper();
        UUID randomUUID = UUID.randomUUID();
        requestBody.ID_EVENT = String.valueOf(randomUUID);

        // Document of the account of the case
        requestBody.KEY = selectedCase.Document__c; 
        // Constant
        requestBody.KEY_TYPE = '2';
        // Constant that varies according to the Status of the case
        if(selectedCase.Status == 'Expirado') {
            requestBody.ID_EVENT_TYPE = '519';
        } else if(selectedCase.Status == 'Closed') {
            requestBody.ID_EVENT_TYPE = '520';
        } else if(selectedCase.Status == 'Aguardando informação') {
            requestBody.ID_EVENT_TYPE = '516';
        }
        // Case creation date
        DateTime caseDateTime = selectedCase.CreatedDate;
        String formattedDate = caseDateTime.format('dd/MM/yyyy');
        requestBody.DT_EVENT = formattedDate; 
        // Case creation DateTime
        requestBody.DTTM_EVENT = String.valueOf(selectedCase.CreatedDate.format('dd/MM/yyyy hh:mm:ss.SSS a')); 
        // Constant
        requestBody.ID_SOURCE_TYPE = '1';
        // Contact phone of the case
        requestBody.DS_EVENT_ADD1 = String.valueOf(selectedCase.ContactPhone__c).remove('+');
        // First name of the account of the case
        requestBody.DS_EVENT_ADD2 = (selectedCase.Account.Name).split(' ')[0];
        // RecordType of the case
        requestBody.DS_EVENT_ADD3 = selectedCase.RecordType.DeveloperName;
        requestBody.DS_EVENT_ADD4 = selectedCase.Id;
        requestBody.DS_EVENT_ADD5 = selectedCase.Protocol__c;

        return JSON.serialize(requestBody);
    }

    public void execute(QueueableContext context) {
        sendNotification(this.selectedCaseId);
    }

    public HttpResponse sendNotification(String selectedCaseId) {
        // Select the Custom Setting with the callout data and add the path to the endPoint
        Webservice__c wsConfig = [SELECT Id, IsDeleted, Name, SetupOwnerId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, AccessToken__c, AltEndpoint__c, AppKey__c, Application__c, Certificate__c, CommitTransactionsList__c, Endpoint__c, ExpireIn__c, HasAuthToken__c, HasJWT__c, Headers__c, Password__c, ServiceName__c, ServiceOperation__c, ServiceProvider__c, SubscriptionKey__c, Timeout__c, User__c, Validate__c, Version__c, switchedOn__c, ServiceAccountUser__c, AsyncLogServiceTransaction__c, LogServiceTransaction__c FROM Webservice__c WHERE Name =: WEBSERVICE_NAME];
        wsConfig.Endpoint__c = wsConfig.Endpoint__c + '/SF-TICKET-UPDATE-SAS';
        wsConfig.Headers__c = wsConfig.Headers__c + ';x-4p-provider:SF-TICKET-UPDATE-SAS';

        String jsonBody = NotificadorPushSMS.buildRequestBody(selectedCaseId);
        HttpClient client = new HttpClient();
        HttpResponse response = client.post(wsConfig, jsonBody);
        requestBody = jsonBody;
        return response;
    }

    private class RequestWrapper {
        public String ID_EVENT;
        public String KEY;
        public String KEY_TYPE;
        public String ID_EVENT_TYPE;
        public String DT_EVENT;
        public String DTTM_EVENT;
        public String ID_SOURCE_TYPE;
        public String DS_EVENT_ADD1;
        public String DS_EVENT_ADD2;
        public String DS_EVENT_ADD3;
        public String DS_EVENT_ADD4;
        public String DS_EVENT_ADD5;
    }
}