force-app/main/default/objects/Case/fields/ContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ContactPhone__c</fullName>
    <label>Telefone de Contato</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/ChangeOfAddress.recordType-meta.xml
<RecordType>
    <fullName>ChangeOfAddress</fullName>
    <active>true</active>
    <businessProcess>Minhas Solicitações</businessProcess>
    <description>Caso pertencente ao fluxo de Minhas Solicitações para realizar o atendimento das solicitações abertas pelos clientes através de Canais Digitais, como exemplo o App Vivo.</description>
    <label>Mudança do Endereço de Instalação</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Helpwithbilling.recordType-meta.xml
<RecordType>
    <fullName>Helpwithbilling</fullName>
    <active>true</active>
    <businessProcess>Minhas Solicitações</businessProcess>
    <description>Caso pertencente ao fluxo de Minhas Solicitações para realizar o atendimento das solicitações abertas pelos clientes através de Canais Digitais, como exemplo o App Vivo.</description>
    <label>Ajuda com Cobrança</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/HelpWithTheOrder.recordType-meta.xml
<RecordType>
    <fullName>HelpWithTheOrder</fullName>
    <active>true</active>
    <businessProcess>Minhas Solicitações</businessProcess>
    <description>Caso pertencente ao fluxo de Minhas Solicitações para realizar o atendimento das solicitações abertas pelos clientes através de Canais Digitais, como exemplo o App Vivo.</description>
    <label>Ajuda com o Pedido</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ProblemWithPortability.recordType-meta.xml
<RecordType>
    <fullName>ProblemWithPortability</fullName>
    <active>true</active>
    <businessProcess>Minhas Solicitações</businessProcess>
    <description>Caso pertencente ao fluxo de Minhas Solicitações para realizar o atendimento das solicitações abertas pelos clientes através de Canais Digitais, como exemplo o App Vivo.</description>
    <label>Problema com Portabilidade</label>
</RecordType>

force-app/main/default/objects/MyRequests__c/MyRequests__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configurações personalizadas de Minhas Solicitações</description>
    <label>Minhas Solicitações</label>
</CustomObject>

force-app/main/default/objects/MyRequests__c/fields/AppVivoRedirectURL__c.field-meta.xml
<CustomField>
    <fullName>AppVivoRedirectURL__c</fullName>
    <description>URL para deep link utilizado em requisições no App Vivo.</description>
    <label>URL de Redirecionamento App Vivo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/AltEndpoint__c.field-meta.xml
<CustomField>
    <fullName>AltEndpoint__c</fullName>
    <label>AltEndpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/AppKey__c.field-meta.xml
<CustomField>
    <fullName>AppKey__c</fullName>
    <label>App Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Aplicação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/AsyncLogServiceTransaction__c.field-meta.xml
<CustomField>
    <fullName>AsyncLogServiceTransaction__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Caso o campo esteja marcado, o log na Service Transaction será feito de maneira assíncrona.</description>
    <label>Log assíncrono na service transaction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <label>Certificado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/CommitTransactionsList__c.field-meta.xml
<CustomField>
    <fullName>CommitTransactionsList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salvar logs em lista</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ExpireIn__c.field-meta.xml
<CustomField>
    <fullName>ExpireIn__c</fullName>
    <label>Expire In</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/HasAuthToken__c.field-meta.xml
<CustomField>
    <fullName>HasAuthToken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui Token de Autenticação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/HasJWT__c.field-meta.xml
<CustomField>
    <fullName>HasJWT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui JWT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/LogServiceTransaction__c.field-meta.xml
<CustomField>
    <fullName>LogServiceTransaction__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Caso esse campo esteja marcado como true, será salvo o log da operação na Service Transaction.</description>
    <label>Salvar log de service transaction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceAccountUser__c.field-meta.xml
<CustomField>
    <fullName>ServiceAccountUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Account User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>Nome do Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceOperation__c.field-meta.xml
<CustomField>
    <fullName>ServiceOperation__c</fullName>
    <label>Operação de Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>ServiceProvider__c</fullName>
    <label>Provedor de serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <label>Validade dos dados da consulta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Versão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NotificadorCallOut.cls
public with sharing class NotificadorCallOut implements Queueable, Database.AllowsCallouts {

    private static final String WEBSERVICE_NAME = 'KafkaEvents';
    private String selectedCaseId;
    private GATILHO_DISPARO_NOTIFICACAO triggerType;
    @TestVisible
    private static String requestBody;
    private static final String CALLOUT_ACTION_URL = 'AppVivoCalloutActionUrl';
    public static final List<String> listMascRecordTypes = new List<String>{
        'ProblemWithPortability'

    };

    public static final List<String> listFemRecordTypes = new List<String>{
        'Helpwithbilling',
        'ChangeOfAddress',
        'HelpWithTheOrder'
    };

    public NotificadorCallOut(String selectedCaseId, GATILHO_DISPARO_NOTIFICACAO triggerType) {
        this.selectedCaseId = selectedCaseId;
        this.triggerType = triggerType;
    }

    public NotificadorCallOut(GATILHO_DISPARO_NOTIFICACAO triggerType) {
        this.triggerType = triggerType;
    }

    public String buildRequestBody(String selectedCaseId) {
        Case selectedCase = [SELECT Id, Status, AccountId, Account.Name, Document__c, CreatedDate, ContactPhone__c, RecordType.DeveloperName, RecordType.Name, Protocol__c 
                             FROM Case WHERE Id =: selectedCaseId];
        
        if (String.isBlank(selectedCase.ContactPhone__c))
            throw new MyRequestNotificationException('Caso não possui contato cadastrado');
        
        NotificadorCallOut.RequestWrapper requestBody = new NotificadorCallOut.RequestWrapper();
        // Try to find the user profile of the account associated with this case
        List<UserProfileTO> listUserProfiles = UserProfileService.getUserProfileByAccountId(selectedCase.AccountId);
        requestBody.user_id = listUserProfiles[0].id;

        String accountFirstName = selectedCase.Account.Name.split(' ')[0];
        String recordTypeDevName = String.valueOf(selectedCase.RecordType.DeveloperName);
        String recordTypeName = String.valueOf(selectedCase.RecordType.Name);

        // Title, description, and button name of the callout, which will be defined according to the Status and type of case
        String calloutDescription;
        String calloutTitle;
        String actionName;

        if(this.triggerType == GATILHO_DISPARO_NOTIFICACAO.STATUS_CASO) {
            if(selectedCase.Status == 'Aguardando Informação') {
                calloutTitle = 'Estamos esperando seu retorno';
                actionName = 'Responder';
    
                if(listFemRecordTypes.contains(recordTypeDevName)) {
                    calloutDescription = buildMessageTypeOne(accountFirstName, recordTypeName, 'fem');
                } else if(listMascRecordTypes.contains(recordTypeDevName)) {
                    calloutDescription = buildMessageTypeOne(accountFirstName, recordTypeName, 'masc'); 
                }
            } else if(selectedCase.Status == 'Closed') {
                calloutTitle = 'Sua solicitação foi concluída';
                actionName = 'Acessar';
    
                if(listFemRecordTypes.contains(recordTypeDevName)) {
                    calloutDescription = buildMessageTypeTwo(accountFirstName, recordTypeName, 'fem');
                } else if(listMascRecordTypes.contains(recordTypeDevName)) {
                    calloutDescription = buildMessageTypeTwo(accountFirstName, recordTypeName, 'masc');
                }
            }
        } else if(this.triggerType == GATILHO_DISPARO_NOTIFICACAO.BOTAO_NOTIFICAR_CLIENTE) {
            calloutTitle = 'Sua solicitação foi atualizada';
            actionName = 'Acessar';

            if(listFemRecordTypes.contains(recordTypeDevName)) {
                calloutDescription = buildMessageTypeOne(accountFirstName, recordTypeName, 'fem');
            } else if(listMascRecordTypes.contains(recordTypeDevName)) {
                calloutDescription = buildMessageTypeOne(accountFirstName, recordTypeName, 'masc');  
            }
        }

        requestBody.name = calloutTitle;
        requestBody.description = calloutDescription;
        requestBody.status = recordTypeDevName;
        requestBody.type = 'ticket_update';
        requestBody.view = 'true';
        DateTime caseDateTime = selectedCase.CreatedDate;
        String formattedDate = caseDateTime.format('yyyy-MM-dd\'T\'HH:mm:ss.SSSSSS\'Z\'');
        requestBody.creation_date = formattedDate;         
        // List of identifiers for the request (initially only passing the contact phone of the case)
        requestBody.identifiers = new List<String>();
        requestBody.identifiers.add(String.valueOf(selectedCase.ContactPhone__c));
        // List of actions for the request: actionName is the button name and the url is the redirection url
        requestBody.actions = new List<NotificadorCallOut.Actions>();
        NotificadorCallOut.Actions newAction = new NotificadorCallOut.Actions();
        newAction.name = actionName;
        newAction.type = 'url';
        newAction.url = getRedirectUrl(CALLOUT_ACTION_URL);
        newAction.main_action = true;
        requestBody.actions.add(newAction);

        return JSON.serialize(requestBody);
    }

    public void execute(QueueableContext context) {
        sendNotification(this.selectedCaseId);
    }

    public HttpResponse sendNotification(String selectedCaseId) {
        // Select the Custom Setting with the callout data and add the path to the endPoint
        Webservice__c wsConfig = [SELECT Id, IsDeleted, Name, SetupOwnerId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, AccessToken__c, AltEndpoint__c, AppKey__c, Application__c, Certificate__c, CommitTransactionsList__c, Endpoint__c, ExpireIn__c, HasAuthToken__c, HasJWT__c, Headers__c, Password__c, ServiceName__c, ServiceOperation__c, ServiceProvider__c, SubscriptionKey__c, Timeout__c, User__c, Validate__c, Version__c, switchedOn__c, ServiceAccountUser__c, AsyncLogServiceTransaction__c, LogServiceTransaction__c FROM Webservice__c WHERE Name =: WEBSERVICE_NAME];
        wsConfig.Endpoint__c = wsConfig.Endpoint__c + '/SF-TICKET-UPDATE';
        wsConfig.Headers__c = wsConfig.Headers__c + ';x-4p-provider:SF-TICKET-UPDATE';

        String jsonBody = buildRequestBody(selectedCaseId);
        HttpClient client = new HttpClient();
        HttpResponse response = client.post(wsConfig, jsonBody);
        requestBody = jsonBody;
        return response;
    }

    public static String buildMessageTypeOne(String accountFirstName, String recordTypeName, String gender) {
        if(gender == 'masc') {
            return accountFirstName + ', você tem uma nova mensagem para seu ' + recordTypeName.toLowerCase(); 
        } else if(gender == 'fem') {
            return accountFirstName + ', você tem uma nova mensagem para sua ' + recordTypeName.toLowerCase(); 
        }

        return null;
    }

    
    public static String buildMessageTypeTwo(String accountFirstName, String recordTypeName, String gender) {
        if(gender == 'masc') {
            return accountFirstName + ', seu ' + recordTypeName.toLowerCase() + ' foi resolvido'; 
        } else if(gender == 'fem') {
            return accountFirstName + ', sua ' + recordTypeName.toLowerCase() + ' foi resolvida'; 
        }

        return null;
    }

    private String getRedirectUrl(String instanceName) {
        return MyRequests__c.getInstance(instanceName)?.AppVivoRedirectURL__c;
    }

    public class RequestWrapper {
        public String user_id;
        public String name;
        public String description;
        public String status;
        public String type;
        public String view;
        public String creation_date;
        public List<String> identifiers;
        public List<Actions> actions;
    }

    public class Actions {
        public String name;
        public String type;
        public String url;
        public Boolean main_action;
    }
}