force-app/main/default/objects/Case/fields/HDEOtherProducts__c.field-meta.xml
<CustomField>
    <fullName>HDEOtherProducts__c</fullName>
    <label>Outros Produtos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsHDE__c.field-meta.xml
<CustomField>
    <fullName>IsHDE__c</fullName>
    <formula>CONTAINS(RecordType.Name, &quot;HDE&quot;)</formula>
    <label>É do HDE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Campo utilizado na parametrização de casos de alta complexidade e críticos no custom metadata HDE DE-PARA, para dependencias de campos e para campos fórmula no objeto. ex: visão</description>
    <label>Grupo de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
                <label>Revendas</label>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>VPR Lojas</fullName>
            </value>
            <value>
                <fullName>V</fullName>
                <isActive>false</isActive>
                <label>V</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/View__c.field-meta.xml
<CustomField>
    <fullName>View__c</fullName>
    <formula>CASE( RecordType.DeveloperName+text(Segment__c),
&quot;EmailTriggerVivo V&quot;, &quot;CRI E-mail V&quot;,
&quot;GoldProcessesEscalationGold&quot;, &quot;CRI Escalonamento Gold&quot;,
&quot;PurpuraProcessesEscalationPúrpura&quot;, &quot;CRI Escalonamento Púrpura&quot;,	
&quot;SilverProcessesEscalationSilver&quot;, &quot;CRI Escalonamento Silver&quot;,					
&quot;StoreProcessesEscalationLoja&quot;, &quot;CRI Escalonamento Loja&quot;,
&quot;ResellerStoreProcessesEscalationLojas (Revendas)&quot;, &quot;CRI Escalonamento Lojas (Revendas)&quot;,					
&quot;PlatinumProcessesEscalationPlatinum&quot;, &quot;CRI Escalonamento Platinum&quot;,
&quot;PrimeProcessesEscalationPrime&quot;, &quot;CRI Escalonamento Prime&quot;,
&quot;OuvidoriaProcessesEscalationOuvidoria&quot;, &quot;CRI Escalonamento Ouvidoria&quot;,
&quot;CommunityOuvidoriaProcessesEscalationOuvidoria Comunidades&quot;, &quot;CRI Escalonamento Ouvidoria Comunidades&quot;,					
&quot;VivoVProcessesEscalationVivo V&quot;, &quot;CRI Escalonamento V&quot;,
&quot;CallSupervisorVivo V&quot;, &quot;CRI Supervisor V&quot;,
&quot;EscalationAndLawSuitsVivo V&quot;, &quot;CRI Escalonamento V&quot;,
&quot;EscalationAndLawSuitsGold&quot;, &quot;CRI Escalonamento Gold&quot;,
&quot;EscalationAndLawSuitsPlatinum&quot;, &quot;CRI Escalonamento Platinum&quot;,
&quot;EscalationAndLawSuitsLoja&quot;, &quot;CRI Escalonamento Loja&quot;,
&quot;EscalationAndLawSuitsPrime&quot;, &quot;CRI Escalonamento Prime&quot;,
&quot;EscalationAndLawSuitsOuvidoria&quot;, &quot;CRI Escalonamento Ouvidoria&quot;,

&quot;&quot;
)</formula>
    <label>Visão</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/EmailTrigger.recordType-meta.xml
<RecordType>
    <fullName>EmailTrigger</fullName>
    <active>true</active>
    <businessProcess>HDE</businessProcess>
    <description>Chamado gestão de casos de tratativas exclusivas via e-mail (exclusivo grupo de atendimento V</description>
    <label>HDE - Acionamento E-mail</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/HDETask.recordType-meta.xml
<RecordType>
    <fullName>HDETask</fullName>
    <active>true</active>
    <description>Tipo de registro para usuários do HDE</description>
    <label>HDE - Tarefa</label>
</RecordType>

force-app/main/default/classes/TaskTriggerTest.cls
@isTest
public with sharing class TaskTriggerTest {

    @testSetup 
    static void setup(){

        UserRole userR = new UserRole();
        userR.Name = 'GoldFixa';
        Database.insert(userR);
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Representante'];
        User u = new User(Alias = 'SysAdmin', Email='stdstdteste@teste.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId = userR.Id,
                          TimeZoneSidKey='America/Sao_Paulo', UserName='stdteste@teste.com');
        Database.insert(u);
        System.runAs(u){

            Account account1 = DataFactory.createAccount();
            insert account1;

            //Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('EmailTrigger').getRecordTypeId();
            
            Case case1 = new Case();
            case1.RecordTypeId = [Select Id,SobjectType,Name From RecordType WHERE Name ='HDE - Acionamento E-mail' and SobjectType ='Case'  limit 1].Id;
            case1.Origin = 'HDE';
            case1.Subject = 'TestCase';
            //case1.Segment__c = 'Gold';
            case1.AccountId = account1.Id;
            case1.HDEOtherProducts__c = 'TV';
            insert case1;
            
            Task task1 = new Task();
            //task1.AccountId = account1.Id;
            task1.WhatId = case1.Id;
            task1.RecordTypeId = [Select Id,SobjectType,Name From RecordType WHERE Name ='HDE - Tarefa' and SobjectType ='Task'  limit 1].Id;
            task1.Subject = 'Cobrar Gerente';
            task1.View__c = 'CRI E-mail V';
            //task1.IsHDE__c = TRUE;
            //task1.RecordType.DeveloperName = 'HDETask';
            task1.Status = 'Aberto';
            insert task1;


        }

    }

    static testmethod void testPreventTaskDel(){

        User u = [SELECT id FROM User WHERE UserName = 'stdteste@teste.com' LIMIT 1];

        System.runAs(u){

            Task taskRecord = [SELECT Id FROM Task WHERE IsHDE__c = TRUE LIMIT 1];

            try{
                delete taskRecord;

            }catch(DMLexception e){
                system.assert(e.getMessage().contains('Você não tem permissão para excluir a tarefa'),'Você não tem permissão para excluir a tarefa');                       
            }
        }
    }
}