force-app/main/default/objects/Case/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Campo utilizado na parametrização de casos de alta complexidade e críticos no custom metadata HDE DE-PARA, para dependencias de campos e para campos fórmula no objeto. ex: visão</description>
    <label>Grupo de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
                <label>Revendas</label>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>VPR Lojas</fullName>
            </value>
            <value>
                <fullName>V</fullName>
                <isActive>false</isActive>
                <label>V</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/FromToMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para ser utilizado para inclusão de de/para que serão utilizados na Org.</description>
    <label>Mapeamento DePara</label>
    <pluralLabel>Mapeamento DePara</pluralLabel>
</CustomObject>

force-app/main/default/objects/FromToMapping__mdt/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <description>Segmento do operador utilizado no de-para do componente de atendimento.</description>
    <label>Segmento do Operador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
                <default>true</default>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Omnichannel</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>Revenda</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
            </value>
            <value>
                <fullName>Suporte a Lojas</fullName>
            </value>
            <value>
                <fullName>Televendas</fullName>
            </value>
            <value>
                <fullName>Atendimento</fullName>
            </value>
            <value>
                <fullName>Backoffice</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Retencao</fullName>
            </value>
            <value>
                <fullName>Purpura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/fields/OriginApiName__c.field-meta.xml
<CustomField>
    <fullName>OriginApiName__c</fullName>
    <description>ApiName do campo desejado origem</description>
    <label>ApiName do campo Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChangeOwnerHDEEngine.cls
public with sharing class ChangeOwnerHDEEngine {
    
    public static List<User> getUserByRole(Id caseId){

        Case caseFields = CaseDAO.getCasebyId(caseId);
        Map<String, FromToMapping__mdt> mappingRoles = FromToMapping__mdt.getAll();
        Set<String> caseRoles = new Set<String>();

        for(FromToMapping__mdt role : mappingRoles.values()){
            if(role.OperatorSegment__c == caseFields.Segment__c){
                caseRoles.add(role.OriginApiName__c);
            }
        }

        List<User> allowedUsers = UserDAO.getUserByRole(caseRoles);

        return allowedUsers;

    }

}