force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>InAnalisys</fullName>
                <label>Em análise</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Encerrado</label>
            </value>
            <value>
                <fullName>Concession</fullName>
                <label>Concessão</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Procedente</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <label>Improcedente</label>
            </value>
            <value>
                <fullName>Contested</fullName>
                <label>Contestado</label>
            </value>
            <value>
                <fullName>Impugned</fullName>
                <label>Impugnado</label>
            </value>
            <value>
                <fullName>Partially Impugned</fullName>
                <label>Impugnado Parcial</label>
            </value>
            <value>
                <fullName>Does Not Proceed</fullName>
                <label>Não Procede</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>Not Contested</fullName>
                <label>Não Contestado</label>
            </value>
            <value>
                <fullName>Impugnation Limit Reached</fullName>
                <label>Limite de Impugnações Atingido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisputeCheckLast45Days.cls
public with sharing class DisputeCheckLast45Days {
    @InvocableMethod(label='Existe contestação nos últimos 45 dias?')
    public static LIST<DisputeCheckLast45DaysOutputs> checkLast45Days(LIST<DisputeCheckLast45DaysInputs> parameters){
        LIST<DisputedItem__c> disputeLast45Days = DisputedItemDAO.getDisputeLast45Days(parameters.get(0).accountId, parameters.get(0).description);
        List<DisputeCheckLast45DaysOutputs> listResult = new List<DisputeCheckLast45DaysOutputs>();
        DisputeCheckLast45DaysOutputs result =  new DisputeCheckLast45DaysOutputs();
        
        result.checaContestacao = disputeLast45Days.size() > 0 ? 'Sim' : 'Não';
        result.checaNegada = 'Não';
        
        if(result.checaContestacao == 'Sim'){
            for (DisputedItem__c dispute : disputeLast45Days) {
                if (dispute.Status__c == 'Denied'){
                    result.checaNegada = 'Sim';
                }
            }
        }
        listResult.add(result);
        return listResult;
    }

    public class DisputeCheckLast45DaysInputs{
        @InvocableVariable
        public String accountId;
    
        @InvocableVariable
        public String description;
    }

    public class DisputeCheckLast45DaysOutputs{
        @InvocableVariable
        public String checaContestacao;
    
        @InvocableVariable
        public String checaNegada;
    }
}