force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedItem__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens Contestados</relationshipLabel>
    <relationshipName>DisputedItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/fields/IsConcession__c.field-meta.xml
<CustomField>
    <fullName>IsConcession__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Concessão</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>InAnalisys</fullName>
                <label>Em análise</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Encerrado</label>
            </value>
            <value>
                <fullName>Concession</fullName>
                <label>Concessão</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Procedente</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <label>Improcedente</label>
            </value>
            <value>
                <fullName>Contested</fullName>
                <label>Contestado</label>
            </value>
            <value>
                <fullName>Impugned</fullName>
                <label>Impugnado</label>
            </value>
            <value>
                <fullName>Partially Impugned</fullName>
                <label>Impugnado Parcial</label>
            </value>
            <value>
                <fullName>Does Not Proceed</fullName>
                <label>Não Procede</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>Not Contested</fullName>
                <label>Não Contestado</label>
            </value>
            <value>
                <fullName>Impugnation Limit Reached</fullName>
                <label>Limite de Impugnações Atingido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisputeFixedFlowConcessionVerifier.cls
public with sharing class DisputeFixedFlowConcessionVerifier {

    public class DisputeCheckConcessionInLast180Days {
        @InvocableVariable
        public String caseAccountId;

        @InvocableVariable
        public String caseId;
    }
    
    @InvocableMethod(label='Cliente possui concessão nos últimos 180 dias?')
    public static List<String> customerHasConcessionInLast180Days(List<DisputeCheckConcessionInLast180Days> parameters) {
        Id caseAccountId = parameters.get(0).caseAccountId;
        Id caseId = parameters.get(0).caseId;
        
        List<String> results = new List<String>();
        
        List<DisputedItem__c> disputedItems = [
            SELECT
        		Id,
				Name,
				Status__c,
				IsConcession__c
			FROM
                DisputedItem__c
            WHERE
                CaseId__r.AccountId =: caseAccountId AND
                Status__c != 'InAnalisys' AND
                Status__c != 'NotStarted' AND
                IsConcession__c = True AND
                CreatedDate >= LAST_N_DAYS:180 AND
                CaseId__c != :caseId
		];
        
        results.add(disputedItems.size() > 0 ? 'Sim' : 'Não');
        return results;
    }
    
}