force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedItem__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens Contestados</relationshipLabel>
    <relationshipName>DisputedItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DisputedItemControllerTest.cls
@isTest
public with sharing class DisputedItemControllerTest {
    @isTest
    public static void getByCaseId(){
        Case nuCase = new Case();
        insert nuCase;

        DisputedItem__c nuItem = new DisputedItem__c();
        nuItem.CaseId__c = nuCase.id;
        insert nuItem;

        Test.startTest();
            List<DisputedItem__c> result =  DisputedItemController.getByCaseId(nuCase.Id);
        Test.stopTest();

        System.assert(result.size()>0);

    }
}