force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedItem__c/fields/AvailableAmount__c.field-meta.xml
<CustomField>
    <fullName>AvailableAmount__c</fullName>
    <label>Valor Atual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens Contestados</relationshipLabel>
    <relationshipName>DisputedItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>InAnalisys</fullName>
                <label>Em análise</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Encerrado</label>
            </value>
            <value>
                <fullName>Concession</fullName>
                <label>Concessão</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Procedente</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <label>Improcedente</label>
            </value>
            <value>
                <fullName>Contested</fullName>
                <label>Contestado</label>
            </value>
            <value>
                <fullName>Impugned</fullName>
                <label>Impugnado</label>
            </value>
            <value>
                <fullName>Partially Impugned</fullName>
                <label>Impugnado Parcial</label>
            </value>
            <value>
                <fullName>Does Not Proceed</fullName>
                <label>Não Procede</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>Not Contested</fullName>
                <label>Não Contestado</label>
            </value>
            <value>
                <fullName>Impugnation Limit Reached</fullName>
                <label>Limite de Impugnações Atingido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisputedItemController.cls
public class DisputedItemController {
    @AuraEnabled(cacheable=false)
    public static List<DisputedItem__c> getByCaseId(Id caseId) {
        return [
            select
            Id,
            Description__c,
            AvailableAmount__c,
            Status__c,
            toLabel(Status__c) statusLabel
            from DisputedItem__c 
            where CaseId__c =: caseId
        ];
    }
}