force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlowExecutionStepHistory__c/FlowExecutionStepHistory__c.object-meta.xml
<CustomObject>
    <label>Histórico de Execução de Fluxo</label>
    <nameField>
        <label>Step</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Execução de Fluxos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlowExecutionStepHistory__c/fields/DisputedItem__c.field-meta.xml
<CustomField>
    <fullName>DisputedItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Contestado</label>
    <referenceTo>DisputedItem__c</referenceTo>
    <relationshipLabel>Históricos de Execução de Fluxos</relationshipLabel>
    <relationshipName>Hist_ricos_de_Execu_o_de_Fluxos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/FromToMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para ser utilizado para inclusão de de/para que serão utilizados na Org.</description>
    <label>Mapeamento DePara</label>
    <pluralLabel>Mapeamento DePara</pluralLabel>
</CustomObject>

force-app/main/default/objects/FromToMapping__mdt/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <description>Segmento do operador utilizado no de-para do componente de atendimento.</description>
    <label>Segmento do Operador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
                <default>true</default>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Omnichannel</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>Revenda</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
            </value>
            <value>
                <fullName>Suporte a Lojas</fullName>
            </value>
            <value>
                <fullName>Televendas</fullName>
            </value>
            <value>
                <fullName>Atendimento</fullName>
            </value>
            <value>
                <fullName>Backoffice</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Retencao</fullName>
            </value>
            <value>
                <fullName>Purpura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/GeneralSetting__c.object-meta.xml
<CustomObject>
    <label>Configuração Geral</label>
    <nameField>
        <label>Configuração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralSetting__c/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <label>Segmento do Operador</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>LOJA</fullName>
            </value>
            <value>
                <fullName>OMNICHANNEL</fullName>
            </value>
            <value>
                <fullName>OUVIDORIA</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>PÚRPURA</fullName>
            </value>
            <value>
                <fullName>REVENDA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>SUPORTE A LOJAS</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
            <value>
                <fullName>VIVO V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/PartnerGroup__c.field-meta.xml
<CustomField>
    <fullName>PartnerGroup__c</fullName>
    <label>Grupo do Aliado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VendasAliado</fullName>
                <label>Vendas Aliado</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPConsultor</fullName>
                <label>Vendas Aliado PaP Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPGerente</fullName>
                <label>Vendas Aliado PaP Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaConsultor</fullName>
                <label>Vendas Aliado Revenda Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaGerente</fullName>
                <label>Vendas Aliado Revenda Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasGerente</fullName>
                <label>Vendas Aliado Televendas Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPSupervisor</fullName>
                <label>Vendas Aliado PaP Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasCoordenador</fullName>
                <label>Vendas Aliado Televendas Coordenador</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasSupervisor</fullName>
                <label>Vendas Aliado Televendas Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasConsultor</fullName>
                <label>Vendas Aliado Televendas Consultor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeOperador</fullName>
                <label>Atendimento Aliado Backoffice Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoOp</fullName>
                <label>Atendimento Aliado Backoffice Retencao Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoSup</fullName>
                <label>Atendimento Aliado Backoffice Retencao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeSupervisor</fullName>
                <label>Atendimento Aliado Backoffice Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Ativo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Ativo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaOperador</fullName>
                <label>Atendimento Aliado Ouvidoria Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaSupervisor</fullName>
                <label>Atendimento Aliado Ouvidoria Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingOp</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingSup</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Supervisor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisputeFixedFlowController.cls
public with sharing class DisputeFixedFlowController {
    @InvocableMethod(label='Funcionário tem Escopo?')
    public static LIST<String> DisputeCheckScope(LIST<DisputeCheckScopeInputs> parameters){
        GeneralSetting__c disputeScope = GeneralSettingDAO.getGeneralSettingbyName(parameters.get(0).Name,parameters.get(0).recortTypeName);
        User infoUser = UserDAO.getById(UserInfo.getUserId());
        FromToMapping__mdt fromToMap = FromToMappingDAO.getRecordByUsersRoleAndUsedIn(infoUser.Profile.UserLicense.name == 'Partner Community'? infoUser.PartnerGroup__c : infoUser.UserRole.DeveloperName , 'ServiceFlow');

        LIST<String> result =  new LIST<String>();
        result.add(disputeScope.OperatorSegment__c.contains(fromToMap.OperatorSegment__c.contains('Adm')? fromToMap.OperatorSegment__c : fromToMap.OperatorSegment__c.toUpperCase()) ? 'Sim' : 'Não');
        return result;
    }

    public class DisputeCheckScopeInputs{
        @InvocableVariable
        public String Name;
    
        @InvocableVariable
        public String recortTypeName;
    }
    @AuraEnabled()
    public static void restartFlow(String caseId){

        LIST<DisputedItem__c> itemsToDelete = DisputedItemDAO.getByCaseId(caseId);

        LIST<FlowExecutionStepHistory__c> stepsToDelete = FlowExecutionStepHistoryDAO.getByCaseId(caseId);
        
        try {
            delete itemsToDelete;
            delete stepsToDelete;
        } catch (DmlException e) {
            System.debug('restartFlow Error:'+ e);
        }
        
    }
}