force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedItem__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens Contestados</relationshipLabel>
    <relationshipName>DisputedItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>InAnalisys</fullName>
                <label>Em análise</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Encerrado</label>
            </value>
            <value>
                <fullName>Concession</fullName>
                <label>Concessão</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Procedente</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <label>Improcedente</label>
            </value>
            <value>
                <fullName>Contested</fullName>
                <label>Contestado</label>
            </value>
            <value>
                <fullName>Impugned</fullName>
                <label>Impugnado</label>
            </value>
            <value>
                <fullName>Partially Impugned</fullName>
                <label>Impugnado Parcial</label>
            </value>
            <value>
                <fullName>Does Not Proceed</fullName>
                <label>Não Procede</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>Not Contested</fullName>
                <label>Não Contestado</label>
            </value>
            <value>
                <fullName>Impugnation Limit Reached</fullName>
                <label>Limite de Impugnações Atingido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisputeCheckLast45DaysTest.cls
@isTest
public with sharing class DisputeCheckLast45DaysTest {
   
    @TestSetup
    static void makeData()
    {
        Account acc = new Account();
        acc.name = 'testDispute45Days';
        insert acc;

        Case case0 = new Case();
        case0.AccountId = acc.id;
        insert case0;

        DisputedItem__c itemEmAnalise = new DisputedItem__c();
        itemEmAnalise.CaseId__c = case0.id;
        itemEmAnalise.Description__c = 'itemEmAnalise';
        itemEmAnalise.Status__c = 'InAnalisys';
        insert itemEmAnalise;

        DisputedItem__c itemNegado = new DisputedItem__c();
        itemNegado.CaseId__c = case0.id;
        itemNegado.Description__c = 'itemNegado';
        itemNegado.Status__c = 'Denied';
        insert itemNegado;

        DisputedItem__c itemContestado = new DisputedItem__c();
        itemContestado.CaseId__c = case0.id;
        itemContestado.Description__c = 'itemContestado'; 
        itemNegado.Status__c = 'Approved';
        insert itemContestado;
    }
    
    @isTest
    static void disputeCheckLast45DaysDenied()
    {
        DisputeCheckLast45Days.DisputeCheckLast45DaysInputs parameters = new DisputeCheckLast45Days.DisputeCheckLast45DaysInputs();
        List<DisputeCheckLast45Days.DisputeCheckLast45DaysInputs> inputs = new List<DisputeCheckLast45Days.DisputeCheckLast45DaysInputs>();
        parameters.accountId = [SELECT Id FROM Account WHERE Account.Name = 'testDispute45Days' LIMIT 1].Id;
        parameters.description = 'itemNegado';
        inputs.add(parameters);

        Test.startTest();
        List<DisputeCheckLast45Days.DisputeCheckLast45DaysOutputs> result = DisputeCheckLast45Days.checkLast45Days(inputs);
        Test.stopTest();

        System.assertEquals(result.get(0).checaContestacao, 'Sim');
        System.assertEquals(result.get(0).checaNegada, 'Sim');
    }

    @isTest
    static void disputeCheckLast45DaysInAnalysis()
    {
        DisputeCheckLast45Days.DisputeCheckLast45DaysInputs parameters = new DisputeCheckLast45Days.DisputeCheckLast45DaysInputs();
        List<DisputeCheckLast45Days.DisputeCheckLast45DaysInputs> inputs = new List<DisputeCheckLast45Days.DisputeCheckLast45DaysInputs>();
        parameters.accountId = [SELECT Id FROM Account WHERE Account.Name = 'testDispute45Days' LIMIT 1].Id;
        parameters.description = 'itemEmAnalise';       
        inputs.add(parameters); 
        
        Test.startTest();
        List<DisputeCheckLast45Days.DisputeCheckLast45DaysOutputs> result = DisputeCheckLast45Days.checkLast45Days(inputs);
        Test.stopTest();

        System.assertEquals(result.get(0).checaContestacao, 'Não');
        System.assertEquals(result.get(0).checaNegada, 'Não');
    }

    @isTest
    static void disputeCheckLast45DaysContested()
    {
        DisputeCheckLast45Days.DisputeCheckLast45DaysInputs parameters = new DisputeCheckLast45Days.DisputeCheckLast45DaysInputs();
        List<DisputeCheckLast45Days.DisputeCheckLast45DaysInputs> inputs = new List<DisputeCheckLast45Days.DisputeCheckLast45DaysInputs>();
        parameters.accountId = [SELECT Id FROM Account WHERE Account.Name = 'testDispute45Days' LIMIT 1].Id;
        parameters.description = 'itemContestado';
        inputs.add(parameters);
        
        Test.startTest();
        List<DisputeCheckLast45Days.DisputeCheckLast45DaysOutputs> result = DisputeCheckLast45Days.checkLast45Days(inputs);
        Test.stopTest();
        
        System.assertEquals(result.get(0).checaContestacao, 'Sim');
        System.assertEquals(result.get(0).checaNegada, 'Não');
    }
}