force-app/main/default/objects/Case/recordTypes/DisputeInvoiceCase.recordType-meta.xml
<RecordType>
    <fullName>DisputeInvoiceCase</fullName>
    <active>true</active>
    <businessProcess>DisputeInvoiceCase</businessProcess>
    <description>Tipo de registro específico para os Casos gerados através do Fluxo de Contestação de Faturas.</description>
    <label>Contestação de Fatura</label>
</RecordType>

force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedItem__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens Contestados</relationshipLabel>
    <relationshipName>DisputedItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>InAnalisys</fullName>
                <label>Em análise</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Encerrado</label>
            </value>
            <value>
                <fullName>Concession</fullName>
                <label>Concessão</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Procedente</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <label>Improcedente</label>
            </value>
            <value>
                <fullName>Contested</fullName>
                <label>Contestado</label>
            </value>
            <value>
                <fullName>Impugned</fullName>
                <label>Impugnado</label>
            </value>
            <value>
                <fullName>Partially Impugned</fullName>
                <label>Impugnado Parcial</label>
            </value>
            <value>
                <fullName>Does Not Proceed</fullName>
                <label>Não Procede</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>Not Contested</fullName>
                <label>Não Contestado</label>
            </value>
            <value>
                <fullName>Impugnation Limit Reached</fullName>
                <label>Limite de Impugnações Atingido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting On Someone Else</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Interrupted</fullName>
                <label>Interrompido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloseCasesBatchTest.cls
@isTest
private class CloseCasesBatchTest {

    @testSetup
    static void setupTestData() {
        List<Case> testCases = new List<Case>();
        for(Integer i = 0; i < 3; i++) {
            Case newCase = new Case(
                Subject = 'Caso de Teste ' + i,
                Status = 'Em Atendimento',
                RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('DisputeInvoiceCase').getRecordTypeId()
            );
            testCases.add(newCase);
        }
        for(Integer i = 3; i < 6; i++) {
            Case newCase = new Case(
                Subject = 'Caso de Teste ' + i,
                Status = 'InTransfer',
                RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('DisputeInvoiceCase').getRecordTypeId()
            );
            testCases.add(newCase);
        }
        for(Integer i = 6; i < 9; i++) {
            Case newCase = new Case(
                Subject = 'Caso de Teste ' + i,
                Status = 'Consulting',
                RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('DisputeInvoiceCase').getRecordTypeId()
            );
            testCases.add(newCase);
        }
        insert testCases;
        
        for (Case c : testCases) {
    		Test.setCreatedDate(c.Id, DateTime.now().addDays(-1));
		}

        List<DisputedItem__c> disputedItems = new List<DisputedItem__c>();
        for (Case c : testCases) {
            DisputedItem__c newItem = new DisputedItem__c(
                Name = 'Item Contestado para ' + c.Subject,
                CaseId__c = c.Id, 
                Status__c = 'InAnalisys'
            );
            disputedItems.add(newItem);
        }
        insert disputedItems;

        List<vlocity_cmt__CustomerInteraction__c> customerInteractions = new List<vlocity_cmt__CustomerInteraction__c>();
        List<vlocity_cmt__CustomerInteractionTopic__c> interactionTopics = new List<vlocity_cmt__CustomerInteractionTopic__c>();
        for (Case c : testCases) {
            vlocity_cmt__CustomerInteraction__c newInteraction = new vlocity_cmt__CustomerInteraction__c(
                vlocity_cmt__Status__c = 'In Progress'
            );
            customerInteractions.add(newInteraction);
        }
        insert customerInteractions;
        
        for (Integer i = 0; i < customerInteractions.size(); i++) {
            vlocity_cmt__CustomerInteraction__c interaction = customerInteractions[i];
            Case relatedCase = testCases[i];

            vlocity_cmt__CustomerInteractionTopic__c topic = new vlocity_cmt__CustomerInteractionTopic__c(
                vlocity_cmt__CustomerInteractionId__c = interaction.Id,
                vlocity_cmt__CaseId__c = relatedCase.Id
            );
            interactionTopics.add(topic);
        }
        insert interactionTopics;
    }

    @isTest
    static void testBatchWithNoMatchingCases() {
        delete [SELECT Id FROM Case];

        Test.startTest();

        CloseCasesBatch batch = new CloseCasesBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        List<Case> updatedCases = [SELECT Id, Status FROM Case];
        System.assert(updatedCases.isEmpty(), 'Nenhum Caso deve ser atualizado');
    }
    
    @isTest
    static void testBatchWithMatchingCases() {
        Test.startTest();
        CloseCasesBatch.start();
        Test.stopTest();
   		List<Case> updatedCases = [SELECT Status FROM Case];
        for (Case c : updatedCases) {
            if (c.Status == 'InTransfer' || c.Status == 'Consulting') {
                System.assertEquals('TransferInterrupted', c.Status, 'Status do Caso deve ser TransferInterrupted');
            } else if (c.Status == 'Em Atendimento') {
                System.assertEquals('InterruptedFlow', c.Status, 'Status do Caso deve ser InterruptedFlow');
            }
        }

		List<vlocity_cmt__CustomerInteraction__c> updatedInteractions = [SELECT Id, vlocity_cmt__Status__c FROM vlocity_cmt__CustomerInteraction__c];
        System.assert(updatedInteractions.size() > 0, 'Nenhuma Customer Interaction foi atualizada');
        for (vlocity_cmt__CustomerInteraction__c interaction : updatedInteractions) {
            System.assertEquals('Interrupted', interaction.vlocity_cmt__Status__c, 'Status da Customer Interaction não foi atualizado para Interrupted');
        }

		List<DisputedItem__c> updatedItems = [SELECT Id, Status__c FROM DisputedItem__c];
        System.assert(updatedItems.size() > 0, 'Nenhum Item Contestado atualizado');
        for (DisputedItem__c item : updatedItems) {
            System.assertEquals('Closed', item.Status__c, 'Status do Item Contestado não foi atualizado para Closed');
        }
    }
}