force-app/main/default/objects/Case/recordTypes/VivoVProcessesEscalation.recordType-meta.xml
<RecordType>
    <fullName>VivoVProcessesEscalation</fullName>
    <active>true</active>
    <businessProcess>HDE</businessProcess>
    <description>Chamado gestão de casos para solução de Causa Raiz, Escalonamento, Acompanhamento e Gestão expectativa Cliente</description>
    <label>HDE - V Processos Escalonamento</label>
</RecordType>

force-app/main/default/objects/GeneralSetting__c/GeneralSetting__c.object-meta.xml
<CustomObject>
    <label>Configuração Geral</label>
    <nameField>
        <label>Configuração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationEmailToNCases__c.field-meta.xml
<CustomField>
    <fullName>NotificationEmailToNCases__c</fullName>
    <label>Notificação Email para N Casos</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationEmailToOneCase__c.field-meta.xml
<CustomField>
    <fullName>NotificationEmailToOneCase__c</fullName>
    <label>Notificação E-mail para Um Caso</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationLittleBellToNCases__c.field-meta.xml
<CustomField>
    <fullName>NotificationLittleBellToNCases__c</fullName>
    <label>Notificação Sininho para N Casos</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationLittleBellToOneCase__c.field-meta.xml
<CustomField>
    <fullName>NotificationLittleBellToOneCase__c</fullName>
    <label>Notificação Sininho para um Caso</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationName__c.field-meta.xml
<CustomField>
    <fullName>NotificationName__c</fullName>
    <label>Nome Notificação</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/TitleNotificationLittleBellToNCases__c.field-meta.xml
<CustomField>
    <fullName>TitleNotificationLittleBellToNCases__c</fullName>
    <label>Título Notificação Sininho para N Casos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/TitleNotificationLittleBellToOneCase__c.field-meta.xml
<CustomField>
    <fullName>TitleNotificationLittleBellToOneCase__c</fullName>
    <label>Título Notificação Sininho para um Caso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/recordTypes/UserComunicationSetup.recordType-meta.xml
<RecordType>
    <fullName>UserComunicationSetup</fullName>
    <active>true</active>
    <description>Configuração de Notificações de Usuários, informa o tipo de notificação/email que cada tipo de usuário deve receber dependendo do status, momento de trigger, recordtype do caso</description>
    <label>Configuração de Notificações de Usuários</label>
</RecordType>

force-app/main/default/classes/SenderCaseNotificationServiceTest.cls
@IsTest
public class SenderCaseNotificationServiceTest {

    @TestSetup
    static void setupTestData() {

        Id recordTpId = Schema.SObjectType.GeneralSetting__c.getRecordTypeInfosByDeveloperName().get('UserComunicationSetup').getRecordTypeId();
        List<GeneralSetting__c> generalSettings = new List<GeneralSetting__c>{
            new GeneralSetting__c(
            Name = 'CaseOpenedNotification',
            NotificationName__c = 'CaseOpenedNotification',
            NotificationLittleBellToOneCase__c = 'One case bell notification',
            NotificationLittleBellToNCases__c = 'Multiple cases bell notification',
            NotificationEmailToOneCase__c = 'One case email notification',
            NotificationEmailToNCases__c = 'Multiple cases email notification',
            TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases',
            TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one case',
            RecordTypeId = recordTpId),
            new GeneralSetting__c(
            Name = 'RoutingNewOwnerOwner',
            NotificationName__c = 'RoutingNewOwnerOwner',
            NotificationLittleBellToOneCase__c = 'One case bell notifications',
            NotificationLittleBellToNCases__c = 'Multiple cases bell notifications',
            NotificationEmailToOneCase__c = 'One case email notifications',
            NotificationEmailToNCases__c = 'Multiple cases email notifications',
            TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases n',
            TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one cases',
            RecordTypeId = recordTpId),
            new GeneralSetting__c(
            Name = 'RoutingNewOwnerOwnerCrítico',
            NotificationName__c = 'RoutingNewOwnerOwnerCrítico',
            NotificationLittleBellToOneCase__c = 'One case bell notificationsC',
            NotificationLittleBellToNCases__c = 'Multiple cases bell notificationsC',
            NotificationEmailToOneCase__c = 'One case email notificationsC',
            NotificationEmailToNCases__c = 'Multiple cases email notificationsC',
            TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases nC',
            TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one caseCs',
            RecordTypeId = recordTpId),
            new GeneralSetting__c(
            Name = 'ExpiredSLAUserAbove3rd',
            NotificationName__c = 'ExpiredSLAUserAbove3rd',
            NotificationLittleBellToOneCase__c = 'One case bell notificationsCx',
            NotificationLittleBellToNCases__c = 'Multiple cases bell notificationsCx',
            NotificationEmailToOneCase__c = 'One case email notificationsCx',
            NotificationEmailToNCases__c = 'Multiple cases email notificationsCx',
            TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases nCx',
            TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one caseCsx',
            RecordTypeId = recordTpId),
            new GeneralSetting__c(
            Name = 'ExpiredSLARoleOuvidoriaAdmPerformance',
            NotificationName__c = 'ExpiredSLARoleOuvidoriaAdmPerformance ',
            NotificationLittleBellToOneCase__c = 'One case bell notificationsCx',
            NotificationLittleBellToNCases__c = 'Multiple cases bell notificationsCx',
            NotificationEmailToOneCase__c = 'One case email notificationsCx',
            NotificationEmailToNCases__c = 'Multiple cases email notificationsCx',
            TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases nCx',
            TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one caseCsx',
            RecordTypeId = recordTpId),
            new GeneralSetting__c(
            Name = 'StatusChangeOwnerAtenção',
            NotificationName__c = 'StatusChangeOwnerAtenção',
            NotificationLittleBellToOneCase__c = 'One case bell notificationsCx',
            NotificationLittleBellToNCases__c = 'Multiple cases bell notificationsCx',
            NotificationEmailToOneCase__c = 'One case email notificationsCx',
            NotificationEmailToNCases__c = 'Multiple cases email notificationsCx',
            TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases nCx',
            TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one caseCsx',
            RecordTypeId = recordTpId),
            new GeneralSetting__c(
            Name = 'StatusChangeUserAbove2ndAtenção',
            NotificationName__c = 'StatusChangeUserAbove2ndAtenção',
            NotificationLittleBellToOneCase__c = 'One case bell notificationsCx',
            NotificationLittleBellToNCases__c = 'Multiple cases bell notificationsCx',
            NotificationEmailToOneCase__c = 'One case email notificationsCx',
            NotificationEmailToNCases__c = 'Multiple cases email notificationsCx',
            TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases nCx',
            TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one caseCsx',
            RecordTypeId = recordTpId)
        };

        insert generalSettings;

        Id userId = UserInfo.getUserId();
        Id recordTypeId = getCaseRecordTypeId('VivoVProcessesEscalation');

        // Insert test Cases
        List<Case> cases = new List<Case>{
            new Case(Status = 'A Iniciar', OwnerId = userId, RecordTypeId = recordTypeId),
            new Case(Status = 'Crítico', OwnerId = userId, RecordTypeId = recordTypeId),
            new Case(Status = 'A Iniciar', OwnerId = userId, RecordTypeId = recordTypeId)
        };
        insert cases;
    }

    static Id getCaseRecordTypeId(String developerName) {
        return Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(developerName).getRecordTypeId();
    }

  
    @IsTest
    static void testSendOnInsert() {
        List<Case> cases = [SELECT Id, CaseNumber, Status, OwnerId, RecordTypeId FROM Case];

        Test.startTest();
        SenderCaseNotificationService service = new SenderCaseNotificationService();
        
        service.sendOnInsert(cases);
        Test.stopTest();
    }

    @IsTest
    static void testSendOnUpdate() {
        List<Case> cases = [SELECT Id, CaseNumber, Status, OwnerId, RecordTypeId FROM Case];
        Map<Id, Case> oldCases = new Map<Id, Case>([SELECT Id, Status, OwnerId, RecordTypeId FROM Case]);
        
        cases.get(0).Status = 'Atenção';
        update cases;

        Test.startTest();
        SenderCaseNotificationService service = new SenderCaseNotificationService();
        
        service.sendOnUpdate(cases, oldCases);
        Test.stopTest();
    }

    @IsTest
    static void testSendOnFlowScheduled() {
        
        List<SenderCaseNotificationService.NoticationCaseModel> notificationModels = new List<SenderCaseNotificationService.NoticationCaseModel>();
        
        Case testCase = [SELECT Id, CaseNumber, Status,OwnerId, RecordTypeId FROM Case LIMIT 1];
        SenderCaseNotificationService.NoticationCaseModel model = new SenderCaseNotificationService.NoticationCaseModel();
        model.varCase = testCase;
        model.messageType = new List<String>{'CaseOpenedNotification'};
        
        notificationModels.add(model);

        Test.startTest();
        SenderCaseNotificationService.sendOnFlowScheduled(notificationModels);
        Test.stopTest();
    }

    @IsTest
    static void testSendToUsers() {
        
        List<Id> userIds = new List<Id>{ UserInfo.getUserId() };

        Test.startTest();
        SenderCaseNotification service = new SenderCaseNotification();
        service.sendToUsers(userIds);
        Test.stopTest();
    }

    @IsTest
    static void testSendMultipleCases() {
        List<Case> cases = [SELECT Id, CaseNumber, Status, OwnerId FROM Case LIMIT 3];

        Test.startTest();
        SenderCaseNotification sender = new SenderCaseNotification();
        sender.send(cases, 'CaseOpenedNotification', null);
        Test.stopTest();
    }

    @IsTest
    static void testSendStatusRot() {
        List<Case> cases = [SELECT Id, CaseNumber, Status, OwnerId FROM Case LIMIT 3];

        Test.startTest();
        SenderCaseNotificationService senderService = new SenderCaseNotificationService();
        SenderCaseNotification sender = new SenderCaseNotification();
        sender.sendHub(cases, 'ExpiredSLARoleOuvidoriaAdmPerformance', 'notification,Email,formerOwner,Supervisor,RotA,NewA', UserInfo.getUserId());
        Test.stopTest();
    }
    
    @IsTest
    static void testSendHubEmail() {
        List<Case> cases = [SELECT Id, CaseNumber, Status, OwnerId FROM Case LIMIT 1];

        Test.startTest();
        SenderCaseNotification sender = new SenderCaseNotification();

        sender.sendHub(cases, 'CaseOpenedNotification', 'email,NewA', null);
        Test.stopTest();
    }
}