force-app/main/default/objects/GeneralSetting__c/GeneralSetting__c.object-meta.xml
<CustomObject>
    <label>Configuração Geral</label>
    <nameField>
        <label>Configuração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralSetting__c/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <label>Segmento do Operador</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>LOJA</fullName>
            </value>
            <value>
                <fullName>OMNICHANNEL</fullName>
            </value>
            <value>
                <fullName>OUVIDORIA</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>PÚRPURA</fullName>
            </value>
            <value>
                <fullName>REVENDA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>SUPORTE A LOJAS</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
            <value>
                <fullName>VIVO V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GeneralSettingDAO.cls
public with sharing class GeneralSettingDAO {
    public static GeneralSetting__c getGeneralSettingbyName(String name, String recordTypeName) {
        return [
            SELECT    
                Id, 
                Name,
                OperatorSegment__c 
            FROM 
                GeneralSetting__c
            WHERE   
                Name = :name
            AND RecordType.DeveloperName = :recordTypeName    
        ];
    }
}