force-app/main/default/objects/PartialRenewalSteps__c/PartialRenewalSteps__c.object-meta.xml
<CustomObject>
    <label>Step de Renovação Parcial</label>
    <nameField>
        <label>Nome do Step</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps de Renovação Parcial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartialRenewalSteps__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Preço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os preços dos materias provenientes via carga de arquivo do SAP (materiais como Simcard, Aparelhos).</description>
    <label>Preço</label>
    <nameField>
        <displayFormat>Price-{0000000000}</displayFormat>
        <label>Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Armazena o valor da coluna Preço do arquivo SAP_NFO_PRECO.txt</description>
    <label>Preço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BalanceLineController.cls
global class BalanceLineController implements vlocity_cmt.VlocityOpenInterface2 {
    
    global Boolean invokeMethod(String methodName, Map<String, Object> inputMap, Map<String, Object> outputMap, Map<String, Object> optionMap) {
        
        Boolean success = true;
        String errors;

        try {
            switch on methodName {
                when 'getSmallStepValue' {
                    getSmallStepValue(inputMap, outputMap); 
                }
                when 'parseTextAmountToNumber' {
                    parseTextAmountToNumber(inputMap, outputMap); 
                }
            }

        } catch(Exception e) {
            errors = e.getMessage(); 
            success = false;
        }

        outputMap.put('success', success);
        outputMap.put('error', errors);

        return success;

    }

    @testVisible
    private void getSmallStepValue(Map<String, Object> inpMap, Map<String, Object> outMap) {

        List<PartialRenewalSteps__c> stepLst = (List<PartialRenewalSteps__c>) JSON.deserialize(JSON.serialize(inpMap.get('steps')), List<PartialRenewalSteps__c>.class);
        Decimal smallStepValue = null;

        for (PartialRenewalSteps__c step : stepLst) {
            if (String.isNotBlank(step.Price__c)) {
                Decimal price = parseTextToNumber(step.Price__c);
                if (smallStepValue > price) {
                    smallStepValue = price;
                } else if (smallStepValue == null) {
                    smallStepValue = price;
                }
            }
        }

        outMap.put('result', smallStepValue);

    }

    @testVisible
    private void parseTextAmountToNumber(Map<String, Object> inpMap, Map<String, Object> outMap) {

        Decimal textToNumber = parseTextToNumber(String.valueOf(inpMap.get('textAmount')));
        outMap.put('result', textToNumber);

    }

    @testVisible
    private Decimal parseTextToNumber(String text) {
        return Decimal.valueOf(text.replace('R$', '').replace(',', '.').trim());
    }

    class BalanceLineWrapper {

        String abbreviatedUnit;
        Decimal availableBalance;
        
    }

}