force-app/main/default/objects/ServiceRequest__c/ServiceRequest__c.object-meta.xml
<CustomObject>
    <description>Fluxo de abertura de chamados internos entre areas</description>
    <label>Solicitação de Serviço</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>Nome da Solicitação de Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitações de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>Em Andamento</label>
            </value>
            <value>
                <fullName>AnalysisComplete</fullName>
                <label>Análise Concluída</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/VivoMaestro_ID__c.field-meta.xml
<CustomField>
    <fullName>VivoMaestro_ID__c</fullName>
    <label>VivoMaestro ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/recordTypes/Tsuru.recordType-meta.xml
<RecordType>
    <fullName>Tsuru</fullName>
    <active>true</active>
    <label>Tsuru</label>
</RecordType>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/CommitTransactionsList__c.field-meta.xml
<CustomField>
    <fullName>CommitTransactionsList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salvar logs em lista</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ServiceRequestsHandlerTest.cls
@isTest
public class ServiceRequestsHandlerTest {

    @testSetup 
    static void setup() {
        // Configura o Custom Setting com um endpoint fictício para testes
        WebService__c wsSetting = new WebService__c();
        wsSetting.Name = 'CamundaTicketInformation';  // Defina um valor para o campo Name
        wsSetting.Endpoint__c = 'callout:APITelefonicaESim/camundaTicketInformation/v1';
        wsSetting.Timeout__c = 60000; // Valor fictício para o Timeout (Decimal)
        wsSetting.Headers__c = 'Authorization: Bearer token'; // Valor fictício para os Headers
        wsSetting.CommitTransactionsList__c = true; // Defina conforme necessário
         wsSetting.SubscriptionKey__c='re';
        insert wsSetting;

        // Criação do RecordType "HandlingInconsistencies"
        RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'Tsuru' AND SObjectType = 'ServiceRequest__c' LIMIT 1];

        // Criação de dados de teste no objeto ServiceRequest__c
        ServiceRequest__c sr = new ServiceRequest__c();
        sr.Status__c = 'NotStarted';
        sr.VivoMaestro_ID__c = '123456789';
        sr.OwnerId = UserInfo.getUserId();
        sr.RecordTypeId = rt.Id;
        insert sr;
 
        // Recupera o registro para obter o campo `Name` gerado
        sr = [SELECT Id, Name FROM ServiceRequest__c WHERE Id = :sr.Id LIMIT 1];
        
        // Use o registro para suas necessidades de teste
        System.debug('Record Name: ' + sr.Name);
    }

    @isTest
    static void testServiceRequestHandler() {
        // Adicione o Mock para simular a chamada da API
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
         ServiceRequestsHandler.ServicoDTO servico = new ServiceRequestsHandler.ServicoDTO();
        
        // Definindo valores para os atributos
        servico.motivo = 'Teste de Motivo';
        servico.nrSolicitacaoServico = '123456';
        servico.status = 'Pendente';
        servico.owner = true;
                ServiceRequest__c serviceRequests2 = [SELECT Id, Status__c, Name, VivoMaestro_ID__c, OwnerId FROM ServiceRequest__c WHERE Status__c = 'NotStarted' limit 1];

serviceRequests2.Status__c = 'InProgress';
        update serviceRequests2;
        List<ServiceRequest__c> serviceRequests = [SELECT Id, Status__c, Name, VivoMaestro_ID__c, OwnerId FROM ServiceRequest__c WHERE Status__c = 'InProgress'];

        Test.startTest();
        ServiceRequestsHandler.processServiceRequests(new list<String>{serviceRequests[0].id});
        Test.stopTest();

        // Verificações (assertions)
        // Exemplo: System.assertEquals(expected, actual, 'Mensagem de erro se a condição falhar');
    }

    // Classe de Mock para simular a resposta da API
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": "success"}');
            res.setStatusCode(200);
            return res;
        }
    }
}