force-app/main/default/objects/ServiceRequest__c/ServiceRequest__c.object-meta.xml
<CustomObject>
    <description>Fluxo de abertura de chamados internos entre areas</description>
    <label>Solicitação de Serviço</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>Nome da Solicitação de Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitações de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceRequest__c/fields/ServiceReason__c.field-meta.xml
<CustomField>
    <fullName>ServiceReason__c</fullName>
    <description>Motivo pelo qual o cliente acionou o personal ou foi acionado por ele.</description>
    <inlineHelpText>Motivo pelo qual o cliente acionou o personal ou foi acionado por ele.</inlineHelpText>
    <label>Motivo de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TypeOfService__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MassiveMonitoring</fullName>
                <label>Acompanhamento de Massiva</label>
            </value>
            <value>
                <fullName>RepairMonitoring</fullName>
                <label>Acompanhemento Reparo</label>
            </value>
            <value>
                <fullName>RegistrationChange</fullName>
                <label>Alteração Cadastral</label>
            </value>
            <value>
                <fullName>TVAquisition</fullName>
                <label>Aquisição TV</label>
            </value>
            <value>
                <fullName>LossTheftLock</fullName>
                <label>Bloqueio perda/roubo</label>
            </value>
            <value>
                <fullName>Welcoming</fullName>
                <label>Boas vindas</label>
            </value>
            <value>
                <fullName>PlanCancel</fullName>
                <label>Cancelar plano</label>
            </value>
            <value>
                <fullName>DeviceBuy</fullName>
                <label>Compra aparelho</label>
            </value>
            <value>
                <fullName>Contestation</fullName>
                <label>Contestação</label>
            </value>
            <value>
                <fullName>PlanDowngrade</fullName>
                <label>Downgrade plano</label>
            </value>
            <value>
                <fullName>ExplanationInvoiceWithErrorAlreadyCorrected</fullName>
                <label>Explicação fatura com erro já corrigida</label>
            </value>
            <value>
                <fullName>ExplanationInvoiceVariation</fullName>
                <label>Explicação variação fatura</label>
            </value>
            <value>
                <fullName>Invoice</fullName>
                <label>Fatura</label>
            </value>
            <value>
                <fullName>PlanInformation</fullName>
                <label>Informações plano</label>
            </value>
            <value>
                <fullName>EnterPaymentReconnect</fullName>
                <label>Informe pagamento/religue</label>
            </value>
            <value>
                <fullName>FixedInstallation</fullName>
                <label>Instalação Fixa</label>
            </value>
            <value>
                <fullName>OnlineStore</fullName>
                <label>Loja Online</label>
            </value>
            <value>
                <fullName>MyVivo</fullName>
                <label>Meu Vivo</label>
            </value>
            <value>
                <fullName>TechnologyMigration</fullName>
                <label>Migração Tecnologia</label>
            </value>
            <value>
                <fullName>AddressChange</fullName>
                <label>Mudança de Endereço</label>
            </value>
            <value>
                <fullName>DelayedInvoiceNegociation</fullName>
                <label>Negociação fatura em atraso</label>
            </value>
            <value>
                <fullName>NewHighFxedCustomer</fullName>
                <label>Nova alta cliente fixa</label>
            </value>
            <value>
                <fullName>NewHighMobileCustomer</fullName>
                <label>Nova alta cliente móvel</label>
            </value>
            <value>
                <fullName>DataSharingOrientation</fullName>
                <label>Orientação compartilhamento dados</label>
            </value>
            <value>
                <fullName>FraudOrientation</fullName>
                <label>Orientação Fraude</label>
            </value>
            <value>
                <fullName>ChipQualificationOrientation</fullName>
                <label>Orientação Habilitação Chip</label>
            </value>
            <value>
                <fullName>RomingUseOrientation</fullName>
                <label>Orientação uso Roaming</label>
            </value>
            <value>
                <fullName>VivoTravelOrientation</fullName>
                <label>Orientação Vivo Travel</label>
            </value>
            <value>
                <fullName>VivoValorizeOrientation</fullName>
                <label>Orientação Vivo Valoriza</label>
            </value>
            <value>
                <fullName>OtherTDNA</fullName>
                <label>Outros TDNAs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>Em Andamento</label>
            </value>
            <value>
                <fullName>AnalysisComplete</fullName>
                <label>Análise Concluída</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/VivoMaestro_ID__c.field-meta.xml
<CustomField>
    <fullName>VivoMaestro_ID__c</fullName>
    <label>VivoMaestro ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceRequestsHandler.cls
public with sharing class ServiceRequestsHandler {
    public class ServicoDTO {
      public String motivo { get; set; }
      public String nrSolicitacaoServico { get; set; }
      public String status { get; set; }
      public Boolean owner { get; set; }
  }
  @future(callout=true)
  public static void processServiceRequests(List<String> requests) {
      List<ServiceRequest__c> serviceRequestsToProcess = [select id,name,Status__c,ownerid,ServiceReason__c,VivoMaestro_ID__c from ServiceRequest__c where id in:requests];
     Group queue = [SELECT Id FROM Group WHERE Type = 'Queue' AND Name = 'Backoffice Atendimento' LIMIT 1];

      WebService__c wsConfig = WebService__c.getInstance('CamundaTicketInformation');  

      if (wsConfig == null) {
          System.debug('WebService__c instance is null');
          return;  
      }

   system.debug(wsConfig);

      HttpClient httpClient = new HttpClient();

      for (ServiceRequest__c req : serviceRequestsToProcess) {

          //String  payload = JSON.serialize(req);
          ServicoDTO servico = new ServicoDTO();
          servico.motivo = req.ServiceReason__c;
          servico.nrSolicitacaoServico = req.Name;
          servico.status = req.Status__c;
          if(queue.id == req.ownerid){
                servico.owner = false;
          }else{
               servico.owner = true;
          }

          String requestJson = JSON.serialize(servico);
          wsConfig.Endpoint__c=wsConfig.Endpoint__c + '/api/tratativa-ticket/'+ req.VivoMaestro_ID__c+'/status';


          // Envia a solicitação usando o HttpClient
          HttpResponse response = httpClient.put(wsConfig, requestJson);

          // Log de resposta para depuração
          System.debug('Resposta da API: ' + response.getBody());

          // Verifique o status da resposta
          if (response.getStatusCode() != 200) {
              // Adicionar tratamento de erro, se necessário
              System.debug('Erro ao chamar a API. Código de status: ' + response.getStatusCode());
          }
      }
  }
}