force-app/main/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pela Habilitação Remota. Armazena o campo externalId do serviço de pré-ativação da linha executado pelo HRS.</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/ServiceTicket__c.object-meta.xml
<CustomObject>
    <label>Senha</label>
    <nameField>
        <displayFormat>{YY}{MM}-{000000}</displayFormat>
        <label>Nome do Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Senhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceTicket__c/fields/Activities__c.field-meta.xml
<CustomField>
    <fullName>Activities__c</fullName>
    <description>Atividades Selecionadas</description>
    <label>Atividades</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <description>Atividade</description>
    <label>Atividade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ActivityPriority__c.field-meta.xml
<CustomField>
    <fullName>ActivityPriority__c</fullName>
    <description>Prioridade da Atividade</description>
    <label>Prioridade da Atividade</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>Apelido do Cliente</description>
    <label>Apelido</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/BusinessLineID__c.field-meta.xml
<CustomField>
    <fullName>BusinessLineID__c</fullName>
    <description>ID da Categoria</description>
    <label>ID da Categoria</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/BusinessLineName__c.field-meta.xml
<CustomField>
    <fullName>BusinessLineName__c</fullName>
    <description>Nome da Categoria</description>
    <label>Categoria</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>Nome do Cliente</description>
    <label>Cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <description>CPF</description>
    <label>CPF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Número do Documento</description>
    <label>Nº Documento</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duração do Atendimento</description>
    <label>Duração do Atendimento</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>ID Externo para Identificação do Registro na Base de Dados de Origem</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/GeographicAreaCode__c.field-meta.xml
<CustomField>
    <fullName>GeographicAreaCode__c</fullName>
    <description>Código da Área Geográfica - DDD</description>
    <label>DDD</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/InteractionID__c.field-meta.xml
<CustomField>
    <fullName>InteractionID__c</fullName>
    <description>ID da Interação (Serviço) do Cliente</description>
    <label>ID do Serviço</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/InteractionName__c.field-meta.xml
<CustomField>
    <fullName>InteractionName__c</fullName>
    <description>Nome da Interação (Serviço) do Cliente</description>
    <label>Serviço</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <description>Login de Rede do Atendente que Realizou o Atendimento</description>
    <label>Atendente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/MainDocumentTypeID__c.field-meta.xml
<CustomField>
    <fullName>MainDocumentTypeID__c</fullName>
    <description>ID do Tipo Documento Principal</description>
    <label>ID do Tipo Documento Principal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/MainDocumentTypeName__c.field-meta.xml
<CustomField>
    <fullName>MainDocumentTypeName__c</fullName>
    <description>Nome do Tipo Documento Principal</description>
    <label>Tipo Documento Principal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/NetworkNumber__c.field-meta.xml
<CustomField>
    <fullName>NetworkNumber__c</fullName>
    <description>Número do Celular</description>
    <label>Celular</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Notas</description>
    <label>Notas</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Prioridade de Atendimento</description>
    <label>Prioridade</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SegmentID__c.field-meta.xml
<CustomField>
    <fullName>SegmentID__c</fullName>
    <description>ID da Segmentação do Cliente</description>
    <label>ID da Segmentação</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SegmentName__c.field-meta.xml
<CustomField>
    <fullName>SegmentName__c</fullName>
    <description>Nome da Segmentação do Cliente</description>
    <label>Segmentação</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ServiceEnd__c.field-meta.xml
<CustomField>
    <fullName>ServiceEnd__c</fullName>
    <description>Data e Hora do Término do Atendimento</description>
    <label>Término do Atendimento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ServiceStart__c.field-meta.xml
<CustomField>
    <fullName>ServiceStart__c</fullName>
    <description>Data e Hora do Início do Atendimento</description>
    <label>Início do Atendimento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SpecialNeeds__c.field-meta.xml
<CustomField>
    <fullName>SpecialNeeds__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Necessidades Especiais</description>
    <label>Necessidades Especiais</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>Em Espera</label>
            </value>
            <value>
                <fullName>In Service</fullName>
                <label>Em Atendimento</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <description>Código da Loja</description>
    <label>Loja</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/TicketId__c.field-meta.xml
<CustomField>
    <fullName>TicketId__c</fullName>
    <description>Número da Senha</description>
    <label>Senha</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/WaitTime__c.field-meta.xml
<CustomField>
    <fullName>WaitTime__c</fullName>
    <description>Tempo de Espera</description>
    <label>Tempo de Espera</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/recordTypes/StoreServiceManager.recordType-meta.xml
<RecordType>
    <fullName>StoreServiceManager</fullName>
    <active>true</active>
    <description>Tipo de Registro do Atendimento de Senhas - GSS</description>
    <label>GSS - Atendimento de Senha</label>
</RecordType>

force-app/main/default/classes/ServiceTicketDAO.cls
/*
    @author         Márcio Las
    @company        Telefónica | Vivo
    @date           30/10/2023
    @description    DAO Class for ServiceTicket__c
*/
public with sharing class ServiceTicketDAO {
    public static final String GSS_RECORD_TYPE_NAME = 'StoreServiceManager';
    public static final Id GSS_RECORD_TYPE_ID = getRecordTypeId(GSS_RECORD_TYPE_NAME);

    public static final String GSS_STATUS_ON_HOLD = 'On Hold';
    public static final String GSS_STATUS_IN_SERVICE = 'In Service';
    public static final String GSS_STATUS_CANCELED = 'Canceled';
    public static final String GSS_STATUS_CLOSED = 'Closed';

    public static Id getRecordTypeId(String recordTypeName) {
        return (SObjectType.ServiceTicket__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId());
    }

    public static ServiceTicket__c getById(Id serviceTicketId) {
        List<ServiceTicket__c> lstServiceTicket = getByIds(new Set<Id>{serviceTicketId});

        return ((lstServiceTicket == null || lstServiceTicket.isEmpty()) ? null : lstServiceTicket[0]);
    }

    public static List<ServiceTicket__c> getByIds(Set<Id> serviceTicketId) {
        if (serviceTicketId == null) {
            return (new List<ServiceTicket__c>());
        }

        return ([
            SELECT
                Id, 
                CreatedDate, 
                RecordTypeId, 
                Store__c, 
                TicketId__c, 
                ExternalID__c, 
                SpecialNeeds__c, 
                Priority__c, 
                CustomerName__c, 
                Alias__c, 
                Document__c, 
                GeographicAreaCode__c, 
                NetworkNumber__c, 
                SegmentID__c, 
                SegmentName__c, 
                Activity__c, 
                ActivityPriority__c, 
                Protocol__c, 
                WaitTime__c, 
                Status__c, 
                Login__c, 
                ServiceStart__c, 
                ServiceEnd__c, 
                Duration__c, 
                InteractionID__c, 
                InteractionName__c, 
                BusinessLineID__c, 
                BusinessLineName__c, 
                MainDocumentTypeID__c, 
                MainDocumentTypeName__c, 
                DocumentNumber__c, 
                Activities__c, 
                Notes__c 
            FROM 
                ServiceTicket__c
            WHERE (
                Id IN :serviceTicketId
            )
        ]);
    }

    public static List<ServiceTicket__c> getByRecordTypeStoreAndStatus(String recordTypeName, String store, String status) {
        if (String.isBlank(recordTypeName)) {
            return (new List<ServiceTicket__c>());
        }

        Id recordTypeId = getRecordTypeId(recordTypeName);

        return (getByRecordTypeStoreAndStatus(recordTypeId, store, status));
    }

    public static List<ServiceTicket__c> getByRecordTypeStoreAndStatus(Id recordTypeId, String store, String status) {
        if (recordTypeId == null) {
            return (new List<ServiceTicket__c>());
        }

        if (String.isBlank(store)) {
            return (new List<ServiceTicket__c>());
        }

        if (String.isBlank(status)) {
            return (new List<ServiceTicket__c>());
        }

        return ([
            SELECT
                Id, 
                CreatedDate, 
                RecordTypeId, 
                Store__c, 
                TicketId__c, 
                ExternalID__c, 
                SpecialNeeds__c, 
                Priority__c, 
                CustomerName__c, 
                Alias__c, 
                Document__c, 
                GeographicAreaCode__c, 
                NetworkNumber__c, 
                SegmentID__c, 
                SegmentName__c, 
                Activity__c, 
                ActivityPriority__c, 
                Protocol__c, 
                WaitTime__c, 
                Status__c, 
                Login__c, 
                ServiceStart__c, 
                ServiceEnd__c, 
                Duration__c, 
                InteractionID__c, 
                InteractionName__c, 
                BusinessLineID__c, 
                BusinessLineName__c, 
                MainDocumentTypeID__c, 
                MainDocumentTypeName__c, 
                DocumentNumber__c, 
                Activities__c, 
                Notes__c 
            FROM 
                ServiceTicket__c 
            WHERE (
                RecordTypeId = :recordTypeId AND 
                Store__c = :store AND 
                Status__c = :status AND 
                CreatedDate = TODAY
            ) 
            ORDER BY 
                Priority__c, 
                ActivityPriority__c, 
                CreatedDate
        ]);
    }

    public static List<ServiceTicket__c> getGSSOnHoldByStore(String store) {
        return (getByRecordTypeStoreAndStatus(GSS_RECORD_TYPE_ID, store, GSS_STATUS_ON_HOLD));
    }

    public static ServiceTicket__c getGSSInServiceByStoreLoginAndTicketId(String store, String login, String ticketId) {
        List<ServiceTicket__c> lstServiceTicket = [
            SELECT
                Id, 
                CreatedDate, 
                RecordTypeId, 
                Store__c, 
                Login__c, 
                TicketId__c, 
                Status__c, 
                ServiceStart__c 
            FROM 
                ServiceTicket__c 
            WHERE (
                RecordTypeId = :GSS_RECORD_TYPE_ID AND 
                Store__c = :store AND 
                Login__c = :login AND 
                TicketId__c = :ticketId AND 
                Status__c = :GSS_STATUS_IN_SERVICE AND 
                CreatedDate = TODAY
            )
        ];
        
        return ((lstServiceTicket == null || lstServiceTicket.isEmpty()) ? null : lstServiceTicket[0]);
    }
}