force-app/main/default/objects/PurgeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>configuração personalizada responsável pelas configurações de expurgo exceto objetos de OM, pois serão expurgados pela Job Nativo do OM</description>
    <fields>
        <fullName>ObjectName__c</fullName>
        <inlineHelpText>Nome de API do objeto que vai ter os registros excluídos (“Account”, “Order”, “vlocity_cmt__OrchestrationItem__c” )</inlineHelpText>
        <label>Nome do Objeto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurgeEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expurgo Habilitado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RetentionPeriodMeasurementUnit__c</fullName>
        <label>Unidade de Medida do Período de Retenção</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RetentionPeriod__c</fullName>
        <description>Refine o período de retenção de registros do objeto selecionado. Do dia atual voltando no tempo nesse período, será mantido na org. Registros mais antigos serão deletados.</description>
        <label>Período de Retenção</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Configurações de Expurgo</label>
</CustomObject>

force-app/main/default/classes/SchedulePurgeRoutinesTest.cls
/* -------------------------------------------------------------------------
* Autor....: Renan S. de Freitas - Deloitte
* Data.....: 21/03/2024
* Objetivo.: Rotina de Expurgos
*  -------------------------------------------------------------------------
* Autor....: Pedro Richtmann - Deloitte
* Data.....: 26/01/2024
* Alteração: Remoção do método updateScheduleTime, responsável pela atualização de data de realização do próximo expurgo; alteração de termo de "frequency" para "retentionPeriod" (API name e label do campo também foram alterados);
* US - Rotina de Expurgos
*  -------------------------------------------------------------------------
*/ 
@isTest
public class SchedulePurgeRoutinesTest 
{
    @TestSetup
    public static void makeData()
    {
        PurgeSetting__c objPurgeSettingCase = new PurgeSetting__c();
        objPurgeSettingCase.Name = 'Cases';
        objPurgeSettingCase.PurgeEnabled__c = true;
        objPurgeSettingCase.RetentionPeriod__c = 68;
        objPurgeSettingCase.ObjectName__c = 'Case';
        objPurgeSettingCase.RetentionPeriodMeasurementUnit__c = 'Meses';
        Insert objPurgeSettingCase;
        
        system.debug('objPurgeSettingCase: ' + objPurgeSettingCase);
    }
    
    @isTest
    private static void testScheduledJob() 
    {
        PurgeSetting__c objPurgeSetting = [SELECT Id, Name, ObjectName__c FROM PurgeSetting__c WHERE PurgeEnabled__c = TRUE];
        
        system.debug('objPurgeSetting.ObjectName__c: ' + objPurgeSetting.ObjectName__c);
        
        Test.startTest();
        	String jobId = System.schedule('SchedulePurgeRoutinesTest',   '0 0 0 * * ?' , new SchedulePurgeRoutines());
        Test.stopTest();
        
        System.assert(jobId != null, 'Agendamento não foi realizado');
        System.assertEquals(1, [SELECT count() FROM CronTrigger WHERE Id = :jobId]);
    }
}