force-app/main/default/objects/PurgeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>configuração personalizada responsável pelas configurações de expurgo exceto objetos de OM, pois serão expurgados pela Job Nativo do OM</description>
    <fields>
        <fullName>PurgeEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expurgo Habilitado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SchedulingDate__c</fullName>
        <description>&lt;Campo a ser removido&gt;</description>
        <label>SchedulingDate</label>
        <type>DateTime</type>
    </fields>
    <label>Configurações de Expurgo</label>
</CustomObject>

force-app/main/default/classes/SchedulePurgeRoutines.cls
/* -------------------------------------------------------------------------
* Autor....: Renan S. de Freitas - Deloitte
* Data.....: 21/03/2024
* Objetivo.: Agendador de Rotina de Expurgos
* US - Rotina de Expurgos
*  -------------------------------------------------------------------------
* How to execute:
*/ 
public class SchedulePurgeRoutines implements Schedulable
{
    public void execute(SchedulableContext sc)
    {
        List<PurgeSetting__c> lstPurgeSetting = [SELECT Id, Name FROM PurgeSetting__c WHERE PurgeEnabled__c = TRUE AND SchedulingDate__c = TODAY];
        
        for(PurgeSetting__c objPurgeSetting : lstPurgeSetting)
        {
            BatchPurgeRoutines objBatch = new BatchPurgeRoutines(objPurgeSetting.Name); 
            Database.executeBatch(objBatch, 200);             
        }
   }
}