force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RetrieveBillCycleListForCustomerFacade.cls
public with sharing class RetrieveBillCycleListForCustomerFacade {
    public static string CONST_STRING_WEBSERVICENAME = 'CustomerBillingCycleCallout';

    public static RetrieveBillCycleListForCustomerResponse findByFilters(String accountId, Boolean triggeredByCustomer, Datetime startDate, Datetime endDate){
        System.debug('accountId: ' + accountId);
        WebService__c ws = WebService__c.getInstance('CustomerBillingCycleCallout');
        String endPoint = ws.Endpoint__c;
        endPoint = endPoint.replace('{customerID}', accountId);
        endPoint += '?triggeredByCustomer='+triggeredByCustomer+'&fromCloseDate='+String.valueOf(Date.valueOf(startDate))+'&toCloseDate='+String.valueOf(Date.valueOf(endDate));
        
        HttpClient hClient = new HttpClient();
        HttpResponse response = hClient.get(ws, endPoint);

        RetrieveBillCycleListForCustomerResponse result = (RetrieveBillCycleListForCustomerResponse)JSON.deserialize(response.getBody(), RetrieveBillCycleListForCustomerResponse.class);

        return result;
    }
}