force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/ServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>ServiceProvider__c</fullName>
    <label>Provedor de serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RequestConfiguratorFactory.cls
/*
* @author Diego Costa @ Deloitte
* @date 06/06/2022
* @description classe RequestConfiguratorFactory 
*/
public class RequestConfiguratorFactory {
    private static final String APIGW = 'APIGW';
    private static final String FOURTHPLATFORM = 'FOURTHPLATFORM';
    public static IHttpRequestConfigurator getConfigurator(Webservice__c wsConfig) {

        IHttpRequestConfigurator destinationConfigurator;
        
        if(String.isBlank(wsConfig.ServiceProvider__c))
            destinationConfigurator = new QuartaPlataformaRequestConfigurator();
        
        else if(wsConfig.ServiceProvider__c == APIGW)
            destinationConfigurator = new APIGatewayRequestConfigurator();

        else if(wsConfig.ServiceProvider__c == FOURTHPLATFORM)
            destinationConfigurator = new APIGatewayRequestConfigurator();
        return new OAuthEndUserRequestConfigurator(destinationConfigurator);
    }
}