force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkForceManagementFacade.cls
public with sharing class WorkForceManagementFacade {

    public static final String CONST_STRING_WEBSERVICENAME = 'WorkForceManagementCallout';

    public static WorkOrder findById(String id) {
        
        Webservice__c ws =  Webservice__c.getInstance(CONST_STRING_WEBSERVICENAME);
        ws.Endpoint__c = ws.Endpoint__c.replace('{id}', id);

        HttpClient hClient = new HttpClient();
        HttpResponse response = hClient.get(ws);
        String responseBody = response.getBody();

        try {
            WorkOrder wo = (WorkOrder) JSON.deserialize(responseBody, WorkOrder.class);
            return wo;
        } catch (Exception e) {
            System.debug('Erro ao converter resposta do webservice: ' + e.getMessage());
            return null;
        }

    }

}