force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SearchCustomerKeysFacade.cls
public with sharing class SearchCustomerKeysFacade {

    public static string CONST_STRING_WEBSERVICENAME = 'SearchCustomerKeysCallout';

    public static AccountManagementResponse findByServiceId(String serviceId){

        WebService__c ws = WebService__c.getInstance(CONST_STRING_WEBSERVICENAME);
        ws.Endpoint__c = ws.Endpoint__c + '?serviceId=' + serviceId;
        HttpClient hClient = new HttpClient();
        HttpResponse response = hClient.get(ws);
		AccountManagementResponse result = (AccountManagementResponse)JSON.deserialize(response.getBody(), AccountManagementResponse.class);
		return result;

    }
}