force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderHybrisCallout.cls
public without sharing class OrderHybrisCallout {
    private static final Integer CODE_HTTP_SUCCESS = 200;
    private static final String WEBSERVICE_CANVASHYBRIS = 'OrderHybrisCallout';
            
    public static Map<String, Object> execute(String orderId) { 
        Map<String, Object> mapResult = new Map<String,Object>();
        try {
            WebService__c wsConfig = Webservice__c.getInstance(WEBSERVICE_CANVASHYBRIS); 
            wsConfig.endpoint__c = wsConfig.endpoint__c.replace('{orderId}', orderId);
        
            HttpResponse httpResponse = new HttpClient().get(wsConfig);
        
            if(httpResponse.getStatusCode() != CODE_HTTP_SUCCESS){
                mapResult.put('error', 'API com erro');
            }else{
                mapResult.put('response', httpResponse.getBody());
            }
            
        } catch (Exception ex) {
            mapResult.put('error', 'Erro ao executar ' + ex.getMessage());
        } 
        return mapResult;
    }
}