force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HttpClientTest.cls
@IsTest
public class HttpClientTest {
    @IsTest
    static void testValidHeaders() {
        // Cria um objeto Webservice__c com headers válidos
        Webservice__c wsConfig = new Webservice__c();
        wsConfig.Headers__c = 'Authorization:Bearer 1234567890123456;Content-Type:application/json';

        // Cria um objeto HttpRequest
        HttpRequest request = new HttpRequest();

        // Chama o método setRequestHeaders
        HttpClient.setRequestHeaders(wsConfig, request);

        // Verifica se os headers foram definidos corretamente
        Assert.areEqual('Bearer 1234567890123456', request.getHeader('Authorization'));
        Assert.areEqual('application/json', request.getHeader('Content-Type'));
    }

    @IsTest
    static void testInvalidHeaders() {
        // Cria um objeto Webservice__c com headers inválidos
        Webservice__c wsConfig = new Webservice__c();
        wsConfig.Headers__c = 'Authorization Bearer 1234567890123456; Content-Type application/json';

        // Cria um objeto HttpRequest
        HttpRequest request = new HttpRequest();

        // Chama o método setRequestHeaders
        HttpClient.setRequestHeaders(wsConfig, request);

        // Verifica se nenhum header foi definido e se um log de erro foi gerado
        Assert.areEqual(null, request.getHeader('Authorization'));
        Assert.areEqual(null, request.getHeader('Content-Type'));
    }
}