force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>ServiceProvider__c</fullName>
    <label>Provedor de serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentInstructionsControllerTest.cls
@IsTest
public with sharing class PaymentInstructionsControllerTest {
    @IsTest
    static void testfindPaymentMethodByBillingAccountId() {

        Webservice__c ws = new Webservice__c(
            Name = 'SearchInvoceCreditsCallout',
            Endpoint__c = 'https://contest.proxy.beeceptor.com/customerBillInvoiceManagement/v1/invoiceCredits',
            ServiceProvider__c = 'APIGW',
            SubscriptionKey__c = '89098b41c7884a3d8d55741b46389b61',
            Headers__c = 'application/json; charset=utf-8'
        );
        insert ws;
        
        List<PaymentInstructionsController.PaymentInstructionsFilter> filters = new List<PaymentInstructionsController.PaymentInstructionsFilter>();
        PaymentInstructionsController.PaymentInstructionsFilter nuFilter = new PaymentInstructionsController.PaymentInstructionsFilter();
        nuFilter.billingAccountId = 'teste123';
        filters.add(nuFilter);
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new PaymentInstructionsControllerMock());
            List<PaymentInstructionsController.PaymentInstructionsResponse> result =  PaymentInstructionsController.findPaymentMethodByBillingAccountId(filters);
        Test.stopTest();

        System.debug('result: ' + result);

        System.assert(result.size() == 1);
        PaymentInstructionsController.PaymentInstructionsResponse response = result.get(0);
        System.assert(response.paymentMethod != null);
        System.assertEquals('TESTE_PAYMENT_METHOD', response.paymentMethod);

    }

    private class PaymentInstructionsControllerErrorMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(500);
            return res;
        }
    }

    public class PaymentInstructionsControllerMock implements HttpCalloutMock {

      String jsonResponse = '{ "bankAccountForInstruction": { "authorizations": { "authorization": { "authorizationReference": "string", "authorizationStatus": "string" } }, "bankCode": "string", "bankName": "string", "branchCode": "string", "name": "string", "number": "string" }, "paymentInstructionCard": { "brand": "string", "imprintedName": "string", "validityMonth": "string", "validityYear": "string", "visibleNumber": "string" }, "paymentMethod": "TESTE_PAYMENT_METHOD" }"';      

      public HTTPResponse respond(HTTPRequest req) {
          HttpResponse res = new HttpResponse();
          res.setHeader('Content-Type', 'application/json');
          res.setBody(this.jsonResponse);
          res.setStatusCode(200);
          return res;
      }
    }
}