force-app/main/default/objects/RequiredFieldsMapping__mdt/RequiredFieldsMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para campos requeridos para ser utilizados em API, com  api name, objeto, tipo de registro, onde é utilizado e msg de Erro.</description>
    <label>Mapeamento de campos requeridos</label>
    <pluralLabel>Mapeamento de campos requeridos</pluralLabel>
</CustomObject>

force-app/main/default/objects/RequiredFieldsMapping__mdt/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <description>ApiName do campo desejado</description>
    <label>ApiName</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RequiredFieldsMapping__mdt/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>ErrorMessage Mensagem que deve ser apresentado ao usuario do campo desejado</description>
    <label>Mensagem de Erro</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RequiredFieldsMapping__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Nome do campo desejado</description>
    <label>Nome</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RequiredFieldsMapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Object do campo desejado</description>
    <label>Objeto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RequiredFieldsMapping__mdt/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <description>RecordType do campo desejado</description>
    <label>Tipo de registro</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RequiredFieldsMapping__mdt/fields/UsedIn__c.field-meta.xml
<CustomField>
    <fullName>UsedIn__c</fullName>
    <description>UsedIn onde o campo desejado será utilizado</description>
    <label>Utilizado em</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RequiredFieldsMappingDAO.cls
public without sharing class RequiredFieldsMappingDAO {
    public static List<RequiredFieldsMapping__mdt> get(String objectName, String RecordtypeName, String usedIn){
        return [
            SELECT
                Id,
                ApiName__c,
                ErrorMessage__c,
                Name__c,
                Object__c,
                RecordType__c,
                UsedIn__c
            FROM
                RequiredFieldsMapping__mdt
            WHERE
                   Object__c =:objectName
            AND    RecordType__c=:RecordtypeName
            AND    UsedIn__c=:usedIn    
        ];
    }
}