force-app/main/default/objects/RequiredFieldsMapping__mdt/RequiredFieldsMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para campos requeridos para ser utilizados em API, com  api name, objeto, tipo de registro, onde é utilizado e msg de Erro.</description>
    <label>Mapeamento de campos requeridos</label>
    <pluralLabel>Mapeamento de campos requeridos</pluralLabel>
</CustomObject>

force-app/main/default/objects/RequiredFieldsMapping__mdt/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <description>ApiName do campo desejado</description>
    <label>ApiName</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RequiredFieldsMapping__mdt/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>ErrorMessage Mensagem que deve ser apresentado ao usuario do campo desejado</description>
    <label>Mensagem de Erro</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RequiredFieldsValidator.cls
public without sharing class RequiredFieldsValidator {
    public static void validateFields(Map<String, Object> mapResult, sObject Context, String usedIn){
        List<RequiredFieldsMapping__mdt> requiredFields;
        String sObjectDevName, recordTypeDevName;
        
        
        sObjectDevName = Context.getSObjectType().getDescribe().getName();
        recordTypeDevName = RecordTypeUtil.getDevNameById(sObjectDevName, (Id)Context.get('RecordTypeId'));
        requiredFields = RequiredFieldsMappingDAO.get(sObjectDevName, RecordtypeDevName, usedIn);
        
        if(requiredFields.isEmpty()){
            mapResult.put('success', 'Metadado de campos obrigatórios não encontrado');
            return;
        }

        List<String> fields = new List<String>();
        for(RequiredFieldsMapping__mdt requiredField : requiredFields ){
            if(Context.get(requiredField.ApiName__c) == null){
                fields.add(requiredField.ErrorMessage__c);
            }
        }
        if(!fields.isEmpty()){
            mapResult.put('RequiredFields', fields);
            return;
        }

        if(mapResult.isEmpty()){
            mapResult.put('success', 'Campos validados com sucesso');
        }
    }
}