force-app/main/default/objects/CaseComment__c/CaseComment__c.object-meta.xml
<CustomObject>
    <description>This object corresponds to the &quot;Chat App Vivo&quot;, which records a conversation between the service operator and the b2c customer. It is displayed on the Cases screen in the &quot;Minhas Solicitações&quot; flow: Ajuda com cobrança, Ajuda com fatura ou cobrança, Ajuda com o Pedido, Mudança do Endereço de Instalação, Problema com Portabilidade, Problemas com Recarga.</description>
    <label>Comentário do Caso</label>
    <nameField>
        <displayFormat>CC-{000000000}</displayFormat>
        <label>Número do Comentário do Caso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CaseComments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseComment__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <defaultValue>(&quot;App Vivo&quot;)</defaultValue>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>App Vivo</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseComment__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentId</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>CaseComment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseCommentTriggerHandler.cls
public with sharing class CaseCommentTriggerHandler {
    private List<CaseComment__c> newCaseComments;
    private Map<Id, CaseComment__c> oldCaseComments;

    public CaseCommentTriggerHandler(List<CaseComment__c> newCaseComments, Map<Id, CaseComment__c> oldCaseComments) {
        this.newCaseComments = newCaseComments ?? new List<CaseComment__c>();
        this.oldCaseComments = oldCaseComments ?? new Map<Id, CaseComment__c>();
    }

    public void isAfterInsert() {
        updateParentCases();
    }

    private void updateParentCases() {
        Set<Id> parentCaseIds = new Set<Id>();

        for (CaseComment__c caseCommentObj : this.newCaseComments) {
            if (caseCommentObj.Origin__c == 'App Vivo') {
                parentCaseIds.add(caseCommentObj.ParentId__c);
            }
        }

        if (parentCaseIds.isEmpty()) { return; }

        List<Case> parentCases = CaseDAO.get(parentCaseIds);
        List<Case> parentCasesToUpdate = new List<Case>();
        String waitingforRoutingQueueId = CasesMyRequestsB2CService.getWaitingForRoutingQueueId();
        
        for (Case parentCaseObj : parentCases) {
            if (parentCaseObj.Status == 'Aguardando informação') {
                CasesMyRequestsB2CService.changeCaseOwner(parentCaseObj, waitingforRoutingQueueId);
                CasesMyRequestsB2CService.putTheCaseInTheRouting(parentCaseObj, waitingforRoutingQueueId);
                parentCasesToUpdate.add(parentCaseObj);
            }
        }

        update parentCasesToUpdate;
    }
}