force-app/main/default/objects/CaseComment__c/CaseComment__c.object-meta.xml
<CustomObject>
    <description>This object corresponds to the &quot;Chat App Vivo&quot;, which records a conversation between the service operator and the b2c customer. It is displayed on the Cases screen in the &quot;Minhas Solicitações&quot; flow: Ajuda com cobrança, Ajuda com fatura ou cobrança, Ajuda com o Pedido, Mudança do Endereço de Instalação, Problema com Portabilidade, Problemas com Recarga.</description>
    <label>Comentário do Caso</label>
    <nameField>
        <displayFormat>CC-{000000000}</displayFormat>
        <label>Número do Comentário do Caso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CaseComments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseComment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CaseComment__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <defaultValue>(&quot;App Vivo&quot;)</defaultValue>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>App Vivo</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseComment__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentId</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>CaseComment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChatAppVivoService.cls
public with sharing class ChatAppVivoService
{
    public class Message
    {
        @AuraEnabled public String id;
        @AuraEnabled public String parentId;
        @AuraEnabled public String message;
        @AuraEnabled public Boolean fromCustomer;
        @AuraEnabled public String origin;
    }

    public static CaseComment__c createCaseComment(String caseId, String newMessage)
    {
        CaseComment__c newCaseComment = new CaseComment__c();
        newCaseComment.ParentId__c = caseId;
        newCaseComment.Origin__c = 'Salesforce';
        newCaseComment.Comment__c = newMessage;
        insert newCaseComment;
        return newCaseComment;
    }

    public static List<ChatMessage> buildMessages(List<CaseComment__c> caseComments)
    {
        List<ChatMessage> messages = new List<ChatMessage>();
        for (CaseComment__c caseComment : caseComments)
        {
            ChatMessage message = ChatAppVivoService.buildMessage(caseComment);
            messages.add(message);
        }
        return messages;
    }

    public static ChatMessage buildMessage(CaseComment__c caseComment) 
    {
        ChatMessage message = new ChatMessage();
        message.id = caseComment.Id;
        message.parentId = caseComment.ParentId__c;
        message.message = caseComment.Comment__c;
        message.fromCustomer =  caseComment.Origin__c == 'App Vivo' ? true : false;
        message.origin = caseComment.Origin__c;
        return message;
    }
}