force-app/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Campo para guardar o valor</description>
    <label>StartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/FromToMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para ser utilizado para inclusão de de/para que serão utilizados na Org.</description>
    <label>Mapeamento DePara</label>
    <pluralLabel>Mapeamento DePara</pluralLabel>
</CustomObject>

force-app/main/default/objects/FromToMapping__mdt/fields/TokenPID__c.field-meta.xml
<CustomField>
    <fullName>TokenPID__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag para habilitar o acesso ao componente pidTokenValidate</description>
    <inlineHelpText>Flag para habilitar o acesso ao componente pidTokenValidate</inlineHelpText>
    <label>TokenPID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAuthorization__mdt/ServiceAuthorization__mdt.object-meta.xml
<CustomObject>
    <label>ServiceAuthorization</label>
    <pluralLabel>ServiceAuthorization</pluralLabel>
</CustomObject>

force-app/main/default/objects/ServiceAuthorization__mdt/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <description>Número de tentativas para o envio do token no componente pidTokenValidate.</description>
    <inlineHelpText>Número de tentativas para o envio do token no componente pidTokenValidate.</inlineHelpText>
    <label>Attempts</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAuthorization__mdt/fields/Message_Code__c.field-meta.xml
<CustomField>
    <fullName>Message_Code__c</fullName>
    <description>Código da mensagem SMS do sistema CSS</description>
    <label>Message Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PartnerGroup__c.field-meta.xml
<CustomField>
    <fullName>PartnerGroup__c</fullName>
    <label>Grupo do Aliado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VendasAliado</fullName>
                <label>Vendas Aliado</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPConsultor</fullName>
                <label>Vendas Aliado PaP Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPGerente</fullName>
                <label>Vendas Aliado PaP Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaConsultor</fullName>
                <label>Vendas Aliado Revenda Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaGerente</fullName>
                <label>Vendas Aliado Revenda Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasGerente</fullName>
                <label>Vendas Aliado Televendas Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPSupervisor</fullName>
                <label>Vendas Aliado PaP Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasCoordenador</fullName>
                <label>Vendas Aliado Televendas Coordenador</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasSupervisor</fullName>
                <label>Vendas Aliado Televendas Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasConsultor</fullName>
                <label>Vendas Aliado Televendas Consultor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeOperador</fullName>
                <label>Atendimento Aliado Backoffice Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoOp</fullName>
                <label>Atendimento Aliado Backoffice Retencao Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoSup</fullName>
                <label>Atendimento Aliado Backoffice Retencao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeSupervisor</fullName>
                <label>Atendimento Aliado Backoffice Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Ativo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Ativo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaOperador</fullName>
                <label>Atendimento Aliado Ouvidoria Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaSupervisor</fullName>
                <label>Atendimento Aliado Ouvidoria Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingOp</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingSup</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Supervisor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenSendAttempts__c.field-meta.xml
<CustomField>
    <fullName>TokenSendAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Número com a quantidade de envios de token no fluxo do pidTokenValidate</description>
    <label>TokenSendAttempts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenStatus__c.field-meta.xml
<CustomField>
    <fullName>TokenStatus__c</fullName>
    <description>Status do token de PID usado no componente pidTokenValidate</description>
    <label>TokenStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando validação</fullName>
            </value>
            <value>
                <fullName>Validado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Falha no envio</fullName>
            </value>
            <value>
                <fullName>Falha na comunicação API</fullName>
            </value>
            <value>
                <fullName>Não validado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PIDTokenValidateEngine.cls
public with sharing class PIDTokenValidateEngine {
    private static final String WEB_SERVICE_RTD = 'ServiceAuthorizationPID';
    private static final Integer SUCCESS_CODE = 200;
    private static final String WAITING_APPROVAL = 'Aguardando validação';
    private static final String SEND_ERROR = 'Falha no envio';
    
    public static Boolean postTokenValidate(Id customerIntId, String phoneNumber) {

        Webservice__c wsConfig = Webservice__c.getInstance(WEB_SERVICE_RTD);
        if (wsConfig == null || !wsConfig.switchedOn__c) {
            return false;
        }

        String payload = buildPayload(customerIntId, phoneNumber);
        HttpClient client = new HttpClient();
        HttpResponse response;

        response = client.post(wsConfig, payload);

        ServiceAuthorizationResponse responseParsed = ServiceAuthorizationResponse.parse(response.getBody());
        Boolean successStatus = responseParsed.status == '0';

        if (response.getStatusCode() == SUCCESS_CODE && successStatus) {
            return true;
        } else {
            return false;
        }
    }

    private static String buildPayload(Id customerIntId, String phoneNumber) {
        final String STR_POSPAGO = 'Pós-Pago';
        final String STR_CONTROLE = 'Controle';
        final String STR_PREPAGO = 'Pré';
        ServiceAuthorization__mdt pid = ServiceAuthorization__mdt.getInstance('PID');

        CustomerIntWrapper thisCustomerIntWrapper = new CustomerIntWrapper();
        thisCustomerIntWrapper.correlation_id = customerIntId;
        thisCustomerIntWrapper.message_code = pid.Message_Code__c;
        thisCustomerIntWrapper.msisdn = phoneNumber;

        String jsonBody = JSON.serialize(thisCustomerIntWrapper);
        return jsonBody;
    }

    public static void updateTokenStatus(String customerIntId, String tokenStatus) {
        vlocity_cmt__CustomerInteraction__c thisCustomerInt = new vlocity_cmt__CustomerInteraction__c();
        thisCustomerInt.Id = customerIntId;
        thisCustomerInt.TokenStatus__c = tokenStatus;
        updatePalitagem(thisCustomerInt);

        update thisCustomerInt;
    }

    
    public static void updatePalitagem(vlocity_cmt__CustomerInteraction__c thisCustomerInt) {
        String palitagemString = '';

        switch on thisCustomerInt.TokenStatus__c {
            when 'Falha no envio' {
                palitagemString = 'Validação de segurança não realizada - Erro no envio do Token.';
            }
            when 'Cancelado' {
                palitagemString = '';
            }
            when 'Não validado'{
                ServiceAuthorization__mdt pid = ServiceAuthorization__mdt.getInstance('PID');

                if (thisCustomerInt.TokenSendAttempts__c == pid.Attempts__c) {
                    palitagemString = 'Validação de Token Segurança não realizada - Máximo de tentativas excedido.';
                }
                palitagemString = 'Validação de Token Segurança não realizada.';
            }
            when 'Falha na comunicação API'{
                palitagemString = 'Validação de Token de Segurança não realizada - Falha da API - Token.';
            }
        }

        thisCustomerInt.vlocity_cmt__Comments__c =  palitagemString + thisCustomerInt.vlocity_cmt__Comments__c;
    }

    public static Boolean hasAccess() {
        try {
            User currentUser = UserDAO.getById(UserInfo.getUserId());
            List<FromToMapping__mdt> lstFromToMap =  new List<FromToMapping__mdt>();

            if (currentUser.Profile.UserLicense.Name != 'Partner Community') {
                lstFromToMap = FromToMappingDAO.getLstByUserRole(currentUser.UserRole.DeveloperName);
            } else {
                lstFromToMap = FromToMappingDAO.getLstByUserRole(currentUser.PartnerGroup__c);
            }

            for (FromToMapping__mdt iFromToMap : lstFromToMap) {
                if (iFromToMap.TokenPID__c) {
                    return true;
                }
            }

            return !PermissionSetAssigmentDAO.getCurrentPSA(Userinfo.getUserId(), 'TokenSMS').isEmpty();

        } catch (Exception e) {
            return false;
        }
    }

    public static Map<String, Object> getPhoneNumbers(String accId){
        Map<String, Object> phoneNumbers = new Map<String, Object>();

        List<String> ltPhoneNumbers;
        String phoneNumber = 'Não possui linha válida';

        List<Asset> lstAsset = AssetDAO.getPidAssetMobileByAccount(accId);

        if (!lstAsset.isEmpty()){
            final String posPago = 'Pós-Pago';
            final String controle = 'Controle';
            final String prePago = 'Pré-Pago';

            Map<String, List<String>> mapPhoneProductsMoreThan120 = new Map<String, List<String>>();

            mapPhoneProductsMoreThan120.put(posPago, new List<String>());
            mapPhoneProductsMoreThan120.put(controle, new List<String>());
            mapPhoneProductsMoreThan120.put(prePago, new List<String>());

            Map<String, List<String>> mapPhoneProductsLessThan120 = new Map<String, List<String>>();

            mapPhoneProductsLessThan120.put(posPago, new List<String>());
            mapPhoneProductsLessThan120.put(controle, new List<String>());
            mapPhoneProductsLessThan120.put(prePago, new List<String>());

            for (Asset asset : lstAsset){
                String phoneType = asset.ProductType__c;
                if (asset.StartDate__c != null && phoneType == posPago || phoneType == controle || phoneType == prePago){
                    if (asset.StartDate__c < System.now().addDays(-120)){
                        mapPhoneProductsMoreThan120.get(phoneType).add(asset.Name);
                    }
                    if (asset.StartDate__c >= System.now().addDays(-120)){
                        mapPhoneProductsLessThan120.get(phoneType).add(asset.Name);
                    }
                }
            }

            ltPhoneNumbers = new List<String>();

            if (!mapPhoneProductsMoreThan120.isEmpty()) {

                if (!mapPhoneProductsMoreThan120.get(posPago).isEmpty()){
                    ltPhoneNumbers.addAll(mapPhoneProductsMoreThan120.get(posPago));
                }
    
                if (!mapPhoneProductsMoreThan120.get(controle).isEmpty()){
                    ltPhoneNumbers.addAll(mapPhoneProductsMoreThan120.get(controle));
                }
    
                if (!mapPhoneProductsMoreThan120.get(prePago).isEmpty() && ltPhoneNumbers.isEmpty() && mapPhoneProductsLessThan120.get(posPago).isEmpty() && mapPhoneProductsLessThan120.get(controle).isEmpty()){
                    ltPhoneNumbers.addAll(mapPhoneProductsMoreThan120.get(prePago));
                }
                
            }
             
            if (!mapPhoneProductsLessThan120.isEmpty() && ltPhoneNumbers.isEmpty()) {

                if (!mapPhoneProductsLessThan120.get(posPago).isEmpty()){
                    ltPhoneNumbers.add(mapPhoneProductsLessThan120.get(posPago)[0]);
                }

                if (!mapPhoneProductsLessThan120.get(controle).isEmpty() && ltPhoneNumbers.isEmpty()){
                    ltPhoneNumbers.add(mapPhoneProductsLessThan120.get(controle)[0]);
                }

                if (!mapPhoneProductsLessThan120.get(prePago).isEmpty() && ltPhoneNumbers.isEmpty()){
                    ltPhoneNumbers.add(mapPhoneProductsLessThan120.get(prePago)[0]);
                }
            }             
            
            if (!ltPhoneNumbers.isEmpty()) {
                phoneNumbers.put('phones', ltPhoneNumbers);
                phoneNumbers.put('phone', ltPhoneNumbers[0]);
                return phoneNumbers;
            } 
        }
        
		phoneNumbers.put('phones', ltPhoneNumbers);
        phoneNumbers.put('phone', phoneNumber);
        return phoneNumbers;
    }

    public class CustomerIntWrapper {
        public String correlation_id {get;set;}
        public String msisdn {get;set;}
        public String message_code {get;set;}
    }
}