force-app/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <label>Sistema de Origem</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerInteractionId__c.field-meta.xml
<CustomField>
    <fullName>CustomerInteractionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associação do caso com um protocolo (Customer Interaction) pai</description>
    <label>Protocolo Pai</label>
    <referenceTo>vlocity_cmt__CustomerInteraction__c</referenceTo>
    <relationshipLabel>Casos Protocolo</relationshipLabel>
    <relationshipName>CaseProtocol</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/DisputedInvoice__c.object-meta.xml
<CustomObject>
    <label>Fatura Contestada</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faturas Contestadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedInvoice__c/fields/case__c.field-meta.xml
<CustomField>
    <fullName>case__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Faturas Contestadas</relationshipLabel>
    <relationshipName>FaturasContestadas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedItem__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens Contestados</relationshipLabel>
    <relationshipName>DisputedItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlowExecutionStepHistory__c/FlowExecutionStepHistory__c.object-meta.xml
<CustomObject>
    <label>Histórico de Execução de Fluxo</label>
    <nameField>
        <label>Step</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Execução de Fluxos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlowExecutionStepHistory__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Históricos de Execução de Fluxos</relationshipLabel>
    <relationshipName>Hist_ricos_de_Execu_o_de_Fluxos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlowExecutionStepHistory__c/fields/DisputedItem__c.field-meta.xml
<CustomField>
    <fullName>DisputedItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Contestado</label>
    <referenceTo>DisputedItem__c</referenceTo>
    <relationshipLabel>Históricos de Execução de Fluxos</relationshipLabel>
    <relationshipName>Hist_ricos_de_Execu_o_de_Fluxos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/GeneralSetting__c.object-meta.xml
<CustomObject>
    <label>Configuração Geral</label>
    <nameField>
        <label>Configuração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralSetting__c/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <label>Segmento do Operador</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>LOJA</fullName>
            </value>
            <value>
                <fullName>OMNICHANNEL</fullName>
            </value>
            <value>
                <fullName>OUVIDORIA</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>PÚRPURA</fullName>
            </value>
            <value>
                <fullName>REVENDA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>SUPORTE A LOJAS</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
            <value>
                <fullName>VIVO V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo do Produto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CONVERGENTE</fullName>
                <isActive>false</isActive>
                <label>CONVERGENTE</label>
            </value>
            <value>
                <fullName>FIXA</fullName>
            </value>
            <value>
                <fullName>MÓVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/recordTypes/ServiceGroupSetting.recordType-meta.xml
<RecordType>
    <fullName>ServiceGroupSetting</fullName>
    <active>true</active>
    <description>Configuração de Grupos de Atendimento por ação, assim podendo ser comparado o Grupo de Atendimento do Usuário e verificado se ele está contido em determinado agrupamento.</description>
    <label>Configuração Grupo de Atendimento</label>
</RecordType>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DisputeFixedFlowControllerTest.cls
@IsTest(SeeAllData=true)
public class DisputeFixedFlowControllerTest {
    @isTest
    public static void DisputeCheckScopeTest() {
        UserRole userR = [SELECT Id FROM UserRole WHERE DeveloperName ='AtendimentoGoldOperadorFixa'];
        Profile p = [SELECT Id FROM Profile WHERE Name='AdministracaoSistema'];
        
        User u = new User(Alias = 'SysAdmin', Email='stdstdteste@teste.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId = userR.Id,
                          TimeZoneSidKey='America/Sao_Paulo', UserName='stdteste@teste.com');
        Database.insert(u);
        
        System.runAs(u) {
            GeneralSetting__c gsNu = new GeneralSetting__c();
            gsNu.Name = 'Contestação';
            gsNu.OperatorSegment__c = 'Gold;Silver';
            gsNu.RecordTypeId = Schema.SObjectType.GeneralSetting__c.getRecordTypeInfosByDeveloperName().get('ServiceGroupSetting').getRecordTypeId();
            insert gsNu;
            
            Test.startTest();        
            DisputeFixedFlowController.DisputeCheckScopeInputs inputNu = new DisputeFixedFlowController.DisputeCheckScopeInputs();
            inputNu.Name = 'Contestação';
            inputNu.recortTypeName = 'ServiceGroupSetting';
            LIST<DisputeFixedFlowController.DisputeCheckScopeInputs> parameters = new LIST<DisputeFixedFlowController.DisputeCheckScopeInputs>();
            parameters.add(inputNu);
            LIST<String> response = DisputeFixedFlowController.DisputeCheckScope(parameters);
         
            Test.stopTest();
            
            System.assertEquals('Sim', response[0]);
        }
    }
        
    @isTest
    public static void restartFlowTest() {
        Case nuCase = new Case();
        insert nuCase;

        DisputedInvoice__c nuInvoice = new DisputedInvoice__c();
        nuInvoice.case__c = nuCase.Id;
        insert nuInvoice;

        DisputedItem__c nuItem = new DisputedItem__c();
        nuItem.CaseId__c = nuCase.Id;
        insert nuItem;
        
        FlowExecutionStepHistory__c nuStep = new FlowExecutionStepHistory__c();
        nuStep.CaseId__c = nuCase.Id;
        insert nuStep;
        
        Test.startTest();
            DisputeFixedFlowController.restartFlow(nuCase.Id);
        Test.stopTest();
        
    }

    @isTest
    public static void getParamsByAccountIdTest() {
        Account nuAcc = new Account();
        nuAcc.Name = 'Teste';
        insert nuAcc;
        
        Asset nuAsset = new Asset();
        nuAsset.name = 'Teste asset';
        nuAsset.SourceSystem__c = 'NEXT';
        nuAsset.ProductType__c = 'Voz';
        nuAsset.vlocity_cmt__ServiceIdentifier__c = '11991111111';
        nuAsset.AccountId = nuAcc.Id;
        insert nuAsset;

        Test.startTest();
            Map<String,String> result =  DisputeFixedFlowController.getParamsByAccountId(nuAcc.Id);
        Test.stopTest();

        System.assertEquals('11991111111', result.get('customerPhoneNumber'));
    }

    @isTest
    public static void getCaseParamTest() {
        Case nuCase = new Case();
        insert nuCase;

        Test.startTest();
            Case result =  DisputeFixedFlowController.getCaseParam(nuCase.Id);
        Test.stopTest();

        System.assert(result.Id != null);
    }

    @isTest
    public static void getCustomerInteractionsTest() {
        vlocity_cmt__CustomerInteraction__c nuCI = new vlocity_cmt__CustomerInteraction__c();
        insert nuCI;

        Case nuCase = new Case();
        nuCase.CustomerInteractionId__c = nuCI.Id;
        nuCase.Protocol__c = 'testeNumber';
        insert nuCase;

        vlocity_cmt__CustomerInteractionTopic__c nuCIT = new vlocity_cmt__CustomerInteractionTopic__c();
        nuCIT.vlocity_cmt__CustomerInteractionId__c = nuCI.Id;
        nuCIT.vlocity_cmt__CaseId__c = nuCase.Id;
        insert nuCIT;

        Test.startTest();
            Map<String,String> result =  DisputeFixedFlowController.getCustomerInteractions(nuCase.Id);
        Test.stopTest();

        System.assertEquals(nuCI.Id, result.get('interactionId'));
    }

}