force-app/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tipo</fullName>
            </value>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Movel</fullName>
                <label>Móvel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo fixo</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Movel.recordType-meta.xml
<RecordType>
    <fullName>Movel</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo móvel</description>
    <label>Movel</label>
</RecordType>

force-app/main/default/classes/CanvasCPQControllerTest.cls
@isTest
private class CanvasCPQControllerTest {
    @TestSetup
    static void setup() {
	    AccountTestFactory.start().startPersonAccount().isAccount().create();
    }

    @isTest
    static void getCanvasDataTestMovel(){
        Account acc = [ SELECT Id FROM Account LIMIT 1];
        Asset ast = new Asset();
        ast.Name = 'Marcos';
        ast.AccountId = acc.Id;
        insert ast;
        String tipoOferta = 'migration';

        

        Test.startTest();
            Asset asts = [ SELECT Id FROM Asset LIMIT 1];
        	CanvasCPQController.CanvasResult result = CanvasCPQController.getCanvasData(new list<String>{ast.Id},tipoOferta);
        Test.stopTest();
        System.assertEquals(result.canOpenCanvas, true);
    } 

    @isTest
    static void getCanvasDataTestFixa(){
        Account acc = [ SELECT Id FROM Account LIMIT 1];
        Asset ast = new Asset();
        ast.Name = 'Marcos';
        ast.AccountId = acc.Id;
        ast.Type__c = 'Fixa';
        ast.ProductType__c = 'Controle';
        insert ast;
        String tipoOferta = 'fixaMigration';

        

        Test.startTest();
            Asset asts = [ SELECT Id FROM Asset LIMIT 1];
        	CanvasCPQController.CanvasResult result = CanvasCPQController.getCanvasData(new list<String>{ast.Id},tipoOferta);
        Test.stopTest();
        System.assertEquals(result.canOpenCanvas, true);
    } 

    @isTest
    static void getCanvasDataTestVivoTotal(){
        Account acc = [ SELECT Id FROM Account LIMIT 1];
        Asset ast = new Asset();
        ast.Name = 'Marcos';
        ast.AccountId = acc.Id;
        ast.Type__c = 'Movel';
        ast.ProductType__c = 'Pré-Pago';
        insert ast;
        String tipoOferta = 'vivoTotalMigration';
       

        

        Test.startTest();
            Asset asts = [ SELECT Id FROM Asset LIMIT 1];
        	CanvasCPQController.CanvasResult result = CanvasCPQController.getCanvasData(new list<String>{ast.Id},tipoOferta);
        Test.stopTest();
        System.assertEquals(result.canOpenCanvas, true);
    } 

    @isTest
    static void getCanvasDataTestWithoutRecordId(){

        Test.startTest();       
            CanvasCPQController.CanvasResult result = CanvasCPQController.getCanvasData(new list<String>(),'migration');
        Test.stopTest();
        System.assertEquals(result.canOpenCanvas, false);
    } 
}