force-app/main/default/objects/ServiceAuthorization__mdt/ServiceAuthorization__mdt.object-meta.xml
<CustomObject>
    <label>ServiceAuthorization</label>
    <pluralLabel>ServiceAuthorization</pluralLabel>
</CustomObject>

force-app/main/default/objects/ServiceAuthorization__mdt/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <description>Número de tentativas para o envio do token no componente pidTokenValidate.</description>
    <inlineHelpText>Número de tentativas para o envio do token no componente pidTokenValidate.</inlineHelpText>
    <label>Attempts</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAuthorization__mdt/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <description>Tempo de espera em minutos para o recebimento do token no componente pidTokenValidate.</description>
    <inlineHelpText>Tempo de espera em minutos para o recebimento do token no componente pidTokenValidate.</inlineHelpText>
    <label>Interval</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenFirstDateSend__c.field-meta.xml
<CustomField>
    <fullName>TokenFirstDateSend__c</fullName>
    <description>Data de envio do primeiro token no fluxo de pidTokenValidate</description>
    <label>TokenFirstDateSend</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenSendAttempts__c.field-meta.xml
<CustomField>
    <fullName>TokenSendAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Número com a quantidade de envios de token no fluxo do pidTokenValidate</description>
    <label>TokenSendAttempts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenSendNumber__c.field-meta.xml
<CustomField>
    <fullName>TokenSendNumber__c</fullName>
    <description>Campo para gravar o número que o Token SMS foi enviado</description>
    <label>TokenSendNumber</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenStatus__c.field-meta.xml
<CustomField>
    <fullName>TokenStatus__c</fullName>
    <description>Status do token de PID usado no componente pidTokenValidate</description>
    <label>TokenStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando validação</fullName>
            </value>
            <value>
                <fullName>Validado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Falha no envio</fullName>
            </value>
            <value>
                <fullName>Falha na comunicação API</fullName>
            </value>
            <value>
                <fullName>Não validado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PIDTokenValidateService.cls
public with sharing class PIDTokenValidateService {
    public static vlocity_cmt__CustomerInteraction__c sendToken(Id customerIntId, String phoneNumber) {
        vlocity_cmt__CustomerInteraction__c thisCustomerInt = CustomerInteractionDAO.getCustomerInteractionById(customerIntId);

        try {
            Boolean wasSentSuccessfully = PIDTokenValidateEngine.postTokenValidate(thisCustomerInt.Id, phoneNumber);

            if (wasSentSuccessfully) {
                thisCustomerInt.TokenStatus__c = 'Aguardando validação';
                thisCustomerInt.TokenSendAttempts__c ++;
                thisCustomerInt.TokenFirstDateSend__c = thisCustomerInt.TokenFirstDateSend__c != null ? thisCustomerInt.TokenFirstDateSend__c : System.now();
                thisCustomerInt.TokenSendNumber__c = thisCustomerInt.TokenSendNumber__c != null ? thisCustomerInt.TokenSendNumber__c : Double.valueOf(phoneNumber);
            
            } else {
                thisCustomerInt.TokenStatus__c = 'Falha no envio';
            }
            
            PIDTokenValidateEngine.updatePalitagem(thisCustomerInt);
            
            update thisCustomerInt;

            return thisCustomerInt;
              
        } catch (Exception e) {
            System.debug(e.getMessage());

            return thisCustomerInt;
        }
    }

    public static void updateTokenStatus(String customerIntId, String tokenStatus) {
        PIDTokenValidateEngine.updateTokenStatus(customerIntId, tokenStatus);
    }

    public static PIDTokenValidateDTO getCustomerIntAPX(String aRecordId) {
        PIDTokenValidateDTO thisPIDTokenValidateDTO = new PIDTokenValidateDTO();

        thisPIDTokenValidateDTO.hasAccess = false;

        if (PIDTokenValidateEngine.hasAccess()) {
            vlocity_cmt__CustomerInteraction__c thisCustomerInt = CustomerInteractionDAO.getCustomerInteractionById(aRecordId);
            ServiceAuthorization__mdt pid = ServiceAuthorization__mdt.getInstance('PID');
            Map<String, Object> phoneNumbers = PIDTokenValidateEngine.getPhoneNumbers(thisCustomerInt.vlocity_cmt__AccountId__c);

            thisPIDTokenValidateDTO.accountId = thisCustomerInt.vlocity_cmt__AccountId__c;
            thisPIDTokenValidateDTO.attempts = Integer.valueOf(pid.Attempts__c);
            thisPIDTokenValidateDTO.interval = Integer.valueOf(pid.Interval__c);
            thisPIDTokenValidateDTO.tokenStatus = thisCustomerInt.TokenStatus__c	;
            thisPIDTokenValidateDTO.tokenSendAttempts = Integer.valueOf(thisCustomerInt.TokenSendAttempts__c);
            thisPIDTokenValidateDTO.hasAccess = true;
            thisPIDTokenValidateDTO.phone = (String) phoneNumbers.get('phone');
            thisPIDTokenValidateDTO.phones = (List<String>) phoneNumbers.get('phones');
            thisPIDTokenValidateDTO.sendedPhone = String.valueOf(thisCustomerInt.TokenSendNumber__c);
        }

        return (thisPIDTokenValidateDTO);
    }
}