force-app/main/default/objects/OrderIssued__c/OrderIssued__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os pedidos criados no Hybris.</description>
    <label>Pedido Emitido</label>
    <nameField>
        <displayFormat>PE-{00000000}</displayFormat>
        <label>Id Pedido Emitido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos Emitidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderIssued__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo para apresentar a conta relacionada ao pedido emitido.</description>
    <label>Nome da Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos Emitidos</relationshipLabel>
    <relationshipName>PedidosEmitidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/AmdocsOrder__c.field-meta.xml
<CustomField>
    <fullName>AmdocsOrder__c</fullName>
    <description>Campo para armazenar o número do pedido na Amdocs.</description>
    <label>N° Pedido Amdocs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/HybrisOrder__c.field-meta.xml
<CustomField>
    <fullName>HybrisOrder__c</fullName>
    <description>Campo para armazenar o número do pedido gerado na Hybris.</description>
    <externalId>true</externalId>
    <label>N° Pedido Hybris</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Campo para armazenar e apresentar o Status do pedido no Hybris.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>WAITING_FOR_DROP_OFF</fullName>
                <label>Aguardando Postagem - pedido enviado</label>
            </value>
            <value>
                <fullName>WAIT_FRAUD_MANUAL_CHECK</fullName>
                <label>Aguardando validação manual de Fraude</label>
            </value>
            <value>
                <fullName>AMDOCS_DELINQUENCY_CHECK</fullName>
            </value>
            <value>
                <fullName>AMDOCS_GET_CUSTOMER_INFO</fullName>
            </value>
            <value>
                <fullName>AMDOCS_LINE_NOT_CEASED</fullName>
            </value>
            <value>
                <fullName>AMDOCS_WIRELESS_VALIDATION_SUCCESS</fullName>
            </value>
            <value>
                <fullName>SKIP_FRAUD_ANALYSIS</fullName>
                <label>Análise de crédito concluída</label>
            </value>
            <value>
                <fullName>UPDATE_CUSTOMER_PARTIAL</fullName>
                <label>Atualização parcial do cliente na AMDOCS</label>
            </value>
            <value>
                <fullName>AUTO_DEBIT_ACTIVATION_FAIL</fullName>
            </value>
            <value>
                <fullName>AUTO_DEBIT_ACTIVATION_SUCCESS</fullName>
            </value>
            <value>
                <fullName>CLARIFY_ADDRESS</fullName>
                <label>Averiguar endereço - pedido enviado</label>
            </value>
            <value>
                <fullName>CLARIFY_DELIVERY_FAIL</fullName>
                <label>Averiguar falha na entrega - pedido enviado</label>
            </value>
            <value>
                <fullName>CLARIFY_LABEL_FAIL</fullName>
                <label>Averiguar falha na etiqueta - pedido enviado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_APPROVED</fullName>
                <label>Bilhete de portabilidade aprovado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_CANCEL</fullName>
                <label>Bilhete de Portabilidade cancelado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_ERROR</fullName>
                <label>Bilhete de Portabilidade com erro</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_CREATED</fullName>
                <label>Bilhete de Portabilidade criado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_ENABLE</fullName>
                <label>Bilhete de Portabilidade Habilitado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_NOT_APPROVED</fullName>
                <label>Bilhete de portabilidade não aprovado</label>
            </value>
            <value>
                <fullName>BILLING_CYCLE_UPDATED</fullName>
            </value>
            <value>
                <fullName>BILLING_NOTIFICATION</fullName>
                <label>Billing Ativado</label>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_AMDOCS_FAT_ABERTO</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_FRAUDE_CLEARSALE</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_POWCURVE</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_SCORE_POWCURVE_AMDOCS</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
                <label>Cancelado - pedido cancelado</label>
            </value>
            <value>
                <fullName>CHECK_AMDOCS_LINE_CEASED_SUCESS</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_CTRL_PRE_INVALID</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_CTRL_PRE_VALID</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_POS_PRE_VALID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderIssuedDAO.cls
public with sharing class OrderIssuedDAO {
    public static OrderIssued__c getById (Id orderIssuedId){
        List<OrderIssued__c> ltOrderIssued = getById(new Set<Id>{orderIssuedId});
        return ltOrderIssued.isEmpty() ? null : ltOrderIssued[0];
    }

    public static List<OrderIssued__c> getById (Set<Id> setOrderIssuedId) {
        return [
            SELECT 
                Id, 
                Name, 
                AccountId__c, 
                HybrisOrder__c, 
                AmdocsOrder__c, 
                Status__c 
            FROM 
                OrderIssued__c 
            WHERE
                Id IN :setOrderIssuedId
        ];
    }
}