force-app/main/default/objects/OrderIssued__c/OrderIssued__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os pedidos criados no Hybris.</description>
    <label>Pedido Emitido</label>
    <nameField>
        <displayFormat>PE-{00000000}</displayFormat>
        <label>Id Pedido Emitido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos Emitidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderIssued__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo para apresentar a conta relacionada ao pedido emitido.</description>
    <label>Nome da Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos Emitidos</relationshipLabel>
    <relationshipName>PedidosEmitidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/AmdocsOrder__c.field-meta.xml
<CustomField>
    <fullName>AmdocsOrder__c</fullName>
    <description>Campo para armazenar o número do pedido na Amdocs.</description>
    <label>N° Pedido Amdocs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/HybrisOrder__c.field-meta.xml
<CustomField>
    <fullName>HybrisOrder__c</fullName>
    <description>Campo para armazenar o número do pedido gerado na Hybris.</description>
    <externalId>true</externalId>
    <label>N° Pedido Hybris</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Campo para armazenar e apresentar o Status do pedido no Hybris.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>WAITING_FOR_DROP_OFF</fullName>
                <label>Aguardando Postagem - pedido enviado</label>
            </value>
            <value>
                <fullName>WAIT_FRAUD_MANUAL_CHECK</fullName>
                <label>Aguardando validação manual de Fraude</label>
            </value>
            <value>
                <fullName>AMDOCS_DELINQUENCY_CHECK</fullName>
            </value>
            <value>
                <fullName>AMDOCS_GET_CUSTOMER_INFO</fullName>
            </value>
            <value>
                <fullName>AMDOCS_LINE_NOT_CEASED</fullName>
            </value>
            <value>
                <fullName>AMDOCS_WIRELESS_VALIDATION_SUCCESS</fullName>
            </value>
            <value>
                <fullName>SKIP_FRAUD_ANALYSIS</fullName>
                <label>Análise de crédito concluída</label>
            </value>
            <value>
                <fullName>UPDATE_CUSTOMER_PARTIAL</fullName>
                <label>Atualização parcial do cliente na AMDOCS</label>
            </value>
            <value>
                <fullName>AUTO_DEBIT_ACTIVATION_FAIL</fullName>
            </value>
            <value>
                <fullName>AUTO_DEBIT_ACTIVATION_SUCCESS</fullName>
            </value>
            <value>
                <fullName>CLARIFY_ADDRESS</fullName>
                <label>Averiguar endereço - pedido enviado</label>
            </value>
            <value>
                <fullName>CLARIFY_DELIVERY_FAIL</fullName>
                <label>Averiguar falha na entrega - pedido enviado</label>
            </value>
            <value>
                <fullName>CLARIFY_LABEL_FAIL</fullName>
                <label>Averiguar falha na etiqueta - pedido enviado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_APPROVED</fullName>
                <label>Bilhete de portabilidade aprovado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_CANCEL</fullName>
                <label>Bilhete de Portabilidade cancelado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_ERROR</fullName>
                <label>Bilhete de Portabilidade com erro</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_CREATED</fullName>
                <label>Bilhete de Portabilidade criado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_ENABLE</fullName>
                <label>Bilhete de Portabilidade Habilitado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_NOT_APPROVED</fullName>
                <label>Bilhete de portabilidade não aprovado</label>
            </value>
            <value>
                <fullName>BILLING_CYCLE_UPDATED</fullName>
            </value>
            <value>
                <fullName>BILLING_NOTIFICATION</fullName>
                <label>Billing Ativado</label>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_AMDOCS_FAT_ABERTO</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_FRAUDE_CLEARSALE</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_POWCURVE</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_SCORE_POWCURVE_AMDOCS</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
                <label>Cancelado - pedido cancelado</label>
            </value>
            <value>
                <fullName>CHECK_AMDOCS_LINE_CEASED_SUCESS</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_CTRL_PRE_INVALID</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_CTRL_PRE_VALID</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_POS_PRE_VALID</fullName>
            </value>
            <value>
                <fullName>PURCHASE_STATEMENT</fullName>
                <label>Extrato de Compras Gerado</label>
            </value>
            <value>
                <fullName>CHECKED_VALID</fullName>
                <label>Pedido Recebido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncOrderWithHybrisButtonControllerTest.cls
@isTest
public with sharing class SyncOrderWithHybrisButtonControllerTest {
    private static final Map<String,String> CONST_MAPHEADER = new Map<String,String>{'Content-Type' => 'application/json'};
    private static final String CONST_BODYSUCCESS ='{"crmPurchaseOrderNumber":"1107981096A","orderCode":"PE-00999999","products":[{"price":99.99,"productCode":"105310932","productDescription":"VIVO SELFIE BASICO 10GB"},{"price":0,"productCode":"YGSC244U3000","productDescription":"SIM CARD 4G P44 HRS 2/3/4FF UNID OLHAL"}],"status":"PURCHASE_STATEMENT","userId":"55773532034","vendorId":"80708782"}';
    private static final String CONST_BODYERROR = '';

    @TestSetup
    public static void setup(){
        Account acc = DataFactory.createAccount();
        insert acc;
        
        insert new OrderIssued__c(
            AccountId__c = acc.Id,
            HybrisOrder__c = 'PE-00999999',
            AmdocsOrder__c = '123456',
            Status__c = 'CHECKED_VALID'
        );

        insert new Webservice__c(
            Name = 'OrderHybrisCallout',
            Endpoint__c  = 'https://hmlapi.telefonicabigdata.com',
            SubscriptionKey__c = 'd1ca8d57a2984db88f01c9ce7b5862e2'
        );
    }
    @isTest
    public static void syncOrderStatusWithHybrisTest() {
        Test.startTest();
        OrderHybrisCalloutMock getRequest = new OrderHybrisCalloutMock(200, CONST_BODYSUCCESS, CONST_MAPHEADER);
        Test.setMock(HttpCalloutMock.class, getRequest);

        OrderIssued__c orderIssuedToAssert = [SELECT Id FROM OrderIssued__c WHERE HybrisOrder__c ='PE-00999999' limit 1];

        SyncOrderWithHybrisButtonController.syncHybrisOrderStatus(orderIssuedToAssert.Id);
        OrderIssued__c orderIssuedUpdated = [SELECT Status__c FROM OrderIssued__c WHERE HybrisOrder__c ='PE-00999999' limit 1];

        Test.stopTest();
        System.assertEquals('PURCHASE_STATEMENT', orderIssuedUpdated.Status__c, 'Status não foi atualizado como deveria.' );
    }

    @IsTest
    static void syncOrderStatusWithHybrisExceptionTest(){
        Test.startTest();
        OrderHybrisCalloutMock getRequest = new OrderHybrisCalloutMock(200, CONST_BODYERROR, CONST_MAPHEADER);
        Test.setMock(HttpCalloutMock.class, getRequest);

        OrderIssued__c orderIssuedToAssert = [SELECT Id FROM OrderIssued__c WHERE HybrisOrder__c ='PE-00999999' limit 1];

        Boolean isException = false;

        try {
            SyncOrderWithHybrisButtonController.syncHybrisOrderStatus(orderIssuedToAssert.Id);
            OrderIssued__c orderIssuedUpdated = [SELECT Status__c FROM OrderIssued__c WHERE HybrisOrder__c ='PE-00999999' limit 1];
        } catch (Exception e) {
            isException = true;
        }

        Test.stopTest();
        System.assertEquals(true, isException, 'O erro aconteceu como esperado.' );
    }
}