force-app/main/default/objects/OrderIssued__c/OrderIssued__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os pedidos criados no Hybris.</description>
    <label>Pedido Emitido</label>
    <nameField>
        <displayFormat>PE-{00000000}</displayFormat>
        <label>Id Pedido Emitido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos Emitidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderIssued__c/fields/HybrisOrder__c.field-meta.xml
<CustomField>
    <fullName>HybrisOrder__c</fullName>
    <description>Campo para armazenar o número do pedido gerado na Hybris.</description>
    <externalId>true</externalId>
    <label>N° Pedido Hybris</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <label>Status do pedido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Campo para armazenar e apresentar o Status do pedido no Hybris.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>WAITING_FOR_DROP_OFF</fullName>
                <label>Aguardando Postagem - pedido enviado</label>
            </value>
            <value>
                <fullName>WAIT_FRAUD_MANUAL_CHECK</fullName>
                <label>Aguardando validação manual de Fraude</label>
            </value>
            <value>
                <fullName>AMDOCS_DELINQUENCY_CHECK</fullName>
            </value>
            <value>
                <fullName>AMDOCS_GET_CUSTOMER_INFO</fullName>
            </value>
            <value>
                <fullName>AMDOCS_LINE_NOT_CEASED</fullName>
            </value>
            <value>
                <fullName>AMDOCS_WIRELESS_VALIDATION_SUCCESS</fullName>
            </value>
            <value>
                <fullName>SKIP_FRAUD_ANALYSIS</fullName>
                <label>Análise de crédito concluída</label>
            </value>
            <value>
                <fullName>UPDATE_CUSTOMER_PARTIAL</fullName>
                <label>Atualização parcial do cliente na AMDOCS</label>
            </value>
            <value>
                <fullName>AUTO_DEBIT_ACTIVATION_FAIL</fullName>
            </value>
            <value>
                <fullName>AUTO_DEBIT_ACTIVATION_SUCCESS</fullName>
            </value>
            <value>
                <fullName>CLARIFY_ADDRESS</fullName>
                <label>Averiguar endereço - pedido enviado</label>
            </value>
            <value>
                <fullName>CLARIFY_DELIVERY_FAIL</fullName>
                <label>Averiguar falha na entrega - pedido enviado</label>
            </value>
            <value>
                <fullName>CLARIFY_LABEL_FAIL</fullName>
                <label>Averiguar falha na etiqueta - pedido enviado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_APPROVED</fullName>
                <label>Bilhete de portabilidade aprovado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_CANCEL</fullName>
                <label>Bilhete de Portabilidade cancelado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_ERROR</fullName>
                <label>Bilhete de Portabilidade com erro</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_CREATED</fullName>
                <label>Bilhete de Portabilidade criado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_ENABLE</fullName>
                <label>Bilhete de Portabilidade Habilitado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_NOT_APPROVED</fullName>
                <label>Bilhete de portabilidade não aprovado</label>
            </value>
            <value>
                <fullName>BILLING_CYCLE_UPDATED</fullName>
            </value>
            <value>
                <fullName>BILLING_NOTIFICATION</fullName>
                <label>Billing Ativado</label>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_AMDOCS_FAT_ABERTO</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_FRAUDE_CLEARSALE</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_POWCURVE</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_SCORE_POWCURVE_AMDOCS</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
                <label>Cancelado - pedido cancelado</label>
            </value>
            <value>
                <fullName>CHECK_AMDOCS_LINE_CEASED_SUCESS</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_CTRL_PRE_INVALID</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_CTRL_PRE_VALID</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_POS_PRE_VALID</fullName>
            </value>
            <value>
                <fullName>END_ORDER_ACTION</fullName>
                <label>Pedido Concluído - NEXT</label>
            </value>
            <value>
                <fullName>CHECKED_VALID</fullName>
                <label>Pedido Recebido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Possíveis valores: ERROR | SUCCESS</description>
    <label>Código do status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderIssuedTriggerTest.cls
@isTest
private class OrderIssuedTriggerTest {
    private static final String CHECKED_VALID_STATUS = 'Pedido Recebido';
    private static final String END_ORDER_ACTION_STATUS = 'Pedido Concluído';
    
    @TestSetup
    static void setup(){
        List<OrderIssued__c> lOrders = new List<OrderIssued__c>();
        lOrders.add(DataFactory.createOrderIssued(''));
        lOrders.add(DataFactory.createOrderIssued('ERROR'));
        lOrders.add(DataFactory.createOrderIssued('SUCCESS'));
        lOrders.add(DataFactory.createOrderIssued('ERROR', 'CHECKED_VALID'));
                
        OrderIssued__c createOrderIssuedError = new OrderIssued__c();
          createOrderIssuedError.Status__c = 'CHECKED_VALID';
            createOrderIssuedError.StatusCode__c = 'ERROR';
            createOrderIssuedError.OrderStatus__c = 'CHECKED_VALID';
            createOrderIssuedError.HybrisOrder__c = 'OrderIssError';
        lOrders.add(createOrderIssuedError);        

        OrderIssued__c createOrderIssuedUpdateStatusCodeErrorToSuccess = new OrderIssued__c();
          createOrderIssuedUpdateStatusCodeErrorToSuccess.Status__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusCodeErrorToSuccess.StatusCode__c = 'SUCCESS';
            createOrderIssuedUpdateStatusCodeErrorToSuccess.OrderStatus__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusCodeErrorToSuccess.HybrisOrder__c = 'updStatErrToSuc';
        lOrders.add(createOrderIssuedUpdateStatusCodeErrorToSuccess);        
        
        OrderIssued__c createOrderIssuedUpdateStatusCodeSuccessToError = new OrderIssued__c();
          createOrderIssuedUpdateStatusCodeSuccessToError.Status__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusCodeSuccessToError.StatusCode__c = 'ERROR';
            createOrderIssuedUpdateStatusCodeSuccessToError.OrderStatus__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusCodeSuccessToError.HybrisOrder__c = 'updStatSucToErr';
            lOrders.add(createOrderIssuedUpdateStatusCodeSuccessToError);        
        
         OrderIssued__c createOrderIssuedUpdateStatusCodeSuccessToErrore = new OrderIssued__c();
          createOrderIssuedUpdateStatusCodeSuccessToErrore.Status__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusCodeSuccessToErrore.StatusCode__c = 'ERROR';
            createOrderIssuedUpdateStatusCodeSuccessToErrore.OrderStatus__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusCodeSuccessToErrore.HybrisOrder__c = 'updStatSucToEr';
            lOrders.add(createOrderIssuedUpdateStatusCodeSuccessToErrore);        

        OrderIssued__c createOrderIssuedUpdateStatusSameStatusCode = new OrderIssued__c();
            createOrderIssuedUpdateStatusSameStatusCode.Status__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusSameStatusCode.StatusCode__c = 'ERROR';
            createOrderIssuedUpdateStatusSameStatusCode.OrderStatus__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusSameStatusCode.HybrisOrder__c = 'updSameStatCode';
        lOrders.add(createOrderIssuedUpdateStatusSameStatusCode);        

        OrderIssued__c createOrderIssuedUpdateNoChanges = new OrderIssued__c();
            createOrderIssuedUpdateNoChanges.Status__c = 'CHECKED_VALID';
            createOrderIssuedUpdateNoChanges.StatusCode__c = 'ERROR';
            createOrderIssuedUpdateNoChanges.OrderStatus__c = 'CHECKED_VALID';
            createOrderIssuedUpdateNoChanges.HybrisOrder__c = 'updNoChanges';
        lOrders.add(createOrderIssuedUpdateNoChanges);        
                
        OrderIssued__c createOrderIssuedUpdateStatusDifferentStatusCode = new OrderIssued__c();
            createOrderIssuedUpdateStatusDifferentStatusCode.Status__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusDifferentStatusCode.StatusCode__c = 'ERROR';
            createOrderIssuedUpdateStatusDifferentStatusCode.OrderStatus__c = 'CHECKED_VALID';
            createOrderIssuedUpdateStatusDifferentStatusCode.HybrisOrder__c = 'updDiffStCode';
        lOrders.add(createOrderIssuedUpdateStatusDifferentStatusCode);        
                
        insert lOrders;
    }

  @isTest
    public static void createOrderIssued(){

        OrderIssued__c nOrderIssued = [SELECT Status__c, StatusCode__c, HybrisOrder__c, OrderStatus__c FROM OrderIssued__c WHERE StatusCode__c = '' LIMIT 1];
        Test.startTest();
            OrderIssued__c Order4Test = [SELECT Id, Status__c, OrderStatus__c, HybrisOrder__c FROM OrderIssued__c WHERE ID = :nOrderIssued.id LIMIT 1];
        Test.stopTest();

        System.assertEquals(nOrderIssued.HybrisOrder__c, Order4Test.HybrisOrder__c, 'This test verifies if the Hybris orders Ids are the same.');
        System.assertEquals(CHECKED_VALID_STATUS, Order4Test.OrderStatus__c, 'In this scenario, OrderStatus__c MUST be equal Status__c.');
    }

    @isTest
    public static void createOrderIssuedError(){
        
        OrderIssued__c nOrderIssued = [SELECT Status__c, StatusCode__c, HybrisOrder__c, OrderStatus__c FROM OrderIssued__c WHERE HybrisOrder__c = 'OrderIssError' LIMIT 1];
        Test.startTest();
            OrderIssued__c Order4Test = [SELECT Id, Status__c, OrderStatus__c, HybrisOrder__c FROM OrderIssued__c WHERE HybrisOrder__c = :nOrderIssued.HybrisOrder__c LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(nOrderIssued.HybrisOrder__c, Order4Test.HybrisOrder__c, 'This test verifies if the Hybris order,s Ids are the same');
        System.assertEquals(CHECKED_VALID_STATUS+' com erro', Order4Test.OrderStatus__C, 'This scenario should update the OrderStatus__C with Status__c +" com erro" ');
    }

    @isTest
    public static void createOrderIssuedUpdateStatusCodeErrorToSuccess(){
        
        OrderIssued__c nOrderIssued = [SELECT Status__c, StatusCode__c, HybrisOrder__c, OrderStatus__c FROM OrderIssued__c WHERE HybrisOrder__c = 'updStatErrToSuc' LIMIT 1];
        Test.startTest();
            nOrderIssued.StatusCode__c = 'SUCCESS';
            update nOrderIssued;
            OrderIssued__c Order4Test = [SELECT Id, Status__c, OrderStatus__c, HybrisOrder__c FROM OrderIssued__c WHERE HybrisOrder__c = :nOrderIssued.HybrisOrder__c LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(nOrderIssued.HybrisOrder__c, Order4Test.HybrisOrder__c, 'This test verifies if the Hybris order,s Ids are the same');
        System.assertEquals(CHECKED_VALID_STATUS, Order4Test.OrderStatus__C, 'This scenario should update the OrderStatus__C with Status__c +" com erro" ');
    }

    @isTest
    public static void createOrderIssuedUpdateStatusCodeSuccessToError(){
        
        OrderIssued__c nOrderIssued = [SELECT Status__c, StatusCode__c, HybrisOrder__c, OrderStatus__c FROM OrderIssued__c WHERE HybrisOrder__c = 'updStatSucToErr' LIMIT 1];
        Test.startTest();
            nOrderIssued.StatusCode__c = 'ERROR';
            update nOrderIssued;
            OrderIssued__c Order4Test = [SELECT Id, Status__c, OrderStatus__c, HybrisOrder__c FROM OrderIssued__c WHERE HybrisOrder__c = :nOrderIssued.HybrisOrder__c LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(nOrderIssued.HybrisOrder__c, Order4Test.HybrisOrder__c, 'This test verifies if the Hybris order,s Ids are the same');
        System.assertEquals(CHECKED_VALID_STATUS + ' com erro', Order4Test.OrderStatus__C, 'This scenario should update the OrderStatus__C with Status__c +" com erro" ');
    }

    @isTest
    public static void createOrderIssuedUpdateStatusSameStatusCode(){
         
        OrderIssued__c nOrderIssued = [SELECT Status__c, StatusCode__c, HybrisOrder__c, OrderStatus__c FROM OrderIssued__c WHERE HybrisOrder__c = 'updSameStatCode' LIMIT 1];
        Test.startTest();
            nOrderIssued.Status__c = 'END_ORDER_ACTION';
            nOrderIssued.StatusCode__c = 'ERROR';
            update nOrderIssued;
            OrderIssued__c Order4Test = [SELECT Id, Status__c, OrderStatus__c, HybrisOrder__c FROM OrderIssued__c WHERE HybrisOrder__c = :nOrderIssued.HybrisOrder__c LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(nOrderIssued.HybrisOrder__c, Order4Test.HybrisOrder__c, 'This test verifies if the Hybris order,s Ids are the same');
        System.assertEquals(END_ORDER_ACTION_STATUS + ' com erro', Order4Test.OrderStatus__C, 'This scenario should update the OrderStatus__C with Status__c +" com erro" ');
    }

    @isTest
    public static void createOrderIssuedUpdateStatusDifferentStatusCode(){
        
        OrderIssued__c nOrderIssued = [SELECT Status__c, StatusCode__c, HybrisOrder__c, OrderStatus__c FROM OrderIssued__c WHERE HybrisOrder__c = 'updDiffStCode' LIMIT 1];
        Test.startTest();
            nOrderIssued.Status__c = 'END_ORDER_ACTION';
            nOrderIssued.StatusCode__c = 'SUCCESS';
            update nOrderIssued;
            OrderIssued__c Order4Test = [SELECT Id, Status__c, OrderStatus__c, HybrisOrder__c FROM OrderIssued__c WHERE HybrisOrder__c = :nOrderIssued.HybrisOrder__c LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(nOrderIssued.HybrisOrder__c, Order4Test.HybrisOrder__c, 'This test verifies if the Hybris order,s Ids are the same');
        System.assertEquals(END_ORDER_ACTION_STATUS, Order4Test.OrderStatus__C, 'This scenario should update the OrderStatus__C with Status__c +" com erro" ');
    }

    @isTest
    public static void createOrderIssuedUpdateNoChanges(){
        
        OrderIssued__c nOrderIssued = [SELECT Status__c, StatusCode__c, HybrisOrder__c, OrderStatus__c FROM OrderIssued__c WHERE HybrisOrder__c = 'updNoChanges' LIMIT 1];
        Test.startTest();
            nOrderIssued.Status__c = 'CHECKED_VALID';
            nOrderIssued.StatusCode__c = 'ERROR';
            update nOrderIssued;
            OrderIssued__c Order4Test = [SELECT Id, Status__c, OrderStatus__c, HybrisOrder__c FROM OrderIssued__c WHERE HybrisOrder__c = :nOrderIssued.HybrisOrder__c LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(nOrderIssued.HybrisOrder__c, Order4Test.HybrisOrder__c, 'This test verifies if the Hybris order,s Ids are the same');
        System.assertEquals(CHECKED_VALID_STATUS + ' com erro', Order4Test.OrderStatus__C, 'This scenario should update the OrderStatus__C with Status__c +" com erro" ');
    }
}