force-app/main/default/objects/OrderIssued__c/OrderIssued__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os pedidos criados no Hybris.</description>
    <label>Pedido Emitido</label>
    <nameField>
        <displayFormat>PE-{00000000}</displayFormat>
        <label>Id Pedido Emitido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos Emitidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderIssued__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <label>Status do pedido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Campo para armazenar e apresentar o Status do pedido no Hybris.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>WAITING_FOR_DROP_OFF</fullName>
                <label>Aguardando Postagem - pedido enviado</label>
            </value>
            <value>
                <fullName>WAIT_FRAUD_MANUAL_CHECK</fullName>
                <label>Aguardando validação manual de Fraude</label>
            </value>
            <value>
                <fullName>AMDOCS_DELINQUENCY_CHECK</fullName>
            </value>
            <value>
                <fullName>AMDOCS_GET_CUSTOMER_INFO</fullName>
            </value>
            <value>
                <fullName>AMDOCS_LINE_NOT_CEASED</fullName>
            </value>
            <value>
                <fullName>AMDOCS_WIRELESS_VALIDATION_SUCCESS</fullName>
            </value>
            <value>
                <fullName>SKIP_FRAUD_ANALYSIS</fullName>
                <label>Análise de crédito concluída</label>
            </value>
            <value>
                <fullName>UPDATE_CUSTOMER_PARTIAL</fullName>
                <label>Atualização parcial do cliente na AMDOCS</label>
            </value>
            <value>
                <fullName>AUTO_DEBIT_ACTIVATION_FAIL</fullName>
            </value>
            <value>
                <fullName>AUTO_DEBIT_ACTIVATION_SUCCESS</fullName>
            </value>
            <value>
                <fullName>CLARIFY_ADDRESS</fullName>
                <label>Averiguar endereço - pedido enviado</label>
            </value>
            <value>
                <fullName>CLARIFY_DELIVERY_FAIL</fullName>
                <label>Averiguar falha na entrega - pedido enviado</label>
            </value>
            <value>
                <fullName>CLARIFY_LABEL_FAIL</fullName>
                <label>Averiguar falha na etiqueta - pedido enviado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_APPROVED</fullName>
                <label>Bilhete de portabilidade aprovado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_CANCEL</fullName>
                <label>Bilhete de Portabilidade cancelado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_ERROR</fullName>
                <label>Bilhete de Portabilidade com erro</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_CREATED</fullName>
                <label>Bilhete de Portabilidade criado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_ENABLE</fullName>
                <label>Bilhete de Portabilidade Habilitado</label>
            </value>
            <value>
                <fullName>PORT_IN_STATUS_NOT_APPROVED</fullName>
                <label>Bilhete de portabilidade não aprovado</label>
            </value>
            <value>
                <fullName>BILLING_CYCLE_UPDATED</fullName>
            </value>
            <value>
                <fullName>BILLING_NOTIFICATION</fullName>
                <label>Billing Ativado</label>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_AMDOCS_FAT_ABERTO</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_FRAUDE_CLEARSALE</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_POWCURVE</fullName>
            </value>
            <value>
                <fullName>CANCEL_ORDER_REP_SCORE_POWCURVE_AMDOCS</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
                <label>Cancelado - pedido cancelado</label>
            </value>
            <value>
                <fullName>CHECK_AMDOCS_LINE_CEASED_SUCESS</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_CTRL_PRE_INVALID</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_CTRL_PRE_VALID</fullName>
            </value>
            <value>
                <fullName>CHECK_ORDER_DOWN_POS_PRE_VALID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderIssued__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Possíveis valores: ERROR | SUCCESS</description>
    <label>Código do status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderIssuedManagement.cls
public with sharing class OrderIssuedManagement {
    public static void checkOrderError(Map<Id, OrderIssued__c> mOldOrders, List<OrderIssued__c> lNewOrders){
        
        Boolean isUpdated = (mOldOrders != null);
        //System.debug(mOldOrders);
        //System.debug(lNewOrders);

        for ( OrderIssued__c order : lNewOrders) {

            OrderIssued__c checkOrderUpdated = new OrderIssued__c();
            if(isUpdated){                
                checkOrderUpdated = mOldOrders.get(order.id);

                if(checkOrderUpdated == null || (checkOrderUpdated.Status__c == order.Status__c && checkOrderUpdated.StatusCode__c == order.StatusCode__c) ){
                    //System.debug('Não há nada para ser alterado.');
                    break;
                } else {
                    setOrderStatus(order);
                }
            } else {
                setOrderStatus(order);
            }
            order.StatusCode__c = null;
        }   
    }
    
    public static void setOrderStatus(OrderIssued__c order) {
        
        String pickListValue = '';
        Schema.DescribeFieldResult field = OrderIssued__c.order.Status__c.getDescribe();
        for (Schema.PicklistEntry f : field.getPicklistValues()){
            if(f.getValue() == order.Status__c){
                //System.debug('entrei aqui order.Status__c >>' + order.Status__c);
                pickListValue = f.getLabel();
                break;
            }
        }
        //System.debug('PICKLIST >>' + pickListValue);

        //System.debug('antes do teste '+order.StatusCode__c);

        if(order.StatusCode__c == 'ERROR'){
            //System.debug('entrei statuscode = error');
            if (order.OrderStatus__C == null || !order.Status__c.toLowerCase().contains('erro')) {
                //System.debug('n tinha palavra erro');
                order.OrderStatus__c = pickListValue + ' com erro';
            }else {
                //System.debug('tinha palavra erro');
                order.OrderStatus__c = pickListValue;
            }
        } else {
            //System.debug('entrou sucesso');
            order.OrderStatus__c = pickListValue;
        }
    }  
}