force-app/main/default/objects/Account/fields/AcceptPromotion__c.field-meta.xml
<CustomField>
    <fullName>AcceptPromotion__c</fullName>
    <description>O Cliente aceita receber comunicação da Vivo?</description>
    <label>Aceita receber comunicação Vivo?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>Sim</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>Não</label>
            </value>
            <value>
                <fullName>NoAnswer</fullName>
                <default>true</default>
                <label>Sem Resposta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingAddressType__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressType__c</fullName>
    <description>Tipo de logradouro para endereço principal</description>
    <label>Tipo Logradouro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplement1__c.field-meta.xml
<CustomField>
    <fullName>BillingComplement1__c</fullName>
    <description>Complemento</description>
    <label>Complemento 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplement2__c.field-meta.xml
<CustomField>
    <fullName>BillingComplement2__c</fullName>
    <description>Complemento</description>
    <label>Complemento 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplement3__c.field-meta.xml
<CustomField>
    <fullName>BillingComplement3__c</fullName>
    <description>Complemento</description>
    <label>Complemento 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplement4__c.field-meta.xml
<CustomField>
    <fullName>BillingComplement4__c</fullName>
    <description>Complemento</description>
    <label>Complemento 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplementType1__c.field-meta.xml
<CustomField>
    <fullName>BillingComplementType1__c</fullName>
    <description>Tipo de complemento</description>
    <label>Tipo Complemento 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ComplementType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplementType2__c.field-meta.xml
<CustomField>
    <fullName>BillingComplementType2__c</fullName>
    <description>Tipo de complemento</description>
    <label>Tipo Complemento 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ComplementType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplementType3__c.field-meta.xml
<CustomField>
    <fullName>BillingComplementType3__c</fullName>
    <description>Tipo de complemento</description>
    <label>Tipo Complemento 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ComplementType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingComplementType4__c.field-meta.xml
<CustomField>
    <fullName>BillingComplementType4__c</fullName>
    <description>Tipo de complemento</description>
    <label>Tipo Complemento 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ComplementType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingNeighborhood__c.field-meta.xml
<CustomField>
    <fullName>BillingNeighborhood__c</fullName>
    <description>Nome do bairro</description>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingNumber__c.field-meta.xml
<CustomField>
    <fullName>BillingNumber__c</fullName>
    <description>Número do endereço principal</description>
    <label>Número</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/AcceptPromotion__c.field-meta.xml
<CustomField>
    <fullName>AcceptPromotion__c</fullName>
    <label>Aceita receber comunicados Vivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>Sim</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Plataforma</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ComplementType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acesso</fullName>
    </customValue>
    <customValue>
        <fullName>Ala</fullName>
    </customValue>
    <customValue>
        <fullName>Alameda</fullName>
    </customValue>
    <customValue>
        <fullName>Altos</fullName>
    </customValue>
    <customValue>
        <fullName>Altura</fullName>
    </customValue>
    <customValue>
        <fullName>Arco</fullName>
    </customValue>
    <customValue>
        <fullName>Armazem</fullName>
    </customValue>
    <customValue>
        <fullName>Asa</fullName>
    </customValue>
    <customValue>
        <fullName>Baixos</fullName>
    </customValue>
    <customValue>
        <fullName>Banca</fullName>
    </customValue>
    <customValue>
        <fullName>Beco</fullName>
    </customValue>
    <customValue>
        <fullName>Bloco</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>Cabine</fullName>
    </customValue>
    <customValue>
        <fullName>Cais</fullName>
    </customValue>
    <customValue>
        <fullName>Caixa Postal</fullName>
    </customValue>
    <customValue>
        <fullName>Calcada</fullName>
    </customValue>
    <customValue>
        <fullName>Campus</fullName>
    </customValue>
    <customValue>
        <fullName>Casa</fullName>
    </customValue>
    <customValue>
        <fullName>Chacara</fullName>
    </customValue>
    <customValue>
        <fullName>Chale</fullName>
    </customValue>
    <customValue>
        <fullName>Cobertura</fullName>
    </customValue>
    <customValue>
        <fullName>Colonia</fullName>
    </customValue>
    <customValue>
        <fullName>Complemento</fullName>
    </customValue>
    <customValue>
        <fullName>Condominio</fullName>
    </customValue>
    <customValue>
        <fullName>Conjunto</fullName>
    </customValue>
    <customValue>
        <fullName>Corredor</fullName>
    </customValue>
    <customValue>
        <fullName>Edificio</fullName>
    </customValue>
    <customValue>
        <fullName>Entrada</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepiso</fullName>
    </customValue>
    <description>Lista de tipos de complementos</description>
    <masterLabel>Tipo de Complemento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GetAccountByserviceIdentifierController.cls
global without sharing class GetAccountByserviceIdentifierController implements vlocity_cmt.VlocityOpenInterface2 {
    global boolean invokeMethod(String methodName, Map<String, Object> inputs, Map<String, Object> output, Map<String, Object> options) {    
        Boolean success = true;
        String errors;

        try {
            switch on methodName {
                when 'getAccountAssetAddress'
                {
                    getAccountAssetAddress(inputs, output);
                } 
            }
        } catch(Exception e) {
            errors = e.getMessage(); 
            success = false;
        }

        if (!Test.isRunningTest()) {
            output.put('success', success);
        }
        
        output.put('error', errors);

        return success;
    }

private void getAccountAssetAddress(Map<String, Object> inputs, Map<String, Object> output) {
        Id accId = (Id) inputs.get('AccId');
        List<Account> lstAccount = AccountDAO.getAccountAndChildrenById(accId); 
        Set<Id> setAccId = (new Map<Id,SObject>(lstAccount)).keySet();
        List<Asset> lstAsset = AssetDAO.getBySetAccountIdWithPromotionProduct(setAccId);
        List<AddressListClass> lstAddressVar = new List<AddressListClass>();
        AddressListClass addressVar = new AddressListClass();
        addressVar.AddressList = new List<AddressClass>();
        
        for (Asset assetVar : lstAsset) {

            AddressClass addressLstVar = new AddressClass();
            addressLstVar.assetId = assetVar.Id != null ? assetVar.Id : '';
            addressLstVar.mailBox = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType1__c == 'caixa postal';
            addressLstVar.platform = assetVar.Platform__c != null ? assetVar.Platform__c : '';
            addressLstVar.addressType = assetVar.vlocity_cmt__ServiceAccountId__r.BillingAddressType__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingAddressType__c : '';
            addressLstVar.city = assetVar.vlocity_cmt__ServiceAccountId__r.BillingCity != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingCity : '';
            addressLstVar.complement1 = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplement1__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplement1__c : '';
            addressLstVar.complement2 = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplement2__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplement2__c : '';
            addressLstVar.complement3 = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplement3__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplement3__c : '';
            addressLstVar.complement4 = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplement4__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplement4__c : '';
            addressLstVar.complementType1 = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType1__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType1__c : '';
            addressLstVar.complementType2 = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType2__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType2__c : '';
            addressLstVar.complementType3 = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType3__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType3__c : '';
            addressLstVar.complementType4 = assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType4__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingComplementType4__c : '';
            addressLstVar.neighborhood = assetVar.vlocity_cmt__ServiceAccountId__r.BillingNeighborhood__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingNeighborhood__c : '';
            addressLstVar.number_x = assetVar.vlocity_cmt__ServiceAccountId__r.BillingNumber__c != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingNumber__c : '';
            addressLstVar.postalCode = assetVar.vlocity_cmt__ServiceAccountId__r.BillingPostalCode != null ?  assetVar.vlocity_cmt__ServiceAccountId__r.BillingPostalCode : '';
            addressLstVar.state = assetVar.vlocity_cmt__ServiceAccountId__r.BillingState != null ? assetVar.vlocity_cmt__ServiceAccountId__r.BillingState : '';
            addressLstVar.street = assetVar.vlocity_cmt__ServiceAccountId__r.BillingStreet != null ?  assetVar.vlocity_cmt__ServiceAccountId__r.BillingStreet : '';
            addressLstVar.accountId = assetVar.vlocity_cmt__ServiceAccountId__r.Id != null ? assetVar.vlocity_cmt__ServiceAccountId__r.Id : '';
            addressLstVar.recordType = assetVar.vlocity_cmt__ServiceAccountId__r.RecordType.name != null ?  assetVar.vlocity_cmt__ServiceAccountId__r.RecordType.name : '';
            addressLstVar.serviceIdentifier = assetVar.vlocity_cmt__ServiceIdentifier__c != null ? assetVar.vlocity_cmt__ServiceIdentifier__c : '';

            addressVar.AcceptPromotion = assetVar.vlocity_cmt__ServiceAccountId__r.AcceptPromotion__c;
            
            addressVar.AddressList.add(addressLstVar);
        }

        lstAddressVar.add(addressVar);
        output.put('result', JSON.serialize(new List<Object>{lstAddressVar}));    
    }

    public class AddressListClass {
        List<AddressClass> AddressList;
        String acceptPromotion;
    }

    public class AddressClass {
        Boolean mailBox;
        String assetId;
        String platform;
        String addressType;
        String city;
        String complement1;
        String complement2;
        String complement3;
        String complement4;
        String complementType1;
        String complementType2;
        String complementType3;
        String complementType4;
        String neighborhood;
        String number_x;
        String postalCode;
        String state;
        String street;
        String accountId;
        String recordType;
        String serviceIdentifier;
    }
}