force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FeatureFlag__c/FeatureFlag__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Usado como &quot;ligue/desligue&quot; de aplicações.</description>
    <label>FeatureFlag</label>
</CustomObject>

force-app/main/default/objects/FeatureFlag__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o fluxo está ativo ou não.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FeatureFlag__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Nome da aplicação que terá fluxo ligado/desligado.</description>
    <inlineHelpText>Nome da aplicação que terá fluxo ligado/desligado.</inlineHelpText>
    <label>Aplicação</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <label>Segmento do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/TimeAutomaticTicketCall__c.field-meta.xml
<CustomField>
    <fullName>TimeAutomaticTicketCall__c</fullName>
    <description>Define o tempo de chamada automática da senha, em segundos, no Atendimento de Senha.</description>
    <inlineHelpText>Define o tempo de chamada automática da senha, em segundos, no Atendimento de Senha.</inlineHelpText>
    <label>Tempo de Chamada da Senha Automática</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/ServiceTicket__c.object-meta.xml
<CustomObject>
    <label>Senha</label>
    <nameField>
        <displayFormat>{YY}{MM}-{000000}</displayFormat>
        <label>Nome do Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Senhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceTicket__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <description>Atividade</description>
    <label>Atividade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ActivityPriority__c.field-meta.xml
<CustomField>
    <fullName>ActivityPriority__c</fullName>
    <description>Prioridade da Atividade</description>
    <label>Prioridade da Atividade</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>Apelido do Cliente</description>
    <label>Apelido</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <description>Nome do Cliente</description>
    <label>Cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <description>CPF</description>
    <label>CPF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Número do Documento</description>
    <label>Nº Documento</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>ID Externo para Identificação do Registro na Base de Dados de Origem</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/GeographicAreaCode__c.field-meta.xml
<CustomField>
    <fullName>GeographicAreaCode__c</fullName>
    <description>Código da Área Geográfica - DDD</description>
    <label>DDD</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/InteractionID__c.field-meta.xml
<CustomField>
    <fullName>InteractionID__c</fullName>
    <description>ID da Interação (Serviço) do Cliente</description>
    <label>ID do Serviço</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/InteractionName__c.field-meta.xml
<CustomField>
    <fullName>InteractionName__c</fullName>
    <description>Nome da Interação (Serviço) do Cliente</description>
    <label>Serviço</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <description>Login de Rede do Atendente que Realizou o Atendimento</description>
    <label>Atendente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/NetworkNumber__c.field-meta.xml
<CustomField>
    <fullName>NetworkNumber__c</fullName>
    <description>Número do Celular</description>
    <label>Celular</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Prioridade de Atendimento</description>
    <label>Prioridade</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SegmentID__c.field-meta.xml
<CustomField>
    <fullName>SegmentID__c</fullName>
    <description>ID da Segmentação do Cliente</description>
    <label>ID da Segmentação</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SegmentName__c.field-meta.xml
<CustomField>
    <fullName>SegmentName__c</fullName>
    <description>Nome da Segmentação do Cliente</description>
    <label>Segmentação</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/SpecialNeeds__c.field-meta.xml
<CustomField>
    <fullName>SpecialNeeds__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Necessidades Especiais</description>
    <label>Necessidades Especiais</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>Em Espera</label>
            </value>
            <value>
                <fullName>In Service</fullName>
                <label>Em Atendimento</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fechada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <description>Código da Loja</description>
    <label>Loja</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/TicketId__c.field-meta.xml
<CustomField>
    <fullName>TicketId__c</fullName>
    <description>Número da Senha</description>
    <label>Senha</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTicket__c/fields/WaitTime__c.field-meta.xml
<CustomField>
    <fullName>WaitTime__c</fullName>
    <description>Tempo de Espera</description>
    <label>Tempo de Espera</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login de rede</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Loja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>Código da Loja</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Aplicação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SSMAttendanceOperationsControllerTest.cls
@IsTest
public with sharing class SSMAttendanceOperationsControllerTest {
    private static final String TEST_PHONE_NUMBER = '81010101212';
    private static final String TEST_CNPJ_CPF_NUMBER = '55566677788';

    @TestSetup
    public static void setup() {
        Profile profileTest = [
            SELECT Id 
            FROM Profile 
            WHERE Name = 'Representante'
        ];

        UserRole userRoleTest = new UserRole();
        
        userRoleTest.Name = 'Telefonica Brasil';
        
        Database.insert(userRoleTest);

        User userTest = new User(
            Alias = 'SysAdmin', 
            Email = 'atendimento.senha@ssmgssvssf.com',
            EmailEncodingKey = 'UTF-8', 
            LastName = 'Testing', 
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US', 
            ProfileId = profileTest.Id, 
            UserRoleId = userRoleTest.Id,
            TimeZoneSidKey = 'America/Sao_Paulo', 
            UserName = 'ssmgssvssf@ssmgssvssf.com',
            Login__c = 'A024895',
            StoreCode__c = '307'
        );
        
        Database.insert(userTest);

        System.runAs(userTest) {
            FeatureFlag__c featureFlagObj = new FeatureFlag__c();
            featureFlagObj.Name = 'SSMUseServiceTicketObject';
            featureFlagObj.Application__c = 'SSMUseServiceTicketObject';
            featureFlagObj.Active__c = true;
    
            insert featureFlagObj;
            
            List<Webservice__c> ltWebservicesSSM = new List<Webservice__c>();

            ltWebservicesSSM.add(
                new Webservice__c(
                    Name = 'PointOfServiceCallout',
                    switchedOn__c = true,
                    Endpoint__c = 'https://api-hml.telefonica.com.br/pointServiceQueueManagement/v1/pointOfServices?attendantId={attendantId}',
                    SubscriptionKey__c = '36cfd2713668489bb3f7d23d042be3a3'
                )
            );

            ltWebservicesSSM.add(
                new Webservice__c(
                    Name = 'OperationalInformationsCallout',
                    switchedOn__c = true,
                    Endpoint__c = 'https://api-hml.telefonica.com.br/channelSalesManagement/v1/pointOfServices/operationalInformations/',
                    SubscriptionKey__c = '36cfd2713668489bb3f7d23d042be3a3'
                )
            );          

            ltWebservicesSSM.add(
                new Webservice__c(
                    Name = 'UpdateWorkPositionCallout',
                    switchedOn__c = true,
                    Endpoint__c = 'https://api-hml.telefonica.com.br/pointOfServices/{pointOfServiceId}/workPositions/{workPositionId}',
                    SubscriptionKey__c = '36cfd2713668489bb3f7d23d042be3a3'
                )
            );
        
            ltWebservicesSSM.add(
                new Webservice__c(
                    Name = 'PointOfServiceAttendantCallout',
                    switchedOn__c = true,
                    Endpoint__c = 'https://api-hml.telefonica.com.br//pointOfServices/{pointOfServiceId}/attendants/{attendantId}',
                    SubscriptionKey__c = '36cfd2713668489bb3f7d23d042be3a3'
                )
            );

            ltWebservicesSSM.add(
                new Webservice__c(
                    Name = 'PointOfServiceAttendanceCallout',
                    switchedOn__c = true,
                    Endpoint__c = 'https://api-hml.telefonica.com.br/pointOfServices/{pointOfServiceId}/attendants/{attendantId}/attendances',
                    SubscriptionKey__c = '36cfd2713668489bb3f7d23d042be3a3'
                )
            );
        
            ltWebservicesSSM.add(
                new Webservice__c(
                    Name = 'PointOfServiceTicketsCallout',
                    switchedOn__c = true,
                    Endpoint__c = 'https://api-hml.telefonica.com.br/pointOfServices/{pointOfServiceId}/tickets',
                    SubscriptionKey__c = '36cfd2713668489bb3f7d23d042be3a3'
                )
            );

            Database.insert(ltWebservicesSSM);

            Account accountTest = new Account();

            accountTest.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getrecordTypeId();
            accountTest.Name = 'Account Test SSM';
            accountTest.CustomerSegment__c = 'PLATINUM';
            accountTest.vlocity_cmt__Active__c = 'Yes';
            accountTest.DocumentNumber__c = TEST_CNPJ_CPF_NUMBER;
            accountTest.Phone = TEST_PHONE_NUMBER;

            Database.insert(accountTest);

            GeneralParam__c paramTest = new GeneralParam__c(
                TimeAutomaticTicketCall__c = 10
            );

            ServiceTicket__c ticketTest = new ServiceTicket__c(
                ExternalID__c = 'TICKET_TEST',
                Store__c = '307',
                TicketId__c = 'T98',
                Status__c = 'On Hold',
                SpecialNeeds__c = false,
                Priority__c = 2,
                CustomerName__c = 'Márcio Las',
                Alias__c = 'MLAS',
                Document__c = '85274136987',
                GeographicAreaCode__c = '81',
                NetworkNumber__c = '966778899',
                SegmentID__c = '1',
                SegmentName__c = 'Cliente',
                Activity__c = 'Test ticket',
                Protocol__c = '000011/2023',
                InteractionID__c = '4',
                InteractionName__c = 'Teste Componente SSM',
                WaitTime__c = '00:05:25',
                ActivityPriority__c = 1
            );
    
            Database.insert(ticketTest);
        }
    }

    @IsTest
    public static void recallTicketTest() {
        User userTest = [
            SELECT id 
            FROM User 
            WHERE UserName = 'ssmgssvssf@ssmgssvssf.com' 
            LIMIT 1
        ];

        System.runAs(userTest) {
            Map<String, Object> mapServiceTicketTest = SSMTicketsController.getPointOfServiceTitckets();

            List<StoreServiceManagerTO.ServiceTicket> ltServiceTicketTest = 
                (List<StoreServiceManagerTO.ServiceTicket>) mapServiceTicketTest.get('success');

            StoreServiceManagerTO.ServiceTicket serviceTicketTest = ltServiceTicketTest[0];

            Test.startTest();
                Test.setMock(HttpCalloutMock.class, new PointOfServiceAttendanceCalloutMock());

                Map<String, Object> mapTest = SSMAttendanceOperationsController.recallTicket(serviceTicketTest);
            Test.stopTest();

            System.assertEquals('T98', serviceTicketTest.ticketId);
        }
    }

    @IsTest
    public static void returnToHome() { 
        User userTest = [
            SELECT id 
            FROM User 
            WHERE UserName = 'ssmgssvssf@ssmgssvssf.com' 
            LIMIT 1
        ];

        System.runAs(userTest) {
            Map<String, Object> mapServiceTicketTest = SSMTicketsController.getPointOfServiceTitckets();

            List<StoreServiceManagerTO.ServiceTicket> ltServiceTicketTest = 
                (List<StoreServiceManagerTO.ServiceTicket>) mapServiceTicketTest.get('success');

            StoreServiceManagerTO.ServiceTicket serviceTicketTest = ltServiceTicketTest[0];

            Test.startTest();
                Test.setMock(HttpCalloutMock.class, new PointOfServiceAttendanceCalloutMock());

                Map<String, Object> mapTest = SSMAttendanceOperationsController.returnToHome(serviceTicketTest);
            Test.stopTest();

            System.assertEquals('T98', serviceTicketTest.ticketId);
        }
    }

    @IsTest
    public static void giveUpTest() { 
        User userTest = [
            SELECT id 
            FROM User 
            WHERE UserName = 'ssmgssvssf@ssmgssvssf.com' 
            LIMIT 1
        ];

        System.runAs(userTest) {
            Map<String, Object> mapServiceTicketTest = SSMTicketsController.getPointOfServiceTitckets();

            List<StoreServiceManagerTO.ServiceTicket> ltServiceTicketTest = 
                (List<StoreServiceManagerTO.ServiceTicket>) mapServiceTicketTest.get('success');

            StoreServiceManagerTO.ServiceTicket serviceTicketTest = ltServiceTicketTest[0];

            serviceTicketTest.category = 'FIXA';
            serviceTicketTest.categoryName = 'Fixa';
            serviceTicketTest.mainDocumentType = 'CPF';
            serviceTicketTest.mainDocumentTypeName = 'CPF';
            serviceTicketTest.documentNumber = '45678932103';
            serviceTicketTest.giveUpReason = '{\"value\": \"QR1\", \"label\": \"Retornará em outro horário / dia\"}';

            Test.startTest();
                Test.setMock(HttpCalloutMock.class, new PointOfServiceAttendanceCalloutMock());

                Map<String, Object> mapTest = SSMAttendanceOperationsController.giveUp(serviceTicketTest);
            Test.stopTest();

            System.assertEquals('T98', serviceTicketTest.ticketId);
        }
    }

    @IsTest
    public static void confirmServiceTest() { 
        User userTest = [
            SELECT id 
            FROM User 
            WHERE UserName = 'ssmgssvssf@ssmgssvssf.com' 
            LIMIT 1
        ];

        System.runAs(userTest) {
            Map<String, Object> mapCustomer = SSMAttendanceController.getAccount('', TEST_CNPJ_CPF_NUMBER);
            Account acc = (Account) mapCustomer.get('success');
            Id customerInteractionId = (Id) mapCustomer.get('CustomerInteractionId');

            Map<String, Object> mapServiceTicketTest = SSMTicketsController.getPointOfServiceTitckets();

            List<StoreServiceManagerTO.ServiceTicket> ltServiceTicketTest = 
                (List<StoreServiceManagerTO.ServiceTicket>) mapServiceTicketTest.get('success');

            StoreServiceManagerTO.ServiceTicket serviceTicketTest = ltServiceTicketTest[0];
                    
            serviceTicketTest.customerInteractionId = customerInteractionId;
            serviceTicketTest.customerId = acc.Id;
            serviceTicketTest.category = 'FIXA';
            serviceTicketTest.categoryName = 'Fixa';
            serviceTicketTest.mainDocumentType = 'CPF';
            serviceTicketTest.mainDocumentTypeName = 'CPF';
            serviceTicketTest.documentNumber = '45678932103';
            serviceTicketTest.activities = '[{\"value\": \"728\", \"label\": \"Cancelamento - Fixa"}]';
            serviceTicketTest.notes = 'O cliente solicitou o cancelamento';

            Test.startTest();
                Test.setMock(HttpCalloutMock.class, new PointOfServiceAttendanceCalloutMock());

                Map<String, Object> mapTest = SSMAttendanceOperationsController.confirmService(serviceTicketTest);
            Test.stopTest();

            System.assertEquals('T98', serviceTicketTest.ticketId);
        }
    }
}