force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/GenericOptionsLists__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Listas de opções genericas para ser utilizadas nos projetos</description>
    <label>Listas de Opções Generica</label>
</CustomObject>

force-app/main/default/objects/GenericOptionsLists__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/APIDateTime__c.field-meta.xml
<CustomField>
    <fullName>APIDateTime__c</fullName>
    <label>Data/Hora</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>Nome da API</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Código</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description2__c.field-meta.xml
<CustomField>
    <fullName>Description2__c</fullName>
    <label>Descrição 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrição</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/fields/UsedIn__c.field-meta.xml
<CustomField>
    <fullName>UsedIn__c</fullName>
    <label>Usado em</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSMAttendanceControllerTest.cls
@IsTest
public with sharing class SSMAttendanceControllerTest {
    private static final String TEST_PHONE_NUMBER = '81988887777';
    private static final String TEST_CNPJ_CPF_NUMBER = '11122233344';

    @TestSetup
    public static void setup() {
        Account accountTest1 = new Account(
            //RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('RetencaoConvergente').getRecordTypeId(),
            Name = 'Account Test #1',
            DocumentNumber__c = '09845643278'            
        );

        Database.insert(accountTest1);

        Account accountTest2 = new Account(
            //RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('RetencaoConvergente').getRecordTypeId(),
            Name = 'Account Test #2',
            DocumentNumber__c = TEST_CNPJ_CPF_NUMBER
        );
        
        Database.insert(accountTest2);

        Asset assetTest = new Asset(
            AccountId = accountTest1.Id,
            Name = TEST_PHONE_NUMBER
        );

        Database.insert(assetTest);

        GenericOptionsLists__c newCustomerSegmentTest = new GenericOptionsLists__c();

        newCustomerSegmentTest.Name = 'PLATINUM';
        newCustomerSegmentTest.Code__c = 'PLATINUM';
        newCustomerSegmentTest.Description__c = 'PREMIUM';
        newCustomerSegmentTest.Description2__c = '1';
        newCustomerSegmentTest.APIName__c = 'CustomerSegment';
        newCustomerSegmentTest.APIDateTime__c = Date.today();
        newCustomerSegmentTest.UsedIn__c = 'CustomerSegment';
        newCustomerSegmentTest.Active__c = true;

        Database.insert(newCustomerSegmentTest);
    }

    @IsTest
    public static void getAccountByPhoneNumberTest() {
        Test.startTest();
            Map<String, Object> mapTest1 = SSMAttendanceController.getAccount(TEST_PHONE_NUMBER, '');
        Test.stopTest();

        System.assertNotEquals(null, mapTest1.get('success'));
    }

    @IsTest
    public static void getAccountByDocumentNumberTest() {
        Test.startTest();
            Map<String, Object> mapTest2 = SSMAttendanceController.getAccount('', TEST_CNPJ_CPF_NUMBER);
        Test.stopTest();

        System.assertNotEquals(null, mapTest2.get('success'));
    }

    @IsTest
    public static void getAccountErrorNotFoundTest() {
        Test.startTest();
            Map<String, Object> mapTest = SSMAttendanceController.getAccount(TEST_CNPJ_CPF_NUMBER, TEST_PHONE_NUMBER);
        Test.stopTest();
        
        System.assertEquals('Not found.', mapTest.get('error'));
    }

    @IsTest
    public static void getAccountCustomerSegmentGSSTest() {
        String CUSTOMER_SEGMENT_PLATINUM_IN = 'PLATINUM';
        String CUSTOMER_SEGMENT_PLATINUM_OUT = '1';
        String CUSTOMER_SEGMENT_NONE_IN = NULL;
        String CUSTOMER_SEGMENT_NONE_OUT = '3';

        StoreServiceManagerTO.ItemPicklistValue segmentPLATINUM = SSMAttendanceController.getAccountCustomerSegmentGSS(
            CUSTOMER_SEGMENT_PLATINUM_IN
        );

        StoreServiceManagerTO.ItemPicklistValue segmentNONE = SSMAttendanceController.getAccountCustomerSegmentGSS(
            CUSTOMER_SEGMENT_NONE_IN
        );
        
        System.assertEquals(CUSTOMER_SEGMENT_PLATINUM_OUT, segmentPLATINUM.value);
        System.assertEquals(CUSTOMER_SEGMENT_NONE_OUT, segmentNONE.value);
    }
    
    @IsTest
    public static void isPartnerCommunityLicenseTest() {
        Boolean test = SSMAttendanceController.isPartnerCommunityLicense();
    
        System.assertEquals(false, test);
    }
}