force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/CustomerInteractionTopicTree__c.object-meta.xml
<CustomObject>
    <label>Árvore de Palitagem</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Árvore de Palitagem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/GPSFlow__c.field-meta.xml
<CustomField>
    <fullName>GPSFlow__c</fullName>
    <label>Fluxo GPS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/GPSId__c.field-meta.xml
<CustomField>
    <fullName>GPSId__c</fullName>
    <label>Id GPS</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <label>Instância</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LINHA TELEFÔNICA</fullName>
            </value>
            <value>
                <fullName>BANDA LARGA</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>CONTROLE</fullName>
            </value>
            <value>
                <fullName>PÓS-PAGO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <label>Segmento Operador</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>LOJA</fullName>
            </value>
            <value>
                <fullName>OMNICHANNEL</fullName>
            </value>
            <value>
                <fullName>OUVIDORIA</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
                <label>PÚRPURA</label>
            </value>
            <value>
                <fullName>REVENDA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>SUPORTE A LOJAS</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
            <value>
                <fullName>VIVO V</fullName>
            </value>
            <value>
                <fullName>LOJAS</fullName>
                <isActive>false</isActive>
                <label>LOJAS</label>
            </value>
            <value>
                <fullName>Purpura-OLD</fullName>
                <isActive>false</isActive>
                <label>Purpura-OLD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
                <label>Pós/Controle</label>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <label>Fixa</label>
            </value>
            <value>
                <fullName>Pre</fullName>
                <label>Pré</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Campo criado para desenvolvimento de POC</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pasta</fullName>
            </value>
            <value>
                <fullName>Palito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/HasAuthToken__c.field-meta.xml
<CustomField>
    <fullName>HasAuthToken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui Token de Autenticação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GPSFlowIdControllerTest.cls
@isTest
public class GPSFlowIdControllerTest {                          
    @testSetup
    static void setup() {
        Account lAccount = DataFactory.createAccount();
        insert lAccount;

        insert new Webservice__c(
            Name = 'GPSQueryServiceFlowsCallout',
            Endpoint__c = 'http://svuxqa1soa134:7001/gps/crm/api/v3/diagnostic/search/',
            SubscriptionKey__c = 'd1ca8d57a2984db88f01c9ce7b5862e2',
            HasAuthToken__c = true,
            Headers__c = 'sistemaOrigem:LEGADO'
        );
        
        insert new CustomerInteractionTopicTree__c(
            Name = 'Teste de Fluxo de Atendimento',
            Active__c = true,
            GPSId__c = '',
            OperatorSegment__c = 'Gold',
            ProductType__c = 'Fixed',
            Instance__c = 'Banda Larga;TV',
			Type__c = 'Palito'            
        );

        insert new CustomerInteractionTopicTree__c(
            Name = 'Teste de Fluxo de Atendimento 2',
            Active__c = true,
            GPSId__c = '',
            OperatorSegment__c = '',
            Instance__c = ''
        );
        
        WebServiceTestFactory.start().authOAuthProvider().create();
    }

    @isTest
    public static void gpsFlowIdGetListFlowInvalidTest() {                
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new GPSFlowIdCalloutMock());        
        Map<String, Object> mapResult = GPSFlowIdController.getGPSFlow(null);
        
        Test.stopTest();        

        System.assertEquals(Label.ServiceFlowEndFlowValidationMessage, mapResult.get('error'));
    }
    
    @isTest
    public static void gpsFlowIdGetListFlowTest() {
        CustomerInteractionTopicTree__c customerInteractionTopicTree = [SELECT Id, Instance__c, GpsId__c, GpsFlow__c FROM CustomerInteractionTopicTree__c LIMIT 1];
        
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new GPSFlowIdCalloutMock());
        Map<String, Object> mapResult = GPSFlowIdController.getGPSFlow(customerInteractionTopicTree.Id);
        
        Test.stopTest();        

        System.assertNotEquals(null, mapResult.get('success'));
    }
    
    @isTest
    public static void gpsFlowIdUpdateFlowIdTest() {
        CustomerInteractionTopicTree__c customerInteractionTopicTree = [SELECT Id, Instance__c, GpsId__c, GpsFlow__c FROM CustomerInteractionTopicTree__c LIMIT 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new GPSFlowIdCalloutMock());
        
        GPSFlowIdController.updateGPSFlowId(customerInteractionTopicTree.Id, '1234', 'Fluxo Teste');
        Test.stopTest();
        
        CustomerInteractionTopicTree__c customerInteractionTopicTreeFlowUpdated = [SELECT Id, GpsId__c, GpsFlow__c FROM CustomerInteractionTopicTree__c LIMIT 1];
        
        System.assertEquals('Fluxo Teste', customerInteractionTopicTreeFlowUpdated.GPSFlow__c);
        System.assertEquals('1234', customerInteractionTopicTreeFlowUpdated.GPSId__c);
    }
}