force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/MainProductDescription__c.field-meta.xml
<CustomField>
    <fullName>MainProductDescription__c</fullName>
    <description>Campo para informar o plano.</description>
    <label>Plano</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Movel.recordType-meta.xml
<RecordType>
    <fullName>Movel</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo móvel</description>
    <label>Movel</label>
</RecordType>

force-app/main/default/objects/CanvasHybrisMigration__mdt/CanvasHybrisMigration__mdt.object-meta.xml
<CustomObject>
    <description>Metadado responsável por controle de acesso do fluxo de migração hybris.</description>
    <label>Fluxo Migração Hybris</label>
    <pluralLabel>Fluxos de Migrações Hybris</pluralLabel>
</CustomObject>

force-app/main/default/objects/CanvasHybrisMigration__mdt/fields/HasAccessToHybrisMigration__c.field-meta.xml
<CustomField>
    <fullName>HasAccessToHybrisMigration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo define se o papel possui acesso ao fluxo de migração hybris</description>
    <inlineHelpText>Marcado = Tem acesso, Desmarcado = Não tem acesso</inlineHelpText>
    <label>Tem acesso ao fluxo de migração hybris?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CanvasHybrisMigration__mdt/fields/OriginApiName__c.field-meta.xml
<CustomField>
    <fullName>OriginApiName__c</fullName>
    <description>Campo com o DeveloperName do papel do usuário interno ou PartnerGroup__c para usuários externos. Utilizado para o mapeamento &quot;De x Para&quot;.</description>
    <inlineHelpText>DeveloperName do papel do usuário interno ou PartnerGroup__c para usuários externos.</inlineHelpText>
    <label>API name origem</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CanvasHybrisMigration__mdt/fields/UserLicense__c.field-meta.xml
<CustomField>
    <fullName>UserLicense__c</fullName>
    <description>Campo para mostrar se o papel diz respeito a usuário interno ou externo.</description>
    <inlineHelpText>Tipo de licença do usuário: &quot;Salesforce&quot;, &quot;Partner Community&quot;, etc</inlineHelpText>
    <label>Licença do usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FeatureFlag__c/FeatureFlag__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Usado como &quot;ligue/desligue&quot; de aplicações.</description>
    <label>FeatureFlag</label>
</CustomObject>

force-app/main/default/objects/FeatureFlag__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o fluxo está ativo ou não.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FeatureFlag__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Nome da aplicação que terá fluxo ligado/desligado.</description>
    <inlineHelpText>Nome da aplicação que terá fluxo ligado/desligado.</inlineHelpText>
    <label>Aplicação</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssetMigrationExchangePlanControllerTest.cls
@isTest
public with sharing class AssetMigrationExchangePlanControllerTest {

    @TestSetup
    static void setup() {
        // #region setupShowOffer
                
        List<User> lstInsert = new List<User>();

        String profileId = [SELECT Id FROM Profile WHERE Name = 'Governanca'].Id;
        
        UserRole roleToInsert = new UserRole();
        roleToInsert.name = 'PapelSemAcesso';
        roleToInsert.DeveloperName = 'PapelSemAcesso';
        insert roleToInsert;
        
        User userPapelSemAcesso = DataFactory.createUser(profileId, roleToInsert.Id);
        insert userPapelSemAcesso;
    
        CanvasHybrisMigration__mdt chmWithoutAccess = [SELECT id, OriginApiName__c, HasAccessToHybrisMigration__c, UserLicense__c FROM CanvasHybrisMigration__mdt WHERE HasAccessToHybrisMigration__c = false LIMIT  1];
        UserRole role = [SELECT id FROM userRole WHERE DeveloperName   ='PapelSemAcesso'];

        UserRole roleWithAccess = new UserRole();
        roleWithAccess.name = 'PapelComAcesso';
        roleWithAccess.DeveloperName = 'PapelComAcesso';
        insert roleWithAccess;
        
        CanvasHybrisMigration__mdt chmWithSalesforceAccess = [SELECT id, OriginApiName__c, HasAccessToHybrisMigration__c, UserLicense__c FROM CanvasHybrisMigration__mdt WHERE HasAccessToHybrisMigration__c = true and UserLicense__c = 'Salesforce' LIMIT  1];

        User userWithSalesforceAccess = DataFactory.createUser(profileId, roleWithAccess.Id);
        userWithSalesforceAccess.FirstName = 'WithSalesforceAccessUser';
        lstInsert.add(userWithSalesforceAccess);

        User user = DataFactory.createUser(profileId, role.Id);
        user.FirstName = 'NoAccessUser';
        lstInsert.add(user);

        CanvasHybrisMigration__mdt chmWithPartnerAccess = [SELECT id, OriginApiName__c, HasAccessToHybrisMigration__c, UserLicense__c FROM CanvasHybrisMigration__mdt WHERE HasAccessToHybrisMigration__c = true and UserLicense__c = 'Partner Community' LIMIT  1];
        Profile communityProfile = [SELECT id FROM Profile WHERE Name = 'AliadoExterno'];
        
        String profileAdminId = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator'].Id;
        User userAdmin = DataFactory.createUser(profileAdminId, roleWithAccess.Id);
        insert userAdmin;
        
        User userPartner = new User();
        Account acc = new Account();
        system.runAs(userAdmin){
            
            acc = DataFactory.createAccount();
            insert acc;
            
            Contact newContactPartner = DataFactory.createContact();
            newContactPartner.AccountId = acc.id;
            insert newContactPartner;
            
            Asset newAsset = DataFactory.createAsset(acc.id, 'Movel');
            newAsset.Status = 'Active';
            newAsset.MainProductDescription__c  = 'Pós-Controle';
            insert newAsset;
            
            userPartner = DataFactory.createCommunityUser(communityProfile.id, 'VendasAliado', newContactPartner.Id);
            userPartner.FirstName = 'userPartner';
            insert userPartner;

            vlocity_cmt__CustomerInteraction__c newCustomerInteraction = DataFactory.createCustomerInteraction (acc.id);
            insert newCustomerInteraction;
        }
        
        system.runAs(userPartner){
            vlocity_cmt__CustomerInteraction__c newCustomerInteraction = DataFactory.createCustomerInteraction (acc.id);
            insert newCustomerInteraction;
        }
        
        User userWithPermissionSet = DataFactory.createUser(profileId, roleToInsert.Id);
        userWithPermissionSet.FirstName = 'userWithPermissionSet';
        lstInsert.add(userWithPermissionSet);
        insert lstInsert;
        
        PermissionSet canvasPermissionSet = [select id, name from PermissionSet where name = 'CanvasHybrisMigrationE2E'];
        PermissionSetAssignment assignUserToPermission = new PermissionSetAssignment();
        assignUserToPermission.AssigneeId = userWithPermissionSet.Id;
        assignUserToPermission.PermissionSetId = canvasPermissionSet.Id;
        insert assignUserToPermission;
        
    // #endregion
    // #region createCustomerInteractionTopic
    // #endregion
    }

    @isTest
    public static void showOffer() {
        createFeatFlag();
        
        Test.startTest();
            User userTest = [SELECT Id FROM User WHERE FirstName = 'WithSalesforceAccessUser' LIMIT 1];
            AssetMigrationDTO accessReturn = new AssetMigrationDTO();
        
            vlocity_cmt__CustomerInteraction__c cInteractionObj = [SELECT Id FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];
            system.runAs(userTest){
                accessReturn = AssetMigrationExchangePlanController.checkAccessToComponent(cInteractionObj.Id);
                
            }
        Test.stopTest();

        System.assertEquals(true, accessReturn.userHaveAccess, 'Usuário Salesforce sem acesso a troca de ofertas.');
    }

    @isTest
    public static void showOfferTestWithoutUser() {
        createFeatFlag();

        Test.startTest();
            User userTest = [SELECT Id FROM User WHERE FirstName = 'WithSalesforceAccessUser' LIMIT 1];
            AssetMigrationDTO accessReturn = new AssetMigrationDTO();
        	
            vlocity_cmt__CustomerInteraction__c cInteractionObj = [SELECT Id FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];
            system.runAs(userTest){
                accessReturn = AssetMigrationExchangePlanController.checkAccessToComponent(cInteractionObj.Id);
                
            }
        Test.stopTest();

        System.assertEquals(true, accessReturn.userHaveAccess, 'Usuário encontrado');
    }

    @isTest
    public static void showOfferTestWithoutRole() {
      createFeatFlag();

      Test.startTest();
            User userTest = [SELECT Id FROM User WHERE FirstName = 'WithSalesforceAccessUser' LIMIT 1];
            AssetMigrationDTO accessReturn = new AssetMigrationDTO();
        	
            vlocity_cmt__CustomerInteraction__c cInteractionObj = [SELECT Id FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];
            system.runAs(userTest){
                accessReturn = AssetMigrationExchangePlanController.checkAccessToComponent(cInteractionObj.Id);
                
            }
        Test.stopTest();

        System.assertEquals(true, accessReturn.userHaveAccess, 'O papel do usuário permite acesso a troca de ofertas.');
    }

    @isTest
    public static void showOfferPartner() {
        createFeatFlag();

        Test.startTest();
            User userTest = [SELECT Id, profile.userlicense.name FROM User WHERE FirstName = 'userPartner' LIMIT 1];
            AssetMigrationDTO accessReturn = new AssetMigrationDTO();
        	
            system.runAs(userTest){
	            vlocity_cmt__CustomerInteraction__c cInteractionObj = [SELECT Id FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];

                accessReturn = AssetMigrationExchangePlanController.checkAccessToComponent(cInteractionObj.Id);
                
            }
        Test.stopTest();

        System.assertEquals(true, accessReturn.userHaveAccess, 'Usuário Parceiro sem acesso a troca de ofertas.');

    }
    
    @isTest
    public static void showOfferToUserWithPermissionSet() {
       createFeatFlag();

       Test.startTest();
            User userTest = [SELECT Id FROM User WHERE FirstName = 'WithSalesforceAccessUser' LIMIT 1];
            AssetMigrationDTO accessReturn = new AssetMigrationDTO();
        	
            vlocity_cmt__CustomerInteraction__c cInteractionObj = [SELECT Id FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];
            system.runAs(userTest){
                accessReturn = AssetMigrationExchangePlanController.checkAccessToComponent(cInteractionObj.Id);
                
            }
        Test.stopTest();

        System.assertEquals(true , accessReturn.userHaveAccess, 'Usuário sem acesso a troca de ofertas');

    }

    @isTest
    public static void createCustomerInteractionTopicTeste() {
        Test.startTest();
            vlocity_cmt__CustomerInteraction__c newCustomerInteractionTeste = [SELECT id, vlocity_cmt__AccountId__c from vlocity_cmt__CustomerInteraction__c limit 1];
            Asset selectedAsset = AssetDAO.getAssetMobileMigration(newCustomerInteractionTeste.vlocity_cmt__AccountId__c)[0];
        	Map <String, Object> returnMap = AssetMigrationExchangePlanController.createCustomerInteractionTopic(newCustomerInteractionTeste.id, selectedAsset.id);

        Test.stopTest();

        System.assert(returnMap.containsKey('success'), 'CustomerInteractionTopic não foi criada');
    }

    @isTest
    public static void createCustomerInteractionTopicFalse() {
        Test.startTest();
            vlocity_cmt__CustomerInteraction__c newCustomerInteractionTeste = [SELECT id from vlocity_cmt__CustomerInteraction__c limit 1];
            Map <String, Object> returnMap = AssetMigrationExchangePlanController.createCustomerInteractionTopic('xxxxxxxxxx', 'xxxxxxxxxx');

        Test.stopTest();

        System.assert(returnMap.containsKey('error'), 'CustomerInteractionTopic não foi criada');
    }
    
    public static void createFeatFlag() {
        FeatureFlag__c feat = new FeatureFlag__c();
        feat.Name = 'FluxoMigracaoCanvasHybris';
        feat.Active__c = true;
        feat.Application__c = 'FluxoMigracaoCanvasHybris';
        
        insert feat;
    }
}