force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/DDD__c.field-meta.xml
<CustomField>
    <fullName>DDD__c</fullName>
    <label>DDD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BrazilDDD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductEligibility__c/ProductEligibility__c.object-meta.xml
<CustomObject>
    <description>Elegibilidade de produtos por DDD</description>
    <label>Elegibilidade de produtos</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elegibilidades de produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductEligibility__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductEligibility__c/fields/DDD__c.field-meta.xml
<CustomField>
    <fullName>DDD__c</fullName>
    <label>DDD</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BrazilDDD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductEligibility__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Elegibilidades de produtos</relationshipLabel>
    <relationshipName>ProductsEligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/BrazilDDD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>31</fullName>
    </customValue>
    <customValue>
        <fullName>32</fullName>
    </customValue>
    <customValue>
        <fullName>33</fullName>
    </customValue>
    <customValue>
        <fullName>34</fullName>
    </customValue>
    <customValue>
        <fullName>35</fullName>
    </customValue>
    <customValue>
        <fullName>37</fullName>
    </customValue>
    <customValue>
        <fullName>38</fullName>
    </customValue>
    <customValue>
        <fullName>41</fullName>
    </customValue>
    <customValue>
        <fullName>42</fullName>
    </customValue>
    <customValue>
        <fullName>43</fullName>
    </customValue>
    <customValue>
        <fullName>44</fullName>
    </customValue>
    <customValue>
        <fullName>45</fullName>
    </customValue>
    <customValue>
        <fullName>46</fullName>
    </customValue>
    <customValue>
        <fullName>47</fullName>
    </customValue>
    <customValue>
        <fullName>48</fullName>
    </customValue>
    <customValue>
        <fullName>49</fullName>
    </customValue>
    <description>Lista dos DDDs válidos no Brasil</description>
    <masterLabel>DDDs do Brasil</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CpqAppHandlerHookImplementationTest.cls
@isTest private class CpqAppHandlerHookImplementationTest {
    @TestSetup
    static void setup(){
        //Account
        Account acc = new Account();
        acc.Name = 'Conta 1';
        insert acc;

        //Order
        Order order = new Order();
        order.AccountId = acc.Id;
        order.DDD__c = '11';
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        insert order;

        //Product
        Product2 product = new Product2();
        product.Name = 'Produto 1';
        product.ProductCode = '0001';
        insert product;

        ProductEligibility__c prodEle = new ProductEligibility__c();
        prodEle.ProductId__c = product.Id;
        prodEle.DDD__c = '11';
        prodEle.Active__c = true;
        insert prodEle;
    }

    @isTest static void getCartsProducts_PostInvokeTest(){
        CpqAppHandlerHookImplementation controller = new CpqAppHandlerHookImplementation();

        Map<String,Object> inputMap = new Map<String,Object>();
        Map<String,Object> outputMap  = new Map<String,Object>();
        Map<String,Object> options  = new Map<String,Object>();

        Test.startTest();

        Id orderId = [SELECT Id FROM Order].Id;

        inputMap = new Map<String,Object>();
        inputMap.put('cartId', orderId);
        
        controller.invokeMethod('getCartsProducts.PostInvoke', inputMap, outputMap, options);         

        Test.stopTest();
    }

    @isTest static void getOffersByCatalogCode_PostInvoke(){
        CpqAppHandlerHookImplementation controller = new CpqAppHandlerHookImplementation();

        Map<String,Object> inputMap = new Map<String,Object>();
        Map<String,Object> outputMap  = new Map<String,Object>();
        Map<String,Object> options  = new Map<String,Object>();

        Map<String,String> inputValues = new Map<String,String>();
        inputValues.put('DDD' , '11');
        inputMap.put('context', JSON.serialize(inputValues));

        Map<String,String> mapOffer = new Map<String,String>();
        mapOffer.put('ProductCode', '0001');

        List<Object> listOffers = new List<Object>();
        listOffers.add(mapOffer);

        outputMap.put('offers', listOffers);

        Test.startTest();
        controller.invokeMethod('getOffersByCatalogCode.PostInvoke', inputMap, outputMap, options);         
        Test.stopTest();
    }    
}