force-app/main/default/objects/Account/fields/BillingAccountType__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountType__c</fullName>
    <label>Tipo de Conta Faturamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Móvel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FullAddress__c.field-meta.xml
<CustomField>
    <fullName>FullAddress__c</fullName>
    <formula>IF(RecordType.DeveloperName = &quot;Billing&quot;,    BillingAddressType__c  + &apos;,&apos; + BillingStreet + &apos;,&apos; + BillingNumber__c + &apos;,&apos; + BillingNeighborhood__c + &apos;,&apos; + BillingPostalCode + &apos;,&apos; + BillingCity + &apos;,&apos; + BillingState, ShippingAddressType__c  + &apos;,&apos; + ShippingStreet + &apos;,&apos; + ShippingNumber__c + &apos;,&apos; + ShippingNeighborhood__c + &apos;,&apos; + ShippingPostalCode + &apos;,&apos; + ShippingCity + &apos;,&apos; + ShippingState)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Endereço Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OfferReferenceValue__c.field-meta.xml
<CustomField>
    <fullName>OfferReferenceValue__c</fullName>
    <description>Valor utilizado no cálculo das ofertas</description>
    <formula>TVRecurrence__c + BroadbandRecurrence__c + FixedLineRecurrence__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Referência Oferta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <description>Valor total da última fatura</description>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BillingAccountDAO.cls
public with sharing class BillingAccountDAO {
   
    public static List<Account> getByAccountIdDeveloperName(Id accountId, String accountType){
        return[
            SELECT 
                Id, 
                ParentId,  
                FullAddress__c,
                ExternalId__c,
                LastModifiedDate, 
                TotalAmount__c, 
                OfferReferenceValue__c 
            FROM 
                Account 
            WHERE 
                Id IN (SELECT vlocity_cmt__BillingAccountId__c FROM Asset WHERE AccountId =: accountId)
            AND 
              BillingAccountType__c = :accountType
        ];
    }

    public static List<Account> getByAccountIdDeveloperNameLastmodifiedDate(Id accountId, String accountType, Datetime lastModifiedDate){
        return[
            SELECT 
                Id, 
                ParentId,  
                ExternalId__c,
                LastModifiedDate, 
                TotalAmount__c, 
                OfferReferenceValue__c 
            FROM 
                Account 
            WHERE 
                Id IN (SELECT vlocity_cmt__BillingAccountId__c FROM Asset WHERE AccountId =: accountId) 
            AND 
                BillingAccountType__c = :accountType
            AND 
                LastModifiedDate > : lastModifiedDate
        ];
    }
    public static Account getByName(String billingAccountName){
        List<Account> lst = getByName(new Set<String>{billingAccountName});
        return lst.isEmpty() ? null : lst[0];
    }

    public static List<Account> getByName(Set<String> setBillingAccountName){
        return[
            SELECT 
                Id,
                Name, 
                ParentId,  
                ExternalId__c,
                LastModifiedDate, 
                TotalAmount__c, 
                OfferReferenceValue__c 
            FROM 
                Account 
            WHERE 
              Name IN :setBillingAccountName
        ];
    }

    public static List<Account> getByNameOrExternalId(Set<String> setBillingAccountName){
        return[
            SELECT 
                Id,
                Name, 
                ParentId,  
                ExternalId__c,
                LastModifiedDate, 
                TotalAmount__c, 
                OfferReferenceValue__c 
            FROM 
                Account 
            WHERE 
              Name IN :setBillingAccountName
              OR
              ExternalId__c IN :setBillingAccountName
        ];
    }

    public static List<Account> getBillingAccountWithoutAsset(Set<Id> setAccountId){
        return[
            SELECT 
                Id, 
                Name, 
                ParentId 
            FROM 
                Account 
            WHERE 
                    Id NOT IN (SELECT vlocity_cmt__BillingAccountId__c FROM Asset WHERE  AccountId IN :setAccountId) 
                AND 
                    ParentId IN :setAccountId
        ];
    }
}