force-app/main/default/objects/Account/fields/BillingAccountType__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountType__c</fullName>
    <label>Tipo de Conta Faturamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Móvel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo fixo</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/AccountJob__c.field-meta.xml
<CustomField>
    <fullName>AccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar contas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AccountLoadDate__c</fullName>
    <label>Data da carga - Account</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressJob__c.field-meta.xml
<CustomField>
    <fullName>AddressJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar endereços</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AddressLoadDate__c</fullName>
    <label>Data de carga - Endereço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetJob__c.field-meta.xml
<CustomField>
    <fullName>AssetJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Assets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AssetLoadDate__c</fullName>
    <label>Data da carga - Asset</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountJob__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar conta de faturamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountLoadDate__c</fullName>
    <label>Data da carga - Conta de faturamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <label>Segmento do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Tipo do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceJob__c.field-meta.xml
<CustomField>
    <fullName>InvoiceJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Faturas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceLoadDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLoadDate__c</fullName>
    <label>Data da carga - Faturas</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MassiveBillingAccountCaseTest.cls
@isTest
public class MassiveBillingAccountCaseTest {
        
    @testSetup 
    static void setup(){
        Account lAccount = DataFactory.createAccount();
        
        insert lAccount;
        
        Account lBillingAccountFixed = DataFactory.createBillingAccount(lAccount.Id, 'Fixa');
        Account lBillingAccountMobile = DataFactory.createBillingAccount(lAccount.Id, 'Móvel');
        insert lBillingAccountFixed;
        insert lBillingAccountMobile;
        
        List<Asset> lstAsset = new List<Asset>();
        Asset asset = DataFactory.createAsset(lAccount.Id, 'Fixa');
        
        lstAsset.add(asset);
        lstAsset.add(DataFactory.createAsset(lAccount.Id, 'Móvel'));
        insert lstAsset;
        
        List<vlocity_cmt__CustomerInteraction__c> lstCustomerInteraction = new List<vlocity_cmt__CustomerInteraction__c>();        
        vlocity_cmt__CustomerInteraction__c customerInteractionFixa = DataFactory.createCustomerInteraction(lBillingAccountFixed.Id);
        vlocity_cmt__CustomerInteraction__c customerInteractionMovel = DataFactory.createCustomerInteraction(lBillingAccountMobile.Id);
        lstCustomerInteraction.add(customerInteractionFixa);
        lstCustomerInteraction.add(customerInteractionMovel);
		insert lstCustomerInteraction;        
        
        insert new GeneralParam__c(
            AccountLoadDate__c  = Datetime.now().addDays(-1),
            AssetLoadDate__c = Datetime.now().addDays(-1),
            BillingAccountLoadDate__c = Datetime.now().addDays(-1),
            InvoiceLoadDate__c = Datetime.now().addDays(-1),
            AddressLoadDate__c = Datetime.now().addDays(-1),
            AssetJob__c = true,
            BillingAccountJob__c = true,
            AccountJob__c = true,
            AddressJob__c = true,
            InvoiceJob__c = true,
            CustomerType__c = 'Totalizado;Fixa',
            CustomerSegment__c = 'TOP;VIP;PLATINUM'
        );        
    }    
    
    @isTest
    public static void getAccountRetentionFixedTest(){
        List<Account> lAccount = [SELECT Id FROM Account WHERE BillingAccountType__c = 'Fixa' LIMIT 1];	
        List<vlocity_cmt__CustomerInteraction__c> lCustomerInteraction = [SELECT Id FROM vlocity_cmt__CustomerInteraction__c WHERE vlocity_cmt__AccountId__c =: lAccount[0].Id];
        
        Test.startTest();        
        
            AccountRetentionTO.BillingAccount billingAccountObj = MassiveBillingAccountCaseController.getAccountRetentionFixed(lCustomerInteraction[0].Id);
            system.assert(billingAccountObj != null);
                
        Test.stopTest();
    }

    @isTest
    public static void getMassiveFixed(){
        Asset asset = [SELECT Id FROM Asset LIMIT 1];

        Map<String, Object> mapResponse = new Map<String, Object>();
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MassiveFixedCaseMock());
            mapResponse = MassiveBillingAccountCaseController.getMassiveFixed(asset.Id);
            System.assertEquals(true, mapResponse.get('success'));
        Test.stopTest();
    }

    @isTest
    public static void getMassiveSuspicion(){
        Asset asset = [SELECT Id FROM Asset LIMIT 1];

        Map<String, Object> mapResponse = new Map<String, Object>();
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MassiveSuspicionCaseMock());
            mapResponse = MassiveBillingAccountCaseController.getMassiveSuspicion(asset.Id);
            System.assertEquals(true, mapResponse.get('success'));
        Test.stopTest();
    }
}