force-app/main/default/objects/Account/fields/CreditScoreDate__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreDate__c</fullName>
    <label>Data da Consulta de Crédito</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/CreditScoreResultDescription__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreResultDescription__c</fullName>
    <label>Descrição Score de Crédito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/FromToMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para ser utilizado para inclusão de de/para que serão utilizados na Org.</description>
    <label>Mapeamento DePara</label>
    <pluralLabel>Mapeamento DePara</pluralLabel>
</CustomObject>

force-app/main/default/objects/FromToMapping__mdt/fields/DestinyName__c.field-meta.xml
<CustomField>
    <fullName>DestinyName__c</fullName>
    <description>Nome do campo desejado destino</description>
    <label>Nome do campo destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/fields/OriginApiName__c.field-meta.xml
<CustomField>
    <fullName>OriginApiName__c</fullName>
    <description>ApiName do campo desejado origem</description>
    <label>ApiName do campo Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/CreditConsultationExpiration__c.field-meta.xml
<CustomField>
    <fullName>CreditConsultationExpiration__c</fullName>
    <label>Vencimento da consulta de crédito(horas)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login de rede</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PartnerGroup__c.field-meta.xml
<CustomField>
    <fullName>PartnerGroup__c</fullName>
    <label>Grupo do Aliado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VendasAliado</fullName>
                <label>Vendas Aliado</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPConsultor</fullName>
                <label>Vendas Aliado PaP Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPGerente</fullName>
                <label>Vendas Aliado PaP Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaConsultor</fullName>
                <label>Vendas Aliado Revenda Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaGerente</fullName>
                <label>Vendas Aliado Revenda Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasGerente</fullName>
                <label>Vendas Aliado Televendas Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPSupervisor</fullName>
                <label>Vendas Aliado PaP Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasCoordenador</fullName>
                <label>Vendas Aliado Televendas Coordenador</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasSupervisor</fullName>
                <label>Vendas Aliado Televendas Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasConsultor</fullName>
                <label>Vendas Aliado Televendas Consultor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeOperador</fullName>
                <label>Atendimento Aliado Backoffice Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoOp</fullName>
                <label>Atendimento Aliado Backoffice Retencao Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoSup</fullName>
                <label>Atendimento Aliado Backoffice Retencao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeSupervisor</fullName>
                <label>Atendimento Aliado Backoffice Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Ativo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Ativo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaOperador</fullName>
                <label>Atendimento Aliado Ouvidoria Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaSupervisor</fullName>
                <label>Atendimento Aliado Ouvidoria Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingOp</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingSup</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Supervisor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreditAnalysisEngine.cls
public without sharing class CreditAnalysisEngine {

    public static Map<String,Object> executeCreditAnalysis(Account accountContext){
        return executeCreditAnalysis(accountContext, 'CreditService' );
    }

    public static Map<String,Object> executeCreditAnalysis(Account accountContext, String UsedIn){
        Map<String, Object> mapResponse = new Map<String,Object>();
        String salesChannel, salesChannelName;
        User user;
        Map<String,FromToMapping__mdt> mapFromTo;

        GeneralParam__c param = GeneralParam__c.getInstance(); 
       
        //Validar a regra de refazer consulta de crédito
        checkValidCreditAnalysis(mapResponse, accountContext, param.CreditConsultationExpiration__c);
       
        if(mapResponse.containsKey('success')){
            return mapResponse;
        }


        //Validar campos obrigatórios
        RequiredFieldsValidator.validateFields(mapResponse, accountContext, UsedIn);
        
        if(!mapResponse.containsKey('success')){
            return mapResponse;
        }
    
        user = UserDAO.getUserInfo()[0]; 
        
        mapFromTo = new Map<String,FromToMapping__mdt>();

        CollectionUtil.loadMap(mapFromTo, 'OriginApiName__c',
                    FromToMappingDAO.getFromOriginUsedIn('CreditService'));

        //Recuperar o papel do usuario
        if(user.Profile.UserLicense.Name != 'Partner Community'){
            FromToMapping__mdt mapping = mapFromTo.get(User.UserRole.DeveloperName);
            salesChannelname = 'SF-'+User.UserRole.DeveloperName;
            if(mapping != null){
                salesChannel = mapping.DestinyName__c;
            }else{
                salesChannel = user.UserRole.Name;
            }  
        }else{
            fromToMapping__mdt mapping = mapFromTo.get(User.PartnerGroup__c);
            salesChannelname = 'SF-'+User.PartnerGroup__c;
            if(mapping != null){
                salesChannel = mapping.DestinyName__c;
            }else{
                salesChannel = User.PartnerGroup__c;
            }
        }
        
        CreditAnalysisCallout.execute(mapResponse, accountContext, salesChannel, salesChannelName, user.Login__c);
        Account accToUpdate = new Account(Id = accountContext.Id);
        
        if(!mapResponse.containsKey('error') && mapResponse.get('success') != null){
            
            CreditAnalysisResponse response = (CreditAnalysisResponse) mapResponse.get('success');
            accToUpdate.vlocity_cmt__CreditScore__c = response.performAnalysisCreditResponse.customerCreditProfile.creditScore;
            accToUpdate.CreditScoreResultDescription__c = response.performAnalysisCreditResponse.result.description;
            accToUpdate.CreditScoreDate__c = System.now();
        }else{
            accToUpdate.vlocity_cmt__CreditScore__c = null;
            accToUpdate.CreditScoreResultDescription__c = null;
            accToUpdate.CreditScoreDate__c = null;
        }
        update accToUpdate;
        return mapResponse;
    }

    static void checkValidCreditAnalysis(map<String, Object> mapResponse, Account accountContext, String expiratonTime){
        if(accountContext.CreditScoreDate__c != null 
        && accountContext.CreditScoreDate__c.addHours(Integer.valueOf(expiratonTime)) > System.now()){
            mapResponse.put('success', 'A análise de crédito ainda está válida');
        }
    }
}