force-app/main/default/objects/Account/fields/CreditScoreDate__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreDate__c</fullName>
    <label>Data da Consulta de Crédito</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EmailPersonAccount__c.field-meta.xml
<CustomField>
    <fullName>EmailPersonAccount__c</fullName>
    <description>Campo formula para exibir mensagem na visão 360 caso o campo Email esteja vazio.</description>
    <formula>null</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>E-mail Principal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/WhiteListCharacteristic__c.field-meta.xml
<CustomField>
    <fullName>WhiteListCharacteristic__c</fullName>
    <label>Score do Whitelist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WhiteListCharacteristic</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/WhiteListCharacteristic.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VERMELHO</fullName>
    </customValue>
    <customValue>
        <fullName>AMARELO</fullName>
    </customValue>
    <customValue>
        <fullName>VERDE 1</fullName>
    </customValue>
    <customValue>
        <fullName>VERDE 2</fullName>
    </customValue>
    <customValue>
        <fullName>VERDE 3</fullName>
    </customValue>
    <customValue>
        <fullName>VERDE 4</fullName>
    </customValue>
    <customValue>
        <fullName>VERDE 5</fullName>
    </customValue>
    <customValue>
        <fullName>VERDE 6</fullName>
    </customValue>
    <customValue>
        <fullName>VERDE 7</fullName>
    </customValue>
    <customValue>
        <fullName>VERDE 8</fullName>
    </customValue>
    <description>Caracteristica da whitelist</description>
    <masterLabel>WhiteListCharacteristic</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountDAO.cls
/** 
 * @author Diego Costa @ Deloitte
 * @date 02/06/2022
 * @description Controla a busca e criação do objeto Account
 */
public with sharing class AccountDAO {
    
    public static Account getByIds(Id accountId){
        List<Account> lst = getByIds(new Set<Id>{accountId});
        return lst.isEmpty() ? null : lst[0];
    }

    public static Account getAccountByIdAndLastMod(Id accountId, Datetime dateOfLastMod){
        List<Account> lst = getAccountsByIdAndLastMod(new Set<Id>{accountId}, dateOfLastMod);
        return lst.isEmpty() ? null : lst[0];
    }
    
    public static List<Account> getByIds(Set<Id> setAccountId){
        return [SELECT    
               	 Id,
                 Name,
                 DocumentNumber__c,
                 UserId__c,
                 RecordTypeId,
              //   CustomerSegment__c, 
                 vlocity_cmt__CustomerClass__c, 
                 WhiteListCharacteristic__c, 
                 LastModifiedDate
                FROM 
                  Account
                WHERE 
                  Id IN :setAccountId
               ];
    }

    public static List<Account> getAccountById(Id accountId){
        return [
            SELECT    
                Id,
                Name,
                DocumentNumber__c,
                UserId__c,
        //        CustomerSegment__c,
                vlocity_cmt__PrimaryContactId__r.MotherName__c,                
                CreditScoreDate__c,
                RecordTypeId,
                vlocity_cmt__CreditScore__c
            FROM 
                Account
            WHERE 
                Id =: accountId];
        
    }

    public static List<Account> getActiveById(String accountId){
        return [
            SELECT Id, 
          //      CustomerSegment__c, 
                vlocity_cmt__CustomerClass__c, 
                WhiteListCharacteristic__c, 
                LastModifiedDate,
                vlocity_cmt__CreditScore__c
            FROM 
                Account 
            WHERE 
                vlocity_cmt__Active__c = 'Yes' 
            AND Id = :accountId];
    }
    
    public static List<Account> getAccountUserIdById(Id accountId){
        List<Account> lstAccount = new List<Account>();

        lstAccount = [SELECT    
                            Id,
                      		DocumentNumber__c,
                            UserId__c
                        FROM 
                            Account
                        WHERE 
                            Id =: accountId];
        return lstAccount;
    }

    public static List<Account> getAccountsByIdAndLastMod(Set<Id> setAccountId, Datetime dateOfLastMod){
        List<Account> ltAccount = [SELECT    
                                        Id,
                                        Name,
                                        vlocity_cmt__PrimaryContactId__r.MotherName__c,                                        
          //                              EmailPersonAccount__c,
                                        (SELECT Email FROM Contacts)
                                    FROM 
                                        Account
                                    WHERE 
                                        Id IN: setAccountId
                                        AND LastModifiedDate >: dateOfLastMod
                                        ];
        return ltAccount;
    }

    public static Account getAccountByCNPJ(String cnpj){
        List<Account> lst = getAccountListByCNPJ(new Set<String>{cnpj});
        return lst.isEmpty() ? null : lst[0];
    }


    public static List<Account> getAccountListByCNPJ (Set<String> cnpjSet) {
        return [
                SELECT    
                    Id,
                    Name,
                    DocumentNumber__c,
                    UserId__c,
                    vlocity_cmt__PrimaryContactId__r.MotherName__c,                    
                    CreditScoreDate__c,
                    RecordTypeId,
                    vlocity_cmt__CreditScore__c
                FROM 
                    Account
                WHERE 
                    DocumentNumber__c =: cnpjSet
                LIMIT 1
            ];
    }
}