force-app/main/default/objects/Account/fields/CreditScoreDate__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreDate__c</fullName>
    <label>Data da Consulta de Crédito</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/CreditConsultationExpiration__c.field-meta.xml
<CustomField>
    <fullName>CreditConsultationExpiration__c</fullName>
    <label>Vencimento da consulta de crédito(horas)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreditAnalysisEngineTest.cls
@IsTest
public with sharing class CreditAnalysisEngineTest {
    @TestSetup
	static void setup(){
        AccountTestFactory.start().startPersonAccount().create();
        insert new GeneralParam__c(CreditConsultationExpiration__c = '24');
	}

    @IsTest
    static void executeCreditAnalysis(){
        Map<String, object> mapResult = new Map<string, Object>();
		List<Account> accList = [ SELECT    
							Id,
							Name,
							DocumentNumber__c,
							UserId__c,
							vlocity_cmt__PrimaryContactId__r.MotherName__c,
							vlocity_cmt__PrimaryContactId__r.Birthdate,
							CreditScoreDate__c,
							RecordTypeId,
							vlocity_cmt__CreditScore__c
						FROM 
						Account];
        Test.startTest();
           mapResult =  CreditAnalysisEngine.executeCreditAnalysis(accList[0]);
        Test.stopTest();
        System.debug(mapResult);
        System.assert(mapResult != null , 'O objeto de resultado não foi preenchido');
    }
}