force-app/main/default/objects/Account/fields/CustomerMoodRating__c.field-meta.xml
<CustomField>
    <fullName>CustomerMoodRating__c</fullName>
    <label>Cliente irritado no atendimento?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__CustomerValue__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__CustomerValue__c</fullName>
    <description>A ranking of the value of this customer to your business expressed in marketing terms such as Gold, Silver, Bronze, Diamond, Platinum.</description>
    <label>Customer Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CallerPhone__c.field-meta.xml
<CustomField>
    <fullName>CallerPhone__c</fullName>
    <description>Telefone chamador registrado na URA.</description>
    <label>Telefone Chamador</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseComplexityReason__c.field-meta.xml
<CustomField>
    <fullName>CaseComplexityReason__c</fullName>
    <description>Lista de opções para complexidade do caso</description>
    <inlineHelpText>Motivos de baixa Complexidade, o caso é atribuído para o operador que criou o chamado. 
Motivos de Alta Complexidade, o caso é enviado para uma fila para tratativa dos Guardiões</inlineHelpText>
    <label>Complexidade do caso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Motivos de baixa Complexidade</fullName>
                <default>true</default>
                <label>Motivos de Baixa Complexidade</label>
            </value>
            <value>
                <fullName>Motivos de Alta Complexidade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Observação</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ContactPhone__c</fullName>
    <label>Telefone de Contato</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerMoodRating__c.field-meta.xml
<CustomField>
    <fullName>CustomerMoodRating__c</fullName>
    <description>Informação da temperatura do cliente durante o atendimento</description>
    <inlineHelpText>Temperatura do cliente - informar se o cliente está irritado: sim ou não</inlineHelpText>
    <label>Cliente Irritado no Atendimento?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
                <default>true</default>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerServiceReason__c.field-meta.xml
<CustomField>
    <fullName>CustomerServiceReason__c</fullName>
    <description>Campo usado no HDE, atrelado ao grupo do atendente e usado no mapeamento do HDE DE PARA para classificação do chamado como Alta complexidade e crítico</description>
    <label>Motivo do atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2ª via de Nota Fiscal</fullName>
            </value>
            <value>
                <fullName>Acompanhamento de Técnico Fixa</fullName>
            </value>
            <value>
                <fullName>Agenda técnica não cumprida</fullName>
            </value>
            <value>
                <fullName>Alocação de fundos Kenan</fullName>
            </value>
            <value>
                <fullName>Análise/Suspeita de Fraude</fullName>
            </value>
            <value>
                <fullName>Análise de Cobertura</fullName>
            </value>
            <value>
                <fullName>Análise de Cobertura Condomínio</fullName>
            </value>
            <value>
                <fullName>Análise de crédito para mudança de Plano</fullName>
            </value>
            <value>
                <fullName>Análise de Retirada de Fidelidade</fullName>
            </value>
            <value>
                <fullName>Ativação de E-Sim</fullName>
            </value>
            <value>
                <fullName>Ativação de serviço (falha sistêmica)</fullName>
            </value>
            <value>
                <fullName>Atraso na entrega de controle remoto</fullName>
            </value>
            <value>
                <fullName>Baixa de Pagto / Envio de Comprovante / Religue</fullName>
            </value>
            <value>
                <fullName>Biometria Documental</fullName>
            </value>
            <value>
                <fullName>Chamador diferente binado p/ troca de número</fullName>
            </value>
            <value>
                <fullName>Cliente reindente em contestação</fullName>
            </value>
            <value>
                <fullName>Cliente vai pensar</fullName>
            </value>
            <value>
                <fullName>Cliente Vivo 1</fullName>
            </value>
            <value>
                <fullName>Contestação Kenan</fullName>
            </value>
            <value>
                <fullName>Contestação por Retificação acima de 1 Fatura</fullName>
            </value>
            <value>
                <fullName>Contestação Próximo Ciclo</fullName>
            </value>
            <value>
                <fullName>Contestação que seja necessário ouvir gravação</fullName>
            </value>
            <value>
                <fullName>Contrato - Locação</fullName>
            </value>
            <value>
                <fullName>Correção Causa Raiz - Contestação</fullName>
            </value>
            <value>
                <fullName>Correção de cadastro Siebel</fullName>
            </value>
            <value>
                <fullName>Correção de SubSegmento (PJ/PF)</fullName>
            </value>
            <value>
                <fullName>Dados de Oferta/Valores Divergentes</fullName>
            </value>
            <value>
                <fullName>Desbloqueio Linha/Aparelho</fullName>
            </value>
            <value>
                <fullName>Desconto Oferta Totalizadora</fullName>
            </value>
            <value>
                <fullName>Desmembramento de contas (Pós Pago - NEXT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/HDEOtherProducts__c.field-meta.xml
<CustomField>
    <fullName>HDEOtherProducts__c</fullName>
    <label>Outros Produtos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Campo utilizado na parametrização de casos de alta complexidade e críticos no custom metadata HDE DE-PARA, para dependencias de campos e para campos fórmula no objeto. ex: visão</description>
    <label>Grupo de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
                <label>Revendas</label>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>VPR Lojas</fullName>
            </value>
            <value>
                <fullName>V</fullName>
                <isActive>false</isActive>
                <label>V</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SegmentProduct__c.field-meta.xml
<CustomField>
    <fullName>SegmentProduct__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Móvel</fullName>
            </value>
            <value>
                <fullName>OtherProduct</fullName>
                <label>Outros Produtos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/GeneralSetting__c.object-meta.xml
<CustomObject>
    <label>Configuração Geral</label>
    <nameField>
        <label>Configuração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações Gerais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationEmailToNCases__c.field-meta.xml
<CustomField>
    <fullName>NotificationEmailToNCases__c</fullName>
    <label>Notificação Email para N Casos</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationEmailToOneCase__c.field-meta.xml
<CustomField>
    <fullName>NotificationEmailToOneCase__c</fullName>
    <label>Notificação E-mail para Um Caso</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationLittleBellToNCases__c.field-meta.xml
<CustomField>
    <fullName>NotificationLittleBellToNCases__c</fullName>
    <label>Notificação Sininho para N Casos</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationLittleBellToOneCase__c.field-meta.xml
<CustomField>
    <fullName>NotificationLittleBellToOneCase__c</fullName>
    <label>Notificação Sininho para um Caso</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/NotificationName__c.field-meta.xml
<CustomField>
    <fullName>NotificationName__c</fullName>
    <label>Nome Notificação</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/TitleNotificationLittleBellToNCases__c.field-meta.xml
<CustomField>
    <fullName>TitleNotificationLittleBellToNCases__c</fullName>
    <label>Título Notificação Sininho para N Casos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/fields/TitleNotificationLittleBellToOneCase__c.field-meta.xml
<CustomField>
    <fullName>TitleNotificationLittleBellToOneCase__c</fullName>
    <label>Título Notificação Sininho para um Caso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__c/recordTypes/UserComunicationSetup.recordType-meta.xml
<RecordType>
    <fullName>UserComunicationSetup</fullName>
    <active>true</active>
    <description>Configuração de Notificações de Usuários, informa o tipo de notificação/email que cada tipo de usuário deve receber dependendo do status, momento de trigger, recordtype do caso</description>
    <label>Configuração de Notificações de Usuários</label>
</RecordType>

force-app/main/default/classes/SenderCaseNotificationScheduleTest.cls
@IsTest
public with sharing class SenderCaseNotificationScheduleTest {
    @TestSetup
    public static void setup() {   
        Profile profile = [
            SELECT 
                Id, 
                Name 
            FROM 
                Profile 
            WHERE 
                Name LIKE 'Representante' 
            LIMIT 1
        ];
        
        UserRole role = [
            SELECT 
                Id, 
                Name 
            FROM 
                UserRole 
            WHERE 
                DeveloperName LIKE 'AtendimentoGoldOperador' 
            LIMIT 1
        ]; 

        UserRole roleManager = [
            SELECT 
                Id, 
                Name 
            FROM 
                UserRole 
            WHERE 
                DeveloperName LIKE 'AtendimentoGoldAdmProcessos' 
            LIMIT 1
        ];

        User userManagerTest = DataFactory.createUser(profile.Id, roleManager.Id);

        userManagerTest.Email = 'marciol.silva@telefonica.com';

        insert userManagerTest;

        User userTest = DataFactory.createUser(profile.Id, role.Id);

        userTest.ManagerId = userManagerTest.Id;
        
        insert userTest;
        
        System.runAs(userTest) {
            Account accountTest = new Account();
            
            accountTest.Name = 'Validate Test 1';
            accountTest.vlocity_cmt__CustomerValue__c = 'Gold';
            
            insert accountTest; 

            String recType = 'HDE - Gold Processos Escalonamento';
            String recordTypeDeveloperName = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recType).getDeveloperName();
    
            Case caseTest = DataFactory.createCase(recordTypeDeveloperName, 'Test Case #1', 'Case test');
            
            caseTest.Origin = 'HDE';
            caseTest.AccountId = accountTest.Id;
            caseTest.Segment__c = 'Gold';
            caseTest.CustomerServiceReason__c = 'Agenda técnica não cumprida';
            caseTest.ContactPhone__c = '(081)982925763';
            caseTest.CallerPhone__c = '(081)982925763';
            caseTest.Comment__c = 'Caso Gold Test';
            caseTest.Protocol__c = '12345678';
            caseTest.SegmentProduct__c = 'OtherProduct';
            caseTest.HDEOtherProducts__c = 'SIMCard';
            caseTest.CustomerMoodRating__c = 'Não';
            caseTest.CaseComplexityReason__c = 'Motivos de baixa Complexidade';
            caseTest.Status = 'A Iniciar';
            caseTest.OwnerId = userTest.Id;

            insert caseTest;
            
            Id recordTpId = Schema.SObjectType.GeneralSetting__c.getRecordTypeInfosByDeveloperName().get('UserComunicationSetup').getRecordTypeId();
            List<GeneralSetting__c> generalSettings = new List<GeneralSetting__c>{
                new GeneralSetting__c(
                Name = 'ExpiredSLAUserAbove3rd',
                NotificationName__c = 'ExpiredSLAUserAbove3rd',
                NotificationLittleBellToOneCase__c = 'One case bell notification',
                NotificationLittleBellToNCases__c = 'Multiple cases bell notification',
                NotificationEmailToOneCase__c = 'One case email notification',
                NotificationEmailToNCases__c = 'Multiple cases email notification',
                TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases',
                TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one case',
                RecordTypeId = recordTpId),
                new GeneralSetting__c(
                Name = 'RoutingNewOwnerOwner',
                NotificationName__c = 'RoutingNewOwnerOwner',
                NotificationLittleBellToOneCase__c = 'One case bell notification',
                NotificationLittleBellToNCases__c = 'Multiple cases bell notification',
                NotificationEmailToOneCase__c = 'One case email notification',
                NotificationEmailToNCases__c = 'Multiple cases email notification',
                TitleNotificationLittleBellToNCases__c = 'Bell notification title for multiple cases',
                TitleNotificationLittleBellToOneCase__c = 'Bell notification title for one case',
                RecordTypeId = recordTpId)
            }; 
            
            insert generalSettings;
            
        }
    }
    
    @IsTest
    public static void ScheduleSenderNotificationCaseTest() {
        Test.startTest();
            String jobId = System.schedule('ScheduledApexTest',
                '0 0 1 * * ?',
                new SenderCaseNotificationSchedule()
            );
        Test.stopTest();
    }
}