force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo fixo</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Movel.recordType-meta.xml
<RecordType>
    <fullName>Movel</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo móvel</description>
    <label>Movel</label>
</RecordType>

force-app/main/default/objects/BlockPartialDisconnection__c/BlockPartialDisconnection__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Impedimento Desconexao Parcial</label>
</CustomObject>

force-app/main/default/objects/BlockPartialDisconnection__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/AccountJob__c.field-meta.xml
<CustomField>
    <fullName>AccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar contas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AccountLoadDate__c</fullName>
    <label>Data da carga - Account</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressJob__c.field-meta.xml
<CustomField>
    <fullName>AddressJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar endereços</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AddressLoadDate__c</fullName>
    <label>Data de carga - Endereço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetJob__c.field-meta.xml
<CustomField>
    <fullName>AssetJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Assets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AssetLoadDate__c</fullName>
    <label>Data da carga - Asset</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountJob__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar conta de faturamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountLoadDate__c</fullName>
    <label>Data da carga - Conta de faturamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <label>Segmento do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Tipo do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceJob__c.field-meta.xml
<CustomField>
    <fullName>InvoiceJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Faturas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceLoadDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLoadDate__c</fullName>
    <label>Data da carga - Faturas</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InitialOffer__c/InitialOffer__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Oferta Inicial</label>
</CustomObject>

force-app/main/default/objects/InitialOffer__c/fields/BroadbandSpeed__c.field-meta.xml
<CustomField>
    <fullName>BroadbandSpeed__c</fullName>
    <label>Velocidade Banda Larga</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InitialOffer__c/fields/OfferGroup__c.field-meta.xml
<CustomField>
    <fullName>OfferGroup__c</fullName>
    <label>Grupo da Oferta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InitialOffer__c/fields/Tecnology__c.field-meta.xml
<CustomField>
    <fullName>Tecnology__c</fullName>
    <label>Tecnologia</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InitialOffer__c/fields/TvPlanName__c.field-meta.xml
<CustomField>
    <fullName>TvPlanName__c</fullName>
    <label>Nome do Plano de TV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InitialOffer__c/fields/VoicePlan__c.field-meta.xml
<CustomField>
    <fullName>VoicePlan__c</fullName>
    <label>Plano de Voz</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <description>Tipo de Cliente que a Oferta se aplica, utilizado apenas pela Ofertas de Retenção Móvel.</description>
    <inlineHelpText>Tipo de cliente que a oferta de retenção móvel se aplica.</inlineHelpText>
    <label>Tipo de Cliente da Oferta</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Móvel</fullName>
            </value>
            <value>
                <fullName>Totalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/OfferCityCategory__c.field-meta.xml
<CustomField>
    <fullName>OfferCityCategory__c</fullName>
    <description>Categoria da Cidade que a oferta é aplicável</description>
    <label>Categoria Cidade e Armário</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>TODAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/OfferGroup__c.field-meta.xml
<CustomField>
    <fullName>OfferGroup__c</fullName>
    <label>Grupo de Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Aquisição</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/recordTypes/AltaMovel.recordType-meta.xml
<RecordType>
    <fullName>AltaMovel</fullName>
    <active>true</active>
    <description>Ofertas de Alta para Móvel</description>
    <label>Alta Móvel</label>
</RecordType>

force-app/main/default/objects/Offer__c/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <description>Ofertas Fixa de Retenção</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/Offer__c/recordTypes/Movel.recordType-meta.xml
<RecordType>
    <fullName>Movel</fullName>
    <active>true</active>
    <description>Ofertas Móvel de Retenção</description>
    <label>Móvel</label>
</RecordType>

force-app/main/default/objects/OfferFilter__c/OfferFilter__c.object-meta.xml
<CustomObject>
    <description>Registros utilizado para gerenciar filtros do componente customizado de ofertas fixa e móvel</description>
    <label>Filtro de Oferta</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Nome do Filtro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filtro de Ofertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OfferFilter__c/recordTypes/Cabinet.recordType-meta.xml
<RecordType>
    <fullName>Cabinet</fullName>
    <active>true</active>
    <description>Para criar filtros de armários</description>
    <label>Armário</label>
</RecordType>

force-app/main/default/objects/OfferFilter__c/recordTypes/CityCategory.recordType-meta.xml
<RecordType>
    <fullName>CityCategory</fullName>
    <active>true</active>
    <description>Para criar filtros de categoria cidade</description>
    <label>Categoria Cidade</label>
</RecordType>

force-app/main/default/objects/OffersFilter__c/OffersFilter__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Filtro de Ofertas</label>
</CustomObject>

force-app/main/default/objects/OffersFilter__c/fields/BandwidthPlanFTTC__c.field-meta.xml
<CustomField>
    <fullName>BandwidthPlanFTTC__c</fullName>
    <label>Plano de Banda Larga FTTC</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OffersFilter__c/fields/BandwidthPlanFTTH__c.field-meta.xml
<CustomField>
    <fullName>BandwidthPlanFTTH__c</fullName>
    <label>Plano de Banda Larga FTTH</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OffersFilter__c/fields/BandwidthPlanXDSL__c.field-meta.xml
<CustomField>
    <fullName>BandwidthPlanXDSL__c</fullName>
    <label>Plano de Banda Larga XDSL</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OffersFilter__c/fields/OfferGroup__c.field-meta.xml
<CustomField>
    <fullName>OfferGroup__c</fullName>
    <label>Grupo de Ofertas</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OffersFilter__c/fields/TvPlan__c.field-meta.xml
<CustomField>
    <fullName>TvPlan__c</fullName>
    <label>Plano de TV</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OffersFilter__c/fields/VoicePlan__c.field-meta.xml
<CustomField>
    <fullName>VoicePlan__c</fullName>
    <label>Plano de Voz</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuggestedSpeed__c/SuggestedSpeed__c.object-meta.xml
<CustomObject>
    <label>Velocidade sugerida</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Velocidade sugerida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Velocidades sugeridas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuggestedSpeed__c/fields/SuggestedSpeed__c.field-meta.xml
<CustomField>
    <fullName>SuggestedSpeed__c</fullName>
    <label>Velocidade sugerida</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CardOfferControllerTest.cls
/*
---------------------------------------------------
@authors - Geimison Oliveira | Pedro Salles 
@company - Telefonica 
@date - 08/04/2020
@description - Classe de Teste da Controller dos componentes 
customizados de Ofertas para retenção de contas 
do tipo Fixa e Móvel
---------------------------------------------------

*/
@isTest
public class CardOfferControllerTest {
    
    @testSetup 
    static void setup(){
        
        UserRole userR = new UserRole();
        userR.Name = 'Omnichannel';
        Database.insert(userR);
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Governanca'];
        User u = new User(Alias = 'SysAdmin', Email='stdstdteste@teste.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId = userR.Id,
                          TimeZoneSidKey='America/Sao_Paulo', UserName='stdteste@teste.com');
        Database.insert(u);
        
        PermissionSet ps = [SELECT ID,Name,Label FROM PermissionSet WHERE Name = 'OfferMenu' LIMIT 1];
        
        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.PermissionSetId = ps.Id;
        psa.AssigneeId = u.Id;
        
        Database.insert(psa);
        
        System.runAs(u){
            
            Account lAccount = DataFactory.createAccount();
            insert lAccount;
            
            Account lBillingAccountFixed = DataFactory.createBillingAccount(lAccount.Id, 'Fixa');
            Account lBillingAccountMobile = DataFactory.createBillingAccount(lAccount.Id, 'Móvel');
            
            insert lBillingAccountFixed;
            insert lBillingAccountMobile;

            Account lServiceAccountFixed = DataFactory.createServiceAccount(lAccount.Id, lBillingAccountFixed.Id, 'Fixa');
            Account lServiceAccountMobile = DataFactory.createServiceAccount(lAccount.Id, lBillingAccountMobile.Id, 'Móvel');
            
            insert lServiceAccountFixed;
            insert lServiceAccountMobile;

            vlocity_cmt__CustomerInteraction__c lCustomerInteraction = DataFactory.createCustomerInteraction(lAccount.Id);
            insert lCustomerInteraction;


            List<Offer__c> lstOffer = new List<Offer__c>();
            Offer__c offer = DataFactory.createOfferFixed(lAccount.Id);
            Offer__c offerCabinet = DataFactory.createOfferFixed(lAccount.Id);
            offerCabinet.OfferCityCategory__c = null;
            
            lstOffer.add(offer);
            lstOffer.add(offerCabinet);
            lstOffer.add(DataFactory.createOfferMobile(lAccount.Id, 'Movel'));
            lstOffer.add(DataFactory.createOfferMobile(lAccount.Id, 'AltaMovel'));
            insert lstOffer;
            
            List<Asset> lstAsset = new List<Asset>();
            Asset asset = DataFactory.createAsset(lAccount.Id, lBillingAccountFixed.Id, lServiceAccountFixed.Id, 'Fixa');
            // asset.Address__c = address.Id;
            lstAsset.add(asset);
            lstAsset.add(DataFactory.createAsset(lAccount.Id, lBillingAccountMobile.Id, lServiceAccountMobile.Id, 'Móvel'));
            insert lstAsset;
            
            List<OfferFilter__c> lstOfferFilter = new List<OfferFilter__c>();
            lstOfferFilter.add(DataFactory.createOfferFilter('Cabinet'));
            lstOfferFilter.add(DataFactory.createOfferFilter('CityCategory'));
            insert lstOfferFilter;
            
            SuggestedSpeed__c suggestedSpeed = new SuggestedSpeed__c();
            suggestedSpeed = DataFactory.createSuggestedSpeed();
            insert suggestedSpeed;
            
            insert new GeneralParam__c(
                AccountLoadDate__c  = Datetime.now().addDays(-1),
                AssetLoadDate__c = Datetime.now().addDays(-1),
                BillingAccountLoadDate__c = Datetime.now().addDays(-1),
                InvoiceLoadDate__c = Datetime.now().addDays(-1),
                AddressLoadDate__c = Datetime.now().addDays(-1),
                AssetJob__c = true,
                BillingAccountJob__c = true,
                AccountJob__c = true,
                AddressJob__c = true,
                InvoiceJob__c = true,
                CustomerType__c = 'Totalizado;Fixa',
                CustomerSegment__c = 'TOP;VIP'
            );
            
            
            OffersFilter__c offerFilters = new OffersFilter__c();
            offerFilters.Name='Filtro de Ofertas';
            offerFilters.OfferGroup__c = 'Retenção;Aquisição;Base';
            offerFilters.BandwidthPlanFTTC__c = '2;4;6;8;Sem Banda Larga';
            offerFilters.BandwidthPlanFTTH__c = '100;200;300;600;Sem Banda Larga';
            offerFilters.BandwidthPlanXDSL__c = '2;4;Sem Banda Larga';
            offerFilters.TvPlan__c = 'Vivo Play Padrão;Vivo Play Essencial;Vivo Play Ultra;Vivo Play Avançado;Vivo Play Completo;Sem TV';
            offerFilters.VoicePlan__c = 'Vivo Fixo Ilimitado Brasil;Vivo Fixo Ilimitado Local;Vivo Fixo Ilimitado Brasil Especial;Vivo Fixo Ilimitado Local Especial;Sem Voz';
            insert offerFilters;
            
            InitialOffer__c initialOffer = new InitialOffer__c();
            initialOffer.Name='Oferta Inicial';
            initialOffer.BroadbandSpeed__c = '300';
            initialOffer.TvPlanName__c = 'Vivo Play Essencial';
            initialOffer.VoicePlan__c = 'Vivo Fixo Ilimitado Brasil';
            initialOffer.Tecnology__c = 'FTTH';
            initialOffer.OfferGroup__c = 'Aquisição';
            
            insert initialOffer;
                        
            BlockPartialDisconnection__c blockPartialDesco = new BlockPartialDisconnection__c();
            blockPartialDesco.Name='Impedimento Desconexao Parcial';
            blockPartialDesco.Papel__c='OperadorGoldRetencaoFixa';
                        
            insert blockPartialDesco;
        }
    }
    
    @isTest
    public static void getBillingAccountCardTest(){
        
        User u = [SELECT id FROM User WHERE UserName = 'stdteste@teste.com' LIMIT 1];
        System.runAs(u){
            
            Map<String,Object> accountMap = new Map<String,Object>(); 
            Account lAccount = [ SELECT Id, Name FROM Account LIMIT 1];
            Id userId = UserInfo.getUserId();
            
            Test.startTest();       
            Id idOfferFixed;
            Id idOfferMobile;
            Id idOfferMobileAlta;
            
            vlocity_cmt__CustomerInteraction__c lCustomerInteraction = [ SELECT Id FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];
            List<AccountRetentionController.BillingAccount> lLstFixed = AccountRetentionController.getAccountRetentionFixed(lCustomerInteraction.Id);
            for(AccountRetentionController.BillingAccount itemBilling : lLstFixed){
                
                itemBilling.setCityCategories = new List<String>{'A'};
                    itemBilling.setCabinet.add(true);
                itemBilling.setCabinet.add(false);
                itemBilling.setOfferLevel.add('Nivel_1');
                itemBilling.speedSelected = '25';
                itemBilling.tvPlanSelected = 'Sem TV';
                itemBilling.fixedLineSelected = 'Vivo Fixo Ilimitado';
                itemBilling.offerGroupSelected = 'Retenção';
                itemBilling.accTechnology = 'FTTH';
                
                List<AccountRetentionController.Offer> lstOffer = AccountRetentionController.getOfferFilterFixed(itemBilling);
                itemBilling.ltOffer = lstOffer;
                for(AccountRetentionController.Offer itemOffer : lstOffer){
                    idOfferFixed = itemOffer.idOffer;                    
                }
                itemBilling.selectedOfferId = idOfferFixed;            
                
            }
            
            List<AccountRetentionController.BillingAccount> lLstMobile = new List<AccountRetentionController.BillingAccount>(); 
            
            List<AccountRetentionController.Offer> lLstMobileAlta = new List<AccountRetentionController.Offer>();
            
            accountMap = AccountRetentionController.getAccountRetentionMobile(lCustomerInteraction.Id);
            
            lLstMobile.addAll((List<AccountRetentionController.BillingAccount>) accountMap.get('ltBillingAccount'));
            for(AccountRetentionController.BillingAccount itemBilling : lLstMobile){
                if(itemBilling.ltAssetMovel != null && !itemBilling.ltAssetMovel.isEmpty()){
                    for(AccountRetentionController.AssetMovel itemAsset : itemBilling.ltAssetMovel ){
                        if(itemAsset.ltOffer != null && !itemAsset.ltOffer.isEmpty()){
                            for(AccountRetentionController.Offer itemOffer : itemAsset.ltOffer){
                                idOfferMobile = itemOffer.idOffer;
                            }
                            itemAsset.selectedOfferId = idOfferMobile;
                        }
                    }
                }            
            }
            lLstMobileAlta.addAll((List<AccountRetentionController.Offer>) AccountRetentionController.getOffer(lAccount.Id).get('ltOfferAlta'));
            
            for(AccountRetentionController.Offer itemOffer : lLstMobileAlta){            
                idOfferMobileAlta = itemOffer.idOffer;                    
            }
            
            String JSONFixed = JSON.serialize(lLstFixed);
            String JSONMobile = JSON.serialize(lLstMobile);
            String JSONMobileAlta = JSON.serialize(lLstMobileAlta);
            
            CardOfferController.getBillingAccountCard(JSONFixed, JSONMobile, JSONMobileAlta, idOfferMobileAlta, lAccount.Id, userId);
            
            Test.stopTest();
        }
    } 
    
    
}