force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FullAddress__c.field-meta.xml
<CustomField>
    <fullName>FullAddress__c</fullName>
    <formula>IF(RecordType.DeveloperName = &quot;Billing&quot;,    BillingAddressType__c  + &apos;,&apos; + BillingStreet + &apos;,&apos; + BillingNumber__c + &apos;,&apos; + BillingNeighborhood__c + &apos;,&apos; + BillingPostalCode + &apos;,&apos; + BillingCity + &apos;,&apos; + BillingState, ShippingAddressType__c  + &apos;,&apos; + ShippingStreet + &apos;,&apos; + ShippingNumber__c + &apos;,&apos; + ShippingNeighborhood__c + &apos;,&apos; + ShippingPostalCode + &apos;,&apos; + ShippingCity + &apos;,&apos; + ShippingState)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Endereço Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OfferReferenceValue__c.field-meta.xml
<CustomField>
    <fullName>OfferReferenceValue__c</fullName>
    <description>Valor utilizado no cálculo das ofertas</description>
    <formula>TVRecurrence__c + BroadbandRecurrence__c + FixedLineRecurrence__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Referência Oferta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__CustomerValue__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__CustomerValue__c</fullName>
    <description>A ranking of the value of this customer to your business expressed in marketing terms such as Gold, Silver, Bronze, Diamond, Platinum.</description>
    <label>Customer Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/AccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AccountLoadDate__c</fullName>
    <label>Data da carga - Account</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AssetLoadDate__c</fullName>
    <label>Data da carga - Asset</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountLoadDate__c</fullName>
    <label>Data da carga - Conta de faturamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <label>Segmento do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Tipo do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <description>Tipo de Cliente que a Oferta se aplica, utilizado apenas pela Ofertas de Retenção Móvel.</description>
    <inlineHelpText>Tipo de cliente que a oferta de retenção móvel se aplica.</inlineHelpText>
    <label>Tipo de Cliente da Oferta</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Móvel</fullName>
            </value>
            <value>
                <fullName>Totalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountRetentionEngine.cls
public with sharing class AccountRetentionEngine {
    
    public static List<Account> getAccount(Account accountObj, GeneralParam__c generalParamObj, String developerName){	
        List<String> ltCustomerSegment = CollectionUtil.stringForList(generalParamObj.CustomerSegment__c);
        List<String> ltCustomerType = CollectionUtil.stringForList(generalParamObj.CustomerType__c);
        List<Account> ltAccount = new List<Account>();

        if(accountObj == null || (ltCustomerSegment.contains(accountObj.vlocity_cmt__CustomerValue__c) && ltCustomerType.contains(accountObj.vlocity_cmt__CustomerClass__c) && accountObj.LastModifiedDate < generalParamObj.AccountLoadDate__c) ){
            return ltAccount;
        }

        
        if(ltCustomerSegment.contains(accountObj.vlocity_cmt__CustomerValue__c) && ltCustomerType.contains(accountObj.vlocity_cmt__CustomerClass__c)){    
            ltAccount = BillingAccountDAO.getByAccountIdDeveloperNameLastmodifiedDate(accountObj.Id, developerName, generalParamObj.BillingAccountLoadDate__c);
        }else{
            ltAccount = BillingAccountDAO.getByAccountIdDeveloperName(accountObj.Id, developerName);
        }   
        
        return ltAccount;
    }

    public static List<Asset> getAsset(Account accountObj, GeneralParam__c generalParamObj, String developerName){
	
        List<String> ltCustomerSegment = CollectionUtil.stringForList(generalParamObj.CustomerSegment__c);
        List<String> ltCustomerType = CollectionUtil.stringForList(generalParamObj.CustomerType__c);
        List<Asset> ltAsset = new List<Asset>();

        if(ltCustomerSegment.contains(accountObj.vlocity_cmt__CustomerValue__c) && ltCustomerType.contains(accountObj.vlocity_cmt__CustomerClass__c)){  
            ltAsset = AssetDAO.getByAccountIdRecordtypeDeveloperNameLastModifiedDate(accountObj.Id,developerName,generalParamObj.AssetLoadDate__c);
        }else{
            ltAsset = AssetDAO.getByAccountIdRecordtypeDeveloperName(accountObj.Id, developerName);
        }

        return ltAsset;
    }

    public static AccountRetentionTO.BillingAccount createBillingAccount(List<Account> lstAccount, List<Asset> lstAsset, List<Offer__c> ltOffer){
        AccountRetentionTO.BillingAccount billingAccountTOObj = new AccountRetentionTO.BillingAccount();        
        //Ordernar as contas de faturamento com os asset
        Map<Id,List<Asset>> mapAssetForBillintAccount;                
        CollectionUtil.loadMap(mapAssetForBillintAccount = new Map<Id,List<Asset>>(),'vlocity_cmt__BillingAccountId__c',lstAsset);
        
        for(Account billingAccountObj :lstAccount){            
            billingAccountTOObj.ltAsset = new List<Asset>();
            billingAccountTOObj.idBilling = billingAccountObj.Id;
            billingAccountTOObj.name = 'Conta Faturamento: ' + billingAccountObj.ExternalId__c; 
            billingAccountTOObj.totalPrice = billingAccountObj.OfferReferenceValue__c;
            billingAccountTOObj.hasMultipleAssets = false;

            List<Asset> lstAssetInteration = mapAssetForBillintAccount.containsKey(billingAccountObj.Id) != null ? mapAssetForBillintAccount.get(billingAccountObj.Id) : null ; 
            
            if(lstAssetInteration != null){
                Set<String> setProductType = new Set<String>();
                Set<String> setAddress = new Set<String>();
                
                billingAccountTOObj.hasAsset = true;

                for(Asset assetObj : lstAssetInteration){
                    
                    billingAccountTOObj.ltAsset.add(assetObj);
					
                    if(!setProductType.contains(assetObj.ProductType__c)){                        
                        setAddress.add(assetObj.vlocity_cmt__ServiceAccountId__r.FullAddress__c);
                        setProductType.add(assetObj.ProductType__c);
                    }else{
                        billingAccountTOObj.hasMultipleAssets = true;
                    }
                }				
                if(setAddress.isEmpty() || setAddress.size() > 1){
                    billingAccountTOObj.hasAsset = false;
                }   
            }            
        }		
        return billingAccountTOObj;    
    }
}