force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <description>Valor total da última fatura</description>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Cabinet__c.field-meta.xml
<CustomField>
    <fullName>Cabinet__c</fullName>
    <description>Armario do Asset, campo utilizado para realizar a busca de ofertas no componente de Ofertas customizado</description>
    <label>Código Armário</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/HasBonus__c.field-meta.xml
<CustomField>
    <fullName>HasBonus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui Bônus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/HasDiscount__c.field-meta.xml
<CustomField>
    <fullName>HasDiscount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui Desconto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/IsHolder__c.field-meta.xml
<CustomField>
    <fullName>IsHolder__c</fullName>
    <label>TIT_DEP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LegacySystem__c.field-meta.xml
<CustomField>
    <fullName>LegacySystem__c</fullName>
    <description>Sistema legado de origem do Asset do Cliente.</description>
    <label>Sistema de Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATIS</fullName>
            </value>
            <value>
                <fullName>ATLYS</fullName>
            </value>
            <value>
                <fullName>NEXT</fullName>
            </value>
            <value>
                <fullName>NGIN</fullName>
            </value>
            <value>
                <fullName>NSIA</fullName>
            </value>
            <value>
                <fullName>SIA</fullName>
            </value>
            <value>
                <fullName>SIEBEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/MainProductDescription__c.field-meta.xml
<CustomField>
    <fullName>MainProductDescription__c</fullName>
    <description>Campo para informar o plano.</description>
    <label>Plano</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>Número Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PriceCurrent__c.field-meta.xml
<CustomField>
    <fullName>PriceCurrent__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PriceOver__c.field-meta.xml
<CustomField>
    <fullName>PriceOver__c</fullName>
    <label>Valor Excedente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <description>Velocidade do Ativo/Produto</description>
    <label>Velocidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Campo para guardar o valor</description>
    <label>StartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Armazena a tecnologia do registro de Ativo/Produto</description>
    <label>Tecnologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FTTH</fullName>
            </value>
            <value>
                <fullName>FTTC</fullName>
            </value>
            <value>
                <fullName>Movel</fullName>
                <label>Móvel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tipo</fullName>
            </value>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Movel</fullName>
                <label>Móvel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Objeto de faturas destinado a armazenar as informações históricas do cliente.</description>
    <label>Faturamento</label>
    <nameField>
        <label>Mês de Referência</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Campo de relacionamento entre Conta e Invoice.</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamento</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CreationDate__c.field-meta.xml
<CustomField>
    <fullName>CreationDate__c</fullName>
    <label>Data da criação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Downloadurl__c.field-meta.xml
<CustomField>
    <fullName>Downloadurl__c</fullName>
    <label>Download url</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Data do Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <description>Identificador da fatura na 4P.</description>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/NextInvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>NextInvoiceDate__c</fullName>
    <label>Data da próxima fatura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PaymentDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentDate__c</fullName>
    <label>Data do Pagamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <label>Pago</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <label>Não Pago</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TaxInclude__c.field-meta.xml
<CustomField>
    <fullName>TaxInclude__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxa inclusa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/InteractionNumber__c.field-meta.xml
<CustomField>
    <fullName>InteractionNumber__c</fullName>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/vlocity_cmt__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Presencial</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactory.cls
/*
* @authors - Diego Costa @Deloitte   
* @date - 07/06/2022
* @description - fábrica de Fatura__c para classes de testes
*/
@IsTest
public class DataFactory {

    /*
    public static Invoice__c createInvoiceHistory(Id accountId){
        Invoice__c invoiceHistory = new Invoice__c();
        
        invoiceHistory.Name = 'serviceHistory';
        invoiceHistory.AccountId__c = accountId;
        invoiceHistory.InvoiceId__c = '1234567890';
        invoiceHistory.Name = 'Test Invoice';
        invoiceHistory.CreationDate__c = System.today();
        invoiceHistory.StartDate__c = System.today();
        invoiceHistory.EndDate__c = System.today();
        invoiceHistory.DueDate__c = System.today();
        invoiceHistory.PaymentDate__c = System.today();
        invoiceHistory.NextInvoiceDate__c = System.today();
        invoiceHistory.TotalAmount__c = 324.44;
        invoiceHistory.TaxInclude__c = true;
        invoiceHistory.PaymentStatus__c = 'Unpaid';
        invoiceHistory.Downloadurl__c = 'https://invoicedownload.free.beeceptor.com/invoice';

        return invoiceHistory;
    }
    */
    public static Account createAccount(){ 
        Account account = new Account();

        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getrecordTypeId();
        account.Name = 'Account Test';
        account.DocumentNumber__c = '11111111111111';
        account.vlocity_cmt__CustomerClass__c = 'Móvel';
        account.CustomerSegment__c = 'PLATINUM';
        account.vlocity_cmt__Active__c = 'Yes';

        return account;
    }
    
/*
    public static Asset createAsset(Id accountId, String type){
        Asset asset = new Asset();
        
        asset.Name = 'Test Asset';
        asset.AccountId = accountId;        
        asset.MainProductDescription__c = 'Test ' + type;
        asset.vlocity_cmt__BillingAccountId__c = accountId;
        asset.Type__c = type;
        asset.IsHolder__c = 'Sim';
        asset.HasBonus__c = false;
        asset.HasDiscount__c = false;
        asset.PriceOver__c = 150;
        asset.PriceCurrent__c = 200;
        asset.PhoneNumber__c = '12345678901';
        asset.Speed__c = '30';
        asset.ProductType__c = 'VOZ';
        asset.PhoneNumber__c = '11999999999';
        asset.Technology__c = 'FTTH';
        asset.Cabinet__c = 'Cabinet';
        asset.LegacySystem__c = 'ATLYS';

        return asset;
    }
    */
    
    public static vlocity_cmt__CustomerInteraction__c createCustomerInteraction(Id accountId) {
        vlocity_cmt__CustomerInteraction__c customerInteraction = new vlocity_cmt__CustomerInteraction__c();
        customerInteraction.vlocity_cmt__AccountId__c = accountId;
		customerInteraction.Name = 'Test Customer Interaction';		
		customerInteraction.vlocity_cmt__StartDateTime__c = System.today();
		customerInteraction.InteractionNumber__c = '20220630123456';
		customerInteraction.vlocity_cmt__StartDateTime__c = System.today();
		customerInteraction.vlocity_cmt__Type__c = 'Presencial';
		customerInteraction.vlocity_cmt__Verified__c = false;
        
        return customerInteraction;
    }

}