force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FullAddress__c.field-meta.xml
<CustomField>
    <fullName>FullAddress__c</fullName>
    <formula>IF(RecordType.DeveloperName = &quot;Billing&quot;,    BillingAddressType__c  + &apos;,&apos; + BillingStreet + &apos;,&apos; + BillingNumber__c + &apos;,&apos; + BillingNeighborhood__c + &apos;,&apos; + BillingPostalCode + &apos;,&apos; + BillingCity + &apos;,&apos; + BillingState, ShippingAddressType__c  + &apos;,&apos; + ShippingStreet + &apos;,&apos; + ShippingNumber__c + &apos;,&apos; + ShippingNeighborhood__c + &apos;,&apos; + ShippingPostalCode + &apos;,&apos; + ShippingCity + &apos;,&apos; + ShippingState)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Endereço Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__CustomerValue__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__CustomerValue__c</fullName>
    <description>A ranking of the value of this customer to your business expressed in marketing terms such as Gold, Silver, Bronze, Diamond, Platinum.</description>
    <label>Customer Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/BillingAccountFormulaName__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountFormulaName__c</fullName>
    <description>Retorna o Nome da Conta de Faturamento ao invés do ID. Utilizado no componente de seleção de linha.</description>
    <formula>vlocity_cmt__BillingAccountId__r.Name</formula>
    <label>Billing Account Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Cabinet__c.field-meta.xml
<CustomField>
    <fullName>Cabinet__c</fullName>
    <description>Armario do Asset, campo utilizado para realizar a busca de ofertas no componente de Ofertas customizado</description>
    <label>Código Armário</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>Data Fim do Produto</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/HasBonusFormula__c.field-meta.xml
<CustomField>
    <fullName>HasBonusFormula__c</fullName>
    <formula>IF( HasBonus__c = true, 'Sim', 'Não' )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Possui bônus formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/HasDiscount__c.field-meta.xml
<CustomField>
    <fullName>HasDiscount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui Desconto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/HasDiscountFormula__c.field-meta.xml
<CustomField>
    <fullName>HasDiscountFormula__c</fullName>
    <formula>IF( HasDiscount__c = true, &apos;Sim&apos;, &apos;Não&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Possui desconto formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/HolderDependent__c.field-meta.xml
<CustomField>
    <fullName>HolderDependent__c</fullName>
    <formula>IF(



IsHolder__c = &apos;TIT&apos;, &apos;Sim&apos;, &apos;Não&apos;



)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Titular</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <label>Instância</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LegacyAssetId__c.field-meta.xml
<CustomField>
    <fullName>LegacyAssetId__c</fullName>
    <label>ID Produto Legado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LegacyIdentifier__c.field-meta.xml
<CustomField>
    <fullName>LegacyIdentifier__c</fullName>
    <description>Campo utilizado como referencia do pacote a ser enviado aos sistemas legados.</description>
    <externalId>true</externalId>
    <label>LegacyIdentifier</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LegacySystem__c.field-meta.xml
<CustomField>
    <fullName>LegacySystem__c</fullName>
    <description>Sistema legado de origem do Asset do Cliente.</description>
    <label>Sistema de Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATIS</fullName>
            </value>
            <value>
                <fullName>ATLYS</fullName>
            </value>
            <value>
                <fullName>NEXT</fullName>
            </value>
            <value>
                <fullName>NGIN</fullName>
            </value>
            <value>
                <fullName>NSIA</fullName>
            </value>
            <value>
                <fullName>SIA</fullName>
            </value>
            <value>
                <fullName>SIEBEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/MainProductDescription__c.field-meta.xml
<CustomField>
    <fullName>MainProductDescription__c</fullName>
    <description>Campo para informar o plano.</description>
    <label>Plano</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>Número Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Plataforma</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PriceCurrent__c.field-meta.xml
<CustomField>
    <fullName>PriceCurrent__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PriceOver__c.field-meta.xml
<CustomField>
    <fullName>PriceOver__c</fullName>
    <label>Valor Excedente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <label>Sistema de Origem</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <description>Velocidade do Ativo/Produto</description>
    <label>Velocidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Data Inicio do Produto</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Streaming__c.field-meta.xml
<CustomField>
    <fullName>Streaming__c</fullName>
    <description>Lista de streamings contratados</description>
    <label>Streaming</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sem Streaming</fullName>
            </value>
            <value>
                <fullName>Amazon Prime Vídeo</fullName>
            </value>
            <value>
                <fullName>Combo Disney+</fullName>
            </value>
            <value>
                <fullName>Combo Netflix Padrão</fullName>
            </value>
            <value>
                <fullName>Combo Netflix Premium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Armazena a tecnologia do registro de Ativo/Produto</description>
    <label>Tecnologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FTTH</fullName>
            </value>
            <value>
                <fullName>FTTC</fullName>
            </value>
            <value>
                <fullName>Movel</fullName>
                <label>Móvel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/TVOfferFormula__c.field-meta.xml
<CustomField>
    <fullName>TVOfferFormula__c</fullName>
    <description>Campo para fazer o de/para entre o Asset e o objeto de ofertas</description>
    <formula>IF(BEGINS(MainProductDescription__c,&apos;PACOTE B&apos;), &apos;Basico HD&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE FULL HD FUTEBOL&apos;), &apos;Full HD Futebol&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE FULL HD&apos;), &apos;Full HD&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE STANDARD&apos;), &apos;Standard HD&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE SUPER HD FUTEBOL&apos;), &apos;Super HD Futebol&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE SUPER HD&apos;), &apos;Super HD&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE ULTIMATE HD FUTEBO&apos;), &apos;Ultimate HD Futebol&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE ULTIMATE HD&apos;), &apos;Ultimate HD&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE ULTRA HD FUTEBOL&apos;), &apos;Ultra HD Futebol&apos;,
IF(BEGINS(MainProductDescription__c,&apos;PACOTE ULTRA&apos;), &apos;Ultra HD&apos;,
IF(OR(BEGINS(MainProductDescription__c,&apos;VIVO PLAY PADRAO&apos;),BEGINS(MainProductDescription__c,&apos;VIVO PLAY PADRÃO&apos;)), &apos;Vivo Play Padrão&apos;,
IF(BEGINS(MainProductDescription__c,&apos;VIVO PLAY ESSENCIAL&apos;), &apos;Vivo Play Essencial&apos;,
IF(BEGINS(MainProductDescription__c,&apos;VIVO PLAY ULTRA&apos;), &apos;Vivo Play Ultra&apos;,
IF(OR(BEGINS(MainProductDescription__c,&apos;VIVO PLAY AVANCADO&apos;),BEGINS(MainProductDescription__c,&apos;VIVO PLAY AVANÇADO&apos;)), &apos;Vivo Play Avançado&apos;,
IF(BEGINS(MainProductDescription__c,&apos;VIVO PLAY COMPLETO&apos;), &apos;Vivo Play Completo&apos;,



&apos;SEM OFERTA TV&apos;)))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Oferta TV</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tipo</fullName>
            </value>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Movel</fullName>
                <label>Móvel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo fixo</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Movel.recordType-meta.xml
<RecordType>
    <fullName>Movel</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo móvel</description>
    <label>Movel</label>
</RecordType>

force-app/main/default/objects/Product2/fields/vlocity_cmt__SubType__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__SubType__c</fullName>
    <description>Product Sub Type can be used to drive implementations/engines, as well as filtering products in the Catalog/Pricebook. These values may be constrained by the Product Type.</description>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>vlocity_cmt__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Plan</fullName>
                <label>Plano</label>
            </value>
            <value>
                <fullName>TopUp</fullName>
                <label>Recarga</label>
            </value>
            <value>
                <fullName>None</fullName>
                <label>Nenhum</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/vlocity_cmt__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Type__c</fullName>
    <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prepaid</fullName>
                <label>Pré-pago</label>
            </value>
            <value>
                <fullName>Postpaid</fullName>
                <label>Pós-pago</label>
            </value>
            <value>
                <fullName>SIM Card</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <label>Nenhum</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetDAO.cls
/**  
 * @description Controla a busca e criação do objeto Asset
 */
public without sharing class AssetDAO {
    public static List<Asset> getAssetMobileByAccountAndLastModifiedDate(String accountId, DateTime assetLoadDate) {
        return  [
            SELECT Id,                
                MainProductDescription__c, 
                PhoneNumber__c, 
                HolderDependent__c,
                HasDiscountFormula__c, 
                HasBonusFormula__c, 
                HasDiscount__c, 
                PriceCurrent__c, 
                PriceOver__c , 
                ProductType__c, 
                LegacySystem__c,
                Speed__c,
            	vlocity_cmt__BillingAccountId__c
        FROM 
            Asset 
        WHERE 
            AccountId =: accountId 
        AND Type__c = 'Movel'
        AND LastModifiedDate >: assetLoadDate];
    }

    public static List<Asset> getAssetMobileByAccount(String accountId) {
        return   [
            SELECT Id,
            	Name,                            	
            	Account.RecordType.Id,
                MainProductDescription__c, 
                PhoneNumber__c, 
                Type__c,
                HolderDependent__c,
                HasDiscountFormula__c,
                HasBonusFormula__c, 
                HasDiscount__c, 
                PriceCurrent__c, 
                PriceOver__c, 
                ProductType__c, 
                LegacySystem__c,
                Speed__c,
            	vlocity_cmt__BillingAccountId__c,
            	Account.BillingStreet                
        FROM 
            Asset
        WHERE 
            AccountId =: accountId 
        AND Type__c = 'Movel'];
    }
    
	@AuraEnabled
    public static List<Asset> getAssetMobileMigration(String accountId) {
        return   [
            SELECT Id,                          	
                AccountId,
                Status,
                PhoneNumber__c, 
                BillingAccountFormulaName__c,
                Type__c,
                ProductType__c, 
                MainProductDescription__c,
                SourceSystem__c
        FROM 
            Asset
        WHERE 
            AccountId =: accountId
        AND Status = 'Active'
        AND Type__c = 'Movel'
        AND (NOT MainProductDescription__c  LIKE '%Fam%')];
    }

    public static List<Asset> getAssetFixed(String accountId) {
        return  [
            SELECT Id,              
            ProductType__c, 
            Speed__c, 
            Technology__c              
        FROM Asset 
        WHERE AccountId =: accountId 
        //    AND Account.RecordType.DeveloperName = 'Fixa'
        //    AND ProductType__c = 'BANDA LARGA' 
        //    AND Technology__c = 'FTTH'	
        AND vlocity_cmt__ServiceAccountId__r.ShippingState IN ('SP', 'DF')
        AND type__c = 'Fixa' 

        ];
    }

    public static List<Asset> getAssetFixedByAccountAndLastModifiedDate(String accountId, DateTime assetLoadDate){
        return [
        SELECT Id, 
            TVOfferFormula__c,
            MainProductDescription__c, 
            Instance__c,             
            Technology__c, 
            Cabinet__c, 
            ProductType__c, 
            Speed__c, 
            LegacySystem__c, 
            Streaming__c,
            vlocity_cmt__BillingAccountId__c,
            vlocity_cmt__ServiceAccountId__r.ShippingState,
            vlocity_cmt__ServiceAccountId__r.ShippingCity,
            vlocity_cmt__ServiceAccountId__r.FullAddress__c
        FROM Asset 
        WHERE AccountId =: accountId 
            // AND Account.RecordType.DeveloperName = 'Fixa' 
            AND type__c = 'Fixa'
            AND LastModifiedDate >: assetLoadDate
        ];
    }

    public static List<Asset> getAssetFixedByAccount(String accountId){
        return [
            SELECT
                Id, 
                TVOfferFormula__c,
                MainProductDescription__c, 
                LastModifiedDate, 
                Instance__c,                
                AccountId,
                Technology__c,
                Type__c,
                Cabinet__c, 
                ProductType__c, 
                Speed__c, 
                LegacySystem__c, 
                Streaming__c,
                vlocity_cmt__BillingAccountId__c,
                vlocity_cmt__ServiceAccountId__r.ShippingState,
                vlocity_cmt__ServiceAccountId__r.ShippingCity,
                vlocity_cmt__ServiceAccountId__r.FullAddress__c
            FROM Asset 
            WHERE AccountId =: accountId 
            // AND Account.RecordType.DeveloperName = 'Fixa'
            and type__c = 'Fixa'
        ];
    }
    
    public static List<Asset> getAssetPreByAccount(String accountId){
        return [
            SELECT
                Id, 
                TVOfferFormula__c,
                MainProductDescription__c, 
                LastModifiedDate, 
                Instance__c,                
                AccountId,
                Technology__c,
                Type__c,
                Cabinet__c, 
                ProductType__c, 
                Speed__c, 
                LegacySystem__c, 
                Streaming__c,
                vlocity_cmt__BillingAccountId__c,
                vlocity_cmt__ServiceAccountId__r.ShippingState,
                vlocity_cmt__ServiceAccountId__r.ShippingCity,
                vlocity_cmt__ServiceAccountId__r.FullAddress__c
            FROM Asset 
            WHERE AccountId =: accountId 
             AND Product2.vlocity_cmt__Type__c  = 'Prepaid'
        ];
    }    
    
    public static List<Asset> getByAccountIdRecordtypeDeveloperName(Id accountId, String recordtypeName){
        return[
            SELECT 
                Id,
            	vlocity_cmt__BillingAccountId__c,
            	vlocity_cmt__ServiceAccountId__r.FullAddress__c,
                MainProductDescription__c,
                PhoneNumber__c,
                HolderDependent__c,
                HasDiscountFormula__c,
                HasBonusFormula__c,
                HasDiscount__c,
                PriceCurrent__c,
                PriceOver__c ,
                ProductType__c,
                Speed__c,
                Instance__c,
                LastModifiedDate            	
            FROM 
                Asset 
            WHERE 
                AccountId =: accountId 
            AND 
            	Type__c = :recordtypeName                
        ];
    }

    public static List<Asset> getByAccountIdRecordtypeDeveloperNameLastModifiedDate(Id accountId, String recordtypeName, Datetime lastModifiedDate){
        return[
            SELECT 
                Id,
            	Name,
                vlocity_cmt__BillingAccountId__c,
            	vlocity_cmt__ServiceAccountId__r.FullAddress__c,
                MainProductDescription__c,
                PhoneNumber__c,
                HolderDependent__c,
                HasDiscountFormula__c,
                HasBonusFormula__c,
                HasDiscount__c,
                PriceCurrent__c,
                PriceOver__c ,
                ProductType__c,
                Speed__c,
                Instance__c,
                LastModifiedDate	            
            FROM 
                Asset 
            WHERE 
                AccountId =: accountId 
            AND 
       			Type__c = :recordtypeName
            AND 
                LastModifiedDate > :lastModifiedDate   
        ];
    }

    public static Asset getAssetById(String Id) {
        return   [
            SELECT  Id,
                    toLabel(Status),            		
                    Instance__c,
            		Name,
                    MainProductDescription__c,
                    Product2.vlocity_cmt__Type__c,
                    vlocity_cmt__ServiceIdentifier__c
        FROM 
            Asset 
        WHERE 
            Id =: Id
        LIMIT 1 
        ];
    }

    public static List<Asset> getAssetByName(String Name) {
        return   [
		SELECT Id,
                AccountId,
                Account.Name,
                Account.Id,
                Account.DocumentNumber__c,
                Account.vlocity_cmt__CustomerValue__c,
            	Account.vlocity_cmt__PrimaryContactId__c,
            	Account.phone,
            	PhoneNumber__c,
            	Account.CustomerSegment__c
        FROM 
            Asset 
        WHERE 
            Name =: Name 
        ];
    }

    public static List<Asset> getByAccountId(Id accountId){
        return[
            SELECT  
            	Id, 
            	Status, 
            	Product2.vlocity_cmt__SubType__c, 
            	LegacyIdentifier__c, 
            	vlocity_cmt__ServiceIdentifier__c,
            	StartDateTime__c, 
            	EndDateTime__c, 
            	vlocity_cmt__AttributeSelectedValues__c,
                Name,                
                Account.Name,
                LegacyAssetId__c,
                Type__c
            FROM 
                Asset
            WHERE
                AccountId = :accountId 
        ];
    }
    
    public static List<Asset> getBySetAccountIdWithPromotionProduct(Set<Id> setAccId){
        return[
            SELECT  
                Id,
                Name,                
                Account.Name,
                LegacyAssetId__c,
                Type__c,
                Platform__c,
                vlocity_cmt__ServiceIdentifier__c,
                vlocity_cmt__ServiceAccountId__r.AcceptPromotion__c,
                vlocity_cmt__ServiceAccountId__r.BillingAddressType__c,
                vlocity_cmt__ServiceAccountId__r.BillingCity,
                vlocity_cmt__ServiceAccountId__r.BillingComplement1__c,
                vlocity_cmt__ServiceAccountId__r.BillingComplement2__c,
                vlocity_cmt__ServiceAccountId__r.BillingComplement3__c,
                vlocity_cmt__ServiceAccountId__r.BillingComplement4__c,
                vlocity_cmt__ServiceAccountId__r.BillingComplementType1__c,
                vlocity_cmt__ServiceAccountId__r.BillingComplementType2__c,
                vlocity_cmt__ServiceAccountId__r.BillingComplementType3__c,
                vlocity_cmt__ServiceAccountId__r.BillingComplementType4__c,
                vlocity_cmt__ServiceAccountId__r.BillingNeighborhood__c,
                vlocity_cmt__ServiceAccountId__r.BillingNumber__c,
                vlocity_cmt__ServiceAccountId__r.BillingPostalCode,
                vlocity_cmt__ServiceAccountId__r.BillingState,
                vlocity_cmt__ServiceAccountId__r.BillingStreet,
                vlocity_cmt__ServiceAccountId__r.Id,
                vlocity_cmt__ServiceAccountId__r.RecordType.name

            FROM 
                Asset
            WHERE
                AccountId IN :setAccId AND
                Status != 'Terminado' AND
                Product2.vlocity_cmt__SubType__c = 'Promotion' AND
                vlocity_cmt__ServiceIdentifier__c != ''
        ];
    }

   public static List<Asset> getAccountId(Id accountId){
        return[
            SELECT  
                Id,
                Name,
            	vlocity_cmt__BillingAccountId__c,
                vlocity_cmt__BillingAccountId__r.Name,
                LegacyAssetId__c,
                Type__c
            FROM 
                Asset
            WHERE
                AccountId = :accountId 
        ];
    }    
        
    public static List<Asset> getByBillingAccountId(Set<Id> setBillingAccounId){
        return[
            SELECT
                Id,
                Name,
            	LegacyIdentifier__c,
            	Product2.vlocity_cmt__SubType__c,
            	vlocity_cmt__AttributeSelectedValues__c
            FROM
                Asset
        ];
    }

    public static Asset[] getByParentItemId(String parentItemId)
    {
        return [
            SELECT id,
                productcode,
                product2id,
                name,
                externalid__c,
                price,
                vlocity_cmt__assetreferenceid__c
            FROM Asset
            WHERE (Status = 'Active' AND vlocity_cmt__ParentItemId__c = :parentItemId)];
    }
    
    public static List<Asset> getAssetIdByIdentifiers(String serviceIdentifier, String accountId) {
        return [SELECT Id, vlocity_cmt__ServiceIdentifier__c FROM Asset WHERE vlocity_cmt__ServiceIdentifier__c =: serviceIdentifier 
                                                   AND AccountId =: accountId 
                                                   AND Type__c = 'Fixa' AND SourceSystem__c = 'SIEBEL'
               									   LIMIT 1];
    }
    
    public static List<Asset> getAssetIdWithoutIdentifiers(String accountId) {
        return [SELECT Id, Type__c, SourceSystem__c, vlocity_cmt__ServiceIdentifier__c FROM Asset WHERE AccountId =: accountId AND Type__c = 'Fixa' AND SourceSystem__c = 'SIEBEL' LIMIT 1];
         
    }  
    
    public static List<Asset> getPidAssetMobileByAccount(String accountId) {
        final String STR_STATUS = 'Active';

        final List<String> LST_SUBSTATUS_TO_NOT_SEND = new List<String>{
            'SUSPENSÃO A PEDIDO', 
            'SUSPENSO A PEDIDO',
            'SUSPENSO POR CADASTRO', 
            'SUSPENSO POR ROUBO',
            'SUSPAFRAUDE',
            'SUSPAPEDIDO',
            'SUSPAROUBO',
            'SUSPCADASTRO'
        };

        final String STR_TYPE = 'Movel';
        final String STR_NAMELEN = '___________';

        final Set<String> setProduto = new Set<String>{
            'Pós-Pago',
            'Controle',
            'Pré-Pago'
        };

        return [
            SELECT 
                Name, 
                ProductType__c,
                StartDate__c
            FROM
                Asset
            WHERE 
                AccountId = :accountId AND 
                Status = :STR_STATUS AND 
                StatusDescription__c NOT IN :LST_SUBSTATUS_TO_NOT_SEND AND 
                Type__c = :STR_TYPE AND 
                Name LIKE :STR_NAMELEN AND 
                ProductType__c IN :setProduto AND 
                (NOT MainProductDescription__c LIKE '%Linha Adicional%') AND
                (NOT IsHolder__c = 'dependente')
            ORDER BY 
                StartDate__c ASC
        ];
    }    
    
    public static Asset getPlanByMsisdn(String msisdn)
    {
        
        Asset assetPromo = [SELECT vlocity_cmt__AssetReferenceId__c 
                            FROM Asset 
                            WHERE vlocity_cmt__ServiceIdentifier__c  =:msisdn AND Status  = 'Active' AND Product2.vlocity_cmt__SubType__c = 'Promotion' 
                            LIMIT 1];
        System.debug('assetPromo: '+assetPromo);
        if(assetPromo == null) return null;
        System.debug('assetPromo.vlocity_cmt__AssetReferenceId__c: '+assetPromo.vlocity_cmt__AssetReferenceId__c);
        return [
            SELECT id,
                Productcode,
                Product2id,
                Name,
                vlocity_cmt__AttributeSelectedValues__c
            FROM Asset
            WHERE (vlocity_cmt__ParentItemId__c =:assetPromo.vlocity_cmt__AssetReferenceId__c AND Product2.vlocity_cmt__SubType__c = 'Plan') 
            LIMIT 1];
    }
    
 	public static List<Asset> getBy(String accountId, String identifier, String description)
    {
        return [
            SELECT Id, Instance__c
            FROM Asset
            WHERE AccountId = :accountId
            AND vlocity_cmt__ServiceIdentifier__c = :identifier
            AND MainProductDescription__c = :description
        ];
    }

    public static List<Asset> getBy(String accountId, String externalId)
    {
        return [
            SELECT Id
            FROM Asset
            WHERE accountId = :accountId
            AND ExternalId__c = :externalId
        ];

    }

    public static List<Asset> getBy(Set<Id> assetIds)
    {
        return [
            SELECT Id, Type__c, Technology__c, MainProductDescription__c
            FROM Asset
            WHERE Id = :assetIds
        ];
    }
    
    public static List<Asset> getAssetPhoneByAccount(String accountId) {
        return [
            SELECT
                id,
                vlocity_cmt__ServiceIdentifier__c
            FROM Asset
            WHERE SourceSystem__c = 'NEXT'
            AND ProductType__c IN ('Voz', 'Pós-Pago')
            AND AccountId = :accountId
        ];
    }

    public static Asset getAssetByServiceIdentifier(String serviceIdentifier) {
        List<Asset> lstAsset = [
            SELECT  
                Id,
                Account.DocumentNumber__c,
                Account.Name,
                vlocity_cmt__ServiceAccountId__r.BillingAddressType__c,
                vlocity_cmt__ServiceAccountId__r.BillingCity,
                vlocity_cmt__ServiceAccountId__r.BillingNeighborhood__c,
                vlocity_cmt__ServiceAccountId__r.BillingNumber__c,
                vlocity_cmt__ServiceAccountId__r.BillingPostalCode,
                vlocity_cmt__ServiceAccountId__r.BillingState,
                vlocity_cmt__ServiceAccountId__r.BillingStreet
            FROM 
                Asset 
            WHERE 
                vlocity_cmt__ServiceIdentifier__c =: serviceIdentifier AND
                Status = 'Ativo' AND
                Platform__c != 'SIM Card' AND 
            	vlocity_cmt__SubscriptionId__c != null
        ];

        return (lstAsset.isEmpty() ? null : lstAsset[0]);
    }
}