force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Para uso do HDE, trás o segmento do cliente, informação que está no objeto Account</description>
    <formula>Text(Account.CustomerSegment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segmento do Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/FromToMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para ser utilizado para inclusão de de/para que serão utilizados na Org.</description>
    <label>Mapeamento DePara</label>
    <pluralLabel>Mapeamento DePara</pluralLabel>
</CustomObject>

force-app/main/default/objects/FromToMapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Object do campo desejado origem</description>
    <label>Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <description>Segmento do operador utilizado no de-para do componente de atendimento.</description>
    <label>Segmento do Operador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
                <default>true</default>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Omnichannel</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>Revenda</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
            </value>
            <value>
                <fullName>Suporte a Lojas</fullName>
            </value>
            <value>
                <fullName>Televendas</fullName>
            </value>
            <value>
                <fullName>Atendimento</fullName>
            </value>
            <value>
                <fullName>Backoffice</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Retencao</fullName>
            </value>
            <value>
                <fullName>Purpura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/fields/OriginName__c.field-meta.xml
<CustomField>
    <fullName>OriginName__c</fullName>
    <description>Nome do campo desejado origem</description>
    <label>Nome do campo Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ToFromHDE2__mdt/ToFromHDE2__mdt.object-meta.xml
<CustomObject>
    <description>Objeto utilizado na automação de mapeamento de complexidados dos chamados abertos pelos operadores</description>
    <label>HDE - DePara 2</label>
    <pluralLabel>HDE - DePara 2</pluralLabel>
</CustomObject>

force-app/main/default/objects/ToFromHDE2__mdt/fields/CaseRecordType__c.field-meta.xml
<CustomField>
    <fullName>CaseRecordType__c</fullName>
    <label>Formulário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acionamento E-mail</fullName>
                <isActive>false</isActive>
                <label>Acionamento E-mail</label>
            </value>
            <value>
                <fullName>EmailTrigger</fullName>
                <label>HDE - Acionamento E-mail</label>
            </value>
            <value>
                <fullName>CallSupervisor</fullName>
                <label>HDE - Acionamento Supervisor</label>
            </value>
            <value>
                <fullName>TechnicalMonitoring</fullName>
                <label>HDE - Acompanhamento Técnico</label>
            </value>
            <value>
                <fullName>WalletProcessesEscalation</fullName>
                <label>HDE - Carteira Processos Escalonamento</label>
            </value>
            <value>
                <fullName>GoldProcessesEscalation</fullName>
                <label>HDE - Gold Processos Escalonamento</label>
            </value>
            <value>
                <fullName>StoreProcessesEscalation</fullName>
                <label>HDE - Loja Processos Escalonamento</label>
            </value>
            <value>
                <fullName>CommunityOuvidoriaProcessesEscalation</fullName>
                <label>HDE - Ouvidoria Comunidades Processos e Escalonamento</label>
            </value>
            <value>
                <fullName>OuvidoriaProcessesEscalation</fullName>
                <label>HDE - Ouvidoria Processos Escalonamento</label>
            </value>
            <value>
                <fullName>PlatinumProcessesEscalation</fullName>
                <label>HDE - Platinum Processos Escalonamento</label>
            </value>
            <value>
                <fullName>PrimeProcessesEscalation</fullName>
                <label>HDE - Prime Processos Escalonamento</label>
            </value>
            <value>
                <fullName>EscalationAndLawSuits</fullName>
                <label>HDE - Processos Escalonamento</label>
            </value>
            <value>
                <fullName>PurpuraProcessesEscalation</fullName>
                <label>HDE - Púrpura - Processos e Escalonamento</label>
            </value>
            <value>
                <fullName>ResellerStoreProcessesEscalation</fullName>
                <label>HDE - Revendas Processos e Escalonamento</label>
            </value>
            <value>
                <fullName>SilverProcessesEscalation</fullName>
                <label>HDE - Silver - Processos e Escalonamento</label>
            </value>
            <value>
                <fullName>VivoVProcessesEscalation</fullName>
                <label>HDE - V Processos Escalonamento</label>
            </value>
            <value>
                <fullName>VPRStoreProcessesEscalation</fullName>
                <label>HDE - VPR Processos Escalonamento</label>
            </value>
            <value>
                <fullName>Processos Escalonamento</fullName>
                <isActive>false</isActive>
                <label>Processos Escalonamento</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToFromHDE2__mdt/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRE</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToFromHDE2__mdt/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <label>Segmento do Operador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOLD</fullName>
                <default>true</default>
                <label>GOLD</label>
            </value>
            <value>
                <fullName>LOJA</fullName>
            </value>
            <value>
                <fullName>OMNICHANNEL</fullName>
            </value>
            <value>
                <fullName>OUVIDORIA</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
                <label>PÚRPURA</label>
            </value>
            <value>
                <fullName>REVENDA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>SUPORTE A LOJAS</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
            <value>
                <fullName>VIVO V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToFromHDE2__mdt/fields/ORG__c.field-meta.xml
<CustomField>
    <fullName>ORG__c</fullName>
    <label>ORG</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vivo</fullName>
                <default>true</default>
                <label>Vivo</label>
            </value>
            <value>
                <fullName>Comunidades</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchRoutingCasesCallout.cls
public class BatchRoutingCasesCallout implements Database.Batchable<sObject>, Database.AllowsCallouts { 
    public static final String ROUNTING_N1 = 'Automático N1';
    public static final String ROUNTING_N2 = 'Automático N2';
    public static final String ROUNTING_NX = 'Automático N2 e Automático N3';
    public static final String ROUNTING_MANUAL = 'Manual';
    
    public static final String ORG_VIVO = 'Vivo';
    public static final String ORG_COMUNIDADES = 'Comunidades';

    private List<Case> ltCases;
 	private Map<Id, String> casesWithPriorities = new Map<Id, String>();
    
    private Map<Id, Account> accountFromCases;
    private Map<Id, User> userFromCases;
    private List<FromToMapping__mdt> ltFromToMapping;
	private Map<String, String> operatorSegmentFromMdt;
    private Map<String, String> routingLevelFromMdt;
    private Map<String, String> interactionReasonMap;
        
    public BatchRoutingCasesCallout(List<Case> ltCases, Map<Id, String> casesWithPriorities) {
        this.ltCases = ltCases;
        this.casesWithPriorities = casesWithPriorities;
        
        Set<Id> accountIds = new Set<Id>();
        Set<Id> userIds = new Set<Id>();
		Id userAgentId;
        
        for (Case item : ltCases) {
            accountIds.add(item.accountId);

            userAgentId = (
                (item.OwnerId != null && !item.OwnerId.to15().startsWith('00G')) 
                ? item.OwnerId 
                : item.CreatedById
            );

            userIds.add(userAgentId);
        }
        
        accountFromCases = new Map<Id, Account>(AccountDAO.getByIds(accountIds));
        userFromCases = new Map<Id, User>(UserDAO.getById(userIds));

        ltFromToMapping = FromToMappingDAO.getByObjectNameAndUsedIn(
            new Set<String>{'User', 'Role'}, 
            'ServiceFlow'
        );

        operatorSegmentFromMdt = new Map<String, String>();

        for (FromToMapping__mdt item : ltFromToMapping) {
            operatorSegmentFromMdt.put(
                (item.Object__c + item.OriginName__c), 
                (item.OperatorSegment__c ?? '')
            );
        }

        List<ToFromHDE2__mdt> ltToFromHDE2 = [
            SELECT
                CustomerSegment__c, 
                OperatorSegment__c, 
                CaseRecordType__c, 
                ORG__c, 
                CustomerServiceReason__c, 
                Routing__c
            FROM
                ToFromHDE2__mdt
        ];

        routingLevelFromMdt = new Map<String, String>();

        for (ToFromHDE2__mdt item : ltToFromHDE2) {
            routingLevelFromMdt.put(
                (item.CustomerSegment__c + item.OperatorSegment__c + item.CaseRecordType__c + item.ORG__c + 
                    item.CustomerServiceReason__c
                ), 
                (item.Routing__c ?? '')
            );
        }

        interactionReasonMap = new Map<String, String>{
            'CRI E-mail V' => 'Acionamento E-mail V',
            'CRI Escalonamento Gold' => 'Processos Escalonamento Gold',
            'CRI Escalonamento Púrpura' => 'Processos Escalonamento Purpura',
            'CRI Escalonamento Silver' => 'Processos Escalonamento Silver',
            'CRI Escalonamento Loja' => 'Processos Escalonamento Lojas',
            'CRI Escalonamento Lojas (Revendas)' => 'Processos Escalonamento Revendas',
            'CRI Escalonamento Platinum' => 'Processos Escalonamento Platinum',
            'CRI Escalonamento Ouvidoria' => 'Processos Escalonamento Ouvidoria',
            'CRI Escalonamento Ouvidoria Comunidades' => 'Processos Escalonamento Ouvidoria',
            'CRI Escalonamento VPR Lojas' => 'Processos Escalonamento VPR',
            'CRI Escalonamento V' => 'Processos Escalonamento V',
            'CRI Escalonamento Carteira' => 'Processos Escalonamento Carteira'
        };
    }
    
    public Iterable<Case> start(Database.BatchableContext info) { 
        return (ltCases);
    }
    
    public void execute(Database.BatchableContext info, List<Case> ltCases) {
        String caseRecordTypeName;
        String interactionReason;
        String serviceReason;
        Id userAgentId;
        String priority;
        User userAgent;
        String userORG;
        Account accountRecord;
        String customerSegment;
        String operatorSegment;
        String routingLevel;
        String action;
        String agent;
        ContactCenterService.Params params;
        OpenMediaInteractionPayload payloadForRouting;
        String payloadAutomaticRouting;

        for (Case caseForRounting : ltCases) {
            caseRecordTypeName = caseForRounting.RecordType.DeveloperName;
            interactionReason = (caseForRounting.View__c ?? '');
            serviceReason = (caseForRounting.CustomerServiceReason__c ?? '');

            interactionReason = (
                interactionReasonMap.containsKey(interactionReason) 
                ? interactionReasonMap.get(interactionReason) 
                : ''
            );

            priority = this.casesWithPriorities.get(caseForRounting.Id);

            userAgentId = ((caseForRounting.OwnerId != null && !caseForRounting.OwnerId.to15().startsWith('00G')) 
                ? caseForRounting.OwnerId 
                : caseForRounting.CreatedById
            );
            
            userAgent = userFromCases.get(userAgentId);
            userORG = ((userAgent.Profile.UserLicense.Name == 'Partner Community') ? ORG_COMUNIDADES : ORG_VIVO);

            accountRecord = accountFromCases.get(caseForRounting.AccountId);
            customerSegment = (accountRecord.vlocity_cmt__CustomerValue__c ?? '');

            operatorSegment = operatorSegmentFromMdt.get(
                ((userORG == ORG_VIVO) ? 'Role': 'User') + 
                ((userORG == ORG_VIVO) ? userAgent.UserRole.DeveloperName : userAgent.PartnerGroup__c)
            );

            routingLevel = routingLevelFromMdt.get(
                customerSegment + operatorSegment + caseRecordTypeName + userORG + serviceReason
            );

            action = ((routingLevel == ROUNTING_N1 || (caseForRounting.OwnerId != null && !caseForRounting.OwnerId.to15().startsWith('00G')))
                ? ContactCenterService.ACTION_AGENT_STOP 
                : ''
            );

            agent = ((routingLevel == ROUNTING_N1 || (caseForRounting.OwnerId != null && !caseForRounting.OwnerId.to15().startsWith('00G')))
                ? userAgent.Login__c 
                : ''
            );

            if (!String.isBlank(interactionReason)) {
                interactionReason = (interactionReason + '_' + ((userORG == ORG_COMUNIDADES) ? 'OUT': 'IN'));
            }
        
            params = new ContactCenterService.Params();

            params.serviceType = ContactCenterService.INTEGRATIONTYPE_ROUTING;
            params.userAgent = userAgent;
            params.userORG = userORG;

            params.action = action;
            params.agent = agent;
            params.priority = priority;
            params.interactionReason = interactionReason;
            params.interactionDetail = serviceReason;
            params.productSubType = (accountRecord.vlocity_cmt__CustomerValue__c ?? '');
            
            params.caseRecord = caseForRounting;
            params.accountRecord = accountRecord;

            payloadForRouting = ContactCenterService.buildOpenMediaInteractionPayLoad(params);
            
            ContactCenterService.validadePayload(payloadForRouting);

            payloadAutomaticRouting = JSON.serialize(payloadForRouting, true);

            ContactCenterService.callCreateOpenMediaInteraction(payloadAutomaticRouting);
        }
    }
    
	public void finish(Database.BatchableContext info) {
        
    }
}