force-app/main/default/objects/Account/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>Segmentação do cliente (Alto, Médio Valor, etc.).</description>
    <label>Segmento do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
            </value>
            <value>
                <fullName>ALTO VALOR</fullName>
            </value>
            <value>
                <fullName>MEDIO VALOR</fullName>
            </value>
            <value>
                <fullName>Silver I</fullName>
            </value>
            <value>
                <fullName>Silver II</fullName>
            </value>
            <value>
                <fullName>Massivo I</fullName>
            </value>
            <value>
                <fullName>Massivo II</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pela Habilitação Remota. Armazena o campo externalId do serviço de pré-ativação da linha executado pelo HRS.</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ApprovalProcessServiceTest.cls
/* -------------------------------------------------------------------------
* Autor....: Renan S. de Freitas - Deloitte
* Data.....: 09/04/2024
* Objetivo.: J21 - Troca de SimCard - Loja Própria - Solicitar autorização para alçada
*  -------------------------------------------------------------------------
*/ 
@isTest
public class ApprovalProcessServiceTest
{
    @TestSetup
    static void setup()
    {
        Account objAccount = new Account();
        objAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getrecordTypeId();
        objAccount.Name = 'Account Test';
        objAccount.DocumentNumber__c = '11111111111111';
        objAccount.vlocity_cmt__CustomerClass__c = 'Móvel';
        objAccount.CustomerSegment__c = 'PLATINUM';
        objAccount.vlocity_cmt__Active__c = 'Yes';
        objAccount.ExternalId__c = '899941326811';
        insert objAccount; 
        
        order objOrder = new Order();
        objOrder.Name = 'Teste Order';
        objOrder.AccountId = objAccount.Id;
        objOrder.EffectiveDate = Date.newInstance(1960, 2, 17);
        objOrder.Status = 'Draft';
        insert objOrder;
        
        Approval.ProcessSubmitRequest objProcessSubmitRequest = new Approval.ProcessSubmitRequest();
        objProcessSubmitRequest.setComments('Submitting request for approval.');
        objProcessSubmitRequest.setObjectId(objOrder.Id);
        objProcessSubmitRequest.setSubmitterId(UserInfo.getUserId());
        objProcessSubmitRequest.setProcessDefinitionNameOrId('ChangeSimCard');
        objProcessSubmitRequest.setSkipEntryCriteria(true);   
        objProcessSubmitRequest.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        Approval.ProcessResult result = Approval.process(objProcessSubmitRequest);
        
    }
    
    @isTest
    static void approvalProcessTest()
    {
        Order objOrder = [SELECT ID FROM Order LIMIT 1];
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        inputs.put('TargetObjectId', objOrder.Id);
        
        ApprovalProcessService approvalProcessService = new ApprovalProcessService();
        approvalProcessService.invokeMethod('approvalProcess', inputs, output, options);
        System.debug('output: ' + JSON.serializePretty(output));
        
        System.assertEquals(true, (Boolean)output.get('success'), 'Processo de aprovação foi bem sucedido');
    }
}