force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallerDDD__c.field-meta.xml
<CustomField>
    <fullName>CallerDDD__c</fullName>
    <description>DDD chamador do telefone de origem na URA.</description>
    <label>DDD Chamador</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Número do Documento</description>
    <label>Número do Documento</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/DisputedItem__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os itens contestados por fatura.</description>
    <label>Item Contestado</label>
    <nameField>
        <label>Item Contestado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Contestados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedItem__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens Contestados</relationshipLabel>
    <relationshipName>DisputedItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/fields/IsConcession__c.field-meta.xml
<CustomField>
    <fullName>IsConcession__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Concessão</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DisputedItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>InAnalisys</fullName>
                <label>Em análise</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Encerrado</label>
            </value>
            <value>
                <fullName>Concession</fullName>
                <label>Concessão</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Procedente</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <label>Improcedente</label>
            </value>
            <value>
                <fullName>Contested</fullName>
                <label>Contestado</label>
            </value>
            <value>
                <fullName>Impugned</fullName>
                <label>Impugnado</label>
            </value>
            <value>
                <fullName>Partially Impugned</fullName>
                <label>Impugnado Parcial</label>
            </value>
            <value>
                <fullName>Does Not Proceed</fullName>
                <label>Não Procede</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>Not Contested</fullName>
                <label>Não Contestado</label>
            </value>
            <value>
                <fullName>Impugnation Limit Reached</fullName>
                <label>Limite de Impugnações Atingido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisputeFixedFlowConcessionVerifierTest.cls
@isTest
public class DisputeFixedFlowConcessionVerifierTest {

    @TestSetup
    public static void testSetup(){
        Account account = new Account();
        account.Name = 'Teste';
        account.DocumentNumber__c = '111111111111';
        insert account;

        Account accountTwo = new Account();
        accountTwo.Name = 'Teste Dois';
        accountTwo.DocumentNumber__c = '22222222222';
        insert accountTwo;

        Case newCase = new Case();
        newCase.AccountId = account.Id;
        insert newCase;

        DisputedItem__c item = new DisputedItem__c();
        item.Status__c = 'Closed';
        item.IsConcession__c = true;
        item.CaseId__c = newCase.Id;
        insert item;
        
        Case newCase2 = new Case();
        newCase2.AccountId = accountTwo.Id;
        insert newCase2;

        DisputedItem__c item2 = new DisputedItem__c();
        item2.Status__c = 'Closed';
        item2.IsConcession__c = true;
        item2.CaseId__c = newCase2.Id;
        insert item2;
        
        Case newCase3 = new Case();
        newCase3.AccountId = account.Id;
        newCase3.CallerDDD__c = '333';
        insert newCase3;

        DisputedItem__c item3 = new DisputedItem__c();
        item3.Status__c = 'Closed';
        item3.IsConcession__c = true;
        item3.CaseId__c = newCase3.Id;
        insert item3;
    }

    @isTest
    public static void givenValidAccountShouldReturnYes() {
        List<DisputeFixedFlowConcessionVerifier.DisputeCheckConcessionInLast180Days> parameters = new List<DisputeFixedFlowConcessionVerifier.DisputeCheckConcessionInLast180Days>();
        DisputeFixedFlowConcessionVerifier.DisputeCheckConcessionInLast180Days parameter = new DisputeFixedFlowConcessionVerifier.DisputeCheckConcessionInLast180Days();

        Case caseX = [SELECT Id, Account.Id FROM Case WHERE Account.DocumentNumber__c = '111111111111' AND CallerDDD__c = '333'];

        parameter.caseAccountId = caseX.Account.Id;
        parameter.caseId = caseX.Id;
        parameters.add(parameter);
            
        Test.startTest();
        
        List<String> response = DisputeFixedFlowConcessionVerifier.customerHasConcessionInLast180Days(parameters);

        Test.stopTest();
        
        System.assertEquals('Sim', response[0]);
    }

    @isTest
    public static void givenInvalidAccountShouldRetunrNo() {
        List<DisputeFixedFlowConcessionVerifier.DisputeCheckConcessionInLast180Days> parameters = new List<DisputeFixedFlowConcessionVerifier.DisputeCheckConcessionInLast180Days>();
        DisputeFixedFlowConcessionVerifier.DisputeCheckConcessionInLast180Days parameter = new DisputeFixedFlowConcessionVerifier.DisputeCheckConcessionInLast180Days();

        Case caseX = [SELECT Id, Account.Id FROM Case WHERE Account.DocumentNumber__c = '22222222222'];

        parameter.caseAccountId = caseX.Account.Id;
        parameter.caseId = caseX.Id;
        parameters.add(parameter);
            
        Test.startTest();
        
        List<String> response = DisputeFixedFlowConcessionVerifier.customerHasConcessionInLast180Days(parameters);

        Test.stopTest();
        
        System.assertEquals('Não', response[0]);
    }
    
}