force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallerDDD__c.field-meta.xml
<CustomField>
    <fullName>CallerDDD__c</fullName>
    <description>DDD chamador do telefone de origem na URA.</description>
    <label>DDD Chamador</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallerPhone__c.field-meta.xml
<CustomField>
    <fullName>CallerPhone__c</fullName>
    <description>Telefone chamador registrado na URA.</description>
    <label>Telefone Chamador</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Closure__c.field-meta.xml
<CustomField>
    <fullName>Closure__c</fullName>
    <label>Fechamento</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/ComplainedAsset__c.field-meta.xml
<CustomField>
    <fullName>ComplainedAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Para uso do HDE</description>
    <inlineHelpText>Terminal, TV ou Banda Larga</inlineHelpText>
    <label>Produto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O produto adicionado está incorreto ou não está relacionado ao cliente.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Asset.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Contexto</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerInteractionId__c.field-meta.xml
<CustomField>
    <fullName>CustomerInteractionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associação do caso com um protocolo (Customer Interaction) pai</description>
    <label>Protocolo Pai</label>
    <referenceTo>vlocity_cmt__CustomerInteraction__c</referenceTo>
    <relationshipLabel>Casos Protocolo</relationshipLabel>
    <relationshipName>CaseProtocol</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerInteractionTopicTree__c.field-meta.xml
<CustomField>
    <fullName>CustomerInteractionTopicTree__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Árvore de Palitagem</label>
    <referenceTo>CustomerInteractionTopicTree__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/DestinyCell__c.field-meta.xml
<CustomField>
    <fullName>DestinyCell__c</fullName>
    <label>Célula Destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Número do Documento</description>
    <label>Número do Documento</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OriginCell__c.field-meta.xml
<CustomField>
    <fullName>OriginCell__c</fullName>
    <label>Célula Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Instância</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ProtocolURA__c.field-meta.xml
<CustomField>
    <fullName>ProtocolURA__c</fullName>
    <label>Protocolo URA</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceDefinitionId__c.field-meta.xml
<CustomField>
    <fullName>ServiceDefinitionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Definição de Atendimento</label>
    <referenceTo>ServiceDefinition__c</referenceTo>
    <relationshipLabel>Cases Contestados</relationshipLabel>
    <relationshipName>CaseServiceDefinition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceQualificationMobile__c.field-meta.xml
<CustomField>
    <fullName>ServiceQualificationMobile__c</fullName>
    <label>Qualificação de Atendimento</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceRequestId__c.field-meta.xml
<CustomField>
    <fullName>ServiceRequestId__c</fullName>
    <label>Número da SS</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceRequestStatus__c.field-meta.xml
<CustomField>
    <fullName>ServiceRequestStatus__c</fullName>
    <label>Status da SS</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TransferObservation__c.field-meta.xml
<CustomField>
    <fullName>TransferObservation__c</fullName>
    <label>Observação da Transferência</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CallDroped.recordType-meta.xml
<RecordType>
    <fullName>CallDroped</fullName>
    <active>true</active>
    <businessProcess>CTIService</businessProcess>
    <label>Ligação Caiu</label>
</RecordType>

force-app/main/default/objects/CustomerInteractionTopicTree__c/CustomerInteractionTopicTree__c.object-meta.xml
<CustomObject>
    <label>Árvore de Palitagem</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Árvore de Palitagem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/GPSId__c.field-meta.xml
<CustomField>
    <fullName>GPSId__c</fullName>
    <label>Id GPS</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericOptionsLists__c/GenericOptionsLists__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Listas de opções genericas para ser utilizadas nos projetos</description>
    <label>Listas de Opções Generica</label>
</CustomObject>

force-app/main/default/objects/ServiceDefinition__c/ServiceDefinition__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as Definições de Atendimento para fluxos transacionais.</description>
    <label>Definição de Atendimento</label>
    <nameField>
        <label>Processo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Definições de Atendimento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDefinition__c/fields/Closure__c.field-meta.xml
<CustomField>
    <fullName>Closure__c</fullName>
    <label>Fechamento Salesforce</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceDefinition__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Contexto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Informação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDefinition__c/fields/ServiceDefinitionName__c.field-meta.xml
<CustomField>
    <fullName>ServiceDefinitionName__c</fullName>
    <label>Código da Definição de Atendimento</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/CallerDDD__c.field-meta.xml
<CustomField>
    <fullName>CallerDDD__c</fullName>
    <description>DDD chamador do telefone de origem na URA.</description>
    <label>DDD Chamador</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/CallerPhone__c.field-meta.xml
<CustomField>
    <fullName>CallerPhone__c</fullName>
    <description>Telefone chamador registrado na URA.</description>
    <label>Telefone Chamador</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/InteractionNumber__c.field-meta.xml
<CustomField>
    <fullName>InteractionNumber__c</fullName>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WDE</fullName>
            </value>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteractionTopic__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>GPS</fullName>
            </value>
            <value>
                <fullName>GPS Pré</fullName>
            </value>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>Hybris</fullName>
            </value>
            <value>
                <fullName>NEXT</fullName>
                <isActive>false</isActive>
                <label>NEXT</label>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SFA Script - Next</fullName>
            </value>
            <value>
                <fullName>VIVO/NET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteractionTopic__c/fields/remarkup__c.field-meta.xml
<CustomField>
    <fullName>remarkup__c</fullName>
    <description>Remark Up from user when create Relationship Topic</description>
    <label>Comentário</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteractionTopic__c/fields/TopicName__c.field-meta.xml
<CustomField>
    <fullName>TopicName__c</fullName>
    <description>Complete Topic Name from tree (path)</description>
    <label>Palito</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteractionTopic__c/fields/vlocity_cmt__Reason__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Reason__c</fullName>
    <description>Records the reason of the outcome.</description>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cross Order Validation</fullName>
            </value>
            <value>
                <fullName>Subscription Suspended</fullName>
            </value>
            <value>
                <fullName>Suspension Reason Mismatch</fullName>
            </value>
            <value>
                <fullName>Eligibility Check</fullName>
            </value>
            <value>
                <fullName>Report Fraud</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subscription Validation</fullName>
            </value>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Top-Up</fullName>
            </value>
            <value>
                <fullName>Voucher Code Validation</fullName>
            </value>
            <value>
                <fullName>Provide PUK</fullName>
            </value>
            <value>
                <fullName>ICCID Validation</fullName>
            </value>
            <value>
                <fullName>Change Feature</fullName>
            </value>
            <value>
                <fullName>Credit Check Declined</fullName>
            </value>
            <value>
                <fullName>Palitagem Fixa</fullName>
            </value>
            <value>
                <fullName>Palitagem Móvel</fullName>
            </value>
            <value>
                <fullName>Palitagem Pré</fullName>
            </value>
            <value>
                <fullName>Atendimento - GSS</fullName>
            </value>
            <value>
                <fullName>Contestação de Fatura - Móvel</fullName>
            </value>
            <value>
                <fullName>Palitagem Outros Produtos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CTIServiceIntegrationVFController.cls
global class CTIServiceIntegrationVFController {
	public String pageURL {get;set;}
    private static final String CASE_ORIGIN_GPS = 'GPS';
    private static final String CASE_ORIGIN_SALESFORCE = 'Salesforce';
    private static final String CASE_STATUS_NEW = 'New';
    private static final String OBSERVATION_NEW_LINE = ' / ';
    private static final String CASE_STATUS_CLOSED = 'Closed';
    private static final String CASE_STATUS_CONSULTING = 'Consulting';
    private static final String CASE_STATUS_IN_TRANSFER = 'InTransfer';
    private static final String CASE_STATUS_CALL_DROPPED = 'CallDropped';
    private static final String CASE_ORIGIN_CALL_DROPPED = 'CallDropped';
    private static final String CASE_SUBJECT_CALL_DROPPED = 'Ligação Caiu';
    private static final String CUSTOM_SETTING_CALL_DROPPED = 'LigacaoCaiu';
    private static final String BUSINESS_RULE_CALL_DROPPED = 'LIGACAO CAIU';
    private static final String CASE_RECORD_TYPE_CALL_DROPPED = 'CallDroped';
    private static final String CASE_RECORD_TYPE_MOBILE_CALL_DROPPED = 'CallDroped';
    private static final String CASE_STATUS_EM_ATENDIMENTO = 'Em Atendimento';
    private static final String CTI_INTEGRATION_QUEUE = 'CTIIntegrationQueue';
    private static final String CASE_CLOSURE_CALL_DROPPED = 'Informação > Atendimento > Ligação > Caiu';
    private static final String CASE_DESCRIPTION_CALL_DROPPED = 'Identificado queda da ligação durante o atendimento.';
    private static final String CASE_ORIGIN_SFA_NEXT = 'SFA Script - Next';

    public void init() {
        pageURL = ApexPages.currentPage().getHeaders().get('referer');        
    }

    @RemoteAction
    global static String getAccountId(String caseId) {
        return [SELECT Id, AccountId FROM Case WHERE Id =: caseId LIMIT 1].AccountId;
    }

    @RemoteAction
    global static Boolean sendCaseToQueue(Map<String, String> payload) {
        try {
            Case wdeCase = CaseDAO.getCasebyId(payload.get('CaseId__c'));
            List<Group> queue = GroupDAO.getQueueByName(CTI_INTEGRATION_QUEUE);
            wdeCase.OwnerId = queue[0].id;
            update wdeCase;

            return true;
        } catch (Exception e) {
            return false;
        }
    }

    @RemoteAction
    global static Boolean updateWdeCase(Map<String, String> payload) {

        try {
            system.debug('Enter into updateWdeCase payload: ' + payload);
            Boolean methodReturn = true;
            Case wdeCase = CaseDAO.getCasebyId(payload.get('CaseId__c'));            

            String operationType = payload.get('OperationType__c');

            if(operationType == 'DirectTransfer' || operationType == 'AssistedTransfer'){

                if(operationType == 'DirectTransfer'){
                    wdeCase.Status = CASE_STATUS_IN_TRANSFER;
                }else{
                    wdeCase.Status = CASE_STATUS_CONSULTING;
                }

                if(wdeCase.TransferObservation__c != null){
                    wdeCase.TransferObservation__c = wdeCase.TransferObservation__c + OBSERVATION_NEW_LINE + payload.get('Observation__c');
                }else{
                    wdeCase.TransferObservation__c = payload.get('Observation__c');
                }
                
                wdeCase.OriginCell__c = payload.get('OriginCell__c');
                wdeCase.DestinyCell__c = payload.get('DestinyCell__c');
                wdeCase.ServiceRequestId__c = payload.get('ServiceRequestId__c');
                wdeCase.ServiceRequestStatus__c = payload.get('ServiceRequestStatus__c');

                if(payload.get('Context__c') != null && payload.get('Context__c') == 'NonGPS'){
                    wdeCase.Closure__c = payload.get('Closure__c');
                }

            } else if(operationType == 'PerformConsult'){

                wdeCase.Status = CASE_STATUS_CONSULTING;
                wdeCase.OriginCell__c = payload.get('OriginCell__c');
                wdeCase.DestinyCell__c = payload.get('DestinyCell__c');

            } else if(operationType == 'TalkToTheCustomer'){

                wdeCase.Status = wdeCase.Status == CASE_STATUS_EM_ATENDIMENTO ? CASE_STATUS_CONSULTING : CASE_STATUS_EM_ATENDIMENTO;

            } else if(operationType == 'FinalizeConsult' || operationType == 'CancelAssistedTransfer'){

                wdeCase.Status = CASE_STATUS_EM_ATENDIMENTO;

            } else if(operationType == 'FinishAssistedTransfer'){

                wdeCase.Status = CASE_STATUS_IN_TRANSFER;

            } else if(operationType == 'CallDropped'){

                Map<String,String> params = new Map<String,String>();
                User currentUser = UserDAO.getById(UserInfo.getUserId());
                Account currentAccount = AccountDAO.getAccountById(wdeCase.AccountId)[0];
				CustomerInteractionTopicTree__c palito = CustomerInteractionTopicTreeDAO.getEndFlowCustomerInteractionTopicTreeById(payload.get('selectedTopicTreeId'))[0];         
                String selectedAssetInstance = payload.get('ServiceIdentifier');

                if(wdeCase.ProtocolURA__c != null && wdeCase.ProtocolURA__c != ''){
                    params.put('PROTOCOLO', wdeCase.ProtocolURA__c);
                }
                
                if(wdeCase.CaseNumber != null && wdeCase.CaseNumber != ''){
                    params.put('NUMERO_CASO', wdeCase.CaseNumber);
                }

                if(palito.GPSId__c != null && palito.GPSId__c != ''){
                    params.put('TIPIFICACAO', palito.GPSId__c);
                }

                if(wdeCase.ServiceRequestId__c != null && wdeCase.ServiceRequestId__c != ''){
                    params.put('ID_SS', wdeCase.ServiceRequestId__c);
                }

                ServiceFlowGPSResponse ssInformation = ServiceFlowGPSCallout.createSS(BUSINESS_RULE_CALL_DROPPED, currentAccount.DocumentNumber__c, selectedAssetInstance, currentUser.Alias, params);

                wdeCase.Status = CASE_STATUS_CALL_DROPPED;
                wdeCase.Product__c = selectedAssetInstance;
                wdeCase.Protocol__c = ssInformation.protocolo;
                wdeCase.ServiceRequestId__c = ssInformation.idSS;
                wdeCase.ServiceRequestStatus__c = ssInformation.status;
                wdeCase.ComplainedAsset__c = payload.get('selectedAssetId');                
                wdeCase.Closure__c = CASE_CLOSURE_CALL_DROPPED;

                if(ssInformation.protocolo != null && ssInformation.idSS != null && ssInformation.status != null){
                    wdeCase.Protocol__c = ssInformation.protocolo;
                    wdeCase.ServiceRequestId__c = ssInformation.idSS;
                    wdeCase.ServiceRequestStatus__c = ssInformation.status;
                }else{
                    methodReturn = false;
                }
            }

            update wdeCase;

            return methodReturn;
        } catch (Exception e) {
            return false;
        }
    }
    @RemoteAction
    global static Map<String, Object> createMobileNextDisputeCase(Map<String, Object> payload) {
        Map<String, Object> response = new Map<String, Object>();
        response.put('createdCase', false);
        response.put('createdInteraction', false);
        response.put('workflow', 'createCaseOnWDECallDrop');

        try {
            Id rtypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(CASE_RECORD_TYPE_MOBILE_CALL_DROPPED).getrecordTypeId();
            String customerAccountId = CustomerInteractionDAO.getAccountIdById(String.valueOf(payload.get('CustomerInteractionId__c')));
            Case callDroppedCase = new Case();

            String serviceDefinitionId = null;

            List<ServiceDefinition__c> serviceDefinitions = [
                SELECT Id
                FROM ServiceDefinition__c
                WHERE ServiceDefinitionName__c = 'ATC-MVL-FIN-CONT-ENC-LIG-001'
                LIMIT 1
            ];

            if (serviceDefinitions.size() > 0) {
                serviceDefinitionId = serviceDefinitions[0].Id;
            }

            String currentLine = String.valueOf(payload.get('Line'));
            String productNumber = String.valueOf(payload.get('ServiceIdentifier'));
            String protocolNumber = String.valueOf(payload.get('protocolNumber'));
            
            String nextProtocolNumber = null;

            vlocity_cmt__CustomerInteraction__c serviceIdentifier = CustomerInteractionDAO.getCustomerInteractionById(String.valueOf(payload.get('CustomerInteractionId__c')));

            If (currentLine == null || String.isEmpty(currentLine) || String.isBlank(currentLine) || currentLine == '{Line}' || currentLine == '\'\'') {
                currentLine = null;
                productNumber = null;
            }

            if (protocolNumber == null || String.isEmpty(protocolNumber) || String.isBlank(protocolNumber) || protocolNumber == '{protocolNumber}' || protocolNumber == '\'\'') {
                protocolNumber = null;
            }

            callDroppedCase.AccountId = customerAccountId;
            callDroppedCase.RecordTypeId = rtypeId;
            callDroppedCase.Origin = 'CallDropped';
            callDroppedCase.CustomerInteractionId__c = payload.get('CustomerInteractionId__c') == null ? null : String.valueOf(payload.get('CustomerInteractionId__c'));
            callDroppedCase.ComplainedAsset__c = currentLine;
            callDroppedCase.Subject = 'Ligação Caiu';
            callDroppedCase.Description = 'Identificado queda da ligação durante o atendimento.';
            callDroppedCase.CallerDDD__c = serviceIdentifier.CallerDDD__c;
            callDroppedCase.CallerPhone__c = serviceIdentifier.CallerPhone__c;
            callDroppedCase.Closure__c = 'Informação > Atendimento > Ligação > Caiu';
            callDroppedCase.Product__c = productNumber;
            callDroppedCase.Protocol__c = protocolNumber;
            callDroppedCase.ProtocolURA__c = serviceIdentifier.InteractionNumber__c;
            callDroppedCase.ServiceQualificationMobile__c = 'Informação > Atendimento > Ligação > Caiu';
            callDroppedCase.ServiceDefinitionId__c = serviceDefinitionId;
            insert callDroppedCase;
            
            response.put('createdCase', true);
            response.put('caseId', callDroppedCase.Id);
            
            vlocity_cmt__CustomerInteractionTopic__c customerInteractionTopic = new vlocity_cmt__CustomerInteractionTopic__c();
            customerInteractionTopic.vlocity_cmt__AccountId__c = customerAccountId;
            customerInteractionTopic.Origin__c = CASE_ORIGIN_SFA_NEXT;
            customerInteractionTopic.TopicName__c = 'Informação > Atendimento > Ligação > Caiu';
            customerInteractionTopic.vlocity_cmt__Reason__c = 'Ligação Caiu';
            customerInteractionTopic.remarkup__c = 'Identificado queda da ligação durante o atendimento.';
            customerInteractionTopic.vlocity_cmt__CaseId__c = callDroppedCase.Id;
            customerInteractionTopic.vlocity_cmt__AssetId__c = currentLine;
            customerInteractionTopic.vlocity_cmt__CustomerInteractionId__c = String.valueOf(payload.get('CustomerInteractionId__c'));
            insert customerInteractionTopic;

            response.put('createdInteraction', true);
            response.put('customerInteractionTopicId', customerInteractionTopic.Id);
            
            response.put('error', false);

            return response;

        } catch (Exception e) {
            response.put('error', true);
            response.put('errorMessage', e.getMessage());

            return response;
        }
    }

    @RemoteAction
    global static Map<String, Object> updateMobileNextDisputeCase(Map<String, Object> payload) {
        Map<String, Object> response = new Map<String, Object>();
        response.put('updatedCase', false);
        response.put('workflow', 'updateCaseOnWDECallDrop');
        
        try {
            String caseId = String.valueOf(payload.get('CaseId__c'));

            if (caseId == null || String.isEmpty(caseId) || String.isBlank(caseId) || caseId == '{CaseId__c}' || caseId == '\'\'') {
                caseId = null;
            }

            Case wdeCase = CaseDAO.getCasebyId(caseId);

            wdeCase.Status = 'CallDropped';
            wdeCase.Closure__c = 'Informação > Atendimento > Ligação > Caiu';

            upsert wdeCase;

            response.put('updatedCase', true);
            response.put('error', false);

            return response;

        } catch (Exception e) {
            response.put('error', true);
            response.put('errorMessage', e.getMessage());

            return response;
        }
    }
    @RemoteAction
    global static Boolean setCaseOwnerAsCurrentUser(Map<String, String> payload) {

        try {
            Case wdeCase = CaseDAO.getCasebyId(payload.get('CaseId__c'));

            wdeCase.OwnerId = UserInfo.getUserId();
    
            update wdeCase;
    
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    @RemoteAction
    global static Boolean createCase(Map<String, String> payload) {
        try {
            system.debug('Enter into createCase payload: ' + payload);
            Boolean methodReturn = true;            
            String customerInteractionId = payload.get('CustomerInteractionId__c');
            String accountId = CustomerInteractionDAO.getAccountIdById(customerInteractionId); 
            String serviceIdentifier = CustomerInteractionDAO.getIdentifierNumberById(customerInteractionId);
            List<Asset> selectedAsset = AssetDAO.getAssetIdByIdentifiers(serviceIdentifier, accountId);
            
            
            if (selectedAsset.size() == 0) {
                selectedAsset = AssetDAO.getAssetIdWithoutIdentifiers(accountId);
            }
            
            if (selectedAsset.size() > 0) {
                String caseId = createCase(accountId, customerInteractionId, selectedAsset[0].vlocity_cmt__ServiceIdentifier__c, selectedAsset[0].Id);
                createCustomerInteractionTopic(caseId, customerInteractionId, selectedAsset[0].Id, accountId, CASE_ORIGIN_GPS);
            } else {
                createCustomerInteractionTopic(null, customerInteractionId, null, accountId, CASE_ORIGIN_SALESFORCE);
            }
            
            return methodReturn;

        } catch (Exception e) {
            return false;
        }
    }
    private static void createCustomerInteractionTopic(String caseId, String customerInteractionId, String selectedAssetId, String accountId, String origin) {
        try {
            vlocity_cmt__CustomerInteractionTopic__c newCustomerInteractionTopic = new vlocity_cmt__CustomerInteractionTopic__c();
            newCustomerInteractionTopic.vlocity_cmt__AccountId__c = accountId;
            newCustomerInteractionTopic.vlocity_cmt__CustomerInteractionId__c = customerInteractionId;
            newCustomerInteractionTopic.vlocity_cmt__AssetId__c = selectedAssetId;
            newCustomerInteractionTopic.vlocity_cmt__CaseId__c = caseId;
            newCustomerInteractionTopic.Origin__c = origin;
            newCustomerInteractionTopic.vlocity_cmt__Reason__c = CASE_SUBJECT_CALL_DROPPED;
            newCustomerInteractionTopic.remarkup__c = CASE_DESCRIPTION_CALL_DROPPED;
            newCustomerInteractionTopic.TopicName__c = CASE_CLOSURE_CALL_DROPPED;
            
            insert newCustomerInteractionTopic;
        } catch(Exception e) {
            System.debug('Erro ao criar o palito: ' + e.getMessage());
        }
    }

    private static String createCase(String accountId, String customerInteractionId, String selectedAssetInstance, String selectedAssetId) {
        try {
        	Case newCase = new Case();
            User currentUser = UserDAO.getById(UserInfo.getUserId());
            Account currentAccount = AccountDAO.getAccountById(accountId)[0];
            GenericOptionsLists__c callDroppedServiceId = GenericOptionsLists__c.getValues(CUSTOM_SETTING_CALL_DROPPED);
            Id rtypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(CASE_RECORD_TYPE_CALL_DROPPED).getrecordTypeId();
            vlocity_cmt__CustomerInteraction__c currentInteraction = CustomerInteractionDAO.getCustomerInteractionById(customerInteractionId);

            newCase.AccountId = accountId;            
            newCase.CustomerInteractionId__c = currentInteraction.Id;
            newCase.RecordTypeId = rtypeId;
            newCase.Status = CASE_STATUS_NEW;
            newCase.Origin = CASE_ORIGIN_CALL_DROPPED;
            newCase.Product__c = selectedAssetInstance;            
            newCase.ComplainedAsset__c = selectedAssetId;
            newCase.Subject = CASE_SUBJECT_CALL_DROPPED;
            newCase.Closure__c = CASE_CLOSURE_CALL_DROPPED;            
            newCase.Description = CASE_DESCRIPTION_CALL_DROPPED;
            newCase.ProtocolURA__c = currentInteraction.InteractionNumber__c;
            newCase.CallerDDD__c = currentInteraction.CallerDDD__c;
            newCase.CallerPhone__c = currentInteraction.CallerPhone__c;
            newCase.ServiceQualificationMobile__c = CASE_CLOSURE_CALL_DROPPED;

            insert newCase;

            updateCallDroppedCase(newCase.id, currentAccount.DocumentNumber__C,selectedAssetInstance, currentUser.Alias);
        
        	return newCase.id;
        } catch(Exception e) {
            System.debug('Erro ao criar o caso: ' + e.getMessage());
            return null;
        }	        
    }
    @future(callout=true)
    private static void updateCallDroppedCase(String caseId, String cnpj, String selectedAssetInstance, String userAlias){
        try{
            Case savedCase = CaseDAO.getCasebyId(caseId);
            Map<String,String> params = new Map<String,String>();

            if(savedCase.ProtocolURA__c != null && savedCase.ProtocolURA__c != ''){
                params.put('PROTOCOLO', savedCase.ProtocolURA__c);
            }

            if(savedCase.CaseNumber != null && savedCase.CaseNumber != ''){
                params.put('NUMERO_CASO', savedCase.CaseNumber);
            }

            ServiceFlowGPSResponse ssInformation = ServiceFlowGPSCallout.createSS(BUSINESS_RULE_CALL_DROPPED, cnpj, selectedAssetInstance, userAlias, params);
            
            savedCase.Protocol__c = ssInformation.protocolo;
            savedCase.ServiceRequestId__c = ssInformation.idSS;
            savedCase.ServiceRequestStatus__c = ssInformation.status;
            savedCase.Status = CASE_STATUS_CLOSED;

            update savedCase;
        }catch(Exception e){
            System.debug('Erro ao atualizar caso de ligação caiu: '+e.getMessage());
        }
    }

    @RemoteAction
    global static Boolean closeCaseIfNonCanvas(String caseId) {

        try {
            Case wdeCase = CaseDAO.getCasebyId(caseId);

            if(wdeCase.Origin == CASE_ORIGIN_GPS && wdeCase.Closure__c != null){
                wdeCase.Status = CASE_STATUS_CLOSED;
                update wdeCase;
            }

            return true;

        } catch (Exception e) {
            return false;
        }
    }
}