force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>Passaporte</fullName>
            </value>
            <value>
                <fullName>Documento Estrangeiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HighTemperature__c.field-meta.xml
<CustomField>
    <fullName>HighTemperature__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Atenção - Cliente em outro contato com a empresa se mostrou com temperatura elevada. Entenda o pedido atual e verifique se tem relação com outro contato, atue sobre a causa raiz, se necessário e sendo do seu escopo, abra o HDE</inlineHelpText>
    <label>Temperatura Alta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__CustomerValue__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__CustomerValue__c</fullName>
    <description>A ranking of the value of this customer to your business expressed in marketing terms such as Gold, Silver, Bronze, Diamond, Platinum.</description>
    <label>Customer Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/MainProductDescription__c.field-meta.xml
<CustomField>
    <fullName>MainProductDescription__c</fullName>
    <description>Campo para informar o plano.</description>
    <label>Plano</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Armazena a tecnologia do registro de Ativo/Produto</description>
    <label>Tecnologia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FTTH</fullName>
            </value>
            <value>
                <fullName>FTTC</fullName>
            </value>
            <value>
                <fullName>Movel</fullName>
                <label>Móvel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tipo</fullName>
            </value>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Movel</fullName>
                <label>Móvel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Número do Documento</description>
    <label>Número do Documento</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <formula>TEXT(Account.DocumentType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Documento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactCenterServiceTest.cls
@isTest
private class ContactCenterServiceTest {
    @isTest
    private static void buildOpenMediaInteractionPayLoadTest() {
        Case caseObj = new Case();
        caseObj.Id = TestingUtils.getFakeId(Case.getSobjectType(), 1);

        caseObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(CasesMyRequestsB2C.CHARGE_OF_ADDRESS_RECORD_TYPE_API_NAME).getrecordTypeId();
        caseObj.Protocol__c = '1234';
        caseObj.Description = 'Caso Teste';

        Account accountObj = new Account();
        accountObj.Id = TestingUtils.getFakeId(Account.getSobjectType(), 2);
        accountObj.Name = 'Test Account';
        accountObj.DocumentNumber__c = '1234';
        accountObj.DocumentType__c = 'CPF';
        accountObj.vlocity_cmt__CustomerValue__c = '';
        accountObj.HighTemperature__c = true;

        Asset assetObj = new Asset();
        assetObj.Type__c = '';
        assetObj.Technology__c = '';
        assetObj.MainProductDescription__c = 'Vivo Fibra';

        OpenMediaInteractionPayload payload = ContactCenterService.buildOpenMediaInteractionPayLoad(caseObj, accountObj, assetObj);

        Assert.isNotNull(payload);
        Assert.isInstanceOfType(payload, OpenMediaInteractionPayload.class);
    }

    @isTest
    private static void createOpenMediaInteractionTest() {
        OpenMediaInteractionPayload payload = new OpenMediaInteractionPayload();
        payload.caseId = TestingUtils.getFakeId(Case.getSobjectType(), 55);
        String payloadSerialized = JSON.serialize(payload);
        ContactCenterService.createOpenMediaInteraction(payloadSerialized);
    }

    @isTest
    private static void validadeCreatedStatusCodeTest() {
        Integer statusCode = 500;

        try {
            ContactCenterService.validadeCreatedStatusCode(statusCode);
        } 
        catch (ContactCenterServiceException e) {
            String errorMessage = e.getMessage();   
            Assert.areEqual('Status Code diferente de 201.', errorMessage);
        }  
    }

    @isTest
    private static void validadePayloadTest() {
        // payload válido, não lança exception
        try {
        	OpenMediaInteractionPayload payload = new OpenMediaInteractionPayload();
        	payload.caseId = TestingUtils.getFakeId(Case.getSObjectType(), 1);
        	ContactCenterService.validadePayload(payload);
        }
        catch (IllegalArgumentException e) {
            String errorMessage = e.getMessage();   
            Assert.areEqual('payload não pode ser nulo.', errorMessage);
        }

        // payload invalido, não lança exception
        try {
            OpenMediaInteractionPayload emptyPayload;
            ContactCenterService.validadePayload(emptyPayload);
        } 
        catch (IllegalArgumentException e) {
            String errorMessage = e.getMessage();   
            Assert.areEqual('payload não pode ser nulo.', errorMessage);
        } 
    }
}