force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FullComplement__c.field-meta.xml
<CustomField>
    <fullName>FullComplement__c</fullName>
    <formula>IF(RecordType.DeveloperName = "Billing", IF( AND(OR(ISNULL( BillingComplement1__c ), ISBLANK( BillingComplement1__c )) ,OR(ISNULL( BillingComplement2__c ), ISBLANK( BillingComplement2__c )),OR(ISNULL( BillingComplement3__c ), ISBLANK( BillingComplement3__c ))) , 'Sem Complemento',  BillingComplement1__c  &amp; " " &amp; BillingComplement2__c  &amp; " " &amp;  BillingComplement3__c )

,IF( AND(OR(ISNULL(  ShippingComplement1__c  ), ISBLANK(  ShippingComplement1__c  )) ,OR(ISNULL(  ShippingComplement2__c  ), ISBLANK(  ShippingComplement2__c  )),OR(ISNULL(  ShippingComplement3__c  ), ISBLANK(  ShippingComplement3__c  ))) , 'Sem Complemento',   ShippingComplement1__c   &amp; " " &amp;  ShippingComplement2__c   &amp; " " &amp;   ShippingComplement3__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Complemento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ShippingNumber__c.field-meta.xml
<CustomField>
    <fullName>ShippingNumber__c</fullName>
    <description>Número do endereço de correspondência</description>
    <label>Número</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CanvasHybrisOrderService.cls
public with sharing class CanvasHybrisOrderService extends CanvasHybrisServices {
    protected override Account query(Id recordId){
        return [SELECT  Id, 
                        Name, 
                        DocumentNumber__c,  
                        vlocity_cmt__CreditScore__c,
                        vlocity_cmt__PrimaryContactId__r.MotherName__c, 
                        vlocity_cmt__PrimaryContactId__r.Email,
                        vlocity_cmt__PrimaryContactId__r.MobilePhone,
                        vlocity_cmt__PrimaryContactId__r.Birthdate,
                		ShippingPostalCode,
                        ShippingNumber__c,
                        FullComplement__c
                            
                FROM    Account 
                WHERE   Id = :recordId
                LIMIT   1];
        
    }
}