force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserProfileController.cls
public without sharing class UserProfileController {
    private static final String WEBSERVICE_NAME = 'FourthPlataformUserProfileCallout';
    
        @AuraEnabled
        public static String getUserId(Id recordId){
            List<Account> lstAccount = new List<Account>();
            lstAccount = AccountDAO.getAccountUserIdById(CustomerInteractionDAO.getAccountIdById(recordId));
            
            if(lstAccount.isEmpty() || lstAccount[0].UserId__c != null){
                return null;
            } 

            Webservice__c wsConfig = Webservice__c.getInstance(WEBSERVICE_NAME);
    
            if (wsConfig == null) {
                return 'CustomerPlataformaDigitalCallout: Webservice not found.';
            }
    
            String parameters = '?id_document.type=CPF&id_document.value=' + lstAccount[0].DocumentNumber__c ;
            String endpoint = wsConfig.Endpoint__c + parameters;
            List<UserProfileTO> lstUserProfile = new List<UserProfileTO>();
    
            HttpClient client = new HttpClient();
            HttpResponse response = client.get(wsConfig, endpoint);
            ServiceResponse serviceResponse = new ServiceResponse();
    
            if (response.getStatusCode()/100 == 2) {
                String result = response.getBody();
                serviceResponse.body = result;
                serviceResponse.success = true;
            } else {
                serviceResponse.success = false;
            }
            
            if (serviceResponse.success) {
                lstUserProfile = (List<UserProfileTO>)Json.deserialize(serviceResponse.body, List<UserProfileTO>.class);
            }        
            
            if(!lstUserProfile.isEmpty()){
                for(UserProfileTO result : lstUserProfile){
                    lstAccount[0].UserId__c = result.id;
                    break;
                }
            }
            
            update lstAccount;
            return (lstAccount[0] != null && lstAccount[0].UserId__c != null) ? 'true' : 'false';
        }
    }