force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <externalId>true</externalId>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserProfileService.cls
public without sharing class UserProfileService {
    private static final String WEBSERVICE_NAME = 'UserServiceUserProfileCallout';
    public static List<UserProfileTO> getUserProfileByAccountId(Id recordId){
        List<Account> listAccount = AccountDAO.getAccountById(recordId);

        Webservice__c wsConfig = Webservice__c.getInstance(WEBSERVICE_NAME);
        String endpoint = wsConfig.Endpoint__c + '?id_document.type=CPF&id_document.value=' + listAccount[0].DocumentNumber__c;
        HttpClient client = new HttpClient();
        HttpResponse response = client.get(wsConfig, endpoint);

        List<UserProfileTO> listUserProfile = (List<UserProfileTO>)Json.deserialize(response.getBody(), List<UserProfileTO>.class);
        return listUserProfile;
    }
}