force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AssetPartyRelationship__c/AssetPartyRelationship__c.object-meta.xml
<CustomObject>
    <description>Objeto que estabelece a relação entre ativos (Assets) e partes (Parties), permitindo o gerenciamento das associações entre entidades dentro do sistema Salesforce.&quot;</description>
    <label>Asset Party Relationship</label>
    <nameField>
        <label>Asset Party Relationship</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssetPartyRelationship__c/fields/ApprovedByOwner__c.field-meta.xml
<CustomField>
    <fullName>ApprovedByOwner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o relacionamento foi aprovado pelo titular do ativo associado. Este campo é utilizado para registrar a autorização explícita do titular em relação ao relacionamento estabelecido entre o ativo e a parte associada, conforme as diretrizes estabelecidas pelo cliente.</description>
    <label>Aprovado pelo Titular</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AssetPartyRelationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Define o tipo de relação ou papel que a parte associada desempenha em relação ao ativo específico. Este campo é utilizado para categorizar e identificar o papel ou função da parte associada dentro do contexto do relacionamento estabelecido com o ativo.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Usuário</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssetPartyRelationship__c/fields/SourceParty__c.field-meta.xml
<CustomField>
    <fullName>SourceParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Party</label>
    <referenceTo>vlocity_cmt__Party__c</referenceTo>
    <relationshipLabel>Assets Party Relationships</relationshipLabel>
    <relationshipName>Assets_Party_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssetPartyRelationship__c/fields/TargetAsset__c.field-meta.xml
<CustomField>
    <fullName>TargetAsset__c</fullName>
    <label>Target Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Assets Party Relationships</relationshipLabel>
    <relationshipName>AssetsPartyRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <description>Este campo armazena o endereço de e-mail principal do dependente.</description>
    <label>Email Dependente</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MotherName__c.field-meta.xml
<CustomField>
    <fullName>MotherName__c</fullName>
    <description>Nome da mãe</description>
    <label>Nome da Mãe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>Nome que o cliente informou que gostaria de ser chamado</description>
    <label>Nome Social</label>
    <length>130</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConsultProductUserTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-27-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class ConsultProductUserTest {
    
    @testSetup
    static void testSetup() {
        
		Account testAccount = new Account( Name = 'Test Account', ExternalId__c = '1234567890211999999999');
        insert testAccount;

        Contact testContact = new Contact( AccountId = testAccount.Id,
            CPF__c = '12345678902', FirstName = 'Test', LastName = 'User', ExternalId__c = '1234567890211999999999', ContactEmail__c = 'contactEmail@test.com', AssistantPhone = '1199643388', OtherPhone = '1199643388',
            Nickname__c = 'TestNick', MotherName__c = 'TestMother', Birthdate = Date.newInstance(1990, 1, 1), Email = 'email@test.com', MobilePhone = '1199643388', HomePhone = '113622959', Phone = '113622959');
        insert testContact;
        
        Asset testAsset = new Asset( ExternalId__c = '1234567890211999999999', Name = 'Test Asset', AccountId = testAccount.Id, ContactId = testContact.Id);
        insert testAsset;
        
        vlocity_cmt__Party__c testParty = new vlocity_cmt__Party__c( vlocity_cmt__ContactId__c = testContact.Id );
        insert testParty;
        
        AssetPartyRelationShip__c testAssetPartyRelation = new AssetPartyRelationShip__c( SourceParty__c = testParty.Id, TargetAsset__c = testAsset.Id, Name = 'Test Asset Party Relation', Role__c = 'Usuário', approvedByOwner__c = true );
        insert testAssetPartyRelation;
    }
    
    @isTest
    static void testSelectAllDependentsByCpfWhenSuccess() {
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/consultProductUser/v1/productUsers/12345678902';
        req.httpMethod = 'GET';
        req.headers.put('x-Authorization','Bearer ' + jwt);
        req.addHeader('Content-Type', 'application/json');
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;

        Test.startTest();
        ConsultProductUser.getConsultProductUser();
        Test.stopTest();
        
        GetConsultProductResponseWrapper.ConsultProductUserWrapper response = (GetConsultProductResponseWrapper.ConsultProductUserWrapper) JSON.deserialize(res.responseBody.toString(), GetConsultProductResponseWrapper.ConsultProductUserWrapper.class);
        System.assertEquals(200, res.statusCode);
        System.assertEquals('Registros retornados com sucesso.', response.message);
        System.assertNotEquals(0, response.totalSize);
        
    }
    
    @isTest
    static void testSelectDependentsByCpfAndLineWhenSuccess() {
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/consultProductUser/v1/productUsers/1234567890211999999999';
        req.httpMethod = 'GET';
        req.headers.put('x-Authorization','Bearer ' + jwt);
        req.addHeader('Content-Type', 'application/json');
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        Test.startTest();
        ConsultProductUser.getConsultProductUser();
        Test.stopTest();
        
        GetConsultProductResponseWrapper.ConsultProductUserWrapper response = (GetConsultProductResponseWrapper.ConsultProductUserWrapper) JSON.deserialize(res.responseBody.toString(), GetConsultProductResponseWrapper.ConsultProductUserWrapper.class);
        System.assertEquals(200, res.statusCode);
        System.assertEquals('Registros retornados com sucesso.', response.message);
        System.assertNotEquals(0, response.totalSize);
    }
 
    @isTest
    static void testReturnsErrorWhenCpfIsInvalid() {
        RestResponse res = new RestResponse();
        RestRequest req = new RestRequest();

        RestContext.response = res;
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        req.headers.put('x-Authorization','Bearer ' + jwt);

        req.requestUri = '/services/apexrest/consultProductUser/v1/productUsers/';
        req.httpMethod = 'GET';
        req.addHeader('Content-Type', 'application/json');
        RestContext.request = req;
 
        Test.startTest();
        ConsultProductUser.getConsultProductUser();
        Test.stopTest();

        System.assertEquals(400, res.statusCode);
        String responseBody = res.responseBody.toString();
        GetConsultProductResponseWrapper response = GetConsultProductResponseWrapper.parse(responseBody);

        System.assert(responseBody.contains('BAD_REQUEST'));
        System.assert(responseBody.contains('invalid request'));
    }
 
    
    @isTest
    static void testReturnsErrorWhenCpfOrCpfAndLineNotFound() {
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/consultProductUser/v1/productUsers/1234567890211999999998';
        req.httpMethod = 'GET';
        req.headers.put('x-Authorization','Bearer ' + jwt);
        req.addHeader('Content-Type', 'application/json');
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        Test.startTest();
        ConsultProductUser.getConsultProductUser();
        Test.stopTest();
        
        GetConsultProductResponseWrapper.ConsultProductUserWrapper response = (GetConsultProductResponseWrapper.ConsultProductUserWrapper) JSON.deserialize(res.responseBody.toString(), GetConsultProductResponseWrapper.ConsultProductUserWrapper.class);
        System.assertEquals(404, res.statusCode);
        System.assertEquals('This operation was not found', response.message);
    }
    
	@isTest
    static void testIsValidJWT() {
        JWTUtilityTest.setPublicTestKey();
		RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        String jwt = JWTUtilityTest.createValidJWT();
        String externalId = '1234567891';
        //Contact cc = [SELECT Id, ExternalId__c FROM Contact WHERE ExternalId__c =: externalId];

        req.requestURI = '/services/apexrest/consultProductUser/v1/productUsers/' + externalId;
        req.headers.put('x-Authorization','Bearer ' + jwt);
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        ConsultProductUser.getConsultProductUser();
        Test.stopTest();

        Assert.areEqual(400, res.statusCode);
    }
    
    @isTest
    static void testIsInvalidJWT() {
        JWTUtilityTest.setPublicTestKey();
		RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        String jwt = JWTUtilityTest.createInvalidJWT();
        String externalId = '1234567891';
        //Contact cc = [SELECT Id, ExternalId__c FROM Contact WHERE ExternalId__c =: externalId];

        req.requestURI = '/services/apexrest/consultProductUser/v1/productUsers/' + externalId;
        req.headers.put('x-Authorization','Bearer ' + jwt);
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        ConsultProductUser.getConsultProductUser();
        Test.stopTest();

        GetConsultProductResponseWrapper.ConsultProductUserWrapper response = (GetConsultProductResponseWrapper.ConsultProductUserWrapper) JSON.deserialize(res.responseBody.toString(), GetConsultProductResponseWrapper.ConsultProductUserWrapper.class);
        System.assertEquals(403, res.statusCode);
        System.assertEquals('Forbidden', response.message); 
    }
    
    @isTest
    static void testInternalServerError() {
        JWTUtilityTest.setPublicTestKey();
        String jwt = '';
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/consultProductUser/v1/productUsers/12345678901199999998';
        req.httpMethod = 'GET';
        req.headers.put('x-Authorization','Bearer ' + jwt);
        req.addHeader('Content-Type', 'application/json');
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        Test.startTest();
        ConsultProductUser.getConsultProductUser();
        Test.stopTest();
        
        GetConsultProductResponseWrapper.ConsultProductUserWrapper response = (GetConsultProductResponseWrapper.ConsultProductUserWrapper) JSON.deserialize(res.responseBody.toString(), GetConsultProductResponseWrapper.ConsultProductUserWrapper.class);
        System.assertEquals(500, res.statusCode);
        System.assertEquals('Internal Server Error', response.message); 
    } 
    
    	@isTest
    	static void testJWTForbiden() {
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/consultProductUser/v1/productUsers/12345678901199999998';
        req.httpMethod = 'GET';
        req.headers.put('x-Authorization',' ');
        req.addHeader('Content-Type', 'application/json');
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        Test.startTest();
        ConsultProductUser.getConsultProductUser();
        Test.stopTest();
        
        GetConsultProductResponseWrapper.ConsultProductUserWrapper response = (GetConsultProductResponseWrapper.ConsultProductUserWrapper) JSON.deserialize(res.responseBody.toString(), GetConsultProductResponseWrapper.ConsultProductUserWrapper.class);
        System.assertEquals(403, res.statusCode);
        System.assertEquals('Forbidden', response.message); 
    } 
}