force-app/main/default/objects/Account/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <description>Valor total da última fatura</description>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LegacySystem__c.field-meta.xml
<CustomField>
    <fullName>LegacySystem__c</fullName>
    <description>Sistema legado de origem do Asset do Cliente.</description>
    <label>Sistema de Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATIS</fullName>
            </value>
            <value>
                <fullName>ATLYS</fullName>
            </value>
            <value>
                <fullName>NEXT</fullName>
            </value>
            <value>
                <fullName>NGIN</fullName>
            </value>
            <value>
                <fullName>NSIA</fullName>
            </value>
            <value>
                <fullName>SIA</fullName>
            </value>
            <value>
                <fullName>SIEBEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Campo para guardar o valor</description>
    <label>StartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tipo</fullName>
            </value>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Movel</fullName>
                <label>Móvel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo fixo</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/SearchRangeInvoice__c.field-meta.xml
<CustomField>
    <fullName>SearchRangeInvoice__c</fullName>
    <label>Intervalo de Pesquisa Faturas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Objeto de faturas destinado a armazenar as informações históricas do cliente.</description>
    <label>Faturamento</label>
    <nameField>
        <label>Mês de Referência</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Campo de relacionamento entre Conta e Invoice.</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamento</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CreationDate__c.field-meta.xml
<CustomField>
    <fullName>CreationDate__c</fullName>
    <label>Data da criação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CustomerInteraction__c.field-meta.xml
<CustomField>
    <fullName>CustomerInteraction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocolo</label>
    <referenceTo>vlocity_cmt__CustomerInteraction__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Protocolo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Downloadurl__c.field-meta.xml
<CustomField>
    <fullName>Downloadurl__c</fullName>
    <label>Download url</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Data do Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/FixedAmount__c.field-meta.xml
<CustomField>
    <fullName>FixedAmount__c</fullName>
    <formula>FixedSiebel__c +  FixedRollup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fixa</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceContestedStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceContestedStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status da Fatura Contestada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <description>Identificador da fatura na 4P.</description>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/MobileRollup__c.field-meta.xml
<CustomField>
    <fullName>MobileRollup__c</fullName>
    <description>Campo para sumarizar os itens da fatura em móvel.</description>
    <label>Móvel</label>
    <summarizedField>InvoiceItem__c.Value__c</summarizedField>
    <summaryFilterItems>
        <field>InvoiceItem__c.Type__c</field>
        <operation>equals</operation>
        <value>Celular</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoiceItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/NextInvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>NextInvoiceDate__c</fullName>
    <label>Data da próxima fatura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PaymentDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentDate__c</fullName>
    <label>Data do Pagamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <label>Pago</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <label>Não Pago</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SecondaryDownloadUrl__c.field-meta.xml
<CustomField>
    <fullName>SecondaryDownloadUrl__c</fullName>
    <label>Download url secundária</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TaxInclude__c.field-meta.xml
<CustomField>
    <fullName>TaxInclude__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxa inclusa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Item da Fatura</label>
    <nameField>
        <displayFormat>IF-{0000}</displayFormat>
        <label>Item da Fatura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da Fatura</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identificador</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Itens da Fatura</relationshipLabel>
    <relationshipName>InvoiceItens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/TaxInclude__c.field-meta.xml
<CustomField>
    <fullName>TaxInclude__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxa inclusa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Celular</fullName>
            </value>
            <value>
                <fullName>Fixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <label>Validade dos dados da consulta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoiceHistoryController.cls
/*
* @description - Classe Controller do componente de Fatura, buscando as informações de Fatura na 4P
*/
public without sharing class InvoiceHistoryController {
    private static final String WEBSERVICE_NAME = 'FourthPlataformInvoiceCallout';

    @AuraEnabled
    public static Boolean validateUserIdInformation(String customerInteractionId){
        
        Id accountId = getAccountIdFromCustomerInteraction(customerInteractionId);        
        Account accountObj = AccountDAO.getByIds(accountId);        
        
        return (accountObj != null && accountObj.UserId__c != null);
    }
    
    @AuraEnabled
    public static Boolean getInvoiceHistory(String accountId){
        
        WebService__c wsConfig = Webservice__c.getInstance(WEBSERVICE_NAME);
        
        integer refreshTime = InvoiceHistoryController.getValidateTime(wsConfig) *-1;
        Datetime searchInvoiceDate = system.now().addSeconds(refreshTime);
        
        List<Invoice__c> ltInvoiceHistory = new List<Invoice__c>();
        ltInvoiceHistory = InvoiceHistoryDAO.getInvoiceByAccountId(accountId,searchInvoiceDate);
        if(ltInvoiceHistory.isEmpty()){
            return false;            
        } else {
            return true;           
        }        
    }
    
    @AuraEnabled
    public static List<Asset> createInvoiceHistory(Id customerInteractionId) {
        Id accountId = getAccountIdFromCustomerInteraction(customerInteractionId);
        
        List<Asset> ltAssetObj = new List<Asset>();
        Webservice__c wsConfig = Webservice__c.getInstance(WEBSERVICE_NAME);
        
        if (wsConfig == null) {            
            return ltAssetObj; 
        }
        
        List<Invoice__c> ltInvoiceHistory = new List<Invoice__c>();
        List<InvoiceItem__c> ltInvoiceItem = new List<InvoiceItem__c>();
        List<GeneralParam__c> lstGeneralParams = new List<GeneralParam__c>();
        lstGeneralParams = GeneralParamDAO.getLoadParams();  
        
        String UserId;
                
        List<Account> ltAccount = new List<Account>([SELECT UserId__c, RecordTypeId FROM Account WHERE ID =: accountId]);	
                
        UserId = ltAccount[0].UserId__c; 
                
        Integer searchRange = Integer.valueOf(lstGeneralParams[0].SearchRangeInvoice__c) *-1;
        
        Date startDate = System.Today().addDays(searchRange);
        Date endDate = System.Today();
        
        String parameters = '/'+ UserId + '/invoices?start_date=' + String.valueOf(startDate) +('T00:00:00Z') + '&end_date=' + String.valueOf(endDate) +('T23:59:59Z') ;
        String endpoint = wsConfig.Endpoint__c + parameters;
        
        HttpClient client = new HttpClient();
        HttpResponse response = client.get(wsConfig, endpoint);
        ServiceResponse invoiceResponse = new ServiceResponse();
        
        List<InvoiceServiceReturn> lstInvoiceReturn = new List<InvoiceServiceReturn>();
        
        if (response.getStatusCode()/100 == 2) {
            String result = response.getBody();
            invoiceResponse.body = result;
            invoiceResponse.success = true;
        } else {
            invoiceResponse.success = false;
        }

        if (invoiceResponse.success) {
            lstInvoiceReturn = (List<InvoiceServiceReturn>) Json.deserialize(invoiceResponse.body, List<InvoiceServiceReturn>.class);
        } 
        
        String sStartDate;
        String sEndDate;
        String sCreateDate;
        String sDueDate;
        String sPaymentDate;
        String sNextInvoiceDate;                
        String sStartDateItem;
        String sEndDateItem; 

        String month;
        string year;
        integer dtmonth;
        integer dtyear;
        
        if(lstInvoiceReturn.isEmpty()){
            return ltAssetObj;
        }

        map<String, String> mapProductsForBillingAccount = new Map<String, String>();
               
        for(InvoiceServiceReturn result : lstInvoiceReturn){
            
            Invoice__c invoiceHistory = new Invoice__c();
            
            invoiceHistory.InvoiceId__c = result.id;
            invoiceHistory.AccountId__c = accountId;  
            if(result.due_date != null && result.due_date.contains('T')){
                sEndDate = result.due_date.replaceAll('T',' ');
                dtmonth = Date.valueOf(sEndDate).month();
                dtyear = Date.valueOf(sEndDate).year();
                year = String.valueOf(dtyear);
            
            } else {
                sEndDate = '';
                dtmonth = null;
                dtyear = null;
                year = '';
            }

            Switch on dtmonth {
                when 01 {
                    month = 'Janeiro';
                }
                when 02{
                    month = 'Fevereiro';
                }
                when 03 {
                    month = 'Março';
                }
                when 04 {
                    month = 'Abril';
                }
                when 05 {
                    month = 'Maio';
                }
                when 06 {
                    month = 'Junho';
                }
                when 07 {
                    month = 'Julho';
                }
                when 08 {
                    month = 'Agosto';
                }
                when 09 {
                    month = 'Setembro';
                }
                when 10 {
                    month = 'Outubro';
                }
                when 11 {
                    month = 'Novembro';
                }
                when 12 {
                    month = 'Dezembro';
                }
                when else {
                    month = '';
                }
            }

            if (!String.isBlank(month)) {
                invoiceHistory.Name = month +'/'+ year;

            } else {
                invoiceHistory.Name = 'Indefinido';
            }
            
            invoiceHistory.CreationDate__c      = getFormatedDate(result.creation_date);
            invoiceHistory.StartDate__c         = getFormatedDate(result.start_date);
            invoiceHistory.EndDate__c           = getFormatedDate(result.end_date);
            invoiceHistory.DueDate__c           = getFormatedDate(result.due_date);
            invoiceHistory.PaymentDate__c       = getFormatedDate(result.payment_date);
            invoiceHistory.NextInvoiceDate__c   = getFormatedDate(result.next_invoice_date);
            
            invoiceHistory.TotalAmount__c = decimal.valueOf(result.Total_amount.value);   
            invoiceHistory.TaxInclude__c = result.Total_amount.tax_included;
            invoiceHistory.PaymentStatus__c = result.payment_status;
            invoiceHistory.Downloadurl__c = result.download_url;

            if (result.secondary_download_urls != null && !result.secondary_download_urls.isEmpty()) {
                invoiceHistory.SecondaryDownloadUrl__c = result.secondary_download_urls[0].url;
                invoiceHistory.InvoiceContestedStatus__c = true;
            }
            
            ltInvoiceHistory.add(invoiceHistory);

            for(String identifier : result.identifiers){
                identifier = identifier.contains('+55') ? identifier.substring(3, identifier.length()) : identifier; 
            }

            mapProductsForBillingAccount.put(String.join(result.identifiers,','), result.account_id);
        }
        
        ltAssetObj = AssetDAO.getByAccountId(accountId);
                
        List<Account> billingAccounts = new List<Account>();
        Set<String> validateName = new Set<String>();
        
        for(Asset assetObj : ltAssetObj){

            for(String keyValue : mapProductsForBillingAccount.keySet()){

                if(keyValue.contains(assetObj.Name)){
                    String billingAccount = mapProductsForBillingAccount.get(keyValue);

                    if(validateName.contains(billingAccount)){
                        continue;
                    }

                    billingAccounts.add(createBillingAccount(
                        billingAccount,
                        'Billing',
                        accountId
                    ));                   

                    validateName.add(billingAccount);
                }
            }
        }

        Map<String,Id> mapIdBillingAccountForName = new Map<String,Id>();
        
        for(Account billingAccountObj : billingAccounts){
            mapIdBillingAccountForName.put(billingAccountObj.Name, billingAccountObj.Id);
        }

        for(Asset assetObj : ltAssetObj){

            for(String keyValue : mapProductsForBillingAccount.keySet()){

                if(keyValue.contains(assetObj.Name)){
                    String name = mapProductsForBillingAccount.get(keyValue);                    
                    assetObj.Name = mapIdBillingAccountForName.get(name);
                }
            }
        }
        
        if(ltInvoiceHistory.size() > 0){
            upsert ltInvoiceHistory InvoiceId__c;
            
            Map<String, Id> mapInvoiceExternalId = new Map<String, Id>();
            
            for(Invoice__c item : ltInvoiceHistory){
                mapInvoiceExternalId.put(item.InvoiceId__c, item.Id);
            }
            
            List<InvoiceItem__c> ltInvoiceItemDelete = new List<InvoiceItem__c>([SELECT Id FROM InvoiceItem__c WHERE Invoice__c IN :mapInvoiceExternalId.values()]);
            
            if(ltInvoiceItemDelete.size() > 0){
                delete ltInvoiceItemDelete;
            }

            for(InvoiceServiceReturn result : lstInvoiceReturn){
                if(mapInvoiceExternalId.containsKey(result.id)){
                    for(InvoiceServiceReturn.billed_items_summary item : result.billed_items_summary){
                        if ((item.parent_id =='1000' || item.parent_id =='-1000') &&
                            (item.description.contains('TV') || item.description.contains('Fixo') || 
                                item.description.contains('Internet') || item.description.contains('Celular')))
                        { 
                            InvoiceItem__c invoiceItemSumary = new InvoiceItem__c();
                            invoiceItemSumary.Invoice__c = mapInvoiceExternalId.get(result.id); //invoiceHistory.id;                                            
                            invoiceItemSumary.ParentId__c = item.parent_id;                            
                            invoiceItemSumary.Value__c = item.amount.value;
                            invoiceItemSumary.TaxInclude__c = item.amount.tax_included;
                            
                            if(item.description.contains('Fixo')){
                                invoiceItemSumary.Type__c = 'Fixa';
                            } else{
                                invoiceItemSumary.Type__c = item.description;
                            }                                
                            
                            invoiceItemSumary.StartDate__c  = getFormatedDate(item.start_date);
                            invoiceItemSumary.EndDate__c    = getFormatedDate(item.end_date);
                                                        
                            invoiceItemSumary.Identifier__c = item.identifier;
                            
                            ltInvoiceItem.add(invoiceItemSumary);
                        }
                    }
                }
            }                
            
            if(ltInvoiceItem.size() > 0){
                insert ltInvoiceItem;
            }
        }
		
        updateCustomerInteractionIdInvoice(accountId, customerInteractionId);
        
        return ltAssetObj;
    }
    
    private static Account createBillingAccount(String name, String recordTypeName, Id accountId) { 
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(recordTypeName).getrecordTypeId();
        return new Account(Id = accountId, Name = name, recordTypeId = recordTypeId);
    }
    
    public static Date getFormatedDate(String stringDate){
        if(stringDate != null && stringDate.contains('T')){
            return Date.valueOf(stringDate.replaceAll('T',' '));
        } else {
            return null;
        }
    }

    public static Integer getValidateTime(Webservice__c wsConfig){
        return Integer.valueOf(wsConfig.Validate__c);
    }
    
    @AuraEnabled
    public static InvoiceHistoryTO.InformationMessageTO getMessage(Id accountId){        
        InvoiceHistoryTO.InformationMessageTO returnTO = new InvoiceHistoryTO.InformationMessageTO();
        returnTO.lstMessage = new List<String>();

        Boolean hasAtlys = false;
        Boolean hasNext = false;
        
        // Consulta para verificar qual sistema de origem do Cliente
        
        List<Asset> ltsearchLegacySystem = new List<Asset>();
        ltsearchLegacySystem = [SELECT Id, LegacySystem__c FROM Asset WHERE AccountId =: accountId];
        
        // Consulta para verificar qual status de pagamento tem nas faturas do cliente
        
        List<Invoice__c> ltsearchInvoices = new List<Invoice__c>();
        ltsearchInvoices = [SELECT ID,PaymentStatus__c, MobileRollup__c, FixedAmount__c, DueDate__c FROM Invoice__c WHERE AccountId__c =: accountId ];
        
        // Consulta para verificar os meses correspondentes as faturas móveis
        
        List<AggregateResult> ltMonthInvoice = new List<AggregateResult>();
        ltMonthInvoice = [SELECT CALENDAR_MONTH(DueDate__c) FROM Invoice__c WHERE AccountId__c =: accountId AND  MobileRollup__c != 0 GROUP BY CALENDAR_MONTH(DueDate__c)];
        
        
        Decimal sunValuesMobile = 0;
        Decimal sunValuesFixed = 0;
        Set<Integer> fixedMonths = new Set<Integer>();
        Set<Integer> mobileMonths = new Set<Integer>();

        for(Invoice__c invoiceObj :ltsearchInvoices){
            
            if(invoiceObj.MobileRollup__c != null){
                sunValuesMobile += invoiceObj.MobileRollup__c;
                mobileMonths.add(invoiceObj.DueDate__c.month());
            }

            if(invoiceObj.FixedAmount__c != null){
                sunValuesFixed += invoiceObj.FixedAmount__c;
                fixedMonths.add(invoiceObj.DueDate__c.month());
            }
        } 

        returnTO.FixedAverage = sunValuesFixed != 0 && fixedMonths.size() != 0 ? (sunValuesFixed/fixedMonths.size()) : 0;
        returnTO.MovingAverage = sunValuesMobile != 0 && mobileMonths.size() != 0 ? (sunValuesMobile/mobileMonths.size()) : 0;
        
        // lógica para verificar se o sistema de origem do produto do cliente possui ou Atlys ou Next
        for(Asset item: ltsearchLegacySystem){
            if(item.LegacySystem__c != null && !String.IsBlank(item.LegacySystem__c)){
                if((item.LegacySystem__c.contains('ATLYS'))){
                    hasAtlys = true;
                } else if((item.LegacySystem__c.contains('NEXT'))){
                    hasNext = true;
                }
            }
        }
              
        /* 
            1)  Se for ATLYS e não tiver nenhuma fatura: 
			Para consulta de faturas deste cliente acessar o Vivo 360 
		*/
        
        if(((hasAtlys == true) && (hasNext == false)) && (ltMonthInvoice.size() <= 0))  {
            returnTO.lstMessage.add(Label.SystemOrigemWithoutInvoice);
        } 
        
        /* 
            2) Se for ATLYS e estiver entre 1 mês e 6 meses na exibição das faturas da móvel:
			Para a consulta do histórico com visão dos últimos 6 meses, consultar o Vivo 360
        */
        
        else if(((hasAtlys == true) && (hasNext == false)) && ((ltMonthInvoice.size() >= 1) && (ltMonthInvoice.size() < 6)) ){
            returnTO.lstMessage.add(Label.SystemOrigemWithInvoice);
        } 
        /*
         	3) Se for ATLYS e estiver em um dos dois cenários acima e ter sistemas de origem diferentes em suas contas faturamento (Ex. Uma conta faturamento no 360 e outra no Next), deve-se mostrar a mensagem: 
			Algumas faturas Móvel deste cliente não migraram para o NEXT. Para consulta de histórico acessar o Vivo 360
         */
        else if(((hasAtlys == true) && (hasNext == true)) && ((ltMonthInvoice.size() >= 1) && (ltMonthInvoice.size() < 6)) ){
            returnTO.lstMessage.add(Label.SystemOrigemAtlysNext);
        } 
        
        /* 
         	Regra para status da Fatura como não pago.
            1)  Mensagem de atualização sistêmica do status de fatura será exibida para toda e qualquer fatura com status "Não pago": 
            A atualização sistêmica do ''Status da Fatura'' ocorre em até 26h

		*/

        for(Invoice__c item : ltsearchInvoices){
            if(item.PaymentStatus__c == 'Unpaid'){
                returnTO.lstMessage.add(Label.StatusInvoiceMessage);
                break;
            } 
        }
        
        return returnTO;
    }

    //Solução adotada para quebrar o contexto do retorno da invoice e atualizar os asset´s
    @AuraEnabled
    public static void updateAssetList(List<Asset> lstAssetObj){
        if(lstAssetObj != null && !lstAssetObj.isEmpty()){
            update lstAssetObj;
        }
    }
    
    // Solução adotada para receber o recordId do objeto Protocolo e retornar o Id da conta relacionada a ele.
    public static Id getAccountIdFromCustomerInteraction(Id recordId) {
        List<vlocity_cmt__CustomerInteraction__c> customerInteraction = [SELECT vlocity_cmt__AccountId__c FROM vlocity_cmt__CustomerInteraction__c WHERE Id =: recordId LIMIT 1];
        return customerInteraction.isEmpty() ? null : customerInteraction[0].vlocity_cmt__AccountId__c;        
    }

    // Atualizar campos CustomerInteractionId nos invoices para que o relatório de faturamento possa funcionar corretamente
    private static void updateCustomerInteractionIdInvoice(Id accountId, Id customerInteractionId) {
         List<Invoice__c> listInvoice = [SELECT Id FROM Invoice__c WHERE AccountId__c = :accountId];
         for(Invoice__c invoice : listInvoice) {
            invoice.CustomerInteraction__c = customerInteractionId;
         }
         update listInvoice;
    }    
}