force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Util.cls
/*
* @author Diego Costa @ Deloitte
* @date 06/06/2022
* @description classe Util 
*/
public with sharing class Util {
    
    public static Boolean validateUserIdInformation(Id accountId){
        Account accountObj = AccountDAO.getByIds(accountId);
        return (accountObj != null && accountObj.UserId__c != null);
    }

    public static Webservice__c getWebService(String webServiceName){
        Webservice__c wsConfig = new Webservice__c();
        wsConfig = Webservice__c.getInstance(webServiceName);

        //valida se encontrou
        if(wsConfig == null){
            throw new AuraHandledException('Nenhum webservice encontrado com o nome: ' + webServiceName);
        }

        //Valida se está ligado.
        if(!wsConfig.switchedOn__c){
            throw new AuraHandledException('Webservice está desativado, acesse a configuração do mesmo, caso queira usa-lo');
        }

        return wsConfig;
    }

    public static String getNumbers(String stringValue){

        Pattern objPattern = Pattern.compile('([0-9]+)');
        Matcher objMatcher = objPattern.matcher(stringValue);

        return objMatcher.find() ? objMatcher.group(1) : '';
    }

    public static String getEnvironmentName() {
        String baseUrl = URL.getOrgDomainURL().toExternalForm();
        
        return baseUrl.contains('--')
            ? '.' + baseUrl.substringAfterLast('--').substringBefore('.') 
            : '';
    }


}