force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo fixo</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/AccountJob__c.field-meta.xml
<CustomField>
    <fullName>AccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar contas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AccountLoadDate__c</fullName>
    <label>Data da carga - Account</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressJob__c.field-meta.xml
<CustomField>
    <fullName>AddressJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar endereços</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AddressLoadDate__c</fullName>
    <label>Data de carga - Endereço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetJob__c.field-meta.xml
<CustomField>
    <fullName>AssetJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Assets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AssetLoadDate__c</fullName>
    <label>Data da carga - Asset</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountJob__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar conta de faturamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountLoadDate__c</fullName>
    <label>Data da carga - Conta de faturamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceJob__c.field-meta.xml
<CustomField>
    <fullName>InvoiceJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Faturas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceLoadDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLoadDate__c</fullName>
    <label>Data da carga - Faturas</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/SearchRange__c.field-meta.xml
<CustomField>
    <fullName>SearchRange__c</fullName>
    <label>Intervalo de pesquisa</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/SearchRangeInvoice__c.field-meta.xml
<CustomField>
    <fullName>SearchRangeInvoice__c</fullName>
    <label>Intervalo de Pesquisa Faturas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/ServiceHistoryExpiration__c.field-meta.xml
<CustomField>
    <fullName>ServiceHistoryExpiration__c</fullName>
    <label>Expiração do histórico de atendimento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/TotalNumberRecords__c.field-meta.xml
<CustomField>
    <fullName>TotalNumberRecords__c</fullName>
    <label>Número Total de Registros</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Objeto de faturas destinado a armazenar as informações históricas do cliente.</description>
    <label>Faturamento</label>
    <nameField>
        <label>Mês de Referência</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <label>Validade dos dados da consulta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoiceHistoryControllerTest.cls
/*
* @authors - Diego Costa @Deloitte   
* @date - 07/06/2022
* @description - Classe de teste da Controller InvoiceHistoryController
*/
@isTest
public class InvoiceHistoryControllerTest {
    
    @testSetup 
    static void setup(){
        
        string type = 'Fixa';

        Account lAccount = DataFactory.createAccount();
        insert lAccount;        
        
        Asset lAsset = DataFactory.createAsset(lAccount.Id, type );
        insert lAsset;
        
        vlocity_cmt__CustomerInteraction__c customerInteraction = DataFactory.createCustomerInteraction(lAccount.Id);
        insert customerInteraction;
        
        insert new GeneralParam__c(
            AccountLoadDate__c  = Datetime.now().addDays(-1),
            AssetLoadDate__c = Datetime.now().addDays(-1),
            BillingAccountLoadDate__c = Datetime.now().addDays(-1),
            InvoiceLoadDate__c = Datetime.now().addDays(-1),
            AddressLoadDate__c = Datetime.now().addDays(-1),
            AssetJob__c = true,
            BillingAccountJob__c = true,
            AccountJob__c = true,
            AddressJob__c = true,
            InvoiceJob__c = true,
            SearchRange__c = 90,
            SearchRangeInvoice__c = 1800,
            TotalNumberRecords__c = 100,
            ServiceHistoryExpiration__c = 0
        );

        insert new Webservice__c(
            Name = 'FourthPlataformInvoiceCallout',
            Validate__c = 1800,
            Endpoint__c  = 'https://hmlapi.telefonicabigdata.com',
            SubscriptionKey__c = 'd1ca8d57a2984db88f01c9ce7b5862e2'
        );
        
        WebServiceTestFactory.start().authOAuthProvider().create();
    }

    @isTest
    public static void validateUserIdInformation() {
        Account ltAccount = [SELECT Id,UserId__c FROM Account LIMIT 1];
        
        ltAccount.UserId__c = 'userid';

        update ltAccount;
        
        vlocity_cmt__CustomerInteraction__c customerInteraction = [SELECT Id, vlocity_cmt__AccountId__c FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];
        
        Boolean existUserId = InvoiceHistoryController.validateUserIdInformation(customerInteraction.Id);
        System.assertEquals(true, existUserId);
    }

    @isTest
    public static void getInvoiceHistory(){
        Account lAccount = [ SELECT Id,UserId__c FROM Account LIMIT 1];
        lAccount.UserId__c = 'userid';
        update lAccount;

        InvoiceHistoryController serviceController = new InvoiceHistoryController();
        Boolean hasRecord = InvoiceHistoryController.getInvoiceHistory(lAccount.Id);

        Invoice__c serviceHistory = DataFactory.createInvoiceHistory(lAccount.Id);
        insert serviceHistory;

        hasrecord = InvoiceHistoryController.getInvoiceHistory(lAccount.Id);

        System.assertEquals(true, hasRecord);


    }

    @isTest
    public static void createInvoiceHistory(){
        Account lAccount = [ SELECT Id,UserId__c FROM Account LIMIT 1];
		lAccount.UserId__c = 'userid';
        update lAccount;
        
        vlocity_cmt__CustomerInteraction__c customerInteraction = [SELECT Id, vlocity_cmt__AccountId__c FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];
                
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceCalloutMock());

        InvoiceHistoryController.createInvoiceHistory(customerInteraction.Id);
        Test.stopTest();
    }

    @isTest
    public static void createInvoiceHistoryWithInvalidStatusCode(){
        Account lAccount = [ SELECT Id,UserId__c FROM Account LIMIT 1];
		
        lAccount.UserId__c = 'userid';
        
        update lAccount;
        System.debug('Account: ' + lAccount);
        vlocity_cmt__CustomerInteraction__c customerInteraction = [SELECT Id, vlocity_cmt__AccountId__c FROM vlocity_cmt__CustomerInteraction__c LIMIT 1];
        
        System.debug('customerInteraction: ' + customerInteraction);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceCalloutMock(500));

        InvoiceHistoryController.createInvoiceHistory(customerInteraction.Id);        
        
        Test.stopTest();
    }
    
    @isTest
    public static void createInvoiceHistoryWebServiceWhenNull() {
        Webservice__c wsConfig = Webservice__c.getInstance('FourthPlataformInvoiceCallout');
        Account lAccount = [ SELECT Id,UserId__c FROM Account LIMIT 1];
		
        delete wsConfig;

        lAccount.UserId__c = 'userid';
        
        update lAccount;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceCalloutMock());

        InvoiceHistoryController.createInvoiceHistory(lAccount.Id);
        
        Test.stopTest();
    }

    @isTest
    public static void getMessage(){
        Account lAccount = [ SELECT Id,UserId__c FROM Account LIMIT 1];
		lAccount.UserId__c = 'userid';
        update lAccount;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceCalloutMock());

        InvoiceHistoryController.getMessage(lAccount.Id);
        Test.stopTest();
    }

    @isTest
    public static void getFormatedDate() {
        String dateToValidate = '2020-08-20T03:00:00Z';
        Date returnDate = Date.valueOf(dateToValidate.replaceAll('T',' '));

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceCalloutMock());

        Date validDate = InvoiceHistoryController.getFormatedDate(dateToValidate);
        Date invalidateDate = InvoiceHistoryController.getFormatedDate(null);

        Test.stopTest();

        System.assertEquals(returnDate, validDate);
        System.assertEquals(null, invalidateDate);
    }

    @isTest
    public static void getValidateTime() {
        Webservice__c ws = [SELECT Id, Name, Validate__c, Endpoint__c FROM Webservice__c LIMIT 1];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceCalloutMock());

        Integer validValidate = InvoiceHistoryController.getValidateTime(ws);

        Test.stopTest();

        System.assertEquals(1800, validValidate);
    }
}