force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/SearchRange__c.field-meta.xml
<CustomField>
    <fullName>SearchRange__c</fullName>
    <label>Intervalo de pesquisa</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/TotalNumberRecords__c.field-meta.xml
<CustomField>
    <fullName>TotalNumberRecords__c</fullName>
    <label>Número Total de Registros</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Custom object para Bilhetes de Defeito</description>
    <label>Bilhete de Defeitos</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Detalhamento BDs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bilhete de Defeitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bilhetes de Defeito</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/OpeningDate__c.field-meta.xml
<CustomField>
    <fullName>OpeningDate__c</fullName>
    <label>Data da Abertura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Motivo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/SolutionDate__c.field-meta.xml
<CustomField>
    <fullName>SolutionDate__c</fullName>
    <description>Campo de recebimento de data de solução/fechamento</description>
    <label>Data de Fechamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <label>Atribuido</label>
            </value>
            <value>
                <fullName>DELAYED</fullName>
                <label>Atrasado</label>
            </value>
            <value>
                <fullName>CLOSED</fullName>
                <label>Fechado</label>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketId__c.field-meta.xml
<CustomField>
    <fullName>TicketId__c</fullName>
    <description>Campo de identificação externa para o Id dos tickets abertos.</description>
    <externalId>true</externalId>
    <label>Ticket ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TicketHistoryController.cls
public without sharing class TicketHistoryController {
    private static final String WEBSERVICE_NAME = 'FourthPlataformTicketServiceCallout';

    @AuraEnabled
    public static Boolean validateUserIdInformation(Id accountId){
        Account accountObj = AccountDAO.getByIds(accountId);
        return (accountObj != null && accountObj.UserId__c != null);
    }
    
    @AuraEnabled
    public static Boolean getTicketHistory(Id accountId){
        List<Ticket__c> lstTicketHistory = new List<Ticket__c>();
        lstTicketHistory = TicketDAO.getByAccountId(accountId);
        return lstTicketHistory.isEmpty() ? true : false;       
    }

    @AuraEnabled
    public static String createTicketHistory(Id accountId){
        Webservice__c wsConfig = Webservice__c.getInstance(WEBSERVICE_NAME);

        if (wsConfig == null || !wsConfig.switchedOn__c) {
            return 'CustomerPlataformaDigitalCallout: Webservice not found.';
        }

        List<Ticket__c> lstTicketHistory = new List<Ticket__c>();
        List<GeneralParam__c> lstGeneralParams = new List<GeneralParam__c>();
        lstGeneralParams = GeneralParamDAO.getLoadParams();
        
        Integer searchRange = Integer.valueOf(lstGeneralParams[0].SearchRange__c) *-1;
        Integer totalNumberRecords = Integer.valueOf(lstGeneralParams[0].TotalNumberRecords__c);
 
        DateTime startDate = System.now().addDays(searchRange);
        DateTime endDate = System.now();
        Account accountObj = AccountDAO.getByIds(accountId);

        String parameters = accountObj.UserId__c + '/ticket?type=issue&start_date=' +startDate.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'') + '&end_date=' + endDate.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'') +'&number_tickets=' +50;
        String endpoint = wsConfig.Endpoint__c + parameters;
        
        List<TicketServiceReturn.TicketResponse> lstTicketReturn = new List<TicketServiceReturn.TicketResponse>();

        HttpClient client = new HttpClient();
        HttpResponse response = client.get(wsConfig, endpoint);
        ServiceResponse serviceResponse = new ServiceResponse();

        if (response.getStatusCode()/100 == 2) {
            String result = response.getBody();
            serviceResponse.body = result;
            serviceResponse.success = true;
        } else {
            serviceResponse.success = false;
        }
        
        if (serviceResponse.success) {
            lstTicketReturn = (List<TicketServiceReturn.TicketResponse>)Json.deserialize(serviceResponse.body, List<TicketServiceReturn.TicketResponse>.class);
        }
                
        if(!lstTicketReturn.isEmpty()){
            for(TicketServiceReturn.TicketResponse ticketResponse : lstTicketReturn){

                Ticket__c ticketObj = new Ticket__c();
                
                ticketObj.AccountId__c = accountId;
                ticketObj.TicketId__c = ticketResponse.ticket_id;                
                if(!String.isBlank(ticketResponse.start_date)){
                ticketObj.OpeningDate__c = Date.valueOf(ticketResponse.start_date);
                }
                
                if(!String.isBlank(ticketResponse.end_date)){
                    ticketObj.SolutionDate__c = Date.valueOf(ticketResponse.end_date);
                }
     
                ticketObj.Status__c = ticketResponse.status;
                ticketObj.Reason__c = ticketResponse.reason;

                lstTicketHistory.add(ticketObj);
            }
        }

        upsert lstTicketHistory TicketId__c;
        return 'sucesso'; //String.valueOf(serviceResponse.success);
    }
}