force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Case/fields/Closure__c.field-meta.xml
<CustomField>
    <fullName>Closure__c</fullName>
    <label>Fechamento</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Contexto</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DestinyCell__c.field-meta.xml
<CustomField>
    <fullName>DestinyCell__c</fullName>
    <label>Célula Destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OriginCell__c.field-meta.xml
<CustomField>
    <fullName>OriginCell__c</fullName>
    <label>Célula Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceRequestId__c.field-meta.xml
<CustomField>
    <fullName>ServiceRequestId__c</fullName>
    <label>Número da SS</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceRequestStatus__c.field-meta.xml
<CustomField>
    <fullName>ServiceRequestStatus__c</fullName>
    <label>Status da SS</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/GPSCanvasInterface__e.object-meta.xml
<CustomObject>
    <description>Evento utilizado para comunicação entre GPS e Salesforce.</description>
    <label>GPSCanvasInterface</label>
    <pluralLabel>GPSCanvasInterfaces</pluralLabel>
</CustomObject>

force-app/main/default/objects/GPSCanvasInterface__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Identificador da conta do cliente.</description>
    <label>AccountId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <description>Identificador do caso no salesforce.</description>
    <label>CaseId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/Closure__c.field-meta.xml
<CustomField>
    <fullName>Closure__c</fullName>
    <description>Descrição do fechamento do caso.</description>
    <label>Closure</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Contexto da ligação.</description>
    <label>Context</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrição</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/DestinyCell__c.field-meta.xml
<CustomField>
    <fullName>DestinyCell__c</fullName>
    <description>Célula de destino da ligação.</description>
    <label>DestinyCell</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/Observation__c.field-meta.xml
<CustomField>
    <fullName>Observation__c</fullName>
    <description>Campo de observações para carimbos.</description>
    <label>Observation</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/OperationType__c.field-meta.xml
<CustomField>
    <fullName>OperationType__c</fullName>
    <description>Define a regra de negócio a ser executada.</description>
    <label>OperationType</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/OriginCell__c.field-meta.xml
<CustomField>
    <fullName>OriginCell__c</fullName>
    <description>Célula de origem do atendimento.</description>
    <label>OriginCell</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Número de protocolo gerado para o atendimento.</description>
    <label>Protocol</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/ServiceRequestId__c.field-meta.xml
<CustomField>
    <fullName>ServiceRequestId__c</fullName>
    <description>Identificador da solicitação de serviço criada para o atendimento em questão.</description>
    <label>ServiceRequestId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/ServiceRequestStatus__c.field-meta.xml
<CustomField>
    <fullName>ServiceRequestStatus__c</fullName>
    <description>Identificador da solicitação de serviço criada para o atendimento.</description>
    <label>ServiceRequestStatus</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPSCanvasInterface__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do usuário logado no salesforce.</description>
    <label>UserId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GPSCanvasInterfaceTriggerTest.cls
@isTest
public class GPSCanvasInterfaceTriggerTest {
	@testSetup 
    static void setup() {
		Account nuAcc = new Account();	
		nuAcc.Name = 'NuAcc';
		insert nuAcc;

        Case nuCase = new Case();
        nuCase.AccountId = nuAcc.Id;
		nuCase.Origin = 'URA';
        insert nuCase;
	}
    
    
	static testMethod void testTrigger() {
         Case nuCase = [Select id FROM Case Limit 1];
    		Test.startTest();
         		GPSCanvasInterface__e event = new GPSCanvasInterface__e();
         		event.CaseId__c = nuCase.Id;
        		event.AccountId__c = 'Teste';
        		event.Closure__c = 'Teste';
        		event.Context__c = 'Teste';
        		event.Description__c = 'Teste';
        		event.DestinyCell__c = 'Teste';
        		event.Observation__c = 'Teste';
        		event.OperationType__c = 'Teste';
        		event.OriginCell__c = 'Teste';
        		event.Protocol__c = 'Teste';
        		event.ServiceRequestId__c = 'Teste';
        		event.ServiceRequestStatus__c = 'Teste';
        		event.UserId__c = 'Teste';
        
        		Database.SaveResult sr = EventBus.publish(event);
                if(sr.getErrors() != null){
                	for(Database.Error err : sr.getErrors()) {
            			System.debug('Error returned: ' +
                         err.getStatusCode() +
                         ' - ' +
                         err.getMessage());   
                }
         	Test.stopTest();
     }
    }
}