force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Custom object para Bilhetes de Defeito</description>
    <label>Bilhete de Defeitos</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Detalhamento BDs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bilhete de Defeitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <label>Atribuido</label>
            </value>
            <value>
                <fullName>DELAYED</fullName>
                <label>Atrasado</label>
            </value>
            <value>
                <fullName>CLOSED</fullName>
                <label>Fechado</label>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketId__c.field-meta.xml
<CustomField>
    <fullName>TicketId__c</fullName>
    <description>Campo de identificação externa para o Id dos tickets abertos.</description>
    <externalId>true</externalId>
    <label>Ticket ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TicketPrevisionDateControllerTest.cls
@isTest
public class TicketPrevisionDateControllerTest {

    @TestSetup
    static void setup(){

        Account lAccount = DataFactory.createAccount();
        lAccount.userid__c = 'userId';
        insert lAccount;

        Ticket__c lTicket = DataFactory.createTicketHistory(lAccount.Id);  
        lTicket.Status__c = 'OPEN';
        lticket.TicketId__c = '8-A89554267D-1';
        system.debug(lTicket);
        insert lTicket;
        
        insert new Webservice__c(
            Name = 'WFMSearchByWorkOrderCallout',
            Endpoint__c  = 'https://api-hml.telefonica.com.br/search-by-workorder/v1',
            SubscriptionKey__c = '36cfd2713668489bb3f7d23d042be3a3',
            switchedOn__c = true
        );
        
        WebServiceTestFactory.start().authOAuthProvider().create();
        
    }

    @isTest
    static void getTicketPrevisionDateTrue(){
        Ticket__c lTicket = [ SELECT Id FROM Ticket__c LIMIT 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TicketPrevisionDateCalloutMock());
        String response = TicketPrevisionDateController.getTicketPrevisionDate(lTicket.Id);
        System.assertEquals('200', response);
        Test.stopTest();        
    }
    
    @isTest
    static void getTicketPrevisionDateWsConfigOff(){
        Ticket__c lTicket = [ SELECT Id FROM Ticket__c LIMIT 1];
        
        Webservice__c web = [ SELECT Id, switchedOn__c FROM Webservice__c limit 1];
        
        web.switchedOn__c = false;
        update web;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TicketPrevisionDateCalloutMock());
        String response = TicketPrevisionDateController.getTicketPrevisionDate(lTicket.Id);
        System.assertEquals('', response);
        Test.stopTest();
    }
    
    @isTest
    static void getTicketPrevisionDateTicketNull(){
        Ticket__c lTicket = [ SELECT Id FROM Ticket__c LIMIT 1];
        
        lTicket.TicketId__c = null;
        update lTicket;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TicketPrevisionDateCalloutMock());
        String response = TicketPrevisionDateController.getTicketPrevisionDate(lTicket.Id);
        System.assertEquals('', response);
        Test.stopTest();
    }

}