force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Identificador do cliente na 4P.</description>
    <label>User Id</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/CartAccount__c.object-meta.xml
<CustomObject>
    <description>Armazena registros de ofertas aceitas e estatísticas de acesso aos registros de Account.</description>
    <label>Oferta Oferecida</label>
    <nameField>
        <displayFormat>OF-{00000000}</displayFormat>
        <label>Id Oferta Oferecida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Oferecidas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CartAccount__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <description>Campo para salvar se oferta NBA/NBO  foi aceita ou se o script foi aceito.</description>
    <label>Aceite</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
                <label>Aceitou</label>
            </value>
            <value>
                <fullName>NotAccepted</fullName>
                <label>Não aceitou</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento com a Conta em que foi executada a ação.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ofertas Oferecidas</relationshipLabel>
    <relationshipName>CartAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/OfferType__c.field-meta.xml
<CustomField>
    <fullName>OfferType__c</fullName>
    <description>Campo para salvar o tipo da oferta selecionado pelo usuário.</description>
    <label>Tipo Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TechnologyMigration</fullName>
            </value>
            <value>
                <fullName>Speed​​Upgrade</fullName>
            </value>
            <value>
                <fullName>RPA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Campo para armazenar a mensagem de retorno do RPA.</description>
    <label>Motivo</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/ReasonNotAccepted__c.field-meta.xml
<CustomField>
    <fullName>ReasonNotAccepted__c</fullName>
    <description>Campo para operador informar o motivo pelo não aceite da contratação do plano Móvel.</description>
    <label>Motivo não aceite</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OfferType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Cliente corporativo</fullName>
            </value>
            <value>
                <fullName>Cliente Não Aceitou Ouvir a Ofertas</fullName>
            </value>
            <value>
                <fullName>Cliente Recusou - Fidelizado na concorrência</fullName>
            </value>
            <value>
                <fullName>Cliente Recusou - Motivo Financeiro</fullName>
            </value>
            <value>
                <fullName>Cliente Sem Interesse</fullName>
            </value>
            <value>
                <fullName>Ficou de Pensar - Controle</fullName>
            </value>
            <value>
                <fullName>Ficou de Pensar – Pós</fullName>
            </value>
            <value>
                <fullName>Não Ofertado Fidelizado na concorrência</fullName>
            </value>
            <value>
                <fullName>Recusou - Prefere pré-pago</fullName>
            </value>
            <value>
                <fullName>Aceitou outra oferta</fullName>
            </value>
            <value>
                <fullName>Preço - achou caro</fullName>
            </value>
            <value>
                <fullName>Não quis ouvir a oferta</fullName>
            </value>
            <value>
                <fullName>Não é responsável pela decisão</fullName>
            </value>
            <value>
                <fullName>Prefere comprar em outro canal</fullName>
            </value>
            <value>
                <fullName>Está satisfeito com a velocidade atual</fullName>
            </value>
            <value>
                <fullName>Quer pensar melhor sobre a oferta</fullName>
            </value>
            <value>
                <fullName>Erro: sem disponibilidade Fibra</fullName>
            </value>
            <value>
                <fullName>Não vê benefício na oferta</fullName>
            </value>
            <value>
                <fullName>Não quer receber visita técnica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Preço total da proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/recordTypes/NextBestOfferAndAction.recordType-meta.xml
<RecordType>
    <fullName>NextBestOfferAndAction</fullName>
    <active>true</active>
    <description>Ações Recomendadas</description>
    <label>Ações Recomendadas</label>
</RecordType>

force-app/main/default/objects/FromToMapping__mdt/FromToMapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata genérico para ser utilizado para inclusão de de/para que serão utilizados na Org.</description>
    <label>Mapeamento DePara</label>
    <pluralLabel>Mapeamento DePara</pluralLabel>
</CustomObject>

force-app/main/default/objects/FromToMapping__mdt/fields/DestinyName__c.field-meta.xml
<CustomField>
    <fullName>DestinyName__c</fullName>
    <description>Nome do campo desejado destino</description>
    <label>Nome do campo destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FromToMapping__mdt/fields/OriginApiName__c.field-meta.xml
<CustomField>
    <fullName>OriginApiName__c</fullName>
    <description>ApiName do campo desejado origem</description>
    <label>ApiName do campo Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NextBestOfferAndAction__c/NextBestOfferAndAction__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Cadastro de De Para de Motivo não aceite de Ações Recomendadas NBA/NBO.</description>
    <label>Ações Recomendadas DePara</label>
</CustomObject>

force-app/main/default/objects/NextBestOfferAndAction__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Motivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NextBestOfferAndAction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PartnerGroup__c.field-meta.xml
<CustomField>
    <fullName>PartnerGroup__c</fullName>
    <label>Grupo do Aliado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VendasAliado</fullName>
                <label>Vendas Aliado</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPConsultor</fullName>
                <label>Vendas Aliado PaP Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPGerente</fullName>
                <label>Vendas Aliado PaP Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaConsultor</fullName>
                <label>Vendas Aliado Revenda Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaGerente</fullName>
                <label>Vendas Aliado Revenda Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasGerente</fullName>
                <label>Vendas Aliado Televendas Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPSupervisor</fullName>
                <label>Vendas Aliado PaP Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasCoordenador</fullName>
                <label>Vendas Aliado Televendas Coordenador</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasSupervisor</fullName>
                <label>Vendas Aliado Televendas Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasConsultor</fullName>
                <label>Vendas Aliado Televendas Consultor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeOperador</fullName>
                <label>Atendimento Aliado Backoffice Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoOp</fullName>
                <label>Atendimento Aliado Backoffice Retencao Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoSup</fullName>
                <label>Atendimento Aliado Backoffice Retencao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeSupervisor</fullName>
                <label>Atendimento Aliado Backoffice Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Ativo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Ativo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaOperador</fullName>
                <label>Atendimento Aliado Ouvidoria Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaSupervisor</fullName>
                <label>Atendimento Aliado Ouvidoria Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingOp</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingSup</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Supervisor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CarouselCardOfferEngine.cls
/* 
    Histórias:
    B2C7551-1195 NBA/NBO Sales Cloud - Fase I - https://wikicorp.telefonica.com.br/pages/viewpage.action?pageId=170658664
    B2C7551-2186 Aceite ou Recusa da oferta - https://wikicorp.telefonica.com.br/display/PTI/B2C7551-2186+Aceite+ou+Recusa+da+oferta
*/

public with sharing class CarouselCardOfferEngine {
    private static final String CONST_WEB_SERVICE_RTD = 'RtdNbaNboServiceCallout';
    private static final String CONST_WITHOUT_FROM_TO_MAPPING = 'withoutFromToMapping';
    private static final String CONST_NO_CARD_OFFER = 'noCardOffer';
    private static final Integer CONST_SUCCESS_CODE = 200;
    private static final String CONST_ACCOUNT_RECORD_TYPE = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Consumer').getrecordTypeId();
    private static final String CONST_CART_ACCOUNT_NBO_NBA_RECORD_TYPE = Schema.SObjectType.CartAccount__c.getRecordTypeInfosByDeveloperName().get('NextBestOfferAndAction').getrecordTypeId();

    public static Boolean checkIfAccountHaveUserId (Id accountId) {        
        Account account = AccountDAO.getByIds(accountId);
        if (account.UserId__c != null) {
            return true;
        } else {
            return false;
        }
    }
    
    public static CardOfferServiceReturn getCardsOffers (Id accountId) {
        CardOfferServiceReturn cardOffers = new CardOfferServiceReturn();

        Webservice__c wsConfig = Webservice__c.getInstance(CONST_WEB_SERVICE_RTD);
        if (wsConfig == null || !wsConfig.switchedOn__c) {
            return cardOffers;
        }

        Account account = AccountDAO.getByIds(accountId);
        if (account == null) {
            return cardOffers;
        }

        User userObj = UserDAO.getUserInfo()[0];
        if (userObj == null) {
            return cardOffers;
        }

        String userChannel = getUserChannel(userObj);
     
         if(String.isEmpty(userChannel)){
            cardOffers.msg = CONST_WITHOUT_FROM_TO_MAPPING;
            return cardOffers;
        }
        
        String responseBody;
        String parameters = account.UserId__c + '/modules?card_types=next-best-offer&container_ids=' + EncodingUtil.urlEncode(userChannel, 'UTF-8');
        String endpoint = wsConfig.Endpoint__c + parameters;
        System.debug('Endpoint:'+ endpoint);
        HttpClient client = new HttpClient();
        HttpResponse response;
        try {
            response = client.get(wsConfig, endpoint);
            responseBody = response.getBody();
            System.debug('ResponseBody:' + responseBody);
        } catch (Exception e) {
            cardOffers.msg = e.getMessage();
            return cardOffers;
        }

        String strLtCardWhenEmpty = '[]';
        CardOfferServiceReturn responseService;
        if (response.getStatusCode() == CONST_SUCCESS_CODE 
                && !responseBody.contains(strLtCardWhenEmpty) 
                && String.isNotEmpty(responseBody)) {
            responseService = CardOfferServiceReturn.parse(response.getBody());        
        } else if (response.getStatusCode() == CONST_SUCCESS_CODE) {
            cardOffers.msg = CONST_NO_CARD_OFFER;
            return cardOffers;
        } else {
            return cardOffers;
        }

        if (responseService == null) {
            cardOffers.msg = CONST_NO_CARD_OFFER;
            return cardOffers;
        } else {
            cardOffers = responseService;
            cardOffers.msg = 'success';
            return cardOffers;
        }
    }

    private static String getUserChannel (User user) {
        String userChannel;
        FromToMapping__mdt mapping;
        Map<String,FromToMapping__mdt> mapFromTo = new Map<String,FromToMapping__mdt>();
        CollectionUtil.loadMap(mapFromTo, 'OriginApiName__c', 
                                FromToMappingDAO.getFromOriginUsedIn('NbaNbo'));
        
        if (user.Profile.UserLicense.Name != 'Partner Community') {
            mapping = mapFromTo.get(user.UserRole.DeveloperName);
            if (mapping != null) {
                userChannel = mapping.DestinyName__c;
            }
        } else {
            mapping = mapFromTo.get(user.PartnerGroup__c);
            if (mapping != null) {
                userChannel = mapping.DestinyName__c;
            }
        }

        return userChannel != null ? userChannel : '';
    }

    public static Boolean postCardOffers (Id accountId, 
                                          CardOfferServiceReturn.Card card, 
                                          String acceptOrNot, 
                                          String reason) {
        Webservice__c wsConfig = Webservice__c.getInstance(CONST_WEB_SERVICE_RTD);
        if (wsConfig == null || !wsConfig.switchedOn__c) {
            return false;
        }

        Account accountCurrent = AccountDAO.getByIds(accountId);
        if (accountCurrent == null) {
            return false;
        }

        String payload = buildPayloadAcceptOrDeny(card, acceptOrNot, reason);
        wsConfig.Endpoint__c = wsConfig.Endpoint__c + accountCurrent.UserId__c + '/cards/feedback';
        HttpClient client = new HttpClient();
        HttpResponse response;
        try {
            response = client.post(wsConfig, payload);
        } catch (Exception e) {
            return false;
        }

        if (response.getStatusCode() == CONST_SUCCESS_CODE) {
            return true;
        } else {
            return false;
        }
    }

    private static String buildPayloadAcceptOrDeny (CardOfferServiceReturn.Card card, 
                                                    String acceptOrNot, 
                                                    String reason) {
        JSONGenerator jsonGenerator = JSON.createGenerator(true);
        jsonGenerator.writeStartObject();
        jsonGenerator.writeStringField('container_id', card.id);
        jsonGenerator.writeFieldName('outcomes');
        if (card.sub_offers.isEmpty()) {
            jsonGenerator.writeStartArray();    
            jsonGenerator.writeEndArray();
        } else {
            jsonGenerator.writeStartArray();
            for (CardOfferServiceReturn.SubOffers itemSubOffer : card.sub_offers) {
                jsonGenerator.writeStartObject();
                jsonGenerator.writeStringField('outcome', (itemSubOffer.description + ' | ' + itemSubOffer.categories));
                jsonGenerator.writeStringField('card_id', (acceptOrNot + ' | ' + reason));
                jsonGenerator.writeEndObject();
            }
            jsonGenerator.writeEndArray();
        }
        jsonGenerator.writeEndObject();
        
        if (jsonGenerator != null) {
            return jsonGenerator.getAsString();
        } else {
            return '';    
        }
    }

    public static CardOfferServiceReturn toShapeCardOffer (CardOfferServiceReturn cardOfferToReturn) {
        if (cardOfferToReturn.msg == 'success') {
            List<CardOfferServiceReturn.Card> cardList = new List<CardOfferServiceReturn.Card>();
            List<CardOfferServiceReturn.SubOffers> subOfferList;
            List<NextBestOfferAndAction__c> nboActionsList = NextBestOfferAndAction__c.getall().values();

            for (CardOfferServiceReturn.Card itemCard : cardOfferToReturn.cards) {
                if (itemCard.sub_offers != null) {
                    subOfferList = new List<CardOfferServiceReturn.SubOffers>();
                    for (CardOfferServiceReturn.SubOffers itemSubOffer : itemCard.sub_offers) {
                        itemSubOffer.categories = itemSubOffer.categories.trim();
                        if (isPrincipalOffer(itemSubOffer.categories)) {
                            itemSubOffer.offerPrice = itemCard.voucher_code;
                            itemCard.actionDescription = itemSubOffer.name;
                            subOfferList.add(convertDescriptionToFields(itemSubOffer));
                        } else{
                            subOfferList.add(convertDescriptionToFields(itemSubOffer)); 
                        }
                    }

                    subOfferList = sortSubOffersByCategories(subOfferList);
                    itemCard.sub_offers = subOfferList;
                }
                if (itemCard.title != null) {
                    itemCard.ltOptions = getListOfOptionsNotAccepted(itemCard.title, nboActionsList);
                }

                if (itemCard.source == '9999'){
                    itemCard.isBirthday = true;
                }


                cardList.add(itemCard);
            }

            cardOfferToReturn.cards = sortCardsByPriority(cardList);
            cardOfferToReturn.cards[0].isFocused = true; 
            return cardOfferToReturn;
        } else {
            return cardOfferToReturn;
        }
    }

    private static Boolean isPrincipalOffer (String categories) {
        if (categories == 'P') {
            return true;
        } else {
            return false;
        }
    }
    
    private static CardOfferServiceReturn.SubOffers convertDescriptionToFields (CardOfferServiceReturn.SubOffers subOffer) {
        List<String> splitList = subOffer.description.split('\\|');
        if (isPrincipalOffer(subOffer.categories)) {
            subOffer.description = splitList[0];
        } else {
            subOffer.description = splitList[0];
            subOffer.type = splitList[1];
            subOffer.campaignCode = splitList[2];
            subOffer.offerPrice = splitList[3];       
        }
        return subOffer;
    }
    
    private static List<CardOfferServiceReturn.SubOffers> sortSubOffersByCategories (List<CardOfferServiceReturn.SubOffers> ltSubOffer) {
        List<CardOfferServiceReturn.SubOffers> subOfferToSortList = ltSubOffer;
        for (Integer i = 0; i < subOfferToSortList.size() -1 ; i++) {
            for (Integer j = 0; j < subOfferToSortList.size() - 1 - i; j++) {
                if (!isPrincipalOffer(subOfferToSortList[j].categories)) {
                    CardOfferServiceReturn.SubOffers aux = subOfferToSortList[j];
                    subOfferToSortList[j] = subOfferToSortList[j + 1];
                    subOfferToSortList[j + 1] = aux;
                }
            }
        }
        return subOfferToSortList;
    }

    private static List<String> getListOfOptionsNotAccepted (String cardType, 
                                                             List<NextBestOfferAndAction__c> nboActionsList) {
        List<String> optionsOfNotAcceptedList = new List<String>();
        if (nboActionsList != null) {
            for (NextBestOfferAndAction__c nboAction : nboActionsList) {
                if (nboAction.type__c == cardType) {
                    optionsOfNotAcceptedList.add(nboAction.Reason__c);    
                }
            }
            return optionsOfNotAcceptedList;
        } else {
            optionsOfNotAcceptedList.add('');
            return optionsOfNotAcceptedList;
        }
    }
    
    public static List<CardOfferServiceReturn.Card> sortCardsByPriority (List<CardOfferServiceReturn.Card> cardList) {
        List<CardOfferServiceReturn.Card> cardToSortList = cardList;
        for (Integer i = 0; i < cardToSortList.size() -1 ; i++) {
            for (Integer j = 0; j < cardToSortList.size() - 1 - i; j++) {
                if (Integer.valueOf(cardToSortList[j].rank) > Integer.valueOf(cardToSortList[j + 1].rank)) {
                    CardOfferServiceReturn.Card auxCard = cardToSortList[j];
                    cardToSortList[j] = cardToSortList[j + 1];
                    cardToSortList[j + 1] = auxCard;
                }
            }
        }
        return cardToSortList;
    }

    public static String createNboCartAccount (Id accountId, 
                                               CardOfferServiceReturn.Card card, 
                                               String acceptOrNot, 
                                               String reason, 
                                               Boolean postStatus) {
        if (postStatus) {   
            Decimal price = Decimal.valueOf(card.voucher_code);
            CartAccount__c cartAccountToCreate = new CartAccount__c();
            Id nboRecType = CONST_CART_ACCOUNT_NBO_NBA_RECORD_TYPE;
            cartAccountToCreate.recordTypeId = nboRecType;
            cartAccountToCreate.TotalPrice__c = price;
            cartAccountToCreate.OfferType__c = card.title;
            cartAccountToCreate.AccountId__c = accountId;

            if (acceptOrNot == 'ACEITOU') {
                cartAccountToCreate.Accepted__c = 'Accepted';
            } else {
                cartAccountToCreate.Accepted__c = 'NotAccepted';
                cartAccountToCreate.ReasonNotAccepted__c = reason;
            }

            Database.SaveResult saveResult = Database.insert(cartAccountToCreate);
            if (saveResult.isSuccess()) {
                return 'success';
            } else {
                return 'error';
            }   
        } else {
            return 'error';
        }
    }
}