force-app/main/default/objects/Account/fields/vlocity_cmt__CustomerValue__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__CustomerValue__c</fullName>
    <description>A ranking of the value of this customer to your business expressed in marketing terms such as Gold, Silver, Bronze, Diamond, Platinum.</description>
    <label>Customer Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ComplainedAsset__c.field-meta.xml
<CustomField>
    <fullName>ComplainedAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Para uso do HDE</description>
    <inlineHelpText>Terminal, TV ou Banda Larga</inlineHelpText>
    <label>Produto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O produto adicionado está incorreto ou não está relacionado ao cliente.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Asset.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerServiceReason__c.field-meta.xml
<CustomField>
    <fullName>CustomerServiceReason__c</fullName>
    <description>Campo usado no HDE, atrelado ao grupo do atendente e usado no mapeamento do HDE DE PARA para classificação do chamado como Alta complexidade e crítico</description>
    <label>Motivo do atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2ª via de Nota Fiscal</fullName>
            </value>
            <value>
                <fullName>Acompanhamento de Técnico Fixa</fullName>
            </value>
            <value>
                <fullName>Agenda técnica não cumprida</fullName>
            </value>
            <value>
                <fullName>Alocação de fundos Kenan</fullName>
            </value>
            <value>
                <fullName>Análise/Suspeita de Fraude</fullName>
            </value>
            <value>
                <fullName>Análise de Cobertura</fullName>
            </value>
            <value>
                <fullName>Análise de Cobertura Condomínio</fullName>
            </value>
            <value>
                <fullName>Análise de crédito para mudança de Plano</fullName>
            </value>
            <value>
                <fullName>Análise de Retirada de Fidelidade</fullName>
            </value>
            <value>
                <fullName>Ativação de E-Sim</fullName>
            </value>
            <value>
                <fullName>Ativação de serviço (falha sistêmica)</fullName>
            </value>
            <value>
                <fullName>Atraso na entrega de controle remoto</fullName>
            </value>
            <value>
                <fullName>Baixa de Pagto / Envio de Comprovante / Religue</fullName>
            </value>
            <value>
                <fullName>Biometria Documental</fullName>
            </value>
            <value>
                <fullName>Chamador diferente binado p/ troca de número</fullName>
            </value>
            <value>
                <fullName>Cliente reindente em contestação</fullName>
            </value>
            <value>
                <fullName>Cliente vai pensar</fullName>
            </value>
            <value>
                <fullName>Cliente Vivo 1</fullName>
            </value>
            <value>
                <fullName>Contestação Kenan</fullName>
            </value>
            <value>
                <fullName>Contestação por Retificação acima de 1 Fatura</fullName>
            </value>
            <value>
                <fullName>Contestação Próximo Ciclo</fullName>
            </value>
            <value>
                <fullName>Contestação que seja necessário ouvir gravação</fullName>
            </value>
            <value>
                <fullName>Contrato - Locação</fullName>
            </value>
            <value>
                <fullName>Correção Causa Raiz - Contestação</fullName>
            </value>
            <value>
                <fullName>Correção de cadastro Siebel</fullName>
            </value>
            <value>
                <fullName>Correção de SubSegmento (PJ/PF)</fullName>
            </value>
            <value>
                <fullName>Dados de Oferta/Valores Divergentes</fullName>
            </value>
            <value>
                <fullName>Desbloqueio Linha/Aparelho</fullName>
            </value>
            <value>
                <fullName>Desconto Oferta Totalizadora</fullName>
            </value>
            <value>
                <fullName>Desmembramento de contas (Pós Pago - NEXT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IsHDE__c.field-meta.xml
<CustomField>
    <fullName>IsHDE__c</fullName>
    <formula>CONTAINS(RecordType.Name, &quot;HDE&quot;)</formula>
    <label>É do HDE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>Protocolo recebido da URA.</description>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Campo utilizado na parametrização de casos de alta complexidade e críticos no custom metadata HDE DE-PARA, para dependencias de campos e para campos fórmula no objeto. ex: visão</description>
    <label>Grupo de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Lojas (Revendas)</fullName>
                <label>Revendas</label>
            </value>
            <value>
                <fullName>Ouvidoria Comunidades</fullName>
            </value>
            <value>
                <fullName>VPR Lojas</fullName>
            </value>
            <value>
                <fullName>V</fullName>
                <isActive>false</isActive>
                <label>V</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ServiceReason__c.field-meta.xml
<CustomField>
    <fullName>ServiceReason__c</fullName>
    <description>Descrição do motivo do contato do cliente. Pela integração CTI são as opções percorridas pelo cliente na URA.</description>
    <label>Motivo do Contato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/View__c.field-meta.xml
<CustomField>
    <fullName>View__c</fullName>
    <formula>CASE( RecordType.DeveloperName+text(Segment__c),
&quot;EmailTriggerVivo V&quot;, &quot;CRI E-mail V&quot;,
&quot;GoldProcessesEscalationGold&quot;, &quot;CRI Escalonamento Gold&quot;,
&quot;PurpuraProcessesEscalationPúrpura&quot;, &quot;CRI Escalonamento Púrpura&quot;,	
&quot;SilverProcessesEscalationSilver&quot;, &quot;CRI Escalonamento Silver&quot;,					
&quot;StoreProcessesEscalationLoja&quot;, &quot;CRI Escalonamento Loja&quot;,
&quot;ResellerStoreProcessesEscalationLojas (Revendas)&quot;, &quot;CRI Escalonamento Lojas (Revendas)&quot;,					
&quot;PlatinumProcessesEscalationPlatinum&quot;, &quot;CRI Escalonamento Platinum&quot;,
&quot;PrimeProcessesEscalationPrime&quot;, &quot;CRI Escalonamento Prime&quot;,
&quot;OuvidoriaProcessesEscalationOuvidoria&quot;, &quot;CRI Escalonamento Ouvidoria&quot;,
&quot;CommunityOuvidoriaProcessesEscalationOuvidoria Comunidades&quot;, &quot;CRI Escalonamento Ouvidoria Comunidades&quot;,					
&quot;VivoVProcessesEscalationVivo V&quot;, &quot;CRI Escalonamento V&quot;,
&quot;CallSupervisorVivo V&quot;, &quot;CRI Supervisor V&quot;,
&quot;EscalationAndLawSuitsVivo V&quot;, &quot;CRI Escalonamento V&quot;,
&quot;EscalationAndLawSuitsGold&quot;, &quot;CRI Escalonamento Gold&quot;,
&quot;EscalationAndLawSuitsPlatinum&quot;, &quot;CRI Escalonamento Platinum&quot;,
&quot;EscalationAndLawSuitsLoja&quot;, &quot;CRI Escalonamento Loja&quot;,
&quot;EscalationAndLawSuitsPrime&quot;, &quot;CRI Escalonamento Prime&quot;,
&quot;EscalationAndLawSuitsOuvidoria&quot;, &quot;CRI Escalonamento Ouvidoria&quot;,

&quot;&quot;
)</formula>
    <label>Visão</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchRoutingCasesCalloutTest.cls
@IsTest
private class BatchRoutingCasesCalloutTest {
    @TestSetup
    static void makeData() {
        List<Case> ltCases = new List<Case>();
        List<Account> ltAccount = new List<Account>();
        List<Asset> ltAsset = new List<Asset>();
        
        String recType = 'HDE - Gold Processos Escalonamento';
        String recordTypeDeveloperName = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recType).getDeveloperName();
        
        Profile profile = [
            SELECT 
                Id, 
                Name 
            FROM 
                Profile 
            WHERE 
                Name LIKE 'Representante' 
            LIMIT 1
        ];
        
        UserRole role = [
            SELECT 
                Id, 
                Name 
            FROM 
                UserRole 
            WHERE 
                DeveloperName LIKE 'AtendimentoGoldAdmProcessos' 
            LIMIT 1
        ];

        User userAgent = DataFactory.createUser(profile.Id, role.Id);
        
        insert userAgent;

        User thisUser = [
            SELECT 
                Id 
            FROM 
                User 
            WHERE 
                Id = :UserInfo.getUserId()
        ];
        
        System.runAs(thisUser) {
            Account accountObj1 = new Account();
            
            accountObj1.Name = 'Validate Test 1';
            accountObj1.vlocity_cmt__CustomerValue__c = 'Gold';
            
            ltAccount.add(accountObj1);

            insert ltAccount;

            Asset assetObj1 = new Asset();

            assetObj1.AccountId = accountObj1.Id;
            assetObj1.Name = 'Validate Test';

            ltAsset.add(assetObj1);

            insert ltAsset;       

            Case oldCase1 = DataFactory.createCase(recordTypeDeveloperName, 'Test Case 1', 'add old case test');
            
            oldCase1.AccountId = accountObj1.Id;
            oldCase1.ComplainedAsset__c = assetObj1.Id;
            oldCase1.Priority = 'High';
            oldCase1.Segment__c	 = 'Gold';
            oldCase1.CustomerServiceReason__c = 'Agenda técnica não cumprida';
            oldCase1.OwnerId = userAgent.Id;

            ltCases.add(oldCase1);

            insert ltCases;
        }
    }
    
    @IsTest
    static void executeTest() {
        List<Case> ltCase = [
            SELECT 
                Id, 
                Status, 
                Protocol__c, 
                RecordTypeId, 
                RecordType.Name, 
                RecordType.DeveloperName, 
                AccountId, 
                ComplainedAsset__c, 
                Description, 
                Priority,Segment__c, 
                ServiceReason__c, 
                CustomerServiceReason__c, 
                IsHDE__c, 
                CreatedById, 
                OwnerId, 
                View__c 
            FROM 
                Case 
            WHERE 
                Subject LIKE 'Test Case%'
        ];

        Map<Id, String> casesWithPriorities = new Map<Id, String>();
        
        for (Case item : ltCase) {
            casesWithPriorities.put(item.Id, item.Priority);
        }

        Test.startTest();
            BatchRoutingCasesCallout testBatch = new BatchRoutingCasesCallout(ltCase, casesWithPriorities);
            
            ID batchProcessId = Database.executeBatch(testBatch, 1);
        Test.stopTest();

        AsyncApexJob aaj = [
            SELECT 
                Id, 
                Status, 
                JobItemsProcessed, 
                TotalJobItems, 
                NumberOfErrors 
            FROM 
                AsyncApexJob 
            WHERE 
                ID = :batchProcessId
        ];
        
        System.assertEquals(aaj.Status, 'Completed', 'Job Status not Completed.');  
    }
}