force-app/main/default/objects/Account/fields/vlocity_cmt__CustomerValue__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__CustomerValue__c</fullName>
    <description>A ranking of the value of this customer to your business expressed in marketing terms such as Gold, Silver, Bronze, Diamond, Platinum.</description>
    <label>Customer Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Pre</fullName>
            </value>
            <value>
                <fullName>Púrpura</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CriticalComment__c.field-meta.xml
<CustomField>
    <fullName>CriticalComment__c</fullName>
    <label>Detalhes da Priorização</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerServiceReason__c.field-meta.xml
<CustomField>
    <fullName>CustomerServiceReason__c</fullName>
    <description>Campo usado no HDE, atrelado ao grupo do atendente e usado no mapeamento do HDE DE PARA para classificação do chamado como Alta complexidade e crítico</description>
    <label>Motivo do atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2ª via de Nota Fiscal</fullName>
            </value>
            <value>
                <fullName>Acompanhamento de Técnico Fixa</fullName>
            </value>
            <value>
                <fullName>Agenda técnica não cumprida</fullName>
            </value>
            <value>
                <fullName>Alocação de fundos Kenan</fullName>
            </value>
            <value>
                <fullName>Análise/Suspeita de Fraude</fullName>
            </value>
            <value>
                <fullName>Análise de Cobertura</fullName>
            </value>
            <value>
                <fullName>Análise de Cobertura Condomínio</fullName>
            </value>
            <value>
                <fullName>Análise de crédito para mudança de Plano</fullName>
            </value>
            <value>
                <fullName>Análise de Retirada de Fidelidade</fullName>
            </value>
            <value>
                <fullName>Ativação de E-Sim</fullName>
            </value>
            <value>
                <fullName>Ativação de serviço (falha sistêmica)</fullName>
            </value>
            <value>
                <fullName>Atraso na entrega de controle remoto</fullName>
            </value>
            <value>
                <fullName>Baixa de Pagto / Envio de Comprovante / Religue</fullName>
            </value>
            <value>
                <fullName>Biometria Documental</fullName>
            </value>
            <value>
                <fullName>Chamador diferente binado p/ troca de número</fullName>
            </value>
            <value>
                <fullName>Cliente reindente em contestação</fullName>
            </value>
            <value>
                <fullName>Cliente vai pensar</fullName>
            </value>
            <value>
                <fullName>Cliente Vivo 1</fullName>
            </value>
            <value>
                <fullName>Contestação Kenan</fullName>
            </value>
            <value>
                <fullName>Contestação por Retificação acima de 1 Fatura</fullName>
            </value>
            <value>
                <fullName>Contestação Próximo Ciclo</fullName>
            </value>
            <value>
                <fullName>Contestação que seja necessário ouvir gravação</fullName>
            </value>
            <value>
                <fullName>Contrato - Locação</fullName>
            </value>
            <value>
                <fullName>Correção Causa Raiz - Contestação</fullName>
            </value>
            <value>
                <fullName>Correção de cadastro Siebel</fullName>
            </value>
            <value>
                <fullName>Correção de SubSegmento (PJ/PF)</fullName>
            </value>
            <value>
                <fullName>Dados de Oferta/Valores Divergentes</fullName>
            </value>
            <value>
                <fullName>Desbloqueio Linha/Aparelho</fullName>
            </value>
            <value>
                <fullName>Desconto Oferta Totalizadora</fullName>
            </value>
            <value>
                <fullName>Desmembramento de contas (Pós Pago - NEXT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/HDEOtherProducts__c.field-meta.xml
<CustomField>
    <fullName>HDEOtherProducts__c</fullName>
    <label>Outros Produtos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SegmentProduct__c.field-meta.xml
<CustomField>
    <fullName>SegmentProduct__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Móvel</fullName>
            </value>
            <value>
                <fullName>OtherProduct</fullName>
                <label>Outros Produtos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/VivoVProcessesEscalation.recordType-meta.xml
<RecordType>
    <fullName>VivoVProcessesEscalation</fullName>
    <active>true</active>
    <businessProcess>HDE</businessProcess>
    <description>Chamado gestão de casos para solução de Causa Raiz, Escalonamento, Acompanhamento e Gestão expectativa Cliente</description>
    <label>HDE - V Processos Escalonamento</label>
</RecordType>

force-app/main/default/objects/CaseDetail__c/CaseDetail__c.object-meta.xml
<CustomObject>
    <description>Objeto auxiliar ao objeto Caso (Case), que armazena os campos das jornadas de minhas solicitações recebidos através do fluxo do App Vivo. Projeto Minhas Solicitações PTI4728</description>
    <label>Detalhe do Caso</label>
    <nameField>
        <displayFormat>DC - {00000000}</displayFormat>
        <label>Número do Detalhe do Caso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalhes dos Casos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseDetail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Detalhes dos Casos</relationshipLabel>
    <relationshipName>CaseDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HDECaseDetailServiceTest.cls
@IsTest 
public class HDECaseDetailServiceTest {
	@TestSetup
    static void setup() {
        Profile profile = [
            SELECT 
                Id, 
                Name 
            FROM 
                Profile 
            WHERE 
                Name LIKE 'Representante' 
            LIMIT 
                1
        ];
        
        UserRole role = [
            SELECT 
                Id, 
                Name 
            FROM 
                UserRole 
            WHERE 
                DeveloperName LIKE 'AtendimentoVivoVAdmProcessos' 
            LIMIT 
                1
        ];

        User userAgent = DataFactory.createUser(profile.Id, role.Id);
        
        insert userAgent;

        System.runAs(userAgent) {
            String developerName = 'VivoVProcessesEscalation';
            Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(developerName).getRecordTypeId();
            
            Account accountObj = new Account();
                
            accountObj.Name = 'Validate Test 1';
            accountObj.vlocity_cmt__CustomerValue__c = 'Gold';

            insert accountObj;

            Case caseNew = new Case(
                Status = 'A Iniciar', 
                RecordTypeId = recordTypeId,
                Priority = 'Medium',
                CriticalComment__c = '',
                CustomerServiceReason__c = 'Análise de Cobertura',
                HDEOtherProducts__c = 'SIMCard',
                SegmentProduct__c = 'OtherProduct',
                AccountId = accountObj.Id
            );

            insert caseNew;
        }
    }

    @IsTest 
    static void createCaseDetailTest() {
        Case caseSource = [
            SELECT 
                Id 
            FROM 
                Case 
            WHERE 
                Status LIKE 'A Iniciar' AND 
                CustomerServiceReason__c LIKE 'Análise de Cobertura'
            LIMIT
            	1
        ];
        
        List<CaseDetail__c> ltCaseDetail = [
            SELECT 
                Id 
            FROM 
                CaseDetail__c 
            WHERE 
                Case__c = :caseSource.Id
        ];
        
		System.assertEquals(1, ltCaseDetail.size());
    }
}