force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Custom object para Bilhetes de Defeito</description>
    <label>Bilhete de Defeitos</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Detalhamento BDs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bilhete de Defeitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/PrevisionDate__c.field-meta.xml
<CustomField>
    <fullName>PrevisionDate__c</fullName>
    <description>Campo para retorno da data de previsão de solução do WFM.</description>
    <label>Previsão de Solução</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <label>Atribuido</label>
            </value>
            <value>
                <fullName>DELAYED</fullName>
                <label>Atrasado</label>
            </value>
            <value>
                <fullName>CLOSED</fullName>
                <label>Fechado</label>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketId__c.field-meta.xml
<CustomField>
    <fullName>TicketId__c</fullName>
    <description>Campo de identificação externa para o Id dos tickets abertos.</description>
    <externalId>true</externalId>
    <label>Ticket ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/switchedOn__c.field-meta.xml
<CustomField>
    <fullName>switchedOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TicketPrevisionDateEngine.cls
public with sharing class TicketPrevisionDateEngine {
    
    public static String getTicketPrevisionDate(Id ticketId) {

        String WEBSERVICE_NAME = 'WFMSearchByWorkOrderCallout';
        Webservice__c wsConfig = Webservice__c.getInstance(WEBSERVICE_NAME);
 
        if (wsConfig == null || !wsConfig.switchedOn__c) {
            return '';
        }

        Ticket__c ticketObj = TicketDAO.getTicketById(ticketId);
        
        if(ticketObj == null || ticketObj.Status__c != 'OPEN'){
            return '';
        }

        TicketServicePrevisionReturn.workOrder workOrder;
        TicketServicePrevisionReturn.WorkRequiresAppointment workRequire;
        TicketServicePrevisionReturn.AppointmentIsAssociatedWithCalendarEntry appointment;
        TicketServicePrevisionReturn.TimePeriod timePeriod;
        TicketServicePrevisionReturn responseService;
        String convertedString;
        Date convertedDate;
        Date dateToSet;

        HttpClient client = new HttpClient();
        HttpResponse response = client.post(wsConfig, '{"workOrder": {"id": "'+ ticketObj.TicketId__c +'"}}' );

        if (response.getStatusCode()/100 == 2) {
            responseService = (TicketServicePrevisionReturn) JSON.deserialize(response.getBody(),TicketServicePrevisionReturn.class);
        }
        else if(response.getStatusCode() == 404){
            return '404';
        }
        else if(response.getStatusCode() == 500){
            return '500';
        }
        
        if(responseService == null){
            return '500';
        }
        
        workOrder = responseService.workOrder;
        for(TicketServicePrevisionReturn.WorkOrderComprisedOf itemWO : workOrder.WorkOrderComprisedOf){
                
            for(TicketServicePrevisionReturn.WorkOrderItemInvolvesWork itemWI : itemWO.WorkOrderItemInvolvesWork){
                
                if((itemWI.status =='Agendado') || (itemWI.status=='Iniciado')){
                    workRequire = itemWI.WorkRequiresAppointment;
                    appointment = workRequire.AppointmentIsAssociatedWithCalendarEntry;
                    timePeriod = appointment.timePeriod;
                    if(timePeriod.endDateTime != ''){
                        convertedString = timePeriod.endDateTime.substring(0, timePeriod.endDateTime.indexOf('T'));
                        convertedDate = Date.valueOf(convertedString);
                    }
                    if(dateToSet == null || dateToSet < convertedDate ){
                        dateToSet = convertedDate;    
                    }
                }
            }
        }

        ticketObj.PrevisionDate__c = dateToSet;
        update ticketObj;
        return '200';
    }
}