force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Custom object para Bilhetes de Defeito</description>
    <label>Bilhete de Defeitos</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Detalhamento BDs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bilhete de Defeitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bilhetes de Defeito</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <label>Atribuido</label>
            </value>
            <value>
                <fullName>DELAYED</fullName>
                <label>Atrasado</label>
            </value>
            <value>
                <fullName>CLOSED</fullName>
                <label>Fechado</label>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketId__c.field-meta.xml
<CustomField>
    <fullName>TicketId__c</fullName>
    <description>Campo de identificação externa para o Id dos tickets abertos.</description>
    <externalId>true</externalId>
    <label>Ticket ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <label>Validade dos dados da consulta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TicketDAO.cls
public class TicketDAO {
	public static final String WEBSERVICE_NAME = 'FourthPlataformTicketServiceCallout';    
    
    public static List<Ticket__c> getByAccountId(Id accountId){
        
        WebService__c wsConfig = Webservice__c.getInstance(WEBSERVICE_NAME);
        
		integer refreshTime = Integer.valueOf(wsConfig.Validate__c) *-1;
        Datetime searchTicketDate = system.now().addSeconds(refreshTime);
        
        return [
            SELECT    
                Id 
            FROM 
                Ticket__c
            WHERE
            	AccountId__c =: accountId
            
            AND
             	LastModifiedDate >: searchTicketDate
        ];
    }
    
    public static Ticket__c getTicketById(Id ticketId){
        List<Ticket__c> ltTicket = getTicketByIds(new Set<Id>{ticketId});
        return ltTicket.IsEmpty() ? null : ltTicket[0];
    }
    
    public static List<Ticket__c> getTicketByIds(Set<Id> setTicketId){
        return [
            SELECT
            	TicketId__c,
            	Status__c
            FROM
            	Ticket__c
            WHERE
            	Id IN :setTicketId
            AND
            	TicketId__c != null
        ];
        
    }
}