force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Objeto de faturas destinado a armazenar as informações históricas do cliente.</description>
    <label>Faturamento</label>
    <nameField>
        <label>Mês de Referência</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Campo de relacionamento entre Conta e Invoice.</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamento</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <label>Validade dos dados da consulta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoiceHistoryDAO.cls
/*
* @author Diego Costa @ Deloitte
* @date 06/06/2022
* @description - Classe responsável por verificar se há dados nas respectivas APIs após execução de batchs e realizações novas chamadas
*/
public with sharing class InvoiceHistoryDAO {    
    public static final String WEBSERVICE_NAME = 'FourthPlataformInvoiceCallout';    
    
    public static List<Invoice__c> getInvoiceByAccountId(Id accountId, Datetime searchInvoiceTime){
        Webservice__c wsConfig = Webservice__c.getInstance(WEBSERVICE_NAME);
        
        integer refreshTime = Integer.valueOf(wsConfig.Validate__c) *-1;
        Datetime searchInvoiceDate = system.now().addSeconds(refreshTime);
        
        return [
            SELECT    
                Id 
            FROM 
                Invoice__c
            WHERE
            	AccountId__c =: accountId
            	AND
            	LastModifiedDate >: searchInvoiceDate
            	AND 
            	ID != NULL
        ];
    }
    
}