force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Objeto de faturas destinado a armazenar as informações históricas do cliente.</description>
    <label>Faturamento</label>
    <nameField>
        <label>Mês de Referência</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Campo de relacionamento entre Conta e Invoice.</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamento</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Downloadurl__c.field-meta.xml
<CustomField>
    <fullName>Downloadurl__c</fullName>
    <label>Download url</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <description>Identificador da fatura na 4P.</description>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SecondaryDownloadUrl__c.field-meta.xml
<CustomField>
    <fullName>SecondaryDownloadUrl__c</fullName>
    <label>Download url secundária</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/InvoiceDAO.cls
/** 
 * @author Diego Costa @ Deloitte
 * @date 15/06/2022
 * @description Controla a busca e criação do objeto Invoice__c
 */
public with sharing class InvoiceDAO {
    public static Invoice__c getById(Id invoiceId) {
        List<Invoice__c> ltInvoice = getById(new Set<Id>{invoiceId});

        return (ltInvoice.IsEmpty() ? null : ltInvoice[0]);
    }
    
    public static List<Invoice__c> getById(Set<Id> setInvoiceId){
        return [
            SELECT 
                Id, 
                Name, 
                InvoiceId__c, 
                Downloadurl__c, 
                SecondaryDownloadUrl__c, 
                AccountId__c 
            FROM 
                Invoice__c 
            WHERE 
                Id = :setInvoiceId
        ]; 
    }
}