force-app/main/default/objects/CanalNotificacoesMinhasSolicitacoes__mdt/CanalNotificacoesMinhasSolicitacoes__mdt.object-meta.xml
<CustomObject>
    <label>Canal de Notificação Minhas Solicitações</label>
    <pluralLabel>Canal de Notificação Minhas Solicitações</pluralLabel>
</CustomObject>

force-app/main/default/objects/CanalNotificacoesMinhasSolicitacoes__mdt/fields/CallOut__c.field-meta.xml
<CustomField>
    <fullName>CallOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CallOut</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CanalNotificacoesMinhasSolicitacoes__mdt/fields/FuncionalidadeControlada__c.field-meta.xml
<CustomField>
    <fullName>FuncionalidadeControlada__c</fullName>
    <description>A funcionalidade a qual o controle de canal se refere</description>
    <inlineHelpText>A funcionalidade a qual o controle de canal se refere</inlineHelpText>
    <label>Funcionalidade Controlada</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AtualizacaoStatusCaso</fullName>
                <label>Atualização de Status do Caso</label>
            </value>
            <value>
                <fullName>BotaoNotificarCliente</fullName>
                <label>Botão Notificar Cliente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CanalNotificacoesMinhasSolicitacoes__mdt/fields/PushSMS__c.field-meta.xml
<CustomField>
    <fullName>PushSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push ou SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CanalNotificacoesMinhasSolicitacoes.cls
public with sharing class CanalNotificacoesMinhasSolicitacoes {

    public List<CanalNotificacoesMinhasSolicitacoes__mdt> getMetadataByFuncionalidadeControlada(String funcionalidadeControlada) {
        return [
            SELECT Id, CallOut__c, PushSMS__c, MasterLabel
            FROM CanalNotificacoesMinhasSolicitacoes__mdt
            WHERE FuncionalidadeControlada__c = :funcionalidadeControlada
        ];
    }
}