force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo para marcar ofertas ativas.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobileDescription__c.field-meta.xml
<CustomField>
    <fullName>MobileDescription__c</fullName>
    <description>Descrição da Oferta Móvel</description>
    <label>Descrição Oferta Móvel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobileInternetDescription__c.field-meta.xml
<CustomField>
    <fullName>MobileInternetDescription__c</fullName>
    <description>Descrição da Oferta Móvel Internet</description>
    <label>Descrição Oferta Móvel Internet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobilePlan__c.field-meta.xml
<CustomField>
    <fullName>MobilePlan__c</fullName>
    <label>Plano Móvel</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobilePriceDiscount__c.field-meta.xml
<CustomField>
    <fullName>MobilePriceDiscount__c</fullName>
    <description>Valor do desconto móvel para ofertas de alta</description>
    <label>Desconto Móvel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Preço Final</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/recordTypes/AltaMovel.recordType-meta.xml
<RecordType>
    <fullName>AltaMovel</fullName>
    <active>true</active>
    <description>Ofertas de Alta para Móvel</description>
    <label>Alta Móvel</label>
</RecordType>

force-app/main/default/objects/TemplateMessage__mdt/TemplateMessage__mdt.object-meta.xml
<CustomObject>
    <label>Template Message</label>
    <pluralLabel>Template Message</pluralLabel>
</CustomObject>

force-app/main/default/objects/TemplateMessage__mdt/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Papéis</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TemplateMessage__mdt/fields/TemplateMessage__c.field-meta.xml
<CustomField>
    <fullName>TemplateMessage__c</fullName>
    <label>TemplateMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TemplateMessage__mdt/fields/TemplateType__c.field-meta.xml
<CustomField>
    <fullName>TemplateType__c</fullName>
    <label>TemplateType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixa</fullName>
                <default>true</default>
                <label>Fixa</label>
            </value>
            <value>
                <fullName>Movel</fullName>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Alta Movel</fullName>
            </value>
            <value>
                <fullName>Alta Fixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InsertCartSelector.cls
public without sharing class InsertCartSelector {
    public static List<TemplateMessage__mdt> getListTemplateMessageByType(String type){
        List<TemplateMessage__mdt> ltTemplates = [
                                    SELECT 
                                        TemplateMessage__c, 
                                        Roles__c, 
                                        TemplateType__c 
                                    FROM
                                        TemplateMessage__mdt 
                                    WHERE 
                                        TemplateType__c =: type];
        return ltTemplates;
    }

    public static Offer__c getOfferAlta(Id selectedOfferAltaId){
        Offer__c returnOffer =  [
                            SELECT 
                                Id, 
                                MobilePlan__c,
                                TotalPrice__c, 
                                MobileDescription__c, 
                                MobileInternetDescription__c, 
                                MobilePriceDiscount__c 
                            FROM    
                                Offer__c 
                            WHERE 
                                RecordType.DeveloperName = 'AltaMovel' AND 
                                IsActive__c = true AND 
                                ID =: selectedOfferAltaId];
        return returnOffer;
    }
}