force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo para marcar ofertas ativas.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobileDescription__c.field-meta.xml
<CustomField>
    <fullName>MobileDescription__c</fullName>
    <description>Descrição da Oferta Móvel</description>
    <label>Descrição Oferta Móvel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobileInternetDescription__c.field-meta.xml
<CustomField>
    <fullName>MobileInternetDescription__c</fullName>
    <description>Descrição da Oferta Móvel Internet</description>
    <label>Descrição Oferta Móvel Internet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/OfferDescriptionConcat__c.field-meta.xml
<CustomField>
    <fullName>OfferDescriptionConcat__c</fullName>
    <formula>&apos;Oferta contratada: &apos;+ MobileDescription__c +&apos;, &apos;+ MobilePlan__c +&apos; com &apos;+ MobileInternetDescription__c</formula>
    <label>Descrição oferta consolidada</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/PackageOffer__c.field-meta.xml
<CustomField>
    <fullName>PackageOffer__c</fullName>
    <label>Pacotes da Oferta</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Package1</fullName>
                <label>Pacote 1</label>
            </value>
            <value>
                <fullName>Package2</fullName>
                <label>Pacote 2</label>
            </value>
            <value>
                <fullName>Package3</fullName>
                <label>Pacote 3</label>
            </value>
            <value>
                <fullName>Package4</fullName>
                <label>Pacote 4</label>
            </value>
            <value>
                <fullName>Package5</fullName>
                <label>Pacote 5</label>
            </value>
            <value>
                <fullName>Package6</fullName>
                <label>Pacote 6</label>
            </value>
            <value>
                <fullName>Package7</fullName>
                <label>Pacote 7</label>
            </value>
            <value>
                <fullName>Package8</fullName>
                <label>Pacote 8</label>
            </value>
            <value>
                <fullName>Package9</fullName>
                <label>Pacote 9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Preço Final</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TypePlan__c.field-meta.xml
<CustomField>
    <fullName>TypePlan__c</fullName>
    <description>Utilizado para o cadastro de ofertas de alta de móvel</description>
    <label>Tipo de plano</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Controle</fullName>
            </value>
            <value>
                <fullName>Pós-pago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CardOfferFlowController.cls
/*
---------------------------------------------------
@authors - Rafael Amaral
@company - everis do Brasil
@date - 04/06/2020
@AuraComponent - CardOfferFlow
@description - Retorna uma oferta ao componente lightning
---------------------------------------------------
Changes
2020-09-30 @Alvaro B2C7551-402 - MobilePriceOffer__c removido do SOQL em Offer__c.
*/
public with sharing class CardOfferFlowController 
{
    @AuraEnabled
    public static Offer__c getOffer(String aOfferId)
    {
        return [SELECT Id, Name, OfferDescriptionConcat__c, PackageOffer__c, TypePlan__c, MobileInternetDescription__c,
                MobileDescription__c, TotalPrice__c, IsActive__c FROM Offer__c WHERE Id = :aOfferId ];
    }
}