force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/BroadBandAttribute__c.field-meta.xml
<CustomField>
    <fullName>BroadBandAttribute__c</fullName>
    <description>Velocidade da Banda Larga</description>
    <label>Velocidade Banda Larga</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Technology__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>600</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/BundleType__c.field-meta.xml
<CustomField>
    <fullName>BundleType__c</fullName>
    <description>Tipo do Pacote: 1P, 2P, 3P</description>
    <label>Modalidade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1P</fullName>
            </value>
            <value>
                <fullName>2P</fullName>
            </value>
            <value>
                <fullName>3P</fullName>
            </value>
            <value>
                <fullName>Duo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Campo para detalhar a descrição das ofertas de Book de oferta.</description>
    <label>Descrição</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/FixedCampaignRTD__c.field-meta.xml
<CustomField>
    <fullName>FixedCampaignRTD__c</fullName>
    <description>Descrição da campanha.</description>
    <label>Campanha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/HomeAssist__c.field-meta.xml
<CustomField>
    <fullName>HomeAssist__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Home Assist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo para marcar ofertas ativas.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/OfferGroup__c.field-meta.xml
<CustomField>
    <fullName>OfferGroup__c</fullName>
    <label>Grupo de Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Aquisição</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/PromotionGroup__c.field-meta.xml
<CustomField>
    <fullName>PromotionGroup__c</fullName>
    <label>Grupo de Promoção</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Aquisição BL Avulsa</fullName>
            </value>
            <value>
                <fullName>Aquisição 2P</fullName>
            </value>
            <value>
                <fullName>Rentabilização 2P</fullName>
            </value>
            <value>
                <fullName>Aquisição Full</fullName>
            </value>
            <value>
                <fullName>Aquisição DUO Full</fullName>
            </value>
            <value>
                <fullName>Rentabilização Full</fullName>
            </value>
            <value>
                <fullName>Rentabilização Ultimate</fullName>
            </value>
            <value>
                <fullName>Rentabilização DUO DTH</fullName>
            </value>
            <value>
                <fullName>Rentabilização DTH</fullName>
            </value>
            <value>
                <fullName>Rentabilização 3P DTH</fullName>
            </value>
            <value>
                <fullName>Conteúdos de Vídeo</fullName>
            </value>
            <value>
                <fullName>Aquisição DUO Super</fullName>
            </value>
            <value>
                <fullName>Rentabilização</fullName>
            </value>
            <value>
                <fullName>Rentabilização DUO Full</fullName>
            </value>
            <value>
                <fullName>Rentabilização Híbrido</fullName>
            </value>
            <value>
                <fullName>Rentabilização DUO Ultimate</fullName>
            </value>
            <value>
                <fullName>Rentabilização DUO Super</fullName>
            </value>
            <value>
                <fullName>Rentabilização Super</fullName>
            </value>
            <value>
                <fullName>Rentabilização BL Avulsa</fullName>
            </value>
            <value>
                <fullName>Aquisição DUO Ultimate</fullName>
            </value>
            <value>
                <fullName>Aquisição Ultimate</fullName>
            </value>
            <value>
                <fullName>Aquisição Super</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Tecnologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTTC</fullName>
            </value>
            <value>
                <fullName>FTTH</fullName>
            </value>
            <value>
                <fullName>XDSL</fullName>
            </value>
            <value>
                <fullName>FTTH/FTTC</fullName>
                <isActive>false</isActive>
                <label>FTTH/FTTC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Preço Final</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TVAttribute__c.field-meta.xml
<CustomField>
    <fullName>TVAttribute__c</fullName>
    <description>Nome do pacote de TV</description>
    <label>Plano de TV</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plano 1</fullName>
            </value>
            <value>
                <fullName>Plano 2</fullName>
            </value>
            <value>
                <fullName>Plano 3</fullName>
            </value>
            <value>
                <fullName>Plano 4</fullName>
            </value>
            <value>
                <fullName>Plano 5</fullName>
            </value>
            <value>
                <fullName>Vivo Play Básico</fullName>
            </value>
            <value>
                <fullName>Vivo Play Completo</fullName>
            </value>
            <value>
                <fullName>Full HD Futebol</fullName>
            </value>
            <value>
                <fullName>Vivo Play Padrão</fullName>
            </value>
            <value>
                <fullName>Vivo Play Essencial</fullName>
            </value>
            <value>
                <fullName>Super HD Futebol</fullName>
            </value>
            <value>
                <fullName>Vivo Play Avançado</fullName>
            </value>
            <value>
                <fullName>Ultimate HD Futebol</fullName>
            </value>
            <value>
                <fullName>Vivo Play Ultra</fullName>
            </value>
            <value>
                <fullName>Ultra HD Futebol</fullName>
            </value>
            <value>
                <fullName>Ultimate HD</fullName>
            </value>
            <value>
                <fullName>Standard HD</fullName>
            </value>
            <value>
                <fullName>Super HD</fullName>
            </value>
            <value>
                <fullName>Ultra HD</fullName>
            </value>
            <value>
                <fullName>Full HD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/recordTypes/OfferBook.recordType-meta.xml
<RecordType>
    <fullName>OfferBook</fullName>
    <active>true</active>
    <description>Ofertas do Book de Ofertas</description>
    <label>Book de Ofertas</label>
</RecordType>

force-app/main/default/objects/Offer__c/recordTypes/ServicosAdicionais.recordType-meta.xml
<RecordType>
    <fullName>ServicosAdicionais</fullName>
    <active>true</active>
    <description>Serviços Adicionais</description>
    <label>Serviços Adicionais</label>
</RecordType>

force-app/main/default/classes/OfferController.cls
public with sharing class OfferController {
  static Integer PAGE_SIZE = 25;
  static String OBJ_NAME = 'Offer__c';
  static String FIELD_SET_OFFER_BOOK = 'dataTableBookIntegrado';

  public class Filters {
    @AuraEnabled
    public String searchKey { get; set; }
    @AuraEnabled
    public String technology { get; set; }
    @AuraEnabled
    public String offerGroup { get; set; }
    @AuraEnabled
    public String bundleType { get; set; }
    @AuraEnabled
    public String broadBand { get; set; }
    @AuraEnabled
    public String tvAttribute { get; set; }
    @AuraEnabled
    public String promotionGroup { get; set; }
    @AuraEnabled
    public String homeAssist { get; set; }
    @AuraEnabled
    public Boolean servAdicionais { get; set; }
    @AuraEnabled
    public Boolean isActive { get; set; }
  }

  public class DatatableInfos {
    public List<DataTableColumns> lstDataTableColumns { get; set; }
    public String fieldsSelect { get; set; }

    public DatatableInfos() {
      lstDataTableColumns = new List<DataTableColumns>();
    }
  }

  private static DataTableColumns getPreviewColumn() {
    TypeAttributes typeAtts = new TypeAttributes('utility:add', '', false, 'preview', 'bare');

    return new DataTableColumns('', '', 'button-icon', true, 30, typeAtts);
  }

  private static DatatableInfos getFieldsFromFieldSet() {
    Schema.SObjectType objType = Schema.getGlobalDescribe().get(OBJ_NAME);
    Schema.DescribeSObjectResult describeObjResult = objType.getDescribe();
    Schema.FieldSet fsObj = describeObjResult.FieldSets.getMap()
      .get(FIELD_SET_OFFER_BOOK);

    List<DataTableColumns> lsDataColumns = new List<DataTableColumns>();
    List<String> lsFieldsToQuery = new List<String>();

    DatatableInfos dbInfos = new DatatableInfos();
    //Inclusão da coluna do botão preview
    lsDataColumns.add(getPreviewColumn());

    for (Schema.FieldSetMember fieldMember : fsObj.getFields()) {
      String dataType = String.valueOf(fieldMember.getType()).toLowerCase();

      DataTableColumns dataCols = new DataTableColumns(
        String.valueOf(fieldMember.getLabel()),
        String.valueOf(fieldMember.getFieldPath()),
        String.valueOf(fieldMember.getType()).toLowerCase(),
        true
      );

      lsDataColumns.add(dataCols);
      lsFieldsToQuery.add(
        dataType == 'datetime'
          ? 'FORMAT(' + String.valueOf(fieldMember.getFieldPath()) + ')'
          : String.valueOf(fieldMember.getFieldPath())
      );
    }

    dbInfos.lstDataTableColumns = lsDataColumns;
    dbInfos.fieldsSelect = String.join(lsFieldsToQuery, ',');

    return dbInfos;
  }

  @AuraEnabled(Cacheable=true)
  public static PagedResult getOffers(Filters filters, Integer pageNumber) {
    String whereClause,
      offerGroup,
      technology,
      bundleType,
      broadBand,
      tvAttribute,
      promotionGroup,
      homeAssist,
      key = '';
    Boolean isActive, servAdicionais;
    String[] criteria = new List<String>{};

    String recordTypeServAdicionais = Schema.SObjectType.Offer__c.getRecordTypeInfosByDeveloperName()
      .get('ServicosAdicionais')
      .getRecordTypeId();
    String recordTypeOfferBook = Schema.SObjectType.Offer__c.getRecordTypeInfosByDeveloperName()
      .get('OfferBook')
      .getRecordTypeId();

    if (filters != null) {
      isActive = filters.isActive;
      criteria.add('IsActive__c = :isActive');

      servAdicionais = filters.servAdicionais;
      if (servAdicionais)
        criteria.add('RecordTypeId = :recordTypeServAdicionais');
      else
        criteria.add('RecordTypeId = :recordTypeOfferBook');

      if (!String.isEmpty(filters.searchKey)) {
        key = '%' + filters.searchKey + '%';
        criteria.add('FixedCampaignRTD__c LIKE :key');
      }

      if (filters.offerGroup != null && filters.offerGroup != '') {
        offerGroup = filters.offerGroup;
        criteria.add('OfferGroup__c = :offerGroup');
      }
      if (filters.technology != null && filters.technology != '') {
        technology = filters.technology;
        criteria.add('Technology__c = :technology');
      }
      if (filters.bundleType != null && filters.bundleType != '') {
        bundleType = filters.bundleType;
        criteria.add('BundleType__c = :bundleType');
      }
      if (filters.broadBand != null && filters.broadBand != '') {
        broadBand = filters.broadBand;
        criteria.add('BroadBandAttribute__c = :broadBand');
      }
      if (filters.tvAttribute != null && filters.tvAttribute != '') {
        tvAttribute = filters.tvAttribute;
        criteria.add('TVAttribute__c = :tvAttribute');
      }
      if (filters.promotionGroup != null && filters.promotionGroup != '') {
        promotionGroup = filters.promotionGroup;
        criteria.add('PromotionGroup__c = :promotionGroup');
      }
      if (filters.homeAssist != null && filters.homeAssist != '') {
        homeAssist = filters.homeAssist;
        if (homeAssist.equalsIgnoreCase('y'))
          criteria.add('HomeAssist__c = true');
        else
          criteria.add('HomeAssist__c = false');
      }
      if (criteria.size() > 0) {
        whereClause = 'WHERE ' + String.join(criteria, ' AND ');
      }
    }

    Integer pageSize = OfferController.PAGE_SIZE;
    Integer offset = (pageNumber - 1) * pageSize;
    DatatableInfos dbInfos = getFieldsFromFieldSet();

    PagedResult result = new PagedResult();
    result.pageSize = pageSize;
    result.pageNumber = pageNumber;
    result.lsColumns = dbInfos.lstDataTableColumns;
    result.totalItemCount = Database.countQuery(
      'SELECT count() FROM Offer__c ' + whereClause
    );

    List<Offer__c> offers = Database.query(
      ' SELECT ID, Description__c, ' +
      dbInfos.fieldsSelect +
      ' FROM Offer__c ' +
      whereClause +
      ' ORDER BY Name LIMIT :pageSize OFFSET :offset'
    );

    result.records = offers;

    return result;
  }

  @AuraEnabled(cacheable=true)
  public static List<Offer__c> getAdditionalServices() {
    String recordTypeServAdicionais = Schema.SObjectType.Offer__c.getRecordTypeInfosByDeveloperName()
      .get('ServicosAdicionais')
      .getRecordTypeId();
      
    return [SELECT ID, FixedCampaignRTD__c,TotalPrice__c 
            FROM Offer__c 
            WHERE RecordTypeId = :recordTypeServAdicionais 
            AND IsActive__c = true
            ORDER BY FixedCampaignRTD__c ASC];
  }
}