force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/BroadBandAttribute__c.field-meta.xml
<CustomField>
    <fullName>BroadBandAttribute__c</fullName>
    <description>Velocidade da Banda Larga</description>
    <label>Velocidade Banda Larga</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Technology__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>600</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/BroadbandDescription__c.field-meta.xml
<CustomField>
    <fullName>BroadbandDescription__c</fullName>
    <description>Descrição da Oferta Banda Larga</description>
    <label>Descrição Oferta Banda Larga</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/BroadBandDiscount__c.field-meta.xml
<CustomField>
    <fullName>BroadBandDiscount__c</fullName>
    <description>Desconto do plano da Banda Larga</description>
    <label>Desconto Banda Larga</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Cabinet__c.field-meta.xml
<CustomField>
    <fullName>Cabinet__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo para marcar se as ofertas possuem uma oferta de armario.</description>
    <label>Armário</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/CreditScoreCharacteristicOffer__c.field-meta.xml
<CustomField>
    <fullName>CreditScoreCharacteristicOffer__c</fullName>
    <description>Score de Crédito do cliente recuperado via API de consulta de credito.</description>
    <label>Score de Crédito</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/FixedCampaignRTD__c.field-meta.xml
<CustomField>
    <fullName>FixedCampaignRTD__c</fullName>
    <description>Descrição da campanha.</description>
    <label>Campanha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/FixedLineDescription__c.field-meta.xml
<CustomField>
    <fullName>FixedLineDescription__c</fullName>
    <description>Descrição da Oferta Voz</description>
    <label>Descrição Oferta Voz</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/FixedLineDiscount__c.field-meta.xml
<CustomField>
    <fullName>FixedLineDiscount__c</fullName>
    <description>Desconto do plano de Voz fixo</description>
    <label>Desconto Voz</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/FixedLinePlanAttribute__c.field-meta.xml
<CustomField>
    <fullName>FixedLinePlanAttribute__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para marcas ofertas que contemplam plano de Voz fixo</description>
    <label>Plano de Voz</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instruções</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo para marcar ofertas ativas.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobileDescription__c.field-meta.xml
<CustomField>
    <fullName>MobileDescription__c</fullName>
    <description>Descrição da Oferta Móvel</description>
    <label>Descrição Oferta Móvel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobileInternetDescription__c.field-meta.xml
<CustomField>
    <fullName>MobileInternetDescription__c</fullName>
    <description>Descrição da Oferta Móvel Internet</description>
    <label>Descrição Oferta Móvel Internet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobilePlan__c.field-meta.xml
<CustomField>
    <fullName>MobilePlan__c</fullName>
    <label>Plano Móvel</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/MobilePriceDiscount__c.field-meta.xml
<CustomField>
    <fullName>MobilePriceDiscount__c</fullName>
    <description>Valor do desconto móvel para ofertas de alta</description>
    <label>Desconto Móvel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/OfferCardDescription__c.field-meta.xml
<CustomField>
    <fullName>OfferCardDescription__c</fullName>
    <description>Campo utilizado para exibir a descrição das ofertas no card do componente de ofertas customizado</description>
    <formula>IF(CONTAINS(&quot;Fixa:AcquisitionFixed:BaseFixed&quot;, RecordType.DeveloperName),
IF(FixedLinePlanAttribute__c = False,&apos;&apos;,FixedLineDescription__c&amp;&apos; &apos;&amp;BR()&amp;BR())&amp;
IF(TVDescription__c = &apos;&apos;,TEXT(TVAttribute__c)&amp;&apos; &apos;&amp;BR()&amp;BR(),TVDescription__c&amp;&apos; &apos;&amp;BR()&amp;BR())&amp;
IF(TEXT(BroadBandAttribute__c) = &apos;&apos;,&apos;&apos;,TEXT(BroadBandAttribute__c)&amp;&apos; Mbps &apos;&amp;BroadbandDescription__c),


IF(RecordType.DeveloperName = &apos;Movel&apos;,
MobileDescription__c&amp;&apos; &apos;&amp;BR()&amp;MobileInternetDescription__c,&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descrição da Oferta</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/PlanTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>PlanTotalPrice__c</fullName>
    <label>Preço Total do Planos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <label>Sistema de Origem</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atlys</fullName>
            </value>
            <value>
                <fullName>Vivo Next</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Tecnologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTTC</fullName>
            </value>
            <value>
                <fullName>FTTH</fullName>
            </value>
            <value>
                <fullName>XDSL</fullName>
            </value>
            <value>
                <fullName>FTTH/FTTC</fullName>
                <isActive>false</isActive>
                <label>FTTH/FTTC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Preço Final</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TVAttribute__c.field-meta.xml
<CustomField>
    <fullName>TVAttribute__c</fullName>
    <description>Nome do pacote de TV</description>
    <label>Plano de TV</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plano 1</fullName>
            </value>
            <value>
                <fullName>Plano 2</fullName>
            </value>
            <value>
                <fullName>Plano 3</fullName>
            </value>
            <value>
                <fullName>Plano 4</fullName>
            </value>
            <value>
                <fullName>Plano 5</fullName>
            </value>
            <value>
                <fullName>Vivo Play Básico</fullName>
            </value>
            <value>
                <fullName>Vivo Play Completo</fullName>
            </value>
            <value>
                <fullName>Full HD Futebol</fullName>
            </value>
            <value>
                <fullName>Vivo Play Padrão</fullName>
            </value>
            <value>
                <fullName>Vivo Play Essencial</fullName>
            </value>
            <value>
                <fullName>Super HD Futebol</fullName>
            </value>
            <value>
                <fullName>Vivo Play Avançado</fullName>
            </value>
            <value>
                <fullName>Ultimate HD Futebol</fullName>
            </value>
            <value>
                <fullName>Vivo Play Ultra</fullName>
            </value>
            <value>
                <fullName>Ultra HD Futebol</fullName>
            </value>
            <value>
                <fullName>Ultimate HD</fullName>
            </value>
            <value>
                <fullName>Standard HD</fullName>
            </value>
            <value>
                <fullName>Super HD</fullName>
            </value>
            <value>
                <fullName>Ultra HD</fullName>
            </value>
            <value>
                <fullName>Full HD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TVDescription__c.field-meta.xml
<CustomField>
    <fullName>TVDescription__c</fullName>
    <description>Descrição da Oferta TV</description>
    <label>Descrição Oferta TV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/TVDiscount__c.field-meta.xml
<CustomField>
    <fullName>TVDiscount__c</fullName>
    <description>Desconto do plano de TV</description>
    <label>Desconto TV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/WhiteListCharacteristicOffer__c.field-meta.xml
<CustomField>
    <fullName>WhiteListCharacteristicOffer__c</fullName>
    <description>Campo utilizado para funcionalidade whitelist em ofertas de alta</description>
    <label>Características WhiteList</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VERMELHO</fullName>
            </value>
            <value>
                <fullName>AMARELO</fullName>
            </value>
            <value>
                <fullName>VERDE 1</fullName>
            </value>
            <value>
                <fullName>VERDE 2</fullName>
            </value>
            <value>
                <fullName>VERDE 3</fullName>
            </value>
            <value>
                <fullName>VERDE 4</fullName>
            </value>
            <value>
                <fullName>VERDE 5</fullName>
            </value>
            <value>
                <fullName>VERDE 6</fullName>
            </value>
            <value>
                <fullName>VERDE 7</fullName>
            </value>
            <value>
                <fullName>VERDE 8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/recordTypes/AltaMovel.recordType-meta.xml
<RecordType>
    <fullName>AltaMovel</fullName>
    <active>true</active>
    <description>Ofertas de Alta para Móvel</description>
    <label>Alta Móvel</label>
</RecordType>

force-app/main/default/classes/OfferDAO.cls
public class OfferDAO {
    //trocar o whiteList por score de credito
    public static List<Offer__c> getOfferAltaMovelByCreditScore(String accountCreditScore) {
        return [
            SELECT Id, 
                MobilePlan__c,
                TotalPrice__c, 
                MobileDescription__c, 
                MobileInternetDescription__c, 
                MobilePriceDiscount__c, 
                WhiteListCharacteristicOffer__c, 
                SourceSystem__c 
            FROM 
                Offer__c 
            WHERE 
                RecordType.DeveloperName = 'AltaMovel' 
            AND IsActive__c = true 
            // AND WhiteListCharacteristicOffer__c INCLUDES (:whitelist) 
            AND CreditScoreCharacteristicOffer__c INCLUDES(:accountCreditScore)
            ORDER BY TotalPrice__c DESC];
    }  

    public static List<Offer__c> getOfferMovelITV(String offerType) {
        return [
            SELECT Id,
                TotalPrice__c, 
                MobileDescription__c,
                Instructions__c	
            FROM 
                Offer__c 
            WHERE 
                RecordType.DeveloperName =: offerType 
            AND IsActive__c = true 
            ORDER BY TotalPrice__c ASC];
    } 

    public static List<Offer__c> getEnabledFilteredOffers( List<String> setCityCategories, 
                            String accTechnology, List<String> setOfferLevel, List<Boolean> setCabinet, String offerType, String broadBand, String tvPlan, String fixedLineDesc, Boolean order){

        //System.assert(false, 'categories ' + setCityCategories + ' technology ' + accTechnology + ' Offer ' + setOfferLevel + ' Cabinet ' + setCabinet + ' offertype ' + offerType + 'broadband' + broadBand + ' tvPlan ' + tvPlan + ' linedesc ' + fixedLineDesc + ' order ' + order);
        if(order){
            return  [
            SELECT Id, 
            Cabinet__c, 
            FixedLineDiscount__c, 
            FixedCampaignRTD__c, 
            BroadBandDiscount__c, 
            TVDiscount__c,
            FixedLineDescription__c, 
            BroadbandDescription__c, 
            TVDescription__c,
            OfferCardDescription__c, 
            PlanTotalPrice__c,
            Technology__c, 
            BroadBandAttribute__c, 
            FixedLinePlanAttribute__c, 
            TvAttribute__c, 
            OfferCityCategory__c, 
            TotalPrice__c, 
            BroadbandDiscountDuration__c, 
            FixedLineDiscountDuration__c, 
            TVDiscountDuration__c,
            BroadbandPromoPrice__c,
            TVPromoPrice__c,
            FixedLinePromoPrice__c
        FROM Offer__c 
        WHERE IsActive__c = true 
            AND OfferCityCategory__c IN: setCityCategories 
            AND Technology__c =: accTechnology 
            AND BroadBandAttribute__c =: broadBand 
            AND Cabinet__c IN: setCabinet  
            AND RecordType.DeveloperName =: offerType 
            AND OfferLevel__c IN: setOfferLevel 
            AND TVAttribute__c =: tvPlan 
            AND FixedLineDescription__c =: fixedLineDesc 
            ORDER BY TotalPrice__c ASC
        /*AND StatusDW__c = true*/];
        }else{
            return  [
            SELECT Id, 
            Cabinet__c, 
            FixedLineDiscount__c, 
            FixedCampaignRTD__c, 
            BroadBandDiscount__c, 
            TVDiscount__c,
            FixedLineDescription__c, 
            BroadbandDescription__c, 
            TVDescription__c,
            OfferCardDescription__c, 
            PlanTotalPrice__c,
            Technology__c, 
            BroadBandAttribute__c, 
            FixedLinePlanAttribute__c, 
            TvAttribute__c, 
            OfferCityCategory__c, 
            TotalPrice__c, 
            BroadbandDiscountDuration__c, 
            FixedLineDiscountDuration__c, 
            TVDiscountDuration__c,
            BroadbandPromoPrice__c,
            TVPromoPrice__c,
            FixedLinePromoPrice__c
        FROM Offer__c 
        WHERE IsActive__c = true 
            AND OfferCityCategory__c IN: setCityCategories 
            AND Technology__c =: accTechnology 
            AND BroadBandAttribute__c =: broadBand 
            AND Cabinet__c IN: setCabinet  
            AND RecordType.DeveloperName =: offerType 
            AND OfferLevel__c IN: setOfferLevel 
            AND TVAttribute__c =: tvPlan 
            AND FixedLineDescription__c =: fixedLineDesc 
            ORDER BY TotalPrice__c DESC
        /*AND StatusDW__c = true*/];
        } 
    }
    
    public static List<Offer__c> getOffersById(Set<id> setOffers) {
        List<Offer__c> ltOffer = [
                        SELECT 
                            Id, 
                            FixedLineDescription__c, 
                            BroadbandDescription__c, 
                            RecordType.DeveloperName 
                        FROM
                            Offer__c 
                        WHERE 
                            Id IN :setOffers];
        return ltOffer;
    }
    


    public static List<Offer__c> getOfferMobileByOrder(Set<String> setMainProductDescription,String recordType, String accCustomerType){
        return [SELECT Id, MobilePlan__c,TotalPrice__c, MobileDescription__c, MobileInternetDescription__c, SourceSystem__c, DDDOferta__c 
            FROM Offer__c 
            WHERE IsActive__c = true 
            AND MobilePlan__c IN: setMainProductDescription 
            AND RecordType.DeveloperName = :recordType 
            AND CustomerType__c includes ( :accCustomerType )
            ORDER BY TotalPrice__c DESC];
    }
}