force-app/main/default/objects/ChatIA__c/ChatIA__c.object-meta.xml
<CustomObject>
    <label>Chat IA</label>
    <nameField>
        <label>Nome de Chat IA</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat IA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChatIA__c/fields/History__c.field-meta.xml
<CustomField>
    <fullName>History__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HIstory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChatIA__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Chat_IA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionSuggestion__c/QuestionSuggestion__c.object-meta.xml
<CustomObject>
    <label>Question Suggestion</label>
    <nameField>
        <label>Question Suggestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Suggestions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/StandardQuestionSuggestion__mdt/StandardQuestionSuggestion__mdt.object-meta.xml
<CustomObject>
    <description>This is the standard question suggetions when no record are found in the specific object.</description>
    <label>Standard Question Suggestion</label>
    <pluralLabel>Standard Question Suggestions</pluralLabel>
</CustomObject>

force-app/main/default/objects/StandardQuestionSuggestion__mdt/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login de rede</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChatIASelector.cls
public with sharing class ChatIASelector {
    private final static ChatIASelector instance = new ChatIASelector();

    private ChatIASelector() {}

    public static ChatIASelector getInstance(){
        return instance;
    }

    public List<ChatIA__c> getLastChatIA(String userId) {
        return [SELECT Id, Session__c, History__c, Active__c, Backup__c, Usuario__c FROM ChatIA__c WHERE Usuario__c =:userId ORDER BY CreatedDate DESC LIMIT 1];
    }

    public List<QuestionSuggestion__c> getQuestionSuggestion() {
        return [SELECT Id, Question__c, Order__c FROM QuestionSuggestion__c ORDER BY Order__c LIMIT 3];
    }

    public List<StandardQuestionSuggestion__mdt> getStandardQuestionSuggestion(Integer quantityNeeded) {
        return [SELECT Id, Question__c, Order__c FROM StandardQuestionSuggestion__mdt ORDER BY Order__c LIMIT :quantityNeeded];
    }
    public List<PermissionSetAssignment> getPermission(String userId) {
        return [SELECT Id, AssigneeId, PermissionSet.Name FROM PermissionSetAssignment WHERE AssigneeId =: userId AND PermissionSet.Name = 'ChatIA'];
    }
    public User getUser(String userId) {
        //para B2B usar BI_BR_Login_de_rede__c
        return [SELECT Id, Name, Email, Login__c, Profile.Name FROM User WHERE Id =: userId];
    }
}