force-app/main/default/objects/Timer__c/Timer__c.object-meta.xml
<CustomObject>
    <label>Timer</label>
    <nameField>
        <label>Número da linha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timer__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>OrderId</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Timers</relationshipLabel>
    <relationshipName>Timers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timer__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Início</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
                <default>true</default>
                <label>Aberto</label>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Timer Cadastro</fullName>
            </value>
            <value>
                <fullName>Timer PID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimerParametros__mdt/TimerParametros__mdt.object-meta.xml
<CustomObject>
    <description>US-418-1
@autor: carlosaraujo@deloitte.com
@date: 26/13/2023</description>
    <label>Timer Parâmetros</label>
    <pluralLabel>Timers Parâmetros</pluralLabel>
</CustomObject>

force-app/main/default/objects/TimerParametros__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Código</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimerParametros__mdt/fields/IntegrationProcName__c.field-meta.xml
<CustomField>
    <fullName>IntegrationProcName__c</fullName>
    <label>Nome da Integration Procedure</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimerParametros__mdt/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <label>Processo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimerParametros__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SuspendOrderBatch.cls
/**
 * Batch responsável por iniciar processo de suspensão
 * Criação: US-418 - 26/01/2023
 * @author: diogsousa@deloitte.com & carlosaraujo@deloitte.com
 */
public class SuspendOrderBatch implements Database.Batchable<sObject> { 
    
    Map<String,  TimerParametros__mdt> mapParamsMdt = new Map<String,  TimerParametros__mdt>();
    String timerType;
    
    public SuspendOrderBatch(String processName, String type){
        List<TimerParametros__mdt> params = [
            SELECT Code__c, Value__c, IntegrationProcName__c 
            FROM TimerParametros__mdt 
            WHERE Process__c =: processName
        ];
        timerType = type;
        for (TimerParametros__mdt mdt : params) {
            mapParamsMdt.put(mdt.Code__c, mdt);   
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext info) {        
        return Database.getQueryLocator('SELECT StartDate__c, Type__c, OrderId__c FROM Timer__c WHERE Status__c = \'Aberto\' AND Type__c = \'' + timerType + '\'');
    }
    
    public void execute(Database.BatchableContext info, List<Timer__c> timers) {
        List<String> lstOrderId = new List<String>();   
        for (Timer__c timer : timers) {
            if (mapParamsMdt.containsKey(timer.Type__c)) {
                Integer valueInDays = Integer.valueOf(mapParamsMdt.get(timer.Type__c).Value__c) / 24;
                Date startDate = date.newinstance(timer.StartDate__c.year(), timer.StartDate__c.month(), timer.StartDate__c.day());

                if (valueInDays <= (startDate.daysBetween(System.today()))) {
                    lstOrderId.add(timer.OrderId__c);
                }
            }
		}

        callIP(mapParamsMdt.get(this.timerType).IntegrationProcName__c, lstOrderId);
    }
    public void finish(Database.BatchableContext info) {
		System.debug('SuspendOrderBatch >> finish');
    }

    /**
	 * @author carlosaraujo@deloitte.com & diogsousa@deloitte.com
     * @modify_date 05/06/2023
	 * @description Chama a Integration Procedure
     * @param procedureName Nome da Integration Procedure
     * @param lstOrderId Ids da ordem vinculada ao Timer [Timer__c]
	 */
    public void callIP(String procedureName, List<String> lstOrderId){
        Map <String, Object> ipInput = new Map <String, Object> ();
        Map <String, Object> ipOutput = new Map <String, Object> ();
        Map <String, Object> ipOptions = new Map <String, Object> ();
        
        /* Populating input map for an Integration Procedure. Follow whatever structure your VIP expects */
        ipInput.put('ListOrderId', lstOrderId);
        /* Call the IP via runIntegrationService, and save the output to ipOutput */
        ipOutput = (Map <String, Object>) vlocity_cmt.IntegrationProcedureService.runIntegrationService(procedureName, ipInput, ipOptions);  
        System.debug('IP Result: ' + ipOutput);      
    }
}