force-app/main/default/objects/Timer__c/Timer__c.object-meta.xml
<CustomObject>
    <label>Timer</label>
    <nameField>
        <label>Número da linha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timer__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>OrderId</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Timers</relationshipLabel>
    <relationshipName>Timers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timer__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Início</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
                <default>true</default>
                <label>Aberto</label>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Timer Cadastro</fullName>
            </value>
            <value>
                <fullName>Timer PID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SuspendOrderBatchTest.cls
/**
 * Classe de teste responsável por testar a classe: SuspendOrderBatch
 * Criação: US-418 - 26/01/2023
 * @author: diogsousa@deloitte.com 
 */
@isTest
private class SuspendOrderBatchTest {
    @testSetup
    static void setup() {
         //Account
        Account account = new Account();
        account.name = 'testAccount';
        insert account;

        //Order
        Order order = new Order();
        order.AccountId = account.Id;
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        order.Pricebook2Id = test.getStandardPricebookId();
        insert order;
        
        //Timer__c
        Timer__c timerTest = new Timer__c();
        timerTest.Name = 'Teste class';
        timerTest.OrderId__c =  order.Id;
        timerTest.StartDate__c = System.now().addDays(-11);
        timerTest.Type__c = 'Timer Cadastro';
        insert timerTest;
    }
    @isTest static void test() {
        Test.startTest();
        SuspendOrderBatch b = new SuspendOrderBatch('Suspensão Hab Remota', 'Timer Cadastro');
        System.assertEquals('Aberto', [select Status__c from Timer__c where Name = 'Teste class' and Status__c = 'Aberto' LIMIT 1].Status__c);
        Id batchId = Database.executeBatch(b);
        Test.stopTest();
        System.debug([select Status__c from Timer__c where Name = 'Teste class' and Status__c = 'Aberto' LIMIT 1]);
        
    }
}