force-app/main/default/objects/Timer__c/Timer__c.object-meta.xml
<CustomObject>
    <label>Timer</label>
    <nameField>
        <label>Número da linha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timer__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>OrderId</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Timers</relationshipLabel>
    <relationshipName>Timers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timer__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Início</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
                <default>true</default>
                <label>Aberto</label>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Timer Cadastro</fullName>
            </value>
            <value>
                <fullName>Timer PID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SuspendOrderScheduleTest.cls
@isTest
private class SuspendOrderScheduleTest {
    
    static testmethod void testScheduledJob() {
        //Account
        Account account = new Account();
        account.name = 'testAccount';
        insert account;

        //Order
        Order order = new Order();
        order.AccountId = account.Id;
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        order.Pricebook2Id = test.getStandardPricebookId();
        insert order;
        
        //Timer__c
        Timer__c timerTest = new Timer__c();
        timerTest.Name = 'Teste class';
        timerTest.OrderId__c =  order.Id;
        timerTest.StartDate__c = System.now().addDays(-11);
        timerTest.Type__c = 'Timer Cadastro';
        insert timerTest;
        
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('ScheduledApexTest',
            '0 0 1 * * ?',
            new SuspendOrderSchedule());
        // Verify the scheduled job has not run yet.
        //System.assertEquals('Fechado', [select Status__c from Timer__c where Name = 'Teste class' and Status__c = 'Fechado' LIMIT 1].Status__c);
        // Stopping the test will run the job synchronously
        Test.stopTest();
        
        //System.assertEquals('Fechado', [select Status__c from Timer__c where Name = 'Teste class' and Status__c = 'Fechado' LIMIT 1].Status__c);
    }
}