force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <!---->
    <description>Criação de cluster (agrupamento) para realizar notificações aos clientes</description>
    <label>Cluster</label>
    <nameField>
        <label>Nome do cluster</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>Término</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Prioridade</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Início</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Técnico</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Contas</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Desconto</fullName>
                <isActive>false</isActive>
                <label>Desconto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cluster__c/recordTypes/Cluster.recordType-meta.xml
<RecordType>
    <fullName>Cluster</fullName>
    <active>true</active>
    <label>Cluster</label>
</RecordType>

force-app/main/default/classes/ClusterTestFactory.cls
public class ClusterTestFactory {
     private Cluster__c fCluster;
    
    public ClusterTestFactory( Cluster__c aCluster ){
        fCluster = aCluster;
    }
    
    public static ClusterTestFactory start(){
        return new ClusterTestFactory (
            new Cluster__c(
                Name = 'Cluster Test',
                Type__c = 'Comercial',
                Priority__c = 1,
                Start__c = system.today(),
                End__c = system.today()
            ) );
    }
    public ClusterTestFactory isPriority(){
        fCluster.Name = 'teste produto movel';
        fCluster.Type__c = 'Comercial';
        fCluster.Priority__c = 1;
        fCluster.Type__c = 'Movel';
        fCluster.Start__c = system.today();
        fCluster.End__c = system.today();

        return this;
    }
    
   
    public Cluster__c create() {
        insert fCluster;
        return fCluster;
    }
    	public Cluster__c build() {
		return fCluster;
	}
    

}