force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <!---->
    <description>Criação de cluster (agrupamento) para realizar notificações aos clientes</description>
    <label>Cluster</label>
    <nameField>
        <label>Nome do cluster</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>Término</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Prioridade</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Início</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Técnico</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Contas</fullName>
            </value>
            <value>
                <fullName>Retenção</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Desconto</fullName>
                <isActive>false</isActive>
                <label>Desconto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClusterTriggerTest.cls
@isTest
public class ClusterTriggerTest {
     @testSetup 
    static void setup(){
        
         Cluster__c lCluster = ClusterTestFactory.start().create();   
         Cluster__c lClusterIsPriority = ClusterTestFactory.start().isPriority().build(); 

         
    }
    @isTest
    public static void insertClusterTest(){
        
        Cluster__c lCluster = [ SELECT Id, Priority__c FROM Cluster__c LIMIT 1];   
        
        Test.startTest();
        
        Database.update(lCluster);
        
        Test.stopTest();

    } 
    @isTest
    public static void insertClusterTestError(){
        Cluster__c fCluster = new Cluster__c();
            fCluster.Name = 'teste produto movel';
            fCluster.Type__c = 'Comercial';
            fCluster.Priority__c = 1;
            fCluster.Type__c = 'Outros';
            fCluster.Start__c = system.today();
            fCluster.End__c = system.today();
            

        Test.startTest();
        
        try{
            Database.insert(fCluster);
        } catch(Exception e){
            system.assert(e.getMessage().contains('Esta prioridade já existe. Insira um novo valor.'));
        }        
        
        
        Test.stopTest();

    } 


}