force-app/main/default/objects/CartAccount__c/CartAccount__c.object-meta.xml
<CustomObject>
    <description>Armazena registros de ofertas aceitas e estatísticas de acesso aos registros de Account.</description>
    <label>Oferta Oferecida</label>
    <nameField>
        <displayFormat>OF-{00000000}</displayFormat>
        <label>Id Oferta Oferecida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Oferecidas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CartAccount__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento com a Conta em que foi executada a ação.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ofertas Oferecidas</relationshipLabel>
    <relationshipName>CartAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Desconto total da proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Preço total da proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UserIndicatorControllerTest.cls
/*
---------------------------------------------------
@authors - Pedro Salles 
@company - Telefonica 
@date - 27/04/2020
@description - Classe de Teste da Controller do componente
de userIndicator
---------------------------------------------------

*/
@isTest
public class UserIndicatorControllerTest {    
	@testSetup 
    static void setup(){
        Account lAccount = AccountTestFactory.start().isAccount().create();
        Account lAccountOfferAlta = AccountTestFactory.start().isAccount().create();
        
        CartAccount__c cartAccount = cartAccountTestFactory.start(lAccount.Id).isUseIndicator(lAccount.Id).create();
    
        
    }
    @isTest
    public static void getUserIndicator(){
        Account lAccount = [ SELECT Id, OwnerId FROM Account LIMIT 1];
        
        Test.startTest();   
        CartAccount__c lUserIndicator = userIndicatorController.insertIndicator( lAccount.Id, lAccount.OwnerId);
        Test.stopTest();
       
    } 
    @isTest
    public static void getUserIndicatorCart(){
        CartAccount__c ltCart = [SELECT  Id, AccountId__c, OwnerId, CreatedDate, TotalPrice__c, Discount__c
                                         FROM CartAccount__c ];
        Id idAccount = ltCart.AccountId__c;
        Account lAccount = [ SELECT Id,Name, OwnerId FROM Account WHERE Id !=: idAccount];
        
        Test.startTest();   
        CartAccount__c lUserIndicator = userIndicatorController.insertIndicator( lAccount.Id, lAccount.OwnerId);
        Test.stopTest();
       
    } 
}