force-app/main/default/objects/CartAccount__c/CartAccount__c.object-meta.xml
<CustomObject>
    <description>Armazena registros de ofertas aceitas e estatísticas de acesso aos registros de Account.</description>
    <label>Oferta Oferecida</label>
    <nameField>
        <displayFormat>OF-{00000000}</displayFormat>
        <label>Id Oferta Oferecida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Oferecidas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CartAccount__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento com a Conta em que foi executada a ação.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ofertas Oferecidas</relationshipLabel>
    <relationshipName>CartAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Desconto total da proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Preço total da proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CartAccountDAO.cls
public with sharing class CartAccountDAO {

    public static CartAccount__c getCartByIdUserRecordTypeCreatedToday(Id accountId, Id userId, String recordType){
        List<CartAccount__c> lst = getListCartByIdUserRecordTypeCreatedToday(new Set<Id>{accountId}, userId, recordType);
        return lst.isEmpty() ? null : lst[0];
    }

    public static List<CartAccount__c> getListCartByIdUserRecordTypeCreatedToday(Set<Id> setAccountId, Id userId, String recordType){
        return[
            SELECT  Id, 
                    AccountId__c, 
                    OwnerId, 
                    CreatedDate, 
                    TotalPrice__c, 
                    Discount__c
            FROM 
                CartAccount__c 
            WHERE 
                AccountId__c IN: setAccountId 
                AND CreatedDate = TODAY 
                AND OwnerId =: userId
                AND RecordType.DeveloperName =: recordType 
        ];
    }

    public static Integer getCartOnTheDay(Id accountId, String recortType){
        return[
            SELECT 
                count()
            FROM
                CartAccount__c
            WHERE
                CreatedDate = TODAY
                AND AccountId__c =: accountId
                AND RecordType.DeveloperName =: recortType
        ];
    }
}