force-app/main/default/objects/CartAccount__c/CartAccount__c.object-meta.xml
<CustomObject>
    <description>Armazena registros de ofertas aceitas e estatísticas de acesso aos registros de Account.</description>
    <label>Oferta Oferecida</label>
    <nameField>
        <displayFormat>OF-{00000000}</displayFormat>
        <label>Id Oferta Oferecida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Oferecidas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CartAccount__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento com a Conta em que foi executada a ação.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ofertas Oferecidas</relationshipLabel>
    <relationshipName>CartAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/recordTypes/SelectCart.recordType-meta.xml
<RecordType>
    <fullName>SelectCart</fullName>
    <active>true</active>
    <label>Carrinho</label>
</RecordType>

force-app/main/default/objects/CartAccount__c/recordTypes/UseIndicator.recordType-meta.xml
<RecordType>
    <fullName>UseIndicator</fullName>
    <active>true</active>
    <label>Utilidade</label>
</RecordType>

force-app/main/default/classes/CartAccountTestFactory.cls
/*
---------------------------------------------------
@authors - Pedro Salles 
@company - Telefonica 
@date - 27/04/2020
@description - Classe de Teste da Controller do componente
de userIndicator
---------------------------------------------------

*/
public class CartAccountTestFactory {
     private CartAccount__c fCartAccount;
    
    public cartAccountTestFactory( CartAccount__c aCartAccount ){
        fCartAccount = aCartAccount;
    }
    
    public static cartAccountTestFactory start(Id aAccountId ){
        return new cartAccountTestFactory (
			new CartAccount__c(
				AccountId__c = aAccountId
        ) );
    }
    
    public cartAccountTestFactory isUseIndicator(Id aAccountId){
    	fCartAccount.RecordTypeId = Schema.SObjectType.CartAccount__c.getRecordTypeInfosByDeveloperName().get('UseIndicator').getrecordTypeId();
        fCartAccount.AccountId__c = aAccountId;
        return this;
    }
    public cartAccountTestFactory isInsertCart(Id aAccountId){
    	fCartAccount.RecordTypeId = Schema.SObjectType.CartAccount__c.getRecordTypeInfosByDeveloperName().get('SelectCart').getrecordTypeId();
        fCartAccount.AccountId__c = aAccountId;
        return this;
    }
    
	public CartAccount__c create() {
		insert fCartAccount;
		return fCartAccount;
	}


}