force-app/main/default/objects/CartAccount__c/CartAccount__c.object-meta.xml
<CustomObject>
    <description>Armazena registros de ofertas aceitas e estatísticas de acesso aos registros de Account.</description>
    <label>Oferta Oferecida</label>
    <nameField>
        <displayFormat>OF-{00000000}</displayFormat>
        <label>Id Oferta Oferecida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Oferecidas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CartAccount__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento com a Conta em que foi executada a ação.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ofertas Oferecidas</relationshipLabel>
    <relationshipName>CartAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/recordTypes/UseIndicator.recordType-meta.xml
<RecordType>
    <fullName>UseIndicator</fullName>
    <active>true</active>
    <label>Utilidade</label>
</RecordType>

force-app/main/default/classes/UserIndicatorController.cls
/*
---------------------------------------------------
@authors -  Pedro Salles 
@company - Telefonica 
@date - 24/04/2020
@description - Classe Controller do componente
Indicadores de Utilização dos usuários
---------------------------------------------------

*/
public class UserIndicatorController {
    
    @AuraEnabled
    public static CartAccount__c insertIndicator (id accountId, Id userId) {
        CartAccount__c insertIndicator = new CartAccount__c();
        
        List<CartAccount__c> findIndicator = [SELECT  Id, AccountId__c, OwnerId, CreatedDate
                                              FROM CartAccount__c 
                                              WHERE AccountId__c =: accountId 
                                              AND CreatedDate = TODAY
                                              AND OwnerId =: userId
                                              AND RecordType.DeveloperName = 'UseIndicator'];
        system.debug(findIndicator);
        if (findIndicator.size() <= 0){
            insertIndicator.AccountId__c = accountId;
            insertIndicator.RecordTypeId = Schema.SObjectType.CartAccount__c.getRecordTypeInfosByDeveloperName().get('UseIndicator').getrecordTypeId();
            insert insertIndicator;
            
        }   
        
        return insertIndicator;
    }
    
}