force-app/main/default/objects/CartAccount__c/CartAccount__c.object-meta.xml
<CustomObject>
    <description>Armazena registros de ofertas aceitas e estatísticas de acesso aos registros de Account.</description>
    <label>Oferta Oferecida</label>
    <nameField>
        <displayFormat>OF-{00000000}</displayFormat>
        <label>Id Oferta Oferecida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Oferecidas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CartAccount__c/fields/ChipAmount__c.field-meta.xml
<CustomField>
    <fullName>ChipAmount__c</fullName>
    <description>Campo para preenchimento da quantidade de chip para a alta Móvel RPA.</description>
    <label>Quantidade de Chip</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/OfferId__c.field-meta.xml
<CustomField>
    <fullName>OfferId__c</fullName>
    <externalId>true</externalId>
    <label>Id da Oferta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Campo para armazenar a mensagem de retorno do RPA.</description>
    <label>Motivo</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Campo de Status da negociação de Alta Móvel RPA.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RegistrationData</fullName>
                <label>Dados Cadastrais</label>
            </value>
            <value>
                <fullName>Address</fullName>
                <label>Dados de Endereço</label>
            </value>
            <value>
                <fullName>BillingData</fullName>
                <label>Dados Cobrança Faturamento</label>
            </value>
            <value>
                <fullName>SaleData</fullName>
                <label>Dados da Alta</label>
            </value>
            <value>
                <fullName>DeliveryAddress</fullName>
                <label>Endereço de Entrega</label>
            </value>
            <value>
                <fullName>AwaitingAcceptance</fullName>
                <label>Aguardando Aceite</label>
            </value>
            <value>
                <fullName>OfferAccepted</fullName>
                <label>Oferta Aceita</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CartOffer__c/CartOffer__c.object-meta.xml
<CustomObject>
    <label>Produto do Carrinho</label>
    <nameField>
        <displayFormat>Produto-{000000}</displayFormat>
        <label>Produto do Carrinho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do Carrinho</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CartOffer__c/fields/CartId__c.field-meta.xml
<CustomField>
    <fullName>CartId__c</fullName>
    <label>Carrinho</label>
    <referenceTo>CartAccount__c</referenceTo>
    <relationshipLabel>Produtos do Carrinho</relationshipLabel>
    <relationshipName>CartOffer</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CartOffer__c/fields/OfferId__c.field-meta.xml
<CustomField>
    <fullName>OfferId__c</fullName>
    <label>Oferta</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Ofertas do Carrinho</relationshipLabel>
    <relationshipName>CartOffer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CartOffer__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Campo para preenchimento da Razão do chip sendo vendido na Alta Móvel RPA.</description>
    <label>Razão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enabling</fullName>
                <label>Habilitação</label>
            </value>
            <value>
                <fullName>Portability</fullName>
                <label>Portabilidade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CartOffer__c/recordTypes/Chip.recordType-meta.xml
<RecordType>
    <fullName>Chip</fullName>
    <active>true</active>
    <description>Produto do tipo Chip</description>
    <label>Chip</label>
</RecordType>

force-app/main/default/objects/CartOffer__c/recordTypes/Fixed.recordType-meta.xml
<RecordType>
    <fullName>Fixed</fullName>
    <active>true</active>
    <description>Plano Fixa Ofertado</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/CartOffer__c/recordTypes/Mobile.recordType-meta.xml
<RecordType>
    <fullName>Mobile</fullName>
    <active>true</active>
    <description>Plano Móvel Ofertado</description>
    <label>Móvel</label>
</RecordType>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/recordTypes/AltaMovel.recordType-meta.xml
<RecordType>
    <fullName>AltaMovel</fullName>
    <active>true</active>
    <description>Ofertas de Alta para Móvel</description>
    <label>Alta Móvel</label>
</RecordType>

force-app/main/default/objects/Offer__c/recordTypes/Movel.recordType-meta.xml
<RecordType>
    <fullName>Movel</fullName>
    <active>true</active>
    <description>Ofertas Móvel de Retenção</description>
    <label>Móvel</label>
</RecordType>

force-app/main/default/classes/CartAccountTriggerTest.cls
@isTest
public class CartAccountTriggerTest {

    @testSetup 
    static void setup(){
        Account account = DataFactory.createAccount();
        insert account;

        List<Offer__c> lstOffer = new List<Offer__c>();

        lstOffer.add(DataFactory.createOfferMobile(account.Id, 'Movel'));
        lstOffer.add(DataFactory.createOfferMobile(account.Id, 'AltaMovel'));
        lstOffer.add(DataFactory.createOfferFixed(account.Id));

        insert lstOffer;

        CartAccount__c cartAccount = DataFactory.createCartAccount(account.Id);
        cartAccount.Status__c = 'SaleData';
        insert cartAccount;

        List<CartOffer__c> lstCartOffer = new List<CartOffer__c>();

        for (Offer__c itemLstOffer: lstOffer) {
            String recordTypeOffer = Schema.getGlobalDescribe().get('Offer__c').getDescribe().getRecordTypeInfosById().get(itemLstOffer.RecordTypeId).getDeveloperName();
            CartOffer__c cartOffer = DataFactory.createCartOffer(cartAccount.Id, itemLstOffer.Id);
            if (recordTypeOffer == 'Movel' || recordTypeOffer == 'AltaMovel') 
                cartOffer.RecordTypeId = Schema.SObjectType.CartOffer__c.getRecordTypeInfosByDeveloperName().get('Mobile').getrecordTypeId();
            else 
                cartOffer.RecordTypeId = Schema.SObjectType.CartOffer__c.getRecordTypeInfosByDeveloperName().get('Fixed').getrecordTypeId();
            lstCartOffer.add(cartOffer);
        }
        
        insert lstCartOffer;


    }

    @isTest
    public static void updateChipAmount(){      
        CartAccount__c cartAccount = [SELECT Id, ChipAmount__c FROM CartAccount__c LIMIT 1];

        Test.startTest();
        
        cartAccount.ChipAmount__c = 3;
        Database.update(cartAccount);
        cartAccount.ChipAmount__c = 2;
        Database.update(cartAccount);
        List<CartOffer__c> lstCartOffers = [SELECT CartId__c, OfferId__c, RecordType.DeveloperName FROM CartOffer__c WHERE CartId__c =: cartAccount.Id AND RecordType.DeveloperName = 'Chip'];
        System.assertEquals(2, lstCartOffers.size());
        
        Test.stopTest();
    }
    
    @isTest
    public static void updateReason(){      
        CartAccount__c cartAccount = [SELECT Id, ChipAmount__c, Status__c FROM CartAccount__c LIMIT 1];
        cartAccount.Status__c = 'RegistrationData';
        cartAccount.ChipAmount__c = 2;
        Database.update(cartAccount);

        List<CartOffer__c> lstCartOffers = [SELECT Reason__c FROM CartOffer__c WHERE CartId__c =: cartAccount.Id AND RecordType.DeveloperName = 'Chip'];
        CartOffer__c chip1 = lstCartOffers[0];
        CartOffer__c chip2 = lstCartOffers[1];
        chip1.Reason__c = 'Enabling';
        Database.update(chip1);
        chip2.Reason__c = 'Enabling';
        Database.update(chip2);  

        Test.startTest();
        cartAccount.Status__c = 'RegistrationData';
        Database.SaveResult result = Database.update(cartAccount);
        Test.stopTest();
        System.assert(result.isSuccess());

    } 

    @isTest
    public static void validaChipTest(){
        Test.startTest();
        Boolean hasFamilyPlan = true;
        Decimal chipAmount = 2;
      	Boolean result = CartAccountTriggerHandler.validaChip(hasFamilyPlan, chipAmount);        
        Test.stopTest();
        System.assertEquals(true, result);
    }
    
    @isTest
    public static void validaChipTestTwo(){
        Test.startTest();
        Boolean hasFamilyPlan = false;
        Decimal chipAmount = 2;
      	Boolean result = CartAccountTriggerHandler.validaChip(hasFamilyPlan, chipAmount);        
        Test.stopTest();
        System.assertEquals(true, result);
    }    
}