force-app/main/default/objects/CartAccount__c/CartAccount__c.object-meta.xml
<CustomObject>
    <description>Armazena registros de ofertas aceitas e estatísticas de acesso aos registros de Account.</description>
    <label>Oferta Oferecida</label>
    <nameField>
        <displayFormat>OF-{00000000}</displayFormat>
        <label>Id Oferta Oferecida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas Oferecidas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CartAccount__c/fields/ChipAmount__c.field-meta.xml
<CustomField>
    <fullName>ChipAmount__c</fullName>
    <description>Campo para preenchimento da quantidade de chip para a alta Móvel RPA.</description>
    <label>Quantidade de Chip</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/OfferId__c.field-meta.xml
<CustomField>
    <fullName>OfferId__c</fullName>
    <externalId>true</externalId>
    <label>Id da Oferta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Campo para armazenar a mensagem de retorno do RPA.</description>
    <label>Motivo</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CartAccount__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Campo de Status da negociação de Alta Móvel RPA.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RegistrationData</fullName>
                <label>Dados Cadastrais</label>
            </value>
            <value>
                <fullName>Address</fullName>
                <label>Dados de Endereço</label>
            </value>
            <value>
                <fullName>BillingData</fullName>
                <label>Dados Cobrança Faturamento</label>
            </value>
            <value>
                <fullName>SaleData</fullName>
                <label>Dados da Alta</label>
            </value>
            <value>
                <fullName>DeliveryAddress</fullName>
                <label>Endereço de Entrega</label>
            </value>
            <value>
                <fullName>AwaitingAcceptance</fullName>
                <label>Aguardando Aceite</label>
            </value>
            <value>
                <fullName>OfferAccepted</fullName>
                <label>Oferta Aceita</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CartOffer__c/CartOffer__c.object-meta.xml
<CustomObject>
    <label>Produto do Carrinho</label>
    <nameField>
        <displayFormat>Produto-{000000}</displayFormat>
        <label>Produto do Carrinho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do Carrinho</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CartOffer__c/fields/CartId__c.field-meta.xml
<CustomField>
    <fullName>CartId__c</fullName>
    <label>Carrinho</label>
    <referenceTo>CartAccount__c</referenceTo>
    <relationshipLabel>Produtos do Carrinho</relationshipLabel>
    <relationshipName>CartOffer</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CartOffer__c/fields/OfferId__c.field-meta.xml
<CustomField>
    <fullName>OfferId__c</fullName>
    <label>Oferta</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Ofertas do Carrinho</relationshipLabel>
    <relationshipName>CartOffer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CartOffer__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Campo para preenchimento da Razão do chip sendo vendido na Alta Móvel RPA.</description>
    <label>Razão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enabling</fullName>
                <label>Habilitação</label>
            </value>
            <value>
                <fullName>Portability</fullName>
                <label>Portabilidade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CartOffer__c/recordTypes/Chip.recordType-meta.xml
<RecordType>
    <fullName>Chip</fullName>
    <active>true</active>
    <description>Produto do tipo Chip</description>
    <label>Chip</label>
</RecordType>

force-app/main/default/objects/CartOffer__c/recordTypes/Mobile.recordType-meta.xml
<RecordType>
    <fullName>Mobile</fullName>
    <active>true</active>
    <description>Plano Móvel Ofertado</description>
    <label>Móvel</label>
</RecordType>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Cadastro de ofertas convergentes para serem oferecidas aos clientes Vivo conforme matriz de ofertas.</description>
    <label>Oferta</label>
    <nameField>
        <displayFormat>OFE-{000000}</displayFormat>
        <label>ID Oferta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/FamilyPlan__c.field-meta.xml
<CustomField>
    <fullName>FamilyPlan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar se o plano Móvel se trata de Família.</description>
    <label>Plano Família</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateCartAccount.cls
public class UpdateCartAccount {
    /*public static void execute(){
        Map<String, Decimal> mapCartAccount = new Map<String, Decimal>();
        List<CartOffer__c> lstNewCartOffer = new List<CartOffer__c>();
        

        for(CartAccount__c itemTrigger : (List<CartAccount__c>) trigger.new){
            Map<Id, CartAccount__c> oldRecords = (Map<Id, CartAccount__c>) Trigger.oldMap;

            if(itemTrigger.ChipAmount__c != oldRecords.get(itemTrigger.Id).ChipAmount__c) {
                mapCartAccount.put(itemTrigger.Id, itemTrigger.ChipAmount__c);
            }
        }
        
        if(!mapCartAccount.isEmpty()){
            List<CartOffer__c> lstCartOffer = [SELECT CartId__c, OfferId__c, RecordTypeId FROM CartOffer__c WHERE CartId__c IN: mapCartAccount.keySet()  AND RecordType.DeveloperName = 'Mobile'];   
            List<CartOffer__c> lstCartOfferChip = [SELECT CartId__c, OfferId__c FROM CartOffer__c WHERE CartId__c IN: mapCartAccount.keySet() AND RecordType.DeveloperName = 'Chip']; 
            
            if(lstCartOffer.isEmpty()) return;
            
            if (!lstCartOfferChip.isEmpty()) { Database.delete(lstCartOfferChip); }             
            for(String key : mapCartAccount.keySet()) {
                Decimal chipAmount = mapCartAccount.get(key);
                String cartId = key;
                String offerId;

                for (CartOffer__c itemLstCartOffer : lstCartOffer) {
                    if (itemLstCartOffer.CartId__c == cartId) {
                        offerId = itemLstCartOffer.OfferId__c;
                    }
                }

                for(Integer i = 0; i < chipAmount; i++){
                    CartOffer__c newCartOffer = new CartOffer__c(CartId__c=cartId, OfferId__c = offerId);
                    newCartOffer.RecordTypeId = Schema.SObjectType.CartOffer__c.getRecordTypeInfosByDeveloperName().get('Chip').getrecordTypeId();
                    lstNewCartOffer.add(newCartOffer);
                 }
            }

            if (!lstNewCartOffer.isEmpty()) Database.insert(lstNewCartOffer); 
        }              
    }

    public static void validate(){
        Map<String, Decimal> mapCartAccount = new Map<String, Decimal>();
        Map<String, String> mapOffer = new Map<String, String>();

        for(CartAccount__c itemTrigger : (List<CartAccount__c>) trigger.new){
            Map<Id, CartAccount__c> oldRecords = (Map<Id, CartAccount__c>) Trigger.oldMap;
            if(itemTrigger.ChipAmount__c != oldRecords.get(itemTrigger.Id).ChipAmount__c) {
                mapCartAccount.put(itemTrigger.Id, itemTrigger.ChipAmount__c);
            }
        }

        if (!mapCartAccount.isEmpty()) {
            List<CartOffer__c> lstCartOffer = [SELECT CartId__c, OfferId__c FROM CartOffer__c WHERE CartId__c IN :mapCartAccount.keySet() AND RecordType.DeveloperName = 'Mobile'];   

            for (CartOffer__c cartOffer : lstCartOffer) {
                mapOffer.put(cartOffer.CartId__c, cartOffer.OfferId__c);
            }

            List<Offer__c> lstOffers = [SELECT Id, FamilyPlan__c FROM Offer__c WHERE Id =: mapOffer.values()];

            for(CartAccount__c itemTrigger : (List<CartAccount__c>) trigger.new){
                Decimal amountChip = itemTrigger.ChipAmount__c;
                String idOffer = mapOffer.get(itemTrigger.Id);
                for (Offer__c offer : lstOffers) {
                    if (offer.Id == idOffer) {
                       if (!UpdateCartAccount.validaChip(offer.FamilyPlan__c, amountChip)) {
                        itemTrigger.addError('Quantidade de Chip informada fora do permitido para o tipo de plano. Para Plano Família é permitido até 5 chips e para Plano não Família até 3 chips');
                       }
                    }
                }
            }
        }
    }*/

    public static Boolean validaChip(Boolean hasFamilyPlan, Decimal chipAmount){
        if (hasFamilyPlan && (chipAmount >= 1 && chipAmount <= 5)) return true;
        else if (!hasFamilyPlan && (chipAmount >= 1 && chipAmount <= 3)) return true;
        else return false;
    }

    /*public static void validateCartOfferEquality(){
        String recordTypeIdChip = Schema.SObjectType.CartOffer__c.getRecordTypeInfosByDeveloperName().get('Chip').getrecordTypeId();
        Set<Id> setCartAccountId = new set<Id>();
        Boolean hasReasonEmpty = false;
        Integer qtdHabilitacao = 0;
        Integer qtdPortabilidade = 0;
        Integer countChipProducts ;

        for(CartAccount__c itemTrigger : (List<CartAccount__c>) trigger.new){

            Map<Id, CartAccount__c> oldRecords = (Map<Id, CartAccount__c>) Trigger.oldMap;
            if(oldRecords.get(itemTrigger.id).Status__c == 'SaleData' && itemTrigger.Status__c != 'SaleData'){
                setCartAccountId.add(itemTrigger.id);
            }
        }
        if(setCartAccountId.isEmpty()) return;

        List<CartOffer__c> lstCartOffer = [SELECT Id, Reason__c, CartId__c FROM CartOffer__c WHERE CartId__c IN:setCartAccountId AND RecordType.DeveloperName = 'Chip'];
        
        if(lstCartOffer.isEmpty()) return;
        countChipProducts = lstCartOffer.size();

        for(CartOffer__c card : lstCartOffer ){
            if(card.Reason__c == null){
                 hasReasonEmpty = true;
            }
                 
            if(card.Reason__c == 'Enabling'){
                qtdHabilitacao ++;
            }

            if(card.Reason__c == 'Portability'){
                qtdPortabilidade ++;
            }
            
            continue;
        }

        for(CartAccount__c itemTrigger : (List<CartAccount__c>) trigger.new){

            if(hasReasonEmpty){
                itemTrigger.addError('Por Favor!');
                return;
            }

            if((qtdHabilitacao != 0 &&  qtdHabilitacao != countChipProducts) || (qtdPortabilidade != 0 && qtdPortabilidade != countChipProducts )  ){
                itemTrigger.addError('Todos os chips devem conter a mesma Razão!');
                return;
            }
        }

    }*/
}