force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/CallerDDD__c.field-meta.xml
<CustomField>
    <fullName>CallerDDD__c</fullName>
    <description>DDD chamador do telefone de origem na URA.</description>
    <label>DDD Chamador</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/CallerPhone__c.field-meta.xml
<CustomField>
    <fullName>CallerPhone__c</fullName>
    <description>Telefone chamador registrado na URA.</description>
    <label>Telefone Chamador</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Usado para armazenar o CallId do WDE</description>
    <label>Id Externo</label>
    <length>33</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/IdentifierNumber__c.field-meta.xml
<CustomField>
    <fullName>IdentifierNumber__c</fullName>
    <description>Usado para armazenar o produto escolhido no WDE</description>
    <label>Instancia/Detalhe</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/InteractionNumber__c.field-meta.xml
<CustomField>
    <fullName>InteractionNumber__c</fullName>
    <label>Protocolo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/InteractionNumberInternal__c.field-meta.xml
<CustomField>
    <fullName>InteractionNumberInternal__c</fullName>
    <displayFormat>P{0000000}</displayFormat>
    <label>Número da Interação</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WDE</fullName>
            </value>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Motivo de criação do registro</description>
    <label>Motivo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenFirstDateSend__c.field-meta.xml
<CustomField>
    <fullName>TokenFirstDateSend__c</fullName>
    <description>Data de envio do primeiro token no fluxo de pidTokenValidate</description>
    <label>TokenFirstDateSend</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenSendAttempts__c.field-meta.xml
<CustomField>
    <fullName>TokenSendAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Número com a quantidade de envios de token no fluxo do pidTokenValidate</description>
    <label>TokenSendAttempts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenSendNumber__c.field-meta.xml
<CustomField>
    <fullName>TokenSendNumber__c</fullName>
    <description>Campo para gravar o número que o Token SMS foi enviado</description>
    <label>TokenSendNumber</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenStatus__c.field-meta.xml
<CustomField>
    <fullName>TokenStatus__c</fullName>
    <description>Status do token de PID usado no componente pidTokenValidate</description>
    <label>TokenStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando validação</fullName>
            </value>
            <value>
                <fullName>Validado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Falha no envio</fullName>
            </value>
            <value>
                <fullName>Falha na comunicação API</fullName>
            </value>
            <value>
                <fullName>Não validado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/vlocity_cmt__Channel__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Rep</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>URA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting On Someone Else</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Interrupted</fullName>
                <label>Interrompido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/vlocity_cmt__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Presencial</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerInteractionDAO.cls
public class CustomerInteractionDAO {
    public static vlocity_cmt__CustomerInteraction__c getCustomerInteractionById(String customerInteractionId) {
        return [
            SELECT
            	Id,
				vlocity_cmt__AccountId__c,
				vlocity_cmt__Channel__c,
				vlocity_cmt__Comments__c,
				vlocity_cmt__ConsoleCardLayout__c,
				vlocity_cmt__ContactId__c,
				Name,
				CallerDDD__c,
				vlocity_cmt__DurationInMinute__c,
				vlocity_cmt__EndDateTime__c,
				ExternalId__c,	
				IdentifierNumber__c,
				Subject__c,
				InteractionNumberInternal__c,
				Origin__c,
				InteractionNumber__c,
				vlocity_cmt__StartDateTime__c,
				vlocity_cmt__Status__c,
				CallerPhone__c,
				vlocity_cmt__Type__c,
				vlocity_cmt__VerificationTimestamp__c,
				vlocity_cmt__Verified__c,
				vlocity_cmt__VerifiedAgentName__c,
				TokenStatus__c,
				TokenSendAttempts__c,
				TokenFirstDateSend__c,
				TokenSendNumber__c
            FROM
            	vlocity_cmt__CustomerInteraction__c
            WHERE
            	Id =: customerInteractionId
            LIMIT 1
        ];
    }
    
    public static String getAccountIdById(String customerInteractionId) {
        return [SELECT Id, vlocity_cmt__AccountId__c FROM vlocity_cmt__CustomerInteraction__c WHERE Id =: customerInteractionId LIMIT 1].vlocity_cmt__AccountId__c;
    }
    
    public static String getIdentifierNumberById(String customerInteractionId) {
        return [SELECT Id, IdentifierNumber__c FROM vlocity_cmt__CustomerInteraction__c WHERE Id =: customerInteractionId LIMIT 1].IdentifierNumber__c;
    }

}