force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/vlocity_cmt__CustomerInteraction__c.object-meta.xml
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenLastDateSend__c.field-meta.xml
<CustomField>
    <fullName>TokenLastDateSend__c</fullName>
    <description>Data em que o cliente validou o token no fluxo de pidTokenValidate</description>
    <label>TokenLastDateSend</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenSendAttempts__c.field-meta.xml
<CustomField>
    <fullName>TokenSendAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Número com a quantidade de envios de token no fluxo do pidTokenValidate</description>
    <label>TokenSendAttempts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__CustomerInteraction__c/fields/TokenStatus__c.field-meta.xml
<CustomField>
    <fullName>TokenStatus__c</fullName>
    <description>Status do token de PID usado no componente pidTokenValidate</description>
    <label>TokenStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando validação</fullName>
            </value>
            <value>
                <fullName>Validado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Falha no envio</fullName>
            </value>
            <value>
                <fullName>Falha na comunicação API</fullName>
            </value>
            <value>
                <fullName>Não validado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceAuthorization.cls
@RestResource(urlMapping='/service/*')
global with sharing class ServiceAuthorization {

    global class ContentResponseSuccess {
        global String id { get; set; }
        global Boolean success { get; set; }
        global Integer statusCode { get; set; }
    }

    @HttpPost
    global static void processRequest(String sObjectName, String recordType, String id) {

        try {
            vlocity_cmt__CustomerInteraction__c customerInteractionToUpdate = CustomerInteractionDAO.getCustomerInteractionById(id);
           
            if(customerInteractionToUpdate.TokenStatus__c == 'Aguardando validação') {
                DateTime dateTimeAtual = DateTime.now();
                String diaMesAno = dateTimeAtual.format('dd/MM/yy');
                system.debug(Datetime.now().format('dd/MM/yy'));
                system.debug(Datetime.now().format('hh:mm'));
                customerInteractionToUpdate.TokenLastDateSend__c = dateTimeAtual;
                customerInteractionToUpdate.TokenStatus__c = 'Validado';
                customerInteractionToUpdate.vlocity_cmt__Comments__c = 'Validação de Token de Segurança realizada em ' + diaMesAno + ' às ' + dateTimeAtual.format('hh') + 'h' + dateTimeAtual.format('mm') + '.'; 
            }

            Database.SaveResult saveResult = Database.update(customerInteractionToUpdate);

            if (saveResult.isSuccess()) {
                RestResponse res = RestContext.response;
                ContentResponseSuccess ContentResponseSuccess = new ContentResponseSuccess();
                ContentResponseSuccess.id = id;
                ContentResponseSuccess.success = true;
                ContentResponseSuccess.statusCode = 200;
                res.responseBody = Blob.valueOf(JSON.serialize(ContentResponseSuccess, true));

            } else {
                RestResponse resp = RestContext.response;
                ContentResponseSuccess lContentResponseErro = new ContentResponseSuccess();
                lContentResponseErro.success = false;
                lContentResponseErro.id = saveResult.getErrors()[0].getMessage();

                lContentResponseErro.statusCode = 500;
                resp.responseBody = Blob.valueOf(JSON.serialize(lContentResponseErro, true));
            }   
        } catch (Exception ex){
            vlocity_cmt__CustomerInteraction__c customerInteractionToUpdate = new vlocity_cmt__CustomerInteraction__c();
            customerInteractionToUpdate.id = id;
            customerInteractionToUpdate.TokenSendAttempts__c --;
            customerInteractionToUpdate.TokenStatus__c = 'Falha na comunicação API';

            update customerInteractionToUpdate;

            RestResponse resp = RestContext.response;
            ContentResponseSuccess lContentResponseErro = new ContentResponseSuccess();
            lContentResponseErro.success = false;
            lContentResponseErro.id =  ex.getMessage();
            lContentResponseErro.statusCode = 500;
            resp.responseBody = Blob.valueOf(JSON.serialize(lContentResponseErro, true));
        }
    }
}