force-app/main/default/objects/ParameterSLA__c/ParameterSLA__c/ParameterSLA__c.object-meta.xml
<CustomObject>
    <label>Parâmetro SLA</label>
    <nameField>
        <label>Nome Parâmetro SLA</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parâmetros SLA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceRequest__c/ServiceRequest__c.object-meta.xml
<CustomObject>
    <description>Fluxo de abertura de chamados internos entre areas</description>
    <label>Solicitação de Serviço</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>Nome da Solicitação de Serviço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitações de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceRequest__c/fields/BusinessHoursId__c.field-meta.xml
<CustomField>
    <fullName>BusinessHoursId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Solicita_es_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/ClosingDateTime__c.field-meta.xml
<CustomField>
    <fullName>ClosingDateTime__c</fullName>
    <label>Data/Hora de fechamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/NotificationDate__c.field-meta.xml
<CustomField>
    <fullName>NotificationDate__c</fullName>
    <label>Data Notificação</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/OpeningDateTime__c.field-meta.xml
<CustomField>
    <fullName>OpeningDateTime__c</fullName>
    <label>Data/Hora de abertura</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/SlaHours__c.field-meta.xml
<CustomField>
    <fullName>SlaHours__c</fullName>
    <label>SLA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotStarted</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>Em Andamento</label>
            </value>
            <value>
                <fullName>AnalysisComplete</fullName>
                <label>Análise Concluída</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalculateSLAHourForServiceRequests.cls
public with sharing class CalculateSLAHourForServiceRequests {
    public static void execute(List<ServiceRequest__c> lstNew) {

        List<ServiceRequest__c> lLstCases = new List<ServiceRequest__c> ();
        //Set<String> lStatusCancel = new Set<String> { 'Não Iniciado', 'Aprovado', 'Encerrado', 'Reprovado', 'Cancelado' };
        Set<String> lStatusCancel = new Set<String> { 'NotStarted', 'Canceled' };
        Map<Id, ServiceRequest__c> lMapCaseById = new Map<Id, ServiceRequest__c> ();
        Set<String> lSetRecTypeIds = new Set<String> ();

        for (ServiceRequest__c serviceRequest : lstNew) {
           
            if (String.isBlank(serviceRequest.BusinessHoursId__c) || 
                 lStatusCancel.contains(serviceRequest.Status__c) || 
                 serviceRequest.ClosingDateTime__c != null ||
             (serviceRequest.DueDate__c != null && serviceRequest.ClosingDateTime__c == null)) { continue; }

            lMapCaseById.put(serviceRequest.Id, serviceRequest);
            lSetRecTypeIds.add(serviceRequest.RecordTypeId);
        }
        if (lMapCaseById.isEmpty()) { return; }

        if (!lMapCaseById.isEmpty()) { calculateWorkingTime(lMapCaseById, lSetRecTypeIds); }
    }





    private static void calculateWorkingTime(Map<Id, ServiceRequest__c> aMapCaseById, Set<String> aSetRecTypeIds) {
       
        List<RecordType> lLstRecType = new List<RecordType> ([SELECT Id, DeveloperName FROM RecordType WHERE Id = :aSetRecTypeIds]);
        Map<String, String> lMapRecType = new Map<String, String> ();
        for (RecordType iRecType : lLstRecType) { lMapRecType.put(iRecType.DeveloperName, iRecType.Id); }
system.debug(lMapRecType);
        Map<String, List<parameterSLA__c>> lMapParamSLA = StringBooleanEvaluate.getLstParameterSLA(lMapRecType);  
		system.debug(lMapParamSLA);
        if (lMapParamSLA.isEmpty()) { return; }

        Map<String, Map<String, Integer>> lMapMinutesByIdRegister = StringBooleanEvaluate.executeEvaluate(aMapCaseById.values(), lMapParamSLA);
        system.debug(lMapMinutesByIdRegister);
        if (lMapMinutesByIdRegister.isEmpty()) { return; }
        
        Map<String, Datetime> lMapTargetDateByRegister = new Map<String, Datetime> ();
        Map<String, Datetime> lMapNotificationDateByRegister = new Map<String, Datetime> ();
        Map<String, Id> lMapIdBusinessHourByCase= new Map<String, Id>();

        for (ServiceRequest__c serviceRequest : aMapCaseById.values()) {
            if (!lMapMinutesByIdRegister.containsKey(serviceRequest.Id)) {
                aMapCaseById.remove(serviceRequest.Id);
                continue;
            }
            lMapIdBusinessHourByCase.put(serviceRequest.Id, serviceRequest.BusinessHoursId__c);
            lMapTargetDateByRegister.put(serviceRequest.Id, System.now());
            lMapNotificationDateByRegister.put(serviceRequest.Id, System.now());
        }

        lMapTargetDateByRegister = CalculateWorkingTime.calculateTime(lMapTargetDateByRegister, lMapMinutesByIdRegister,lMapIdBusinessHourByCase, 'TargetDate');
        lMapNotificationDateByRegister = CalculateWorkingTime.calculateTime(lMapNotificationDateByRegister, lMapMinutesByIdRegister,lMapIdBusinessHourByCase, 'NotificationDate');

        if (lMapTargetDateByRegister.isEmpty()) { return; }

        for (ServiceRequest__c serviceRequest : aMapCaseById.values()) {
            Map<String, Integer> iMapSLATimer = lMapMinutesByIdRegister.get(serviceRequest.Id);
            Integer iQtdHourSLA = (iMapSLATimer.containsKey('TargetDate')) ? iMapSLATimer.get('TargetDate') : 0;
             iQtdHourSLA /= 60;

            Datetime iDateTarget = lMapTargetDateByRegister.get(serviceRequest.Id);
            serviceRequest.DueDate__c = iDateTarget;
            serviceRequest.SlaHours__c = iQtdHourSLA;
            serviceRequest.NotificationDate__c = lMapNotificationDateByRegister.get(serviceRequest.Id);
            serviceRequest.OpeningDateTime__c = (iDateTarget != null) ? System.now() : null;
        }
    }
   
}