force-app/main/default/objects/FileLink__c/FileLink__c.object-meta.xml
<CustomObject>
    <description>This object was created to store a link from GEDOC that contains the file that was attached by the b2c customer. It is displayed on the Cases screen in the &quot;Minhas Solicitações&quot; flow: Ajuda com cobrança, Ajuda com fatura ou cobrança, Ajuda com o Pedido, Mudança do Endereço de Instalação, Problema com Portabilidade, Problemas com Recarga.</description>
    <label>Link do Arquivo</label>
    <nameField>
        <displayFormat>LA# {00000000}</displayFormat>
        <label>Número do Link do Arquivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Links dos Arquivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FileLink__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Links dos Arquivos</relationshipLabel>
    <relationshipName>Links_dos_Arquivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FileLink__c/fields/FileDescription__c.field-meta.xml
<CustomField>
    <fullName>FileDescription__c</fullName>
    <label>Descrição do Arquivo Para ser Exibido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FileLink__c/fields/IDGedoc__c.field-meta.xml
<CustomField>
    <fullName>IDGedoc__c</fullName>
    <label>Id do Arquivo no Gedoc</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/FileLinkDAO.cls
public inherited sharing class FileLinkDAO
{
    public static FileLink__c getById(String recordId)
    {
        return [
            SELECT Id, IDGedoc__c
            FROM FileLink__c
            WHERE Id = :recordId
        ];
    }

    public static List<FileLink__c> getBy(String caseId)
    {
        return [
            SELECT Id, FileDescription__c, IDGedoc__c
            FROM FileLink__c
            WHERE Case__c = :caseId
            ORDER BY CreatedDate ASC
        ];
    }
}