force-app/main/default/objects/FileLink__c/FileLink__c.object-meta.xml
<CustomObject>
    <description>This object was created to store a link from GEDOC that contains the file that was attached by the b2c customer. It is displayed on the Cases screen in the &quot;Minhas Solicitações&quot; flow: Ajuda com cobrança, Ajuda com fatura ou cobrança, Ajuda com o Pedido, Mudança do Endereço de Instalação, Problema com Portabilidade, Problemas com Recarga.</description>
    <label>Link do Arquivo</label>
    <nameField>
        <displayFormat>LA# {00000000}</displayFormat>
        <label>Número do Link do Arquivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Links dos Arquivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FileLink__c/fields/FileDescription__c.field-meta.xml
<CustomField>
    <fullName>FileDescription__c</fullName>
    <label>Descrição do Arquivo Para ser Exibido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AttachmentService.cls
public without sharing class AttachmentService
{
    public static List<DocumentAttachment> getAttachments(String caseId)
    {
        if (String.isBlank(caseId)) { throw new IllegalArgumentException('caseId não pode ser nulo.'); }
        List<FileLink__c> fileLinks = FileLinkDAO.getBy(caseId);
        List<DocumentAttachment> attachments = new List<DocumentAttachment>();
            
        for (FileLink__c fileLinkRec : fileLinks)
        {
            DocumentAttachment attachment = new DocumentAttachment();
            attachment.id = fileLinkRec.Id;
            attachment.name = fileLinkRec.FileDescription__c;
            attachments.add(attachment);
        }
        return attachments;
    }
}