force-app/main/default/objects/Lead/fields/AddressNumber__c.field-meta.xml
<CustomField>
    <fullName>AddressNumber__c</fullName>
    <label>Número</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Bairro relacionado ao endereço do Lead</description>
    <label>Bairro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <description>CPF do Lead</description>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Determina o produto ou oferta de interesse para o Lead</description>
    <inlineHelpText>Selecione o produto ou oferta de interesse para o Lead</inlineHelpText>
    <label>Produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vivo_Fiber_Rural_Areas_1P_Voice</fullName>
                <label>Vivo Fibra Áreas Rurais 1P Voz</label>
            </value>
            <value>
                <fullName>Vivo_Fiber_Rural_Areas_1P_Broadband</fullName>
                <label>Vivo Fibra Áreas Rurais 1P Banda Larga</label>
            </value>
            <value>
                <fullName>Vivo_Fiber_Rural_Areas_Duo_Broadband_TV</fullName>
                <label>Vivo Fibra Áreas Rurais Duo Banda Larga + TV</label>
            </value>
            <value>
                <fullName>Vivo_Fiber_Rural_Areas_2P</fullName>
                <label>Vivo Fibra Áreas Rurais 2P</label>
            </value>
            <value>
                <fullName>Vivo_Fiber_Rural_Areas_3P</fullName>
                <label>Vivo Fibra Áreas Rurais 3P</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/PropertyName__c.field-meta.xml
<CustomField>
    <fullName>PropertyName__c</fullName>
    <description>Nome da propriedade (fazenda, chácara, sítio, etc)</description>
    <inlineHelpText>Nome da propriedade (fazenda, chácara, sítio, etc)</inlineHelpText>
    <label>Nome da Propriedade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <description>Ponto de referência próximo de onde se encontra a propriedade</description>
    <label>Ponto de Referência</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <label>Certificado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceOperation__c.field-meta.xml
<CustomField>
    <fullName>ServiceOperation__c</fullName>
    <label>Operação de Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/ServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>ServiceProvider__c</fullName>
    <label>Provedor de serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FibraRuralLeadElegibilidadeServiceTest.cls
@isTest
public class FibraRuralLeadElegibilidadeServiceTest {
    
    @testSetup
    public static void setup(){
        insert new Webservice__c(
            Name = 'API_GW_SendMailCSS',
            Endpoint__c  = 'https://api-hml-int.telefonica.com.br/enviar-email-sms/v1/enviarEmailSMSConvergente',
            ServiceOperation__c = 'POST',
            Certificate__c = 'FibraRuralHML',
            SubscriptionKey__c = '',
            ServiceProvider__c = 'APIGW'
        );
        
        insert new Lead(
            RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Fibra Rural').getRecordTypeId(),
            FirstName = 'FirstName',
            LastName = 'LastName',
            Document__c = '65699762060',
            Phone = '99999999999',
            Email = 'testEmail@test.com',
            Status = 'NewFR',
            Street = 'Rua',
            City = 'Cidade',
            State = 'SP',
            Country = 'Brasil',
            PostalCode = '99999999',
            AddressNumber__c = '0',
            District__c = 'Bairro',
            PropertyName__c = 'Name',
            Reference__c = 'Ponto',
            Product__c = 'Vivo_Fiber_Rural_Areas_2P',
            Company = 'Teste'
        );
    }
    
    @isTest
    public static void testUnformatString(){
        
        List<String> testString = new List<String>();
        testString.add('unformatString,á Ä â À ã É è Ê ë Î ï Í ì Ö ó Ò ô Õ ü Ú ù Û ç Ç');
        
        Test.StartTest();
        List<String> response = FibraRuralLeadElegibilidadeService.flowMethods(testString);
        Test.StopTest();
        
        System.assertEquals(1, response.size());
        System.assertEquals('a a a a a e e e e i i i i o o o o o u u u u c c', response[0]);
        
    }
    
    @isTest
    public static void testSendEmailAPI(){
        
        Webservice__c sendMailCss = [SELECT SubscriptionKey__c FROM Webservice__c WHERE Name='API_GW_SendMailCSS' LIMIT 1];
        sendMailCss.SubscriptionKey__c = 'd1ca8d57a2984db88f01c9ce7b5862e2';
        update sendMailCss;
        
        Lead testLead = [SELECT Id FROM Lead WHERE LastName = 'LastName'];
        
        List<String> testString = new List<String>();
        testString.add('sendEmailController,Código da Mensagem,testEmail@test.com,Mr Test User,' + String.valueOf(testLead.Id));
        
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new FibraRuralLeadElegibilidadeMock());
        FibraRuralLeadElegibilidadeCallout.sendEmailAPI(testString[0]);
        Test.StopTest();
        
    }
    
    @isTest
    public static void testSendEmailControllerError(){
        
        Webservice__c sendMailCss = [SELECT SubscriptionKey__c FROM Webservice__c WHERE Name='API_GW_SendMailCSS' LIMIT 1];
        sendMailCss.SubscriptionKey__c = '';
        update sendMailCss;
        
        Lead testLead = [SELECT Id FROM Lead WHERE LastName = 'LastName'];
        
        List<String> testString = new List<String>();
        testString.add('sendEmailController,Código da Mensagem,testEmail@test.com,Mr Test User,' + String.valueOf(testLead.Id));
        
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new FibraRuralLeadElegibilidadeMock());
        List<String> response = FibraRuralLeadElegibilidadeService.flowMethods(testString);
        Test.StopTest();
        
    }
    
    
}