force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/AccessesMinute__c.field-meta.xml
<CustomField>
    <fullName>AccessesMinute__c</fullName>
    <label>Acessos por Minuto</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AccountJob__c.field-meta.xml
<CustomField>
    <fullName>AccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar contas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AccountLoadDate__c</fullName>
    <label>Data da carga - Account</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressJob__c.field-meta.xml
<CustomField>
    <fullName>AddressJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar endereços</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AddressLoadDate__c</fullName>
    <label>Data de carga - Endereço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetJob__c.field-meta.xml
<CustomField>
    <fullName>AssetJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Assets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AssetLoadDate__c</fullName>
    <label>Data da carga - Asset</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountJob__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar conta de faturamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountLoadDate__c</fullName>
    <label>Data da carga - Conta de faturamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <label>Segmento do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>Tipo do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceJob__c.field-meta.xml
<CustomField>
    <fullName>InvoiceJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Faturas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceLoadDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLoadDate__c</fullName>
    <label>Data da carga - Faturas</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/ScriptDetailHistoryExpiration__c.field-meta.xml
<CustomField>
    <fullName>ScriptDetailHistoryExpiration__c</fullName>
    <label>Expiração do histórico de Script Detail</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/SearchRange__c.field-meta.xml
<CustomField>
    <fullName>SearchRange__c</fullName>
    <label>Intervalo de pesquisa</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/SearchRangeInvoice__c.field-meta.xml
<CustomField>
    <fullName>SearchRangeInvoice__c</fullName>
    <label>Intervalo de Pesquisa Faturas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/ServiceHistoryExpiration__c.field-meta.xml
<CustomField>
    <fullName>ServiceHistoryExpiration__c</fullName>
    <label>Expiração do histórico de atendimento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/TotalNumberRecords__c.field-meta.xml
<CustomField>
    <fullName>TotalNumberRecords__c</fullName>
    <label>Número Total de Registros</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GeneralParamDAO.cls
/** 
 * @author Diego Costa @ Deloitte
 * @date 07/06/2022
 * @description Controla a busca e criação do objeto Custom Settings
 */
public with sharing class GeneralParamDAO {

    public static List<GeneralParam__c> getLoadParams(){
        return [
            SELECT    
                Id, 
                AccountLoadDate__c,
                AssetLoadDate__c,
                BillingAccountLoadDate__c,
                InvoiceLoadDate__c,
                AddressLoadDate__c,
                AssetJob__c,
                BillingAccountJob__c,
                AccountJob__c,
                AddressJob__c,
                InvoiceJob__c,
                SearchRange__c,
            	SearchRangeInvoice__c,
            	ServiceHistoryExpiration__c,
                TotalNumberRecords__c,
                CustomerType__c,
                CustomerSegment__c,
                ScriptDetailHistoryExpiration__c,
                AccessesMinute__c
            FROM 
                GeneralParam__c    
        ];
    }
}