force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/BatchSizePurgeServiceTransaction__c.field-meta.xml
<CustomField>
    <fullName>BatchSizePurgeServiceTransaction__c</fullName>
    <description>Campo destinado a definição do tamanho dos lotes (BatchSize) do batch PurgeServiceTransactionBatch. Exemplo: Se definido 20000 no campo, a cada query executada pelo batch, será considerado um LIMIT 20000</description>
    <label>Tamanho do lote de expurgo de ST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/DaysPurgeSeviceTransaction__c.field-meta.xml
<CustomField>
    <fullName>DaysPurgeSeviceTransaction__c</fullName>
    <description>Campo destinado a parametrização de quantos dias o batch PurgeServiceTransacitionBatch irá considerar para expurgo, exemplo: Se configurado 30 no campo, o batch irá excluir os registros com mais de 30 dias na base</description>
    <label>Dias de expurgo de Service Transaction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTransaction__c/ServiceTransaction__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar as transações dos serviços de API.</description>
    <label>Service Transaction</label>
    <nameField>
        <label>Service Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PurgeServiceTransactionBatch.cls
global with sharing class PurgeServiceTransactionBatch implements Database.Batchable<sObject> {
    private GeneralParam__c param;

	global static void start() {
        GeneralParam__c param = GeneralParam__c.getInstance();

		Integer batchSize = ((param.BatchSizePurgeServiceTransaction__c != null) 
			? Integer.valueOf(param.BatchSizePurgeServiceTransaction__c) 
			: 1
		);

		Database.executeBatch(new PurgeServiceTransactionBatch(), batchSize);
	}
	
	global static void start(Integer batchSize) {
		Database.executeBatch(new PurgeServiceTransactionBatch(), batchSize);
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		this.param = GeneralParam__c.getInstance();

		Integer daysOfPurge = ((this.param.DaysPurgeSeviceTransaction__c != null) 
			? Integer.valueOf(this.param.DaysPurgeSeviceTransaction__c) 
			: 1
		);
	
		String query = ('SELECT Id FROM ServiceTransaction__c WHERE CreatedDate < LAST_N_DAYS : ' + daysOfPurge);

		if (Test.isRunningTest()) {
			query = 'SELECT Id FROM ServiceTransaction__c';
		}
	
		return (Database.getQueryLocator(query));
	}
	
	global void execute(Database.BatchableContext BC, List<ServiceTransaction__c> scope) {
		List<String> lstLinkedEntityIds = new List<String>();
		List<ContentDocument> lstContentDocument = new List<ContentDocument>();
	
		for (ServiceTransaction__c st : scope) {
			lstLinkedEntityIds.add(st.Id);
		}
	
		if (lstLinkedEntityIds.size() > 0) {
			List<ContentDocumentLink> lstcdl = [
				SELECT 
					Id, 
					LinkedEntityId, 
					ContentDocumentId 
				FROM 
					ContentDocumentLink 
				WHERE 
					LinkedEntityId IN :lstLinkedEntityIds
			];
	
			for (ContentDocumentLink cdl : lstcdl) {
				lstContentDocument.add(new ContentDocument(
					Id = cdl.ContentDocumentId
				));
			}

			Database.delete(lstContentDocument);
		}
	
		Database.delete(scope);
	}
	
	global void finish(Database.BatchableContext BC) {
	}
}