force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/PurgeObjects__c.field-meta.xml
<CustomField>
    <fullName>PurgeObjects__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Expurgar objetos dinamicamente</description>
    <inlineHelpText>Expurgar objetos dinamicamente</inlineHelpText>
    <label>Expurgar objetos dinamicamente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteObjectDataQueueable.cls
public with sharing class DeleteObjectDataQueueable implements Queueable {

    public DeleteObjectDataQueueable(String objName, Integer nrOfRecords, Datetime startDate, Datetime endDate) {
        this.objectName = objName;
        this.numberOfRecords = nrOfRecords;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    private String objectName;
    private Integer numberOfRecords;
    private Datetime startDate;
    private Datetime endDate;

    public void execute(QueueableContext context) {

        Boolean purgeObjects = GeneralParam__c.getInstance().PurgeObjects__c;

        String query = 'SELECT Id FROM ' + objectName + 
                       ' WHERE CreatedDate >= :startDate AND CreatedDate < :endDate LIMIT :numberOfRecords';
        
        List<SObject> purgeList = Database.query(query);
 
        delete purgeList;

        if (numberOfRecords == purgeList.size() && purgeObjects) {
            System.enqueueJob(new DeleteObjectDataQueueable(this.objectName, this.numberOfRecords, this.startDate, this.endDate));
        }
        
    }

}