force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/AccountJob__c.field-meta.xml
<CustomField>
    <fullName>AccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar contas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AccountLoadDate__c</fullName>
    <label>Data da carga - Account</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressJob__c.field-meta.xml
<CustomField>
    <fullName>AddressJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar endereços</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AddressLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AddressLoadDate__c</fullName>
    <label>Data de carga - Endereço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetJob__c.field-meta.xml
<CustomField>
    <fullName>AssetJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Assets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/AssetLoadDate__c.field-meta.xml
<CustomField>
    <fullName>AssetLoadDate__c</fullName>
    <label>Data da carga - Asset</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountJob__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar conta de faturamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/BillingAccountLoadDate__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountLoadDate__c</fullName>
    <label>Data da carga - Conta de faturamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceJob__c.field-meta.xml
<CustomField>
    <fullName>InvoiceJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processar Faturas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/InvoiceLoadDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLoadDate__c</fullName>
    <label>Data da carga - Faturas</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/SearchRange__c.field-meta.xml
<CustomField>
    <fullName>SearchRange__c</fullName>
    <label>Intervalo de pesquisa</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/ServiceHistoryExpiration__c.field-meta.xml
<CustomField>
    <fullName>ServiceHistoryExpiration__c</fullName>
    <label>Expiração do histórico de atendimento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/TotalNumberRecords__c.field-meta.xml
<CustomField>
    <fullName>TotalNumberRecords__c</fullName>
    <label>Número Total de Registros</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Objeto de faturas destinado a armazenar as informações históricas do cliente.</description>
    <label>Faturamento</label>
    <nameField>
        <label>Mês de Referência</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceDownloadControllerTest.cls
@isTest
public class InvoiceDownloadControllerTest {
    
    @testSetup 
    static void setup() {
        Account lAccount = DataFactory.createAccount();

        insert lAccount;
        
        insert new GeneralParam__c(
            AccountLoadDate__c  = Datetime.now().addDays(-1),
            AssetLoadDate__c = Datetime.now().addDays(-1),
            BillingAccountLoadDate__c = Datetime.now().addDays(-1),
            InvoiceLoadDate__c = Datetime.now().addDays(-1),
            AddressLoadDate__c = Datetime.now().addDays(-1),
            AssetJob__c = true,
            BillingAccountJob__c = true,
            AccountJob__c = true,
            AddressJob__c = true,
            InvoiceJob__c = true,
            SearchRange__c = 90,
            TotalNumberRecords__c = 100,
            ServiceHistoryExpiration__c = 0
        );

        insert new Webservice__c(
            Name = 'FourthPlataformInvoiceCallout',
            Endpoint__c  = 'https://hmlapi.telefonicabigdata.com',
            SubscriptionKey__c = 'd1ca8d57a2984db88f01c9ce7b5862e2'
        );
        
        WebServiceTestFactory.start().authOAuthProvider().create();
    }

    @isTest
    public static void downloadInvoice() {
        Account lAccount = [SELECT Id FROM Account LIMIT 1];
        
		Invoice__c invoiceHistory = DataFactory.createInvoiceHistory(lAccount.Id);
        
        insert invoiceHistory;
        
        String body = 'JVBERi0xLjQKJdPr6eEKMSAwIG9iago8PC9DcmVhdG9yIChNb3ppbGxhLzUuMCBcKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NFwpIEFwcGxl';
        
        Attachment attach = DataFactory.createAttachment(invoiceHistory.Id,body);
        
        insert attach;
       
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceDownloadMock());

        InvoiceDownloadController.downloadInvoice(invoiceHistory.Id, false);
        Test.stopTest();
    }

    @isTest
    public static void secondaryDownloadInvoice(){
        Account lAccount = [SELECT Id FROM Account LIMIT 1];

		Invoice__c invoiceHistory = DataFactory.createInvoiceHistory(lAccount.Id);
        
        insert invoiceHistory;

        String body = 'JVBERi0xLjQKJdPr6eEKMSAwIG9iago8PC9DcmVhdG9yIChNb3ppbGxhLzUuMCBcKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NFwpIEFwcGxl';
        
        Attachment attach = DataFactory.createAttachment(invoiceHistory.Id, body);

        insert attach;
       
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceDownloadMock());
        
        InvoiceDownloadController.downloadInvoice(invoiceHistory.Id, true);
        Test.stopTest();
    }
}