force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/UpdatedPrimaryContactDays__c.field-meta.xml
<CustomField>
    <fullName>UpdatedPrimaryContactDays__c</fullName>
    <description>Dias parametrizados para atualizar os contatos principais no Account</description>
    <inlineHelpText>Dias parametrizados para atualizar os contatos principais no Account</inlineHelpText>
    <label>Dias contatos principais atualizados</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GeneralParam__c/fields/UpdatedPrimaryContactLimit__c.field-meta.xml
<CustomField>
    <fullName>UpdatedPrimaryContactLimit__c</fullName>
    <description>Limite de contatos principais atualizados no Account</description>
    <inlineHelpText>Limite de contatos principais atualizados no Account</inlineHelpText>
    <label>Limite contatos principais atualizados</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdatePrimaryContactBatchTest.cls
@isTest
private class UpdatePrimaryContactBatchTest {
    
    @TestSetup
    static void makeData(){

        Account acc = new Account(Name='Account Test');
        insert acc;

        Contact con = new Contact(FirstName='Contact', LastName='Test', 
                                  AccountId=acc.Id,
                                  Email='contact.test@test1.com');
        insert con;

        GeneralParam__c setting = new GeneralParam__c();
        setting.UpdatedPrimaryContactLimit__c = 100;
        setting.UpdatedPrimaryContactDays__c = 10;
        insert setting;
        
    }

    @isTest
    static void updatePrimaryContactTest() {
        Test.startTest();
        Database.executeBatch(new UpdatePrimaryContactBatch());
        System.Schedule('Atualizar contato principal2', '0 0 3 ? * 1,2,3,4,5,6,7', new UpdatePrimaryContactBatch());
        Test.stopTest();
        System.assertNotEquals([SELECT vlocity_cmt__PrimaryContactId__c FROM Account LIMIT 1], null);
    }


}