force-app/main/default/objects/GeneralParam__c/GeneralParam__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros utilizados para identificar o delta de exibição e exclusão de dados</description>
    <label>Parâmetro geral</label>
</CustomObject>

force-app/main/default/objects/GeneralParam__c/fields/TimeAutomaticTicketCall__c.field-meta.xml
<CustomField>
    <fullName>TimeAutomaticTicketCall__c</fullName>
    <description>Define o tempo de chamada automática da senha, em segundos, no Atendimento de Senha.</description>
    <inlineHelpText>Define o tempo de chamada automática da senha, em segundos, no Atendimento de Senha.</inlineHelpText>
    <label>Tempo de Chamada da Senha Automática</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SSMHomeOperationsEngine.cls
/*
    ---------------------------------------------------
    @author - Márcio Las
    @company - Telefonica  
    @date - 07/04/2022
    @description - Class Engine for SSMHomeOperations
    ---------------------------------------------------
*/
public with sharing class SSMHomeOperationsEngine {
    private static final Integer GENERIC_ERROR_MESSAGE = 699;

    public static Map<String, Object> getTimeAutomaticTicketCallParam() {
        Map<String, Object> mapResponse = new Map<String, Object>();

        try {
            List<GeneralParam__c> ltParam = GeneralParamDAO.getLoadParams();

            if (!ltParam.isEmpty()) {
                mapResponse.put('success', ltParam[0].TimeAutomaticTicketCall__c);

            } else {
                mapResponse.put('success', 10);
            }

        } catch (Exception e) {
            mapResponse.clear();
    
            mapResponse.put('error', GENERIC_ERROR_MESSAGE);
        }
    
        return (mapResponse);
    }

    public static Map<String, Object> startAttendance(StoreServiceManagerTO.ServiceTicket serviceTicket) {
        Map<String, Object> mapResponse = new Map<String, Object>();

        try {
            mapResponse = PointOfServiceAttendanceCallout.execute(serviceTicket);
        
        } catch (Exception e) {
            mapResponse.clear();

            mapResponse.put('error', GENERIC_ERROR_MESSAGE);
        }

        return (mapResponse);
    }
}