force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para Scripts Guiados. Exemplo: Script de Atendimento</description>
    <label>Script</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/QuestionScript__c.field-meta.xml
<CustomField>
    <fullName>QuestionScript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pergunta</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Respostas</relationshipLabel>
    <relationshipName>ParentScripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script__c/recordTypes/Instruction.recordType-meta.xml
<RecordType>
    <fullName>Instruction</fullName>
    <active>true</active>
    <description>Tipo de registro para o fluxo serguir somente por instrução.</description>
    <label>Instrução</label>
</RecordType>

force-app/main/default/objects/Script__c/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <description>Cadastro de perguntas com grupo de opções de resposta</description>
    <label>Pergunta</label>
</RecordType>

force-app/main/default/objects/ScriptConfig__c/ScriptConfig__c.object-meta.xml
<CustomObject>
    <description>Objeto com as Configurações do Script, Grupo, Membro do Grupo e Rota</description>
    <label>Grupo e Rota</label>
    <nameField>
        <displayFormat>G-{00000000}</displayFormat>
        <label>Sequencial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grupos e Rotas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptConfig__c/fields/AnswerOption__c.field-meta.xml
<CustomField>
    <fullName>AnswerOption__c</fullName>
    <description>Campo com a descrição da opção de resposta</description>
    <label>Opção (Campo Técnico)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/ChildScript__c.field-meta.xml
<CustomField>
    <fullName>ChildScript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resposta</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Grupos e Rotas (Resposta)</relationshipLabel>
    <relationshipName>ChildScriptScriptConfigs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/NextScriptConfig__c.field-meta.xml
<CustomField>
    <fullName>NextScriptConfig__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Próximo grupo que deverá ser exibido</description>
    <label>Próximo Grupo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ScriptConfig__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Grupo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ScriptConfig__c</referenceTo>
    <relationshipLabel>Grupos e Rotas (Grupo de saída padrão)</relationshipLabel>
    <relationshipName>DefaultRoute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/NextScriptTech__c.field-meta.xml
<CustomField>
    <fullName>NextScriptTech__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para auxiliar a edição da Rota, quando informado gera automaticamente o cadastro do Próximo Grupo</description>
    <label>Próximo Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Grupos e Rotas (Próximo Script)</relationshipLabel>
    <relationshipName>Grupos_e_Rotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/ParentScript__c.field-meta.xml
<CustomField>
    <fullName>ParentScript__c</fullName>
    <description>Parent Script</description>
    <label>Fluxo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Script__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Fluxo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Grupos</relationshipLabel>
    <relationshipName>Scripts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/ParentScriptConfig__c.field-meta.xml
<CustomField>
    <fullName>ParentScriptConfig__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo</label>
    <referenceTo>ScriptConfig__c</referenceTo>
    <relationshipLabel>Rotas</relationshipLabel>
    <relationshipName>ScriptConfigGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/ScriptToShow__c.field-meta.xml
<CustomField>
    <fullName>ScriptToShow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Script que será apresentado ao usuário</description>
    <inlineHelpText>Script que será apresentado ao usuário</inlineHelpText>
    <label>Script para exibir</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Grupos e Rotas</relationshipLabel>
    <relationshipName>ScriptToShows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Grupo</label>
</RecordType>

force-app/main/default/objects/ScriptConfig__c/recordTypes/Route.recordType-meta.xml
<RecordType>
    <fullName>Route</fullName>
    <active>true</active>
    <description>Rota do Grupo</description>
    <label>Rota</label>
</RecordType>

force-app/main/default/classes/ScriptConfigTriggerHandler.cls
public without sharing class ScriptConfigTriggerHandler {
    
    public static void createRoute(List<ScriptConfig__c> ltScriptConfig) {
        
        Id groupRT = Schema.SObjectType.ScriptConfig__c.getRecordTypeInfosByDeveloperName().get('Group').getRecordTypeId();
        Id routeRT = Schema.SObjectType.ScriptConfig__c.getRecordTypeInfosByDeveloperName().get('Route').getRecordTypeId();
        Id instructionRT = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('Instruction').getRecordTypeId();


        Map<Id, List<Script__c>> mapScriptOptions = new Map<Id, List<Script__c>>();
        Set<Id> setScriptShow = new Set<Id>();
        Set<Id> setRecordTypeScript = new Set<Id>();
        List<Script__c> ltAnswer;

        List<ScriptConfig__c> ltRoute = new List<ScriptConfig__c>();
        ScriptConfig__c routeItem;

        for(ScriptConfig__c item : ltScriptConfig){
            if(item.RecordTypeId == groupRT){
                setScriptShow.add(item.ScriptToShow__c);
            }
        }

        List<Script__c> ltScript = [SELECT Id, RecordType.Id FROM Script__c WHERE Id IN: setScriptShow AND RecordType.DeveloperName = 'Instruction'];

        for(Script__c item : ltScript){
            if(item.RecordTypeId == instructionRT){
                setRecordTypeScript.add(item.Id);
            }
        }

        if(setScriptShow.size() > 0){
            for(Script__c item : [SELECT Id, QuestionScript__c FROM Script__c WHERE QuestionScript__c IN: setScriptShow]){
                ltAnswer = new List<Script__c>();
                if(mapScriptOptions.containsKey(item.QuestionScript__c)){
                    ltAnswer = mapScriptOptions.get(item.QuestionScript__c);
                }
                ltAnswer.add(item);
                mapScriptOptions.put(item.QuestionScript__c, ltAnswer);
            }
        }

        for(ScriptConfig__c item : ltScriptConfig){
            if(item.RecordTypeId == groupRT){
                if(mapScriptOptions.containsKey(item.ScriptToShow__c)){
                    for(Script__c option : mapScriptOptions.get(item.ScriptToShow__c)){
                        routeItem = new ScriptConfig__c();
                        routeItem.RecordTypeId          = routeRT;
                        routeItem.ParentScript__c       = item.ParentScript__c;
                        routeItem.ScriptToShow__c       = item.ScriptToShow__c;
                        routeItem.ParentScriptConfig__c = item.Id;
                        routeItem.ChildScript__c        = option.Id;

                        ltRoute.add(routeItem);
                    }
                } else if(setRecordTypeScript.size() > 0) {
                    routeItem = new ScriptConfig__c();
                    routeItem.RecordTypeId          = routeRT;
                    routeItem.ParentScript__c       = item.ParentScript__c;
                    routeItem.ScriptToShow__c       = item.ScriptToShow__c;
                    routeItem.ParentScriptConfig__c = item.Id;
                    routeItem.AnswerOption__c       = 'Finalizar';
                    ltRoute.add(routeItem);
               }else {
                    routeItem = new ScriptConfig__c();
                    routeItem.RecordTypeId          = routeRT;
                    routeItem.ParentScript__c       = item.ParentScript__c;
                    routeItem.ScriptToShow__c       = item.ScriptToShow__c;
                    routeItem.ParentScriptConfig__c = item.Id;
                    routeItem.AnswerOption__c       = 'Sim';
                    ltRoute.add(routeItem);

                    routeItem = new ScriptConfig__c();
                    routeItem.RecordTypeId          = routeRT;
                    routeItem.ParentScript__c       = item.ParentScript__c;
                    routeItem.ScriptToShow__c       = item.ScriptToShow__c;
                    routeItem.ParentScriptConfig__c = item.Id;
                    routeItem.AnswerOption__c       = 'Não';
                    ltRoute.add(routeItem);

                }
            }
        }

        if( ltRoute.size() > 0){
            insert ltRoute;
        }

    }

    public static void createGroupToRoute(List<ScriptConfig__c> ltScriptConfig) {

        if(ltScriptConfig.size() > 1){
            return;
        }
        Id routeRT = Schema.SObjectType.ScriptConfig__c.getRecordTypeInfosByDeveloperName().get('Route').getRecordTypeId();
        Id groupRT = Schema.SObjectType.ScriptConfig__c.getRecordTypeInfosByDeveloperName().get('Group').getRecordTypeId();        
        Id questionId = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('Question').getRecordTypeId();

        Set<Id> setNextScriptTech = new Set<Id>();
        Set<Id> setQuestionId = new Set<Id>();
        Map<Id, ScriptConfig__c> mapGroup = new Map<Id, ScriptConfig__c>();
        ScriptConfig__c groupItem;
        
        

        for(ScriptConfig__c item : ltScriptConfig){
            if(item.NextScriptTech__c != null){
                setNextScriptTech.add(item.NextScriptTech__c);
            }
        }

        List<Script__c> ltScript = [SELECT Id, RecordType.Id FROM Script__c WHERE Id IN: setNextScriptTech AND RecordType.DeveloperName = 'Question'];
		system.debug('ltScript : ' + ltScript);
        for(Script__c item : ltScript){
            if(item.RecordTypeId == questionId){
                setQuestionId.add(item.Id);
            }
        }
        
        
		system.debug('setQuestionId : ' + setQuestionId);
        List<Script__c> ltAnswer = [SELECT Id FROM Script__c WHERE QuestionScript__c IN: setQuestionId ];
        system.debug('ltScriptConfig : ' + ltScriptConfig);
        system.debug('ltAnswer : ' + ltAnswer);

        if(setQuestionId.size() > 0){
            for(ScriptConfig__c item : ltScriptConfig){
                system.debug('ITEM : ' + item.NextScriptConfig__c);
                for(Script__c itemScript : ltScript){
                    if(item.RecordTypeId == routeRT && item.NextScriptTech__c != null && item.NextScriptConfig__c == null && ltAnswer.size() > 0){
                        groupItem = new ScriptConfig__c();
                        groupItem.RecordTypeId = groupRT;
                        groupItem.ParentScript__c = item.ParentScript__c;
                        groupItem.ScriptToShow__c = item.NextScriptTech__c;
    
                        mapGroup.put(item.NextScriptTech__c, groupItem);
                    } else{
                        item.NextScriptTech__c.addError('Não é possível vincular uma pergunta sem respostas cadastradas');
                    }
                }
            }           

        } else{
            system.debug('ltScriptConfig : '+ ltScriptConfig);
            for(ScriptConfig__c item : ltScriptConfig){
                    if(item.RecordTypeId == routeRT && item.NextScriptTech__c != null && item.NextScriptConfig__c == null){
                        groupItem = new ScriptConfig__c();
                        groupItem.RecordTypeId = groupRT;
                        groupItem.ParentScript__c = item.ParentScript__c;
                        groupItem.ScriptToShow__c = item.NextScriptTech__c;
    
                        mapGroup.put(item.NextScriptTech__c, groupItem);
                    }
                
            }
        }
        
        if(mapGroup.size() > 0){
            insert mapGroup.values();

            for(ScriptConfig__c item : ltScriptConfig){
                if(item.RecordTypeId == routeRT && item.NextScriptTech__c != null && item.NextScriptConfig__c == null && 
                    mapGroup.containsKey(item.NextScriptTech__c))
                {
                    item.NextScriptConfig__c = mapGroup.get(item.NextScriptTech__c).Id;
                    item.NextScriptTech__c = null;
                }

            }
        }

    }
}