force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para Scripts Guiados. Exemplo: Script de Atendimento</description>
    <label>Script</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptRule__c/ScriptRule__c.object-meta.xml
<CustomObject>
    <label>Regra do Script</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Script Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras do Script</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptRule__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Campo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/FieldAPI__c.field-meta.xml
<CustomField>
    <fullName>FieldAPI__c</fullName>
    <description>Campo que contemplará a API do Campo que a regra utilizará.</description>
    <label>API do Campo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/FilterBy__c.field-meta.xml
<CustomField>
    <fullName>FilterBy__c</fullName>
    <description>Campo que contemplará as possibilidades de filtro que o usuário poderá escolher quando o critério for direcionado para um objeto relacionado.</description>
    <label>Filtrar por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>none</fullName>
                <label>Nenhum registro</label>
            </value>
            <value>
                <fullName>allRecords</fullName>
                <label>Todos registros</label>
            </value>
            <value>
                <fullName>oneRecord</fullName>
                <label>Pelo menos um</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/ObjectAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI__c</fullName>
    <description>Campo que contemplará a API do Objeto que a regra terá como base.</description>
    <label>API do Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Campo que contemplará as possíveis operações que o usuário poderá selecionar ao criar a regra do script.</description>
    <label>Operador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>startsWith</fullName>
                <label>começa com</label>
            </value>
            <value>
                <fullName>contains</fullName>
                <label>contém</label>
            </value>
            <value>
                <fullName>equals</fullName>
                <label>igual a</label>
            </value>
            <value>
                <fullName>greaterOrEqual</fullName>
                <label>maior ou igual</label>
            </value>
            <value>
                <fullName>greaterThan</fullName>
                <label>maior que</label>
            </value>
            <value>
                <fullName>lessOrEqual</fullName>
                <label>menor ou igual</label>
            </value>
            <value>
                <fullName>lessThan</fullName>
                <label>menor que</label>
            </value>
            <value>
                <fullName>doesNotContains</fullName>
                <label>não contém</label>
            </value>
            <value>
                <fullName>notEqualsTo</fullName>
                <label>diferente de</label>
            </value>
            <value>
                <fullName>itHas</fullName>
                <label>possui</label>
            </value>
            <value>
                <fullName>doesntHave</fullName>
                <label>não possui</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/RuleNumber__c.field-meta.xml
<CustomField>
    <fullName>RuleNumber__c</fullName>
    <label>Número da Regra</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Aviso</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Regras do Script</relationshipLabel>
    <relationshipName>Regras_do_Script</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor a ser Comparado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRuleNotification__mdt/ScriptRuleNotification__mdt.object-meta.xml
<CustomObject>
    <description>Metadado a ser utilizado para a criação das regras do script de notificação.</description>
    <label>Regras do Script para Comunicados</label>
    <pluralLabel>ScriptRulesNotification</pluralLabel>
</CustomObject>

force-app/main/default/objects/ScriptRuleNotification__mdt/fields/ObjectAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI__c</fullName>
    <description>Campo que contemplará o nome da API do objeto desejado.</description>
    <label>API do Objeto</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ScriptRuleController.cls
public without sharing class ScriptRuleController {
    
    public static String FIELDSET = 'ScriptRuleField';
    
    public class ObjectDetail{
        public String strObjectLabel;
        public String strObjectAPI;
        public Map<String,String> mapFieldsAndLabels;
    }

    public class PicklistDetails{
        public String strAPIPicklistValue;
        public String strLabelPicklistValue;
    }


    public class FieldDetails{
        public String strFieldAPI;
        public String strFieldType;
        public List<Object> mapPicklistValueAndLabel;
    }


    public static String setInfosField(){
        Map<String,List<Object>> lMapInfoFields = new Map<String,List<Object>>();
        for(ScriptRuleNotification__mdt iScriptNotification : [SELECT MasterLabel, ObjectAPI__c FROM ScriptRuleNotification__mdt]){
            String lObjectAPI = iScriptNotification.ObjectAPI__c;
            if(String.isBlank(lObjectAPI)){ continue; }
            List<Schema.FieldSetMember> lLstMembers = SchemaSelector.getFieldSetMembersByFieldSetDeveloperName(lObjectAPI,FIELDSET);
            if(lLstMembers.isEmpty()){ continue; }
            List<ScriptRuleController.FieldDetails> lLstFieldDetails = new List<ScriptRuleController.FieldDetails>();
            for(Schema.FieldSetMember iMember : lLstMembers){
                String lStrType = formattedFieldType(lObjectAPI, iMember.getFieldPath());
                if(String.isBlank(lStrType)){ continue; }
                ScriptRuleController.FieldDetails lFieldDetail = new ScriptRuleController.FieldDetails();
                if(lStrType == 'picklist'){
                    List<Schema.PicklistEntry> lLstPicklist = SchemaSelector.getPicklistValuesByObjectAndFieldAPI(lObjectAPI,iMember.getFieldPath());
                    if(lLstPicklist.isEmpty()){ continue; }
                    lFieldDetail.mapPicklistValueAndLabel = setValuePicklistInMap(lLstPicklist);
                }
                lFieldDetail.strFieldAPI = iMember.getFieldPath();
                lFieldDetail.strFieldType = lStrType;
                lLstFieldDetails.add(lFieldDetail);
            }
            lMapInfoFields.put(lObjectAPI, lLstFieldDetails);
        }
        return JSON.serialize(lMapInfoFields);
    }

    private static String formattedFieldType(String strObjectAPI, String strFieldAPI){
        Schema.DisplayType lStrType = SchemaSelector.getFieldTypeByObjectAndFieldAPI(strObjectAPI, strFieldAPI);
        String lStrFieldTypeFormatted = '';
        switch on lStrType {
            when ADDRESS{ System.debug('ADDRESS'); lStrFieldTypeFormatted = 'text'; }
            when STRING{ System.debug('STRING'); lStrFieldTypeFormatted = 'text'; }
            when REFERENCE{ System.debug('REFERENCE'); lStrFieldTypeFormatted = 'text'; }
            when URL { System.debug('URL'); lStrFieldTypeFormatted = 'text'; }
            when TEXTAREA { System.debug('TEXTAREA'); lStrFieldTypeFormatted = 'text'; }
            when TIME { System.debug('TIME'); lStrFieldTypeFormatted = 'text'; }
            when PHONE { System.debug('PHONE');  lStrFieldTypeFormatted = 'text'; }
            when INTEGER { System.debug('INTEGER'); lStrFieldTypeFormatted = 'number'; }
            when LONG { System.debug('LONG'); lStrFieldTypeFormatted = 'number'; }
            when DOUBLE { System.debug('DOUBLE'); lStrFieldTypeFormatted = 'number'; }
            when ID { System.debug('ID'); lStrFieldTypeFormatted = 'text'; }
            when EMAIL { System.debug('EMAIL'); lStrFieldTypeFormatted = 'text'; }
            when ENCRYPTEDSTRING { System.debug('ENCRYPTEDSTRING'); lStrFieldTypeFormatted = 'text'; } 
            when DATE { System.debug('DATE'); lStrFieldTypeFormatted = 'date'; }
            when DATETIME { System.debug('DATETIME');  lStrFieldTypeFormatted = 'date'; }
            when CURRENCY { System.debug('CURRENCY'); lStrFieldTypeFormatted = 'numberCurrency'; }
            when PERCENT { System.debug('PERCENT'); lStrFieldTypeFormatted = 'numberPercent'; }
            when BOOLEAN { System.debug('BOOLEAN'); lStrFieldTypeFormatted = 'checkbox'; }
            when PICKLIST { System.debug('PICKLIST'); lStrFieldTypeFormatted = 'picklist'; }
            when MULTIPICKLIST { System.debug('MULTIPICKLIST'); lStrFieldTypeFormatted = 'picklist'; }
        }
        return lStrFieldTypeFormatted;
    }


    @AuraEnabled
    public static String getAllObjectsDetails(){
        String lIdProfile = UserInfo.getProfileId();
        if(String.isBlank(lIdProfile)){ return ''; }
        String lStrNameProfile = [SELECT Name FROM Profile WHERE Id =: lIdProfile].Name;
        if(String.isBlank(lStrNameProfile)){ return ''; }
        String lStrProfilesAvailable = System.Label.CreateScriptRuleProfiles;
        if(String.isBlank(lStrProfilesAvailable)){ return ''; }
        List<String> lVetProfilesAvailable = lStrProfilesAvailable.split(','); 
        Boolean lBlnProfileIsValid = lVetProfilesAvailable.contains(lStrNameProfile);
        if(!lBlnProfileIsValid){ return ''; }

        List<Object> lListObjectsDetails = new List<Object>();
        for(ScriptRuleNotification__mdt iScriptNotification : [SELECT MasterLabel, ObjectAPI__c FROM ScriptRuleNotification__mdt]){
            ScriptRuleController.ObjectDetail lObjecDetail = new ScriptRuleController.ObjectDetail();
            String lStrObject = iScriptNotification.ObjectAPI__c;
            String lStrObjectLabel = iScriptNotification.MasterLabel;
            lObjecDetail.strObjectAPI = lStrObject;
            lObjecDetail.strObjectLabel = lStrObjectLabel;
            lObjecDetail.mapFieldsAndLabels = SchemaSelector.getAllFieldsAndLabelsOfFieldSetMembers(lStrObject, FIELDSET);
            lListObjectsDetails.add(lObjecDetail);
        }
        return JSON.serialize(lListObjectsDetails);
    }

    @AuraEnabled
    public static String getValuePicklist(){
        List<Schema.PicklistEntry> lLstPicklistEntryOfFilter = SchemaSelector.getPicklistValuesByObjectAndFieldAPI('ScriptRule__c', 'FilterBy__c');
        Map<String,String> mapWithPicklistValues = new Map<String,String>();
        if(lLstPicklistEntryOfFilter.isEmpty()){ return '';}
        mapWithPicklistValues.put('filter', JSON.serialize(setValuePicklistInMap(lLstPicklistEntryOfFilter)));
        List<Schema.PicklistEntry> lLstPicklistEntryOfOperator = SchemaSelector.getPicklistValuesByObjectAndFieldAPI('ScriptRule__c', 'Operator__c');
        if(lLstPicklistEntryOfOperator.isEmpty()){ return '';}
        mapWithPicklistValues.put('operator', JSON.serialize(setValuePicklistInMap(lLstPicklistEntryOfOperator)));
        mapWithPicklistValues.put('infoFields', setInfosField());
        return JSON.serialize(mapWithPicklistValues);
    }
    
    private static List<Object> setValuePicklistInMap(List<Schema.PicklistEntry> lLstPicklistEntry){
        List<ScriptRuleController.PicklistDetails> lLstPickListDetail = new List<ScriptRuleController.PicklistDetails>(); 
        for(Schema.PicklistEntry iPickListEntry : lLstPicklistEntry){
            ScriptRuleController.PicklistDetails lPickListDetail = new ScriptRuleController.PicklistDetails();
            String lStrAPIValue = iPickListEntry.getValue();
            String lStrLabelValue = iPickListEntry.getLabel();
            lPickListDetail.strAPIPicklistValue = lStrAPIValue;
            lPickListDetail.strLabelPicklistValue = lStrLabelValue;
            lLstPickListDetail.add(lPickListDetail);
        }
        return lLstPickListDetail;
    }

    @AuraEnabled
    public static Boolean saveScriptRules(List<Object> lstScriptRules, Id idScript){
        if(lstScriptRules == null || lstScriptRules.isEmpty() || idScript == null){ return false; }
        List<ScriptRule__c> lNewScriptRule = new List<ScriptRule__c>();
        for(Object iObject : lstScriptRules){
            Map<Object,Object> lMapIObject = (Map<Object, Object>) iObject;
            if(lMapIObject == null || lMapIObject.isEmpty()){ return false; }
            ScriptRule__c lScriptRule = new ScriptRule__c();
            String lNumberRule = (String.isBlank((String) lMapIObject.get('numberRule')))? '' : String.valueOf(lMapIObject.get('numberRule'));
            lScriptRule.Operator__c =  (String.isBlank((String) lMapIObject.get('operatorScript')))? '' : String.valueOf(lMapIObject.get('operatorScript'));
            lScriptRule.ObjectAPI__c =  (String.isBlank((String) lMapIObject.get('objectAPI')))? '' : String.valueOf(lMapIObject.get('objectAPI'));
            lScriptRule.FieldAPI__c =  (String.isBlank((String) lMapIObject.get('fieldScriptAPI')))? '' : String.valueOf(lMapIObject.get('fieldScriptAPI'));
            if(String.isEmpty(lNumberRule) || String.isEmpty(lScriptRule.Operator__c) || String.isEmpty(lScriptRule.ObjectAPI__c) || String.isEmpty(lScriptRule.FieldAPI__c) ){ return false; }
            lScriptRule.Value__c = (String.isBlank((String) lMapIObject.get('valueToCompare')) || (lScriptRule.Operator__c == 'itHas' || lScriptRule.Operator__c == 'doesntHave'))? '' : String.valueOf(lMapIObject.get('valueToCompare'));
            lScriptRule.Value__c = (lMapIObject.get('fieldType') == 'date' && !String.isBlank(lScriptRule.Value__c))? lScriptRule.Value__c + ' 00:00:00' : lScriptRule.Value__c;
            lScriptRule.FilterBy__c = (String.isBlank((String) lMapIObject.get('filterScript')))? '' : String.valueOf(lMapIObject.get('filterScript'));
            lScriptRule.RuleNumber__c = Decimal.valueOf(lNumberRule);
            String lStrLabelObject = SchemaSelector.getObjectLabelByObjectAPI(lScriptRule.ObjectAPI__c);
            String lStrLabelField = SchemaSelector.getFieldLabelByObjectAPIAndFieldAPI(lScriptRule.ObjectAPI__c, lScriptRule.FieldAPI__c);
            if(String.isBlank(lStrLabelObject) || String.isBlank(lStrLabelField)){ return false; }
            lScriptRule.Object__c = lStrLabelObject;
            lScriptRule.Field__c = lStrLabelField;
            lScriptRule.Script__c = idScript;
            lNewScriptRule.add(lScriptRule);
        }
        try{
            insert lNewScriptRule;
        }catch(Exception e){
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
        return true;
    }

    @AuraEnabled
    public static List<Decimal> getListNumberRulesActualScript(Id idScript){
        if(idScript == null) { return new List<Decimal>(); }
        List<Decimal> lListNumberRules = new List<Decimal>();
        for(ScriptRule__c iScripRule : [SELECT RuleNumber__c FROM ScriptRule__c WHERE Script__c =: idScript ORDER BY RuleNumber__c ASC]){
            lListNumberRules.add(iScripRule.RuleNumber__c);
        }
        return lListNumberRules;
    }
}