force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para Scripts Guiados. Exemplo: Script de Atendimento</description>
    <label>Script</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/Logic__c.field-meta.xml
<CustomField>
    <fullName>Logic__c</fullName>
    <label>Lógica</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Script__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SalesSupport</fullName>
                <label>Suporte á Vendas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Script__c/recordTypes/AutomaticWarning.recordType-meta.xml
<RecordType>
    <fullName>AutomaticWarning</fullName>
    <active>true</active>
    <description>Tipo de Registro para criação de avisos automáticos exibidos no mural de avisos do cliente</description>
    <label>Aviso Automático (Massivo)</label>
</RecordType>

force-app/main/default/objects/Script__c/recordTypes/Flow.recordType-meta.xml
<RecordType>
    <fullName>Flow</fullName>
    <active>true</active>
    <description>Cadastro do Fluxo</description>
    <label>Fluxo</label>
</RecordType>

force-app/main/default/objects/ScriptRule__c/ScriptRule__c.object-meta.xml
<CustomObject>
    <label>Regra do Script</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Script Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras do Script</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptRule__c/fields/RuleNumber__c.field-meta.xml
<CustomField>
    <fullName>RuleNumber__c</fullName>
    <label>Número da Regra</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Aviso</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Regras do Script</relationshipLabel>
    <relationshipName>Regras_do_Script</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScriptNotificationTriggerHandler.cls
/**
	* @authors - Marcos Santos 
	* @company - everis 
	* @date - 27/08/2020
	* @description - Classe handler da ScriptTrigger
	*
	* Changes
	* 21/10/2020 @Marina Hessel B2C7551-287 - Criação método validateScriptTypeActiveUnique 
											  que valida a existência de apenas um fluxo ativo de suporte à vendas
**/

public with sharing class ScriptNotificationTriggerHandler {
    
    public static void validateUpdateOfScriptRecord(){
        if(Trigger.isAfter || !Trigger.isUpdate){ return; }
        string customLabel = System.Label.LogicScriptValidation;
        List<Script__c> lLstScripts = new List<Script__c>();
        for(Script__c iScript : (List<Script__c>) Trigger.new){
            Script__c lOldScript = (Script__c) Trigger.oldMap.get(iScript.Id);
            if(getDeveloperNameByRecordId(iScript.RecordTypeId, 'Script__c') != 'AutomaticWarning' || iScript.Status__c != 'Active'){ continue; }
            lLstScripts.add(iScript);
        }

        if(lLstScripts.isEmpty()){ return;}

        Map<Id, Script__c> mapScriptAndScriptRule = new map<Id, Script__c>([SELECT Id, Logic__c, RecordTypeId, Status__c, (SELECT Id, RuleNumber__c FROM Regras_do_Script__r) FROM Script__c WHERE Id IN : lLstScripts]);

        if(mapScriptAndScriptRule.isEmpty()){ return;}

        for(Script__c objScript : lLstScripts){
            if(!mapScriptAndScriptRule.containsKey(objScript.Id)){ continue; }
            Script__c objScriptWithScriptRule = mapScriptAndScriptRule.get(objScript.Id);
            objScriptWithScriptRule.Logic__c = objScript.Logic__c;
            if(HandlerScriptNotification.validateFieldLogic(objScriptWithScriptRule)){ continue; }
            objScript.addError(customLabel); 
        }
    }

    public static String getDeveloperNameByRecordId(String idRecordId, String strObjeto){
        if(String.isBlank(idRecordId) || String.isBlank(strObjeto)){ return ''; }
        try{ return Schema.getGlobalDescribe().get(strObjeto).getDescribe().getRecordTypeInfosById().get(idRecordId).getDeveloperName();}
        catch(Exception e) { return ''; }
    }
    
    
    public static void validateScriptTypeActiveUnique(List<Script__c> newListScript, Map<Id,Script__c> oldMap){
        if(Trigger.isAfter){ return;}
        
        Set<Id> setIdScript = new Set<Id>();
        
        string customLabel = System.Label.ScriptTypeActiveUnique;
        String recordTypeId = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('Flow').getrecordTypeId();
        
        
        for(Script__c forscript : newListScript){
            if(forscript.Status__c == 'Active' && forscript.Type__c == 'SalesSupport' && forscript.RecordTypeId == recordTypeId){
                if(Trigger.IsInsert){
                	setIdScript.add(forscript.Id); 
            	}
                if(Trigger.IsUpdate){
                   if(forscript.Status__c != oldMap.get(forscript.Id).Status__c || forscript.Type__c != oldMap.get(forscript.Id).Type__c){
                	setIdScript.add(forscript.Id);
            		}
           	 	} 
          	}
        }
            
        if(setIdScript.isEmpty()){ return;}
        
        List<Script__c> listScript = [SELECT Id, Status__c, Type__c 
                                      FROM Script__c 
                                      WHERE Status__c = 'Active' 
                                      AND Type__c = 'SalesSupport'
                                      AND RecordTypeId =: recordTypeId];
         
        if(listScript.isEmpty()){ return;}
        
        for(Script__c forscriptError : (List<Script__c>) Trigger.new){
            forscriptError.addError(customLabel);
        }
    }
}