force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para Scripts Guiados. Exemplo: Script de Atendimento</description>
    <label>Script</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/Logic__c.field-meta.xml
<CustomField>
    <fullName>Logic__c</fullName>
    <label>Lógica</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/ScriptRule__c.object-meta.xml
<CustomObject>
    <label>Regra do Script</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Script Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras do Script</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptRule__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Aviso</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Regras do Script</relationshipLabel>
    <relationshipName>Regras_do_Script</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScriptRuleTriggerHandlerTest.cls
@isTest
public class ScriptRuleTriggerHandlerTest {

@testSetup 
    static void setup(){
        Script__c automaticScript = DataFactory.createAutomaticScript();
        insert automaticScript;

        ScriptRule__c scriptRule = DataFactory.createScriptRule(automaticScript.Id, 1, 'S');
        insert scriptRule;
	}
    
    @isTest
    public static void validateDeleteScriptRuleTest(){
        
        List<Script__c> lscript = [SELECT Id FROM Script__c LIMIT 1];

        List<ScriptRule__c> lscriptRule = [SELECT Id FROM ScriptRule__c LIMIT 1];
        
        Test.startTest();
        
        Script__c updateScript = new Script__c(
        	Id = lscript[0].Id,
        	Logic__c = '1'
            );
        
        update updateScript;
        
        Script__c updateScript2 = new Script__c(
            Id = lscript[0].Id,
        	Status__c = 'Active'
            );
        
        update updateScript2;
        

        try
           {
               delete lscriptRule;
           }
           catch(Exception e) 
           {    
           System.Assert(e.getMessage().contains(''));
           }
        
        Test.stopTest();
   }
}