force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para Scripts Guiados. Exemplo: Script de Atendimento</description>
    <label>Script</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/QuestionScript__c.field-meta.xml
<CustomField>
    <fullName>QuestionScript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pergunta</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Respostas</relationshipLabel>
    <relationshipName>ParentScripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script__c/recordTypes/Answer.recordType-meta.xml
<RecordType>
    <fullName>Answer</fullName>
    <active>true</active>
    <description>Cadastro de repostas para as perguntas do Fluxo</description>
    <label>Resposta</label>
</RecordType>

force-app/main/default/objects/Script__c/recordTypes/Flow.recordType-meta.xml
<RecordType>
    <fullName>Flow</fullName>
    <active>true</active>
    <description>Cadastro do Fluxo</description>
    <label>Fluxo</label>
</RecordType>

force-app/main/default/objects/Script__c/recordTypes/Instruction.recordType-meta.xml
<RecordType>
    <fullName>Instruction</fullName>
    <active>true</active>
    <description>Tipo de registro para o fluxo serguir somente por instrução.</description>
    <label>Instrução</label>
</RecordType>

force-app/main/default/objects/Script__c/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <description>Cadastro de perguntas com grupo de opções de resposta</description>
    <label>Pergunta</label>
</RecordType>

force-app/main/default/objects/ScriptConfig__c/ScriptConfig__c.object-meta.xml
<CustomObject>
    <description>Objeto com as Configurações do Script, Grupo, Membro do Grupo e Rota</description>
    <label>Grupo e Rota</label>
    <nameField>
        <displayFormat>G-{00000000}</displayFormat>
        <label>Sequencial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grupos e Rotas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptConfig__c/fields/NextScriptConfig__c.field-meta.xml
<CustomField>
    <fullName>NextScriptConfig__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Próximo grupo que deverá ser exibido</description>
    <label>Próximo Grupo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ScriptConfig__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Grupo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ScriptConfig__c</referenceTo>
    <relationshipLabel>Grupos e Rotas (Grupo de saída padrão)</relationshipLabel>
    <relationshipName>DefaultRoute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/NextScriptTech__c.field-meta.xml
<CustomField>
    <fullName>NextScriptTech__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para auxiliar a edição da Rota, quando informado gera automaticamente o cadastro do Próximo Grupo</description>
    <label>Próximo Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Grupos e Rotas (Próximo Script)</relationshipLabel>
    <relationshipName>Grupos_e_Rotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/ParentScript__c.field-meta.xml
<CustomField>
    <fullName>ParentScript__c</fullName>
    <description>Parent Script</description>
    <label>Fluxo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Script__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Fluxo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Grupos</relationshipLabel>
    <relationshipName>Scripts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/fields/ScriptToShow__c.field-meta.xml
<CustomField>
    <fullName>ScriptToShow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Script que será apresentado ao usuário</description>
    <inlineHelpText>Script que será apresentado ao usuário</inlineHelpText>
    <label>Script para exibir</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Grupos e Rotas</relationshipLabel>
    <relationshipName>ScriptToShows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptConfig__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Grupo</label>
</RecordType>

force-app/main/default/objects/ScriptConfig__c/recordTypes/Route.recordType-meta.xml
<RecordType>
    <fullName>Route</fullName>
    <active>true</active>
    <description>Rota do Grupo</description>
    <label>Rota</label>
</RecordType>

force-app/main/default/classes/ScriptConfigTriggerHandlerTest.cls
@isTest
public class ScriptConfigTriggerHandlerTest {
    
	@testSetup 
    static void setup(){
        String scriptRecordType;
        String scriptConfigType;
        
        scriptRecordType = 'Flow';        
        Script__c newScriptFlow = DataFactory.createScript(scriptRecordType);
        insert newScriptFlow; 
        
        scriptRecordType = 'Question';        
        Script__c newScriptQuestion = DataFactory.createScript(scriptRecordType);
        insert newScriptQuestion;
        
        scriptRecordType = 'Answer';        
        Script__c newScriptAnswer = DataFactory.createScript(scriptRecordType);
        insert newScriptAnswer;
        
        scriptRecordType = 'Instruction';        
        Script__c newScriptInstruction = DataFactory.createScript(scriptRecordType);
        insert newScriptInstruction;
        
        scriptConfigType = 'Group';
        ScriptConfig__c scriptConfigGroup = DataFactory.createScriptConfig(newScriptFlow.Id, scriptConfigType);
        insert scriptConfigGroup;
        
        scriptConfigType = 'Route';
        ScriptConfig__c scriptConfigRoute = DataFactory.createScriptConfig(newScriptFlow.Id, scriptConfigType);
        insert scriptConfigRoute;
        
	}
    
    @isTest
    public static void createScriptTest(){
        
        List<Script__c> ltScript = [SELECT Id, RecordType.DeveloperName FROM Script__c  limit 1]; 

        List<ScriptConfig__c> ltScriptConfig = [SELECT Id, RecordType.DeveloperName, NextScriptTech__c, ScriptToShow__c,ParentScript__c FROM ScriptConfig__c  limit 1]; 

        Id scriptId;
        
        Test.startTest(); 
        
        ScriptConfigTriggerHandler.createRoute(ltScriptConfig);
        system.assert( !ltScriptConfig.isEmpty());
       
        Test.stopTest();
   }
    
    @isTest
    public static void createScriptTestInstruction(){
        
        List<Script__c> ltScript = [SELECT Id, RecordType.DeveloperName FROM Script__c  WHERE RecordType.DeveloperName = 'Instruction' limit 1];
        

        List<ScriptConfig__c> ltScriptConfigInstruction = [SELECT Id, RecordType.DeveloperName, NextScriptTech__c, ScriptToShow__c,ParentScript__c FROM ScriptConfig__c WHERE RecordType.DeveloperName = 'Group' limit 1]; 
	
        for (ScriptConfig__c item : ltScriptConfigInstruction){
            item.ScriptToShow__c = ltScript[0].Id;            
        }
        
        Test.startTest(); 
        
        ScriptConfigTriggerHandler.createRoute(ltScriptConfigInstruction);
        system.assert( !ltScriptConfigInstruction.isEmpty());
        
        Test.stopTest();
   }
    
  @isTest
    public static void createGroupToRouteTest(){
        
        List<Script__c> ltScript = [SELECT Id FROM Script__c  limit 1]; 

        List<ScriptConfig__c> ltScriptConfigRoute = [SELECT Id, RecordType.DeveloperName, NextScriptTech__c FROM ScriptConfig__c WHERE RecordType.DeveloperName = 'Route' limit 1]; 
        
        List<ScriptConfig__c> ltScriptConfigGroup = [SELECT Id, RecordType.DeveloperName, NextScriptTech__c FROM ScriptConfig__c WHERE RecordType.DeveloperName = 'Group' limit 1]; 
     
        Test.startTest();     
        
        ScriptConfigTriggerHandler.createGroupToRoute(ltScriptConfigGroup);
        system.assert( !ltScriptConfigGroup.isEmpty());
		        
        Test.stopTest();
   }

    @isTest
    public static void createRouteTest(){
        
        List<Script__c> ltScript = [SELECT Id, RecordType.DeveloperName FROM Script__c WHERE RecordType.DeveloperName = 'Question' limit 1];

        
        List<ScriptConfig__c> ltScriptConfigGroup = [SELECT Id, RecordType.DeveloperName, NextScriptTech__c, ScriptToShow__c,ParentScript__c FROM ScriptConfig__c WHERE RecordType.DeveloperName = 'Group']; 
     
       for (ScriptConfig__c item : ltScriptConfigGroup){
            item.ScriptToShow__c = ltScript[0].Id;            
        }
        Test.startTest();     
        
        ScriptConfigTriggerHandler.createRoute(ltScriptConfigGroup);
        system.assert( !ltScriptConfigGroup.isEmpty());
        
		        
        Test.stopTest();
   }
    
    @isTest
    public static void createGroupToRouteTestQuestion(){
        
        List<Script__c> ltScriptQuestion = [SELECT Id, RecordType.DeveloperName FROM Script__c WHERE RecordType.DeveloperName = 'Question' limit 1];
        
       
        List<ScriptConfig__c> ltScriptConfigGroup = [SELECT Id, RecordType.DeveloperName, NextScriptTech__c, ScriptToShow__c,ParentScript__c, NextScriptConfig__c FROM ScriptConfig__c WHERE RecordType.DeveloperName = 'Group']; 
     
        for (ScriptConfig__c item : ltScriptConfigGroup){
            item.ScriptToShow__c = ltScriptQuestion[0].Id;  
            item.NextScriptTech__c = ltScriptQuestion[0].Id; 
            item.NextScriptConfig__c = null;
        }
        Test.startTest();     
        
        ScriptConfigTriggerHandler.createGroupToRoute(ltScriptConfigGroup);
        system.assert( !ltScriptConfigGroup.isEmpty());
        
		        
        Test.stopTest();
   } 
    @isTest
    public static void createGroupToRouteTestQuestionRoute(){
        
        List<Script__c> ltScriptQuestion = [SELECT Id, RecordType.DeveloperName FROM Script__c WHERE RecordType.DeveloperName = 'Question' limit 1];
        List<Script__c> ltScript = [SELECT Id, RecordType.DeveloperName, QuestionScript__c FROM Script__c WHERE RecordType.DeveloperName = 'Answer' limit 1];
        for(Script__c item : ltScriptQuestion){ 
            item.QuestionScript__c = ltScript[0].Id;
        }
        List<ScriptConfig__c> ltScriptConfigGroup = [SELECT Id, RecordType.DeveloperName, NextScriptTech__c, ScriptToShow__c,ParentScript__c, NextScriptConfig__c FROM ScriptConfig__c WHERE RecordType.DeveloperName = 'Route']; 
     
        
        for (ScriptConfig__c item : ltScriptConfigGroup){
            item.ScriptToShow__c = ltScriptQuestion[0].Id;  
            item.NextScriptTech__c = ltScript[0].Id; 
            item.NextScriptConfig__c = null;
        }
        system.debug('LT SCRIPT CONFIG : ' + ltScriptConfigGroup);
        Test.startTest();     
        
        ScriptConfigTriggerHandler.createGroupToRoute(ltScriptConfigGroup);
        system.assert( !ltScriptConfigGroup.isEmpty());
        
		        
        Test.stopTest();
   }
}