force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para Scripts Guiados. Exemplo: Script de Atendimento</description>
    <label>Script</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/Logic__c.field-meta.xml
<CustomField>
    <fullName>Logic__c</fullName>
    <label>Lógica</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Script__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Prioridade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Script__c/fields/Recurrent__c.field-meta.xml
<CustomField>
    <fullName>Recurrent__c</fullName>
    <label>Recorrente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>Sim</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Script__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Script__c/recordTypes/AutomaticWarning.recordType-meta.xml
<RecordType>
    <fullName>AutomaticWarning</fullName>
    <active>true</active>
    <description>Tipo de Registro para criação de avisos automáticos exibidos no mural de avisos do cliente</description>
    <label>Aviso Automático (Massivo)</label>
</RecordType>

force-app/main/default/objects/ScriptRule__c/ScriptRule__c.object-meta.xml
<CustomObject>
    <label>Regra do Script</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Script Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras do Script</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptRule__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Campo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/FieldAPI__c.field-meta.xml
<CustomField>
    <fullName>FieldAPI__c</fullName>
    <description>Campo que contemplará a API do Campo que a regra utilizará.</description>
    <label>API do Campo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/FilterBy__c.field-meta.xml
<CustomField>
    <fullName>FilterBy__c</fullName>
    <description>Campo que contemplará as possibilidades de filtro que o usuário poderá escolher quando o critério for direcionado para um objeto relacionado.</description>
    <label>Filtrar por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>none</fullName>
                <label>Nenhum registro</label>
            </value>
            <value>
                <fullName>allRecords</fullName>
                <label>Todos registros</label>
            </value>
            <value>
                <fullName>oneRecord</fullName>
                <label>Pelo menos um</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/ObjectAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI__c</fullName>
    <description>Campo que contemplará a API do Objeto que a regra terá como base.</description>
    <label>API do Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Campo que contemplará as possíveis operações que o usuário poderá selecionar ao criar a regra do script.</description>
    <label>Operador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>startsWith</fullName>
                <label>começa com</label>
            </value>
            <value>
                <fullName>contains</fullName>
                <label>contém</label>
            </value>
            <value>
                <fullName>equals</fullName>
                <label>igual a</label>
            </value>
            <value>
                <fullName>greaterOrEqual</fullName>
                <label>maior ou igual</label>
            </value>
            <value>
                <fullName>greaterThan</fullName>
                <label>maior que</label>
            </value>
            <value>
                <fullName>lessOrEqual</fullName>
                <label>menor ou igual</label>
            </value>
            <value>
                <fullName>lessThan</fullName>
                <label>menor que</label>
            </value>
            <value>
                <fullName>doesNotContains</fullName>
                <label>não contém</label>
            </value>
            <value>
                <fullName>notEqualsTo</fullName>
                <label>diferente de</label>
            </value>
            <value>
                <fullName>itHas</fullName>
                <label>possui</label>
            </value>
            <value>
                <fullName>doesntHave</fullName>
                <label>não possui</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/RuleNumber__c.field-meta.xml
<CustomField>
    <fullName>RuleNumber__c</fullName>
    <label>Número da Regra</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Aviso</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Regras do Script</relationshipLabel>
    <relationshipName>Regras_do_Script</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor a ser Comparado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScriptRuleControllerTest.cls
@isTest
public class ScriptRuleControllerTest {
    
    @testSetup 
    static void setup(){
    	Account account = DataFactory.createAccount();
        insert account;
        
        Script__c automaticScript = DataFactory.createAutomaticScript();
        insert automaticScript;   
        
        ScriptRule__c scriptRule = DataFactory.createScriptRule(automaticScript.Id, 1, 'A');
        insert scriptRule;
    }
    
    @isTest
    public static void getAllObjectsDetails(){
        
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();

        Account account = [SELECT Id FROM Account LIMIT 1];
        
        List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
     
        Test.startTest(); 
        ScriptRuleController.getAllObjectsDetails();
       	Test.stopTest();
    }
	
	@isTest
    public static void getValuePicklistTest(){   
        
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();

        Account account = [SELECT Id FROM Account LIMIT 1];
        
        List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
        List<ScriptRule__c> scriptRule = [SELECT Id, FilterBy__c, Operator__c FROM ScriptRule__c WHERE Script__c =: automaticScript[0].Id LIMIT 1];
        
        ScriptRule__c scriptRuleToUpdate = new ScriptRule__c(
        	Id = scriptRule[0].Id,
        	FilterBy__c = 'none'   
        );
        update scriptRuleToUpdate;

		Test.startTest(); 
        ScriptRuleController.getValuePicklist();
       	Test.stopTest();        
        
   	}
    
    @isTest
    public static void setValuePicklistInMapTest(){
        
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();

        Account account = [SELECT Id FROM Account LIMIT 1];
        
        List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
        List<ScriptRule__c> scriptRule = [SELECT Id, FilterBy__c, Operator__c FROM ScriptRule__c WHERE Script__c =: automaticScript[0].Id LIMIT 1];
        
        Test.startTest();
        
        ScriptRule__c scriptRuleToUpdate = new ScriptRule__c(
        	Id = scriptRule[0].Id,
        	FilterBy__c = 'none'   
        );
        update scriptRuleToUpdate;
        
        Test.stopTest();  
    
    }
   
    @isTest
    public static void saveScriptRulesTest(){
        
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();

        Account account = [SELECT Id FROM Account LIMIT 1];
        
        Script__c automaticScript = new Script__c(        
        Name = 'ScriptTest',
        StartDate__c = system.TODAY(),
        EndDate__c = system.TODAY(),
        Status__c = 'Draft',
        Message__c = 'Message',
        Priority__c = 1,
        Recurrent__c = 'No',
        RecordTypeId = automaticRecordType
        );
        insert automaticScript;
        
        List<Script__c> scriptCreated = [SELECT Id FROM Script__c WHERE RecordTypeId =: automaticRecordType AND Name = 'ScriptTest' LIMIT 1];
        
        Id scriptId = scriptCreated[0].Id;
        
        Test.startTest(); 
        
        ScriptRule__c scriptRule = new ScriptRule__c(
            Script__c = scriptCreated[0].Id,
        	RuleNumber__c = 1,
        	Object__c = 'conta',
        	Field__c = 'Nome',
        	Operator__c = 'startsWith',
        	Value__c = 'S',
        	ObjectAPI__c = 'Account',
       		FieldAPI__c = 'Name',
        	FilterBy__c = 'none'
		);
        
        map<Object, Object> mapScriptRule= new map<Object, Object>();
        
        mapScriptRule.put('numberRule', string.valueOf(scriptRule.RuleNumber__c));
        mapScriptRule.put('operatorScript', string.valueOf(scriptRule.Operator__c));
        mapScriptRule.put('objectAPI', string.valueOf(scriptRule.ObjectAPI__c));
        mapScriptRule.put('fieldScriptAPI', string.valueOf(scriptRule.FieldAPI__c));
        mapScriptRule.put('valueToCompare', string.valueOf(scriptRule.RuleNumber__c));
        mapScriptRule.put('filterScript', string.valueOf(scriptRule.FilterBy__c));
        
        List<map<Object, Object>> listScriptrule = new List<map<Object, Object>>();
        
        listScriptrule.add(mapScriptRule);
        
        ScriptRuleController.saveScriptRules(listScriptrule, scriptId);
       	
        Test.stopTest();

    }
    
    @isTest
    public static void saveScriptRulesTest1(){
        
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();

        Account account = [SELECT Id FROM Account LIMIT 1];
        
        Script__c automaticScript = new Script__c(        
        Name = 'ScriptTest',
        StartDate__c = system.TODAY(),
        EndDate__c = system.TODAY(),
        Status__c = 'Draft',
        Message__c = 'Message',
        Priority__c = 1,
        Recurrent__c = 'No',
        RecordTypeId = automaticRecordType
        );
        insert automaticScript;
        
        List<Script__c> scriptCreated = [SELECT Id FROM Script__c WHERE RecordTypeId =: automaticRecordType AND Name = 'ScriptTest' LIMIT 1];
        
        Id scriptId = scriptCreated[0].Id;
        
        List<scriptRule__c> listScriprule = new List<scriptRule__c>();
        
        Test.startTest(); 
        ScriptRuleController.saveScriptRules(listScriprule, scriptId);
       	Test.stopTest();

    }
    
    @isTest
    public static void getListNumberRulesActualScriptTest(){
        
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();

        Account account = [SELECT Id FROM Account LIMIT 1];
        
        List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        Id scriptId = automaticScript[0].Id;
        
        Test.startTest(); 
        ScriptRuleController.getListNumberRulesActualScript(scriptId);
       	Test.stopTest(); 
    }
    
    @isTest
    public static void getListNumberRulesActualScriptTest1(){
        
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();

        Account account = [SELECT Id FROM Account LIMIT 1];
        
        Id scriptId;
        
        Test.startTest(); 
        ScriptRuleController.getListNumberRulesActualScript(scriptId);
       	Test.stopTest(); 
    }
    
   
    
}