force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para Scripts Guiados. Exemplo: Script de Atendimento</description>
    <label>Script</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptRule__c/ScriptRule__c.object-meta.xml
<CustomObject>
    <label>Regra do Script</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Script Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras do Script</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptRule__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Aviso</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Regras do Script</relationshipLabel>
    <relationshipName>Regras_do_Script</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScriptRuleTriggerHandler.cls
public with sharing class ScriptRuleTriggerHandler {
    
    public static void validateDeleteScriptRule(){
        if(Trigger.isAfter || !Trigger.isDelete){ return;}
        
        string customLabel = System.Label.ScriptRuleDelete;
        
        Set<Id> setIdScript = new Set<Id>();
        Set<Id> setIdScriptActive = new Set<Id>();
        
        for(ScriptRule__c forscriptRule : (List<ScriptRule__c>) Trigger.old){
            setIdScript.add(forscriptRule.Script__c);
     	}

        if(setIdScript.isEmpty()){ return;}
        List<Script__c> listScript = [SELECT Id, Status__c FROM Script__c WHERE Id =: setIdScript];

        for(Script__c forScript : listScript){
        	if(forScript.Status__c == 'Active'){
				setIdScriptActive.add(forScript.Id);
            }
        }
        
        if(setIdScriptActive.isEmpty()){ return;}
        for(ScriptRule__c forscriptRuleError : (List<ScriptRule__c>) Trigger.old){
		   		forscriptRuleError.addError(customLabel);
        }
     }       
}