force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para Scripts Guiados. Exemplo: Script de Atendimento</description>
    <label>Script</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/Logic__c.field-meta.xml
<CustomField>
    <fullName>Logic__c</fullName>
    <label>Lógica</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Script__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Prioridade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Script__c/fields/Recurrent__c.field-meta.xml
<CustomField>
    <fullName>Recurrent__c</fullName>
    <label>Recorrente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>Sim</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Script__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Data Inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Script__c/recordTypes/AutomaticWarning.recordType-meta.xml
<RecordType>
    <fullName>AutomaticWarning</fullName>
    <active>true</active>
    <description>Tipo de Registro para criação de avisos automáticos exibidos no mural de avisos do cliente</description>
    <label>Aviso Automático (Massivo)</label>
</RecordType>

force-app/main/default/objects/Script__c/recordTypes/ManualWarning.recordType-meta.xml
<RecordType>
    <fullName>ManualWarning</fullName>
    <active>true</active>
    <description>Tipo de Registro para criação de avisos com atribuição manual de clientes exibidos no mural de avisos</description>
    <label>Aviso Manual</label>
</RecordType>

force-app/main/default/objects/ScriptDetail__c/ScriptDetail__c.object-meta.xml
<CustomObject>
    <label>Detalhe do Script</label>
    <nameField>
        <label>Nome de ScriptDetail</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Detalhes do Script</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Histórico de Comunicados</relationshipLabel>
    <relationshipName>Script_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptDetail__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Detalhes_do_Script</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScriptDetail__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <formula>Script__r.Priority__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prioridade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScriptDetail__c/fields/Recurrent__c.field-meta.xml
<CustomField>
    <fullName>Recurrent__c</fullName>
    <formula>Text( Script__r.Recurrent__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recorrente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptDetail__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Detalhes do Script</relationshipLabel>
    <relationshipName>ScriptDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScriptDetail__c/fields/Verbalized__c.field-meta.xml
<CustomField>
    <fullName>Verbalized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verbalizado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScriptDetail__c/recordTypes/WarningLogs.recordType-meta.xml
<RecordType>
    <fullName>WarningLogs</fullName>
    <active>true</active>
    <description>Tipo de Registro para Associar os clientes aos avisos manuais e consultar logs do Mural de Avisos</description>
    <label>Log de Avisos</label>
</RecordType>

force-app/main/default/objects/ScriptRule__c/ScriptRule__c.object-meta.xml
<CustomObject>
    <label>Regra do Script</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Script Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regras do Script</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScriptRule__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Campo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/FieldAPI__c.field-meta.xml
<CustomField>
    <fullName>FieldAPI__c</fullName>
    <description>Campo que contemplará a API do Campo que a regra utilizará.</description>
    <label>API do Campo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/FilterBy__c.field-meta.xml
<CustomField>
    <fullName>FilterBy__c</fullName>
    <description>Campo que contemplará as possibilidades de filtro que o usuário poderá escolher quando o critério for direcionado para um objeto relacionado.</description>
    <label>Filtrar por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>none</fullName>
                <label>Nenhum registro</label>
            </value>
            <value>
                <fullName>allRecords</fullName>
                <label>Todos registros</label>
            </value>
            <value>
                <fullName>oneRecord</fullName>
                <label>Pelo menos um</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/ObjectAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI__c</fullName>
    <description>Campo que contemplará a API do Objeto que a regra terá como base.</description>
    <label>API do Objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Campo que contemplará as possíveis operações que o usuário poderá selecionar ao criar a regra do script.</description>
    <label>Operador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>startsWith</fullName>
                <label>começa com</label>
            </value>
            <value>
                <fullName>contains</fullName>
                <label>contém</label>
            </value>
            <value>
                <fullName>equals</fullName>
                <label>igual a</label>
            </value>
            <value>
                <fullName>greaterOrEqual</fullName>
                <label>maior ou igual</label>
            </value>
            <value>
                <fullName>greaterThan</fullName>
                <label>maior que</label>
            </value>
            <value>
                <fullName>lessOrEqual</fullName>
                <label>menor ou igual</label>
            </value>
            <value>
                <fullName>lessThan</fullName>
                <label>menor que</label>
            </value>
            <value>
                <fullName>doesNotContains</fullName>
                <label>não contém</label>
            </value>
            <value>
                <fullName>notEqualsTo</fullName>
                <label>diferente de</label>
            </value>
            <value>
                <fullName>itHas</fullName>
                <label>possui</label>
            </value>
            <value>
                <fullName>doesntHave</fullName>
                <label>não possui</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/RuleNumber__c.field-meta.xml
<CustomField>
    <fullName>RuleNumber__c</fullName>
    <label>Número da Regra</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <label>Aviso</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Regras do Script</relationshipLabel>
    <relationshipName>Regras_do_Script</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScriptRule__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor a ser Comparado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HandlerScriptNotificationTest.cls
@isTest
public class HandlerScriptNotificationTest {

    @testSetup 
    static void setup(){
        
        Account account = DataFactory.createAccount();
        insert account;
        
        Account address = new Account(
        Name = 'Test nome',
        ParentId = account.Id,
        ShippingCity = 'São Paulo'
        );
        insert address; 
        
        Script__c manualScript = DataFactory.createManualScript();
        insert manualScript;
        
        ScriptDetail__c scriptLog = DataFactory.createScripDetailLog(manualScript.Id, account.Id);
        insert scriptLog;
        
        Script__c automaticScript = DataFactory.createAutomaticScript();
        insert automaticScript;
        
        ScriptRule__c scriptRule = DataFactory.createScriptRule(automaticScript.Id, 1, 'A');
        insert scriptRule;
        
        ScriptRule__c scriptRule1 = DataFactory.createScriptRule(automaticScript.Id, 2, 'B');
        insert scriptRule1;
        
       }
    
    
    @isTest
    public static void getIdNotificationTest(){
        
        List<String> listParams = new List<String>();
       
        Account account = [SELECT Id FROM Account LIMIT 1];
        
        listParams.add(account.Id + ',' + UserInfo.getUserId());
        
        String manualRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('ManualWarning').getrecordTypeId();
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
        List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
      
        Script__c updateScript = new Script__c(
        	Id = automaticScript[0].Id,
        	Logic__c = '(1 AND 2)'
            );
        update updateScript; 
        
        Script__c updateScript1 = new Script__c(
        	Id = automaticScript[0].Id,
        	Status__c = 'Active'
            );
        update updateScript1;
        
        Test.startTest(); 
        HandlerScriptNotification.getIdNotification(listParams);
       	Test.stopTest();
   
    }
    @isTest
    public static void getScriptSpecificsTest(){
        
        String manualRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('ManualWarning').getrecordTypeId();
        
        Account account = [SELECT Id FROM Account LIMIT 1];
                
        Script__c manualScript = new Script__c(
        	Name = 'Script',
        	StartDate__c = system.TODAY(),
            EndDate__c = system.TODAY(),
            Status__c = 'Active',
            Message__c = 'Message',
            Priority__c = 1,
            Recurrent__c = 'No',
            RecordTypeId = manualRecordType
        );
        insert manualScript;
        
        List<Id> listScriptsIds = new List<Id>();
        
        for (ScriptDetail__c forScriptDetail : [SELECT Id FROM ScriptDetail__c WHERE Account__c =: account.Id]){
            listScriptsIds.add(forScriptDetail.Id);
        }

         Test.startTest(); 
        HandlerScriptNotification.getScriptSpecifics(listScriptsIds, account.Id);
       	Test.stopTest(); 
    }

    
    @isTest
    public static void validateFieldAccountTest(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
         
        String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
        List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
        ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'startsWith',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c'
            );

        insert scriptRule;
        
         Script__c updateScript = new Script__c(
        	Id = automaticScript[0].Id,
        	Logic__c = '(3)'
            );
        update updateScript; 
        
        Script__c updateScript1 = new Script__c(
        	Id = automaticScript[0].Id,
        	Status__c = 'Active'
            );
        update updateScript1;
        
        system.debug('scriptRule' + scriptRule);
        system.debug('account' + account);
        
		Test.startTest();
        HandlerScriptNotification.validateFieldAccount(account, scriptRule);
        Test.stopTest();
    
    }  
    
    @isTest
    public static void validateObjectRelationship(){
        
         Map<String, List<sObject>> mapObjectsRelationship = new Map<String, List<sObject>>();
        
         Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'startsWith',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'none'
            );
        insert scriptRule;
        
        Script__c updateScript = new Script__c(
        	Id = automaticScript[0].Id,
        	Logic__c = '(3)'
            );
        update updateScript; 
        
        Script__c updateScript1 = new Script__c(
        	Id = automaticScript[0].Id,
        	Status__c = 'Active'
            );
        update updateScript1;
        
        List<Account> listAddress = mapObjectsRelationship.put(scriptRule.ObjectAPI__c, [SELECT Id, ShippingCity FROM Account WHERE ParentId =: account.Id]);    

        Test.startTest();
        HandlerScriptNotification.validateObjectRelationship(mapObjectsRelationship, scriptRule);
        Test.stopTest();
    }
    
    @isTest
    public static void validateObjectRelationship1(){
        Map<String, List<sObject>> mapObjectsRelationship = new Map<String, List<sObject>>();
        
         Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'startsWith',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'oneRecord'
            );
        insert scriptRule;
        
        Script__c updateScript = new Script__c(
        	Id = automaticScript[0].Id,
        	Logic__c = '(3)'
            );
        update updateScript; 
        
        Script__c updateScript1 = new Script__c(
        	Id = automaticScript[0].Id,
        	Status__c = 'Active'
            );
        update updateScript1;
        
        List<Account> listAddress = mapObjectsRelationship.put(scriptRule.ObjectAPI__c, [SELECT Id, ShippingCity FROM Account WHERE ParentId =: account.Id]);    

        Test.startTest();
        HandlerScriptNotification.validateObjectRelationship(mapObjectsRelationship, scriptRule);
        Test.stopTest();
    }
    
    @isTest
    public static void validateObjectRelationship2(){
        Map<String, List<sObject>> mapObjectsRelationship = new Map<String, List<sObject>>();
        
         Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'startsWith',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        Script__c updateScript = new Script__c(
        	Id = automaticScript[0].Id,
        	Logic__c = '(3)'
            );
        update updateScript; 
        
        Script__c updateScript1 = new Script__c(
        	Id = automaticScript[0].Id,
        	Status__c = 'Active'
            );
        update updateScript1;
        
        List<Account> listAddress = mapObjectsRelationship.put(scriptRule.ObjectAPI__c, [SELECT Id, ShippingCity FROM Account WHERE ParentId =: account.Id]);    

        Test.startTest();
        HandlerScriptNotification.validateObjectRelationship(mapObjectsRelationship, scriptRule);
        Test.stopTest();
    }
    
    @isTest
    public static void executeValidateTest(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'startsWith',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
    @isTest
    public static void executeValidateTest1(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'contains',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
    @isTest
    public static void executeValidateTest2(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'doesNotContains',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
    @isTest
    public static void executeValidateTest3(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'equals',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
    @isTest
    public static void executeValidateTest4(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'notEqualsTo',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
     @isTest
    public static void executeValidateTest5(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'greaterOrEqual',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
     @isTest
    public static void executeValidateTest6(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'greaterThan',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
     @isTest
    public static void executeValidateTest7(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'lessOrEqual',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
     @isTest
    public static void executeValidateTest8(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'lessThan',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
     @isTest
    public static void executeValidateTest9(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'itHas',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
         Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
    @isTest
    public static void executeValidateTest10(){
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
         String automaticRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('AutomaticWarning').getrecordTypeId();
        
         List<Script__c> automaticScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: automaticRecordType LIMIT 1];
        
         ScriptRule__c scriptRule = new ScriptRule__c(
        	Script__c = automaticScript[0].Id,
       		RuleNumber__c = 3,
        	Object__c = 'Endereço',
        	Field__c = 'Cidade',
        	Operator__c = 'doesntHave',
        	Value__c = 'S',
        	ObjectAPI__c = 'Address__c',
        	FieldAPI__c = 'City__c',
            FilterBy__c = 'allRecords'
            );
        insert scriptRule;
        
        String field = scriptRule.FieldAPI__c;
        String value = scriptRule.Value__c;
        String operator = scriptRule.Operator__c;
        
        Test.startTest();
        HandlerScriptNotification.executeValidate(field, value, operator);
        Test.stopTest();
        
    }
    
    @isTest
    public static void createLogOfScript(){
       
        String manualRecordType = Schema.SObjectType.Script__c.getRecordTypeInfosByDeveloperName().get('ManualWarning').getrecordTypeId();
        String logRecordType = Schema.SObjectType.ScriptDetail__c.getRecordTypeInfosByDeveloperName().get('WarningLogs').getrecordTypeId();
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        
        List<Script__c> manualScript = [SELECT Id, Name, Message__c, Logic__c, Status__c FROM Script__c WHERE RecordTypeId =: manualRecordType LIMIT 1];
        
        ScriptDetail__c scriptDetail = new ScriptDetail__c(
        Script__c = manualScript[0].Id,
        Account__c = account.Id,
        Name = 'Detalhe Script',
        Verbalized__c = False,
        RecordTypeId = logRecordType
		);
        insert scriptDetail;
        
       List<String> listParams = new List<String>();
        
        listParams.add(account.Id + ',' + UserInfo.getUserId());
       
        List<String> listScriptId = new List<String>();
        
        for(Script__c forScript : [SELECT Id FROM Script__c]){
            listScriptId.add(forScript.Id);
        }
        
        
        Test.startTest();
        HandlerScriptNotification.createLogOfScript(listScriptId, account.Id, UserInfo.getUserId());
        Test.stopTest();
        
    }
    
}