force-app/main/default/objects/OfferFilter__c/OfferFilter__c.object-meta.xml
<CustomObject>
    <description>Registros utilizado para gerenciar filtros do componente customizado de ofertas fixa e móvel</description>
    <label>Filtro de Oferta</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Nome do Filtro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filtro de Ofertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OfferFilter__c/fields/Cabinet__c.field-meta.xml
<CustomField>
    <fullName>Cabinet__c</fullName>
    <description>Código do armário</description>
    <label>Armário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OfferFilter__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Nome da cidade para aplicar o filtro de categoria cidade</description>
    <label>Cidade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OfferFilter__c/fields/FilterCode__c.field-meta.xml
<CustomField>
    <fullName>FilterCode__c</fullName>
    <description>Código ou identificação do filtro</description>
    <label>Código do Filtro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OfferFilter__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo para marcar filtros ativos.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OfferFilter__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <description>Lista de estados para o filtro de categoria cidade</description>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OfferFilter__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Opções de tecnologia utilizada pelo filtro de categoria cidade</description>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FTTC</fullName>
            </value>
            <value>
                <fullName>FTTH</fullName>
            </value>
            <value>
                <fullName>XDSL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OfferFilter__c/recordTypes/CityCategoryAndCabinet.recordType-meta.xml
<RecordType>
    <fullName>CityCategoryAndCabinet</fullName>
    <active>true</active>
    <description>Para criar filtros de categoria cidade e armários</description>
    <label>Categoria Cidade e Armário</label>
</RecordType>

force-app/main/default/classes/OfferFilterDAO.cls
public with sharing class OfferFilterDAO {
    public static List<OfferFilter__c> getAllCitiesCategories(String CityCategoryAndCabinet) {

        return[
            SELECT 
                Id, 
                IsActive__c, 
                Cabinet__c, 
                City__c, 
                FilterCode__c, 
                Technology__c, 
                StateCode__c 
            FROM 
                OfferFilter__c 
            WHERE 
                IsActive__c = true 
            AND 
                RecordType.DeveloperName =: CityCategoryAndCabinet];
    }
}