force-app/main/default/objects/AdabasSite__c/AdabasSite__c.object-meta.xml
<CustomObject>
    <label>Adabas Site</label>
    <nameField>
        <label>Adabas Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adabas Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdabasSite__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Center__c/Center__c.object-meta.xml
<CustomObject>
    <label>Centro</label>
    <nameField>
        <displayFormat>Centro-{000000}</displayFormat>
        <label>Centro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Centros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <label>Centro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Center__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Escritório de Vendas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Center__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Loja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserIdentifier__c.field-meta.xml
<CustomField>
    <fullName>UserIdentifier__c</fullName>
    <label>Identificador do usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PartnerContact.recordType-meta.xml
<RecordType>
    <fullName>PartnerContact</fullName>
    <active>true</active>
    <description>Tipo de registro para a criação de um contato relacionado a conta parceiro</description>
    <label>Contato Parceiro</label>
</RecordType>

force-app/main/default/objects/PublicGroup__mdt/PublicGroup__mdt.object-meta.xml
<CustomObject>
    <description>Utilizado no de/para na criação e alteração dos usuários para inserção nos grupos públicos correspondentes</description>
    <label>Grupo Público</label>
    <pluralLabel>Grupos Públicos</pluralLabel>
</CustomObject>

force-app/main/default/objects/PublicGroup__mdt/fields/PartnerGroup__c.field-meta.xml
<CustomField>
    <fullName>PartnerGroup__c</fullName>
    <label>Grupo do Aliado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TelevendasAliados</fullName>
                <default>true</default>
                <label>Televendas</label>
            </value>
            <value>
                <fullName>PAPAliados</fullName>
                <label>PAP</label>
            </value>
            <value>
                <fullName>RetencaoTotalizadaFixaAliados</fullName>
                <label>Retenção Totalizada Fixa</label>
            </value>
            <value>
                <fullName>RetencaoFixaAltasMovelAliados</fullName>
                <label>Retenção Fixa Altas Móvel</label>
            </value>
            <value>
                <fullName>RetencaoFixaOCAliados</fullName>
                <label>Retenção Fixa OC</label>
            </value>
            <value>
                <fullName>RetencaoFixaAliados</fullName>
                <label>Retenção Fixa</label>
            </value>
            <value>
                <fullName>RetencaoTotalizadaMovelAliados</fullName>
                <label>Retenção Totalizada Móvel</label>
            </value>
            <value>
                <fullName>RetencaoMovelAltasFixaAliados</fullName>
                <label>Retenção Móvel Altas Fixa</label>
            </value>
            <value>
                <fullName>RetencaoMovelOCAliados</fullName>
                <label>Retenção Móvel OC</label>
            </value>
            <value>
                <fullName>RetencaoMovelAliados</fullName>
                <label>Retenção Móvel</label>
            </value>
            <value>
                <fullName>RevendaAliados</fullName>
                <label>Revenda</label>
            </value>
            <value>
                <fullName>SilverRetencaoTotalizada</fullName>
                <label>Silver Retenção Totalizada</label>
            </value>
            <value>
                <fullName>SilverRetencaoFixa</fullName>
                <label>Silver Retenção Fixa</label>
            </value>
            <value>
                <fullName>SilverRetencaoFixaOutraChance</fullName>
                <label>Silver Retenção Fixa Outra Chance</label>
            </value>
            <value>
                <fullName>SilverRetencaoFixaWinback</fullName>
                <label>Silver Retenção Fixa Winback</label>
            </value>
            <value>
                <fullName>SilverRetencaoMovel</fullName>
                <label>Silver Retenção Móvel</label>
            </value>
            <value>
                <fullName>SilverRetencaoMovelOutraChance</fullName>
                <label>Silver Retenção Móvel Outra Chance</label>
            </value>
            <value>
                <fullName>SilverRetencaoMovelWinback</fullName>
                <label>Silver Retenção Móvel Winback</label>
            </value>
            <value>
                <fullName>SilverFixa</fullName>
                <label>Silver Fixa</label>
            </value>
            <value>
                <fullName>SilverFixaCrosseling</fullName>
                <label>Silver Fixa Crosseling</label>
            </value>
            <value>
                <fullName>SilverMovel</fullName>
                <label>Silver Móvel</label>
            </value>
            <value>
                <fullName>SilverMovelCrosseling</fullName>
                <label>Silver Móvel Crosseling</label>
            </value>
            <value>
                <fullName>SAVAliados</fullName>
                <label>SAV</label>
            </value>
            <value>
                <fullName>PurpuraRetencaoFixa</fullName>
                <label>Púrpura Retenção Fixa</label>
            </value>
            <value>
                <fullName>PurpuraRetencaoMovel</fullName>
                <label>Púrpura Retenção Móvel</label>
            </value>
            <value>
                <fullName>PurpuraFixa</fullName>
                <label>Púrpura Fixa</label>
            </value>
            <value>
                <fullName>PurpuraFixaCrosseling</fullName>
                <label>Púrpura Fixa Crosseling</label>
            </value>
            <value>
                <fullName>PurpuraMovel</fullName>
                <label>Púrpura Móvel</label>
            </value>
            <value>
                <fullName>PurpuraMovelCrosseling</fullName>
                <label>Púrpura Móvel Crosseling</label>
            </value>
            <value>
                <fullName>OuvidoriaAliados</fullName>
                <label>Ouvidoria</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOffices__mdt/SalesOffices__mdt.object-meta.xml
<CustomObject>
    <label>Escritório de Vendas</label>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
</CustomObject>

force-app/main/default/objects/SalesOffices__mdt/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <label>Centro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOffices__mdt/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Escritório de Vendas</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Adabas__c.field-meta.xml
<CustomField>
    <fullName>Adabas__c</fullName>
    <label>Adabas</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <label>Centro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/ChannelName__c.field-meta.xml
<CustomField>
    <fullName>ChannelName__c</fullName>
    <description>Channel name</description>
    <label>Channel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login de rede</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Responsável por armazenar as informações do Canal de Atendimento proveniente da integração com IDM.</description>
    <label>Escritório de Vendas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PartnerGroup__c.field-meta.xml
<CustomField>
    <fullName>PartnerGroup__c</fullName>
    <label>Grupo do Aliado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VendasAliado</fullName>
                <label>Vendas Aliado</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPConsultor</fullName>
                <label>Vendas Aliado PaP Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPGerente</fullName>
                <label>Vendas Aliado PaP Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaConsultor</fullName>
                <label>Vendas Aliado Revenda Consultor</label>
            </value>
            <value>
                <fullName>VendasAliadoRevendaGerente</fullName>
                <label>Vendas Aliado Revenda Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasGerente</fullName>
                <label>Vendas Aliado Televendas Gerente</label>
            </value>
            <value>
                <fullName>VendasAliadoPaPSupervisor</fullName>
                <label>Vendas Aliado PaP Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasCoordenador</fullName>
                <label>Vendas Aliado Televendas Coordenador</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasSupervisor</fullName>
                <label>Vendas Aliado Televendas Supervisor</label>
            </value>
            <value>
                <fullName>VendasAliadoTelevendasConsultor</fullName>
                <label>Vendas Aliado Televendas Consultor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraNextConvergenteSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Next Convergente Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoFixaSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Fixa Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraRetratacaoMovelSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Retratacao Movel Supervisor</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoOp</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Operador</label>
            </value>
            <value>
                <fullName>AtendAliadoSilverePurpuraSatisfacaoSup</fullName>
                <label>Atendimento Aliado Silver e Purpura Satisfacao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeOperador</fullName>
                <label>Atendimento Aliado Backoffice Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoOp</fullName>
                <label>Atendimento Aliado Backoffice Retencao Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeRetencaoSup</fullName>
                <label>Atendimento Aliado Backoffice Retencao Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoBackofficeSupervisor</fullName>
                <label>Atendimento Aliado Backoffice Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Ativo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaAtivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Ativo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoOperador</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoCobrancaReceptivoSupervisor</fullName>
                <label>Atendimento Aliado Cobranca Receptivo Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaOperador</fullName>
                <label>Atendimento Aliado Ouvidoria Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoOuvidoriaSupervisor</fullName>
                <label>Atendimento Aliado Ouvidoria Supervisor</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingOp</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Operador</label>
            </value>
            <value>
                <fullName>AtendimentoAliadoPurpuraFixaCrosselingSup</fullName>
                <label>Atendimento Aliado Purpura Fixa Crosseling Supervisor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <description>Responsável por armazenar as informações de Site(Ponto de Venda) provenientes da integração com o sistema IDM/OIM.</description>
    <label>Site</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OAMRegistrationHandler.cls
/*
* @author: Diego Costa @Deloitte
* @description: Classe Handler para aprovisionamento de conta/contato/usuário.
* @data: 10/06/2022
*
*/
global class OAMRegistrationHandler implements Auth.RegistrationHandler {
    private static final String CONST_PARTNER_ACCOUNT_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PartnerAccount').getrecordTypeId();

    class RegHandlerException extends Exception {}

    global User createUser (Id portalId, Auth.UserData data) {        
        return UserProvisioning(data);
    }

    global void updateUser (Id userId, Id portalId, Auth.UserData data) {        
        UserProvisioning(data);
    }

    private User userProvisioning (Auth.UserData data) {
        try{
            system.debug('data: ' + data);
            String sandboxName      = getSandboxName();
            String userNameSandbox  = data.username + sandboxName;
            String CNPJResponse     = data.attributeMap.get('CNPJ');
			
            Profile userProfile         = getProfile(data.attributeMap.get('profile_name')); //getProfile('AdministracaoSistema'); 
            String  userLicenseProfile  = userProfile.Id == null ? '' : userProfile.UserLicense.Name;
            Boolean userInternal        = userLicenseProfile != 'Partner Community';
            // Validação de 1º nível.
            fristValidateResponse(data, userInternal);

            User userRecord = getUserData(userNameSandbox);
            
            // Busca existencia de contato na base.
            Contact contactRecord = getContactData(userInternal, userNameSandbox);
            
            String userRole = getRole(data.attributeMap.get('role'), userInternal); //getRole('Telefonica_Brasil', userInternal);
            List<String> ltPermissionSetResponse = getPermissionSet(data.attributeMap.get('permission_sets'));
            List<PermissionSet> ltPermissionSetSF = new List<PermissionSet>([SELECT Id, Name FROM PermissionSet WHERE Name IN :ltPermissionSetResponse AND ProfileId = null]);

            // Validação de 2º nível.
            secondValidateResponse(data, userInternal, userProfile, userLicenseProfile, userRole, contactRecord, 
                                    ltPermissionSetSF, ltPermissionSetResponse);

            //Chama ação de conta, contato e usuário
            return actionAccCttUs(CNPJResponse, userNameSandbox, userInternal , userRecord, sandboxName, 
                                    userProfile, userRole, contactRecord, data, ltPermissionSetResponse, ltPermissionSetSF);
        }
        catch(RegHandlerException e) {
            throw e;
        }
        catch(exception x) {
            throw new RegHandlerException('Erro desconhecido: ' + x.getMessage());
        }
    }
    
    // Função para buscar contato na base.
    private Contact getContactData (Boolean userInternal, String userName) {
        if (userInternal) {
            return new Contact();
        } else{
            List<Contact> ltContact = new List<Contact>([SELECT Id, Name, Email, AccountId, Account.Name FROM Contact WHERE UserIdentifier__c =: userName LIMIT 1]);
            return (ltContact.size() > 0 ? ltContact[0] : new Contact());
        }
    }

    // Função responsável por chamar a ação de conta contato e usuário
    public User actionAccCttUs (String CNPJResponse, 
                                String userNameResponse, 
                                Boolean userInt , 
                                User lUser, 
                                String nomeSandbox, 
                                Profile lProfile, 
                                String role, 
                                Contact lContact, 
                                Auth.UserData data, 
                                List<String> lPermissionSet, 
                                List<PermissionSet> lPermissionSetSF) {
        if (!userInt) {
            //Cria/atualiza conta
            Account lAccountResult = actionAccount(CNPJResponse, data);
            // Cria/atualiza contato
            Contact lContactResult = actionContact(lContact, lAccountResult, data, userNameResponse);
            
            // cria o usuário
            return createUpdateUser(userInt, lUser, nomeSandbox, lProfile, role, lContactResult, data, lPermissionSetSF); 
        } else {
            // Atualizando o usuário
            return createUpdateUser(userInt, lUser, nomeSandbox, lProfile, role, new Contact(), data, lPermissionSetSF); 
        }
    }

    // Função para retornar o perfil de acordo com interno ou parceiro.
    private Profile getProfile (String profileName) {
        List<Profile> ltProfile = new List<Profile>([SELECT Id, Name, UserLicense.Name FROM profile WHERE name=: profileName  LIMIT 1]);

        return (ltProfile.size() > 0 ? ltProfile[0] : new Profile());
    }

    // Função retorna permissionset do response
    private List<String> getPermissionSet (String responsePermisionSet) {
        if (String.isEmpty(responsePermisionSet)) {
            return new List<String>();
        }
        List<String> ltPermissionSet = (List<String>) JSON.deserialize(responsePermisionSet, List<String>.class);

        return ltPermissionSet;
    }

    // Função para montar filtro da query de Papel
    private String getRole (String roleResponse, Boolean userInternal) {
        system.debug('roleResponse: ' + roleResponse);
        if (userInternal) {
            List<UserRole> ltRole = new List<UserRole>([SELECT Id FROM UserRole WHERE DeveloperName = :roleResponse LIMIT 1]);
			system.debug('roleResponse: ' + roleResponse);
            return (ltRole.size() > 0 ? String.valueOf(ltRole[0].Id) : 'null');
        } else {
            Set<String> setPartnerGroup = new Set<String>();
            Schema.DescribeFieldResult field = User.PartnerGroup__c.getDescribe();
            
            for (Schema.PicklistEntry item : field.getPicklistValues()) {
                setPartnerGroup.add(item.getValue());
            }
            return (setPartnerGroup.contains(roleResponse) ? roleResponse : 'null');
        }
    }

    // Função para trabalhar com usuário
    private User createUpdateUser(Boolean userInternal, 
                                    User userRecord, 
                                    String sandboxName, 
                                    Profile userProfile, 
                                    String userRole, 
                                    Contact contactRecord, 
                                    Auth.UserData data, 
                                    List<PermissionSet> ltPermissionSetSF) {
        try{
            userRecord.IsActive     = true;
            userRecord.UserName     = data.username + sandboxName;
            userRecord.Email        = userInternal ? data.email : data.username; 
            userRecord.FirstName    = data.firstName;
            userRecord.LastName     = data.lastName;
            userRecord.FederationIdentifier = data.username; 

            String alias = data.username;
            userRecord.alias = alias.left(8);

            Boolean updateGroup = false;

            if(contactRecord.Id != null && userRecord.Id == null) {
                userRecord.ContactId = contactRecord.Id;
            }
            if(userProfile.Id != null) {
                userRecord.ProfileId = userProfile.Id;
            }
            if(data.attributeMap.containsKey('network_id')) {
                userRecord.Login__c = data.attributeMap.get('network_id');
            }
            if(data.attributeMap.containsKey('adabas')) {
                userRecord.Adabas__c = data.attributeMap.get('adabas');
            }
            if(data.attributeMap.containsKey('employee_number')) {
                userRecord.EmployeeNumber = data.attributeMap.get('employee_number');
            }
            if(data.attributeMap.containsKey('phone_number')) {
                userRecord.MobilePhone = data.attributeMap.get('phone_number');
            }
            if(userInternal) {
                userRecord.UserRoleId = Id.valueOf(userRole);
            } else{
                if(userRecord.PartnerGroup__c != userRole) {
                    updateGroup = true;
                }
                userRecord.PartnerGroup__c = userRole;
            }
            if(data.attributeMap.containsKey('canal_atendimento')) {
        		userRecord.ChannelName__c = data.attributeMap.get('canal_atendimento');
   	        }
	        if(data.attributeMap.containsKey('site')) {
        		userRecord.Site__c = data.attributeMap.get('site');
    	    }    
	        if(data.attributeMap.containsKey('escritorio_vendas')) {
		        SalesOffices__mdt office =  getOffice(data.attributeMap.get('escritorio_vendas'));

                if (office != null) {
                    userRecord.Office__c = office.Office__c;
                    userRecord.Center__c = office.Center__c;
                    userRecord.Store__c = office.Store__c;
                } else {
                    userRecord.Office__c = data.attributeMap.get('escritorio_vendas');
                    userRecord.Center__c = null;
                    userRecord.Store__c = null;
                }
    	    }            
            userRecord.LanguageLocaleKey    = 'pt_BR';
            userRecord.LocaleSidKey         = 'pt_BR';
            userRecord.TimeZoneSidKey       = 'America/Sao_Paulo';
            userRecord.LocaleSidKey         = 'pt_BR';
            userRecord.EmailEncodingKey     = 'UTF-8';           
           
            if (userRecord.Id == null) {
                insert userRecord;
            } else{
                updateUserFuture(JSON.serialize(userRecord));
            }
            
            if(updateGroup == true) {
                updatePublicGroupFuture(JSON.serialize(userRecord), JSON.serialize(data.attributeMap.get('role')));
            }
            
            updatePermissionSetFuture(JSON.serialize(userRecord), JSON.serialize(ltPermissionSetSF));
            return userRecord;
        } catch (Exception e) {            
            throw new RegHandlerException('Erro em criar/atualizar usuário: ' + e.getMessage());
        } 
    }

    // Função para trabalhar com a conta
    public Account actionAccount (String CNPJResponse, Auth.UserData data ) {
        try{
            Account accountToUpdateInsert = AccountDAO.getAccountByCNPJ(CNPJResponse);
            if (accountToUpdateInsert == null) {
                accountToUpdateInsert = new Account();
                accountToUpdateInsert.Name = CNPJResponse; 
                accountToUpdateInsert.DocumentNumber__c = CNPJResponse;
                accountToUpdateInsert.RecordTypeId = CONST_PARTNER_ACCOUNT_RECORD_TYPE_ID;
                Insert accountToUpdateInsert;
            } 

            accountToUpdateInsert.vlocity_cmt__Active__c = 'Yes';
            accountToUpdateInsert.IsPartner = true;
            update accountToUpdateInsert;
            return accountToUpdateInsert;
        }
        catch (Exception e) {throw new RegHandlerException('Erro em criar/atualizar conta: ' + e.getMessage());}
    }

    // Função para trabalhar com o contato
    public Contact actionContact (Contact con, Account acc, Auth.UserData data, String userNameResponse) {
        try{
            Contact contactToUpsert = con.Id != null ? con : new Contact ();
            contactToUpsert.FirstName = data.FirstName;
            contactToUpsert.LastName = data.LastName;  
            contactToUpsert.UserIdentifier__c = userNameResponse;
            contactToUpsert.AccountId = acc.Id;
            contactToUpsert.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('PartnerContact').getrecordTypeId();
            if (contactToUpsert.Email == '') {
                contactToUpsert.Email = data.email;
            }

            if (data.attributeMap.containsKey('phone_number')) {
                contactToUpsert.Phone = data.attributeMap.get('phone_number');
            }
            upsert contactToUpsert;
            return contactToUpsert;
        }
        catch (Exception e) {throw new RegHandlerException('Erro em criar/atualizar contato: ' + e.getMessage());}
    }

    @future
    public static void updatePermissionSetFuture(String userString, String permissionSetString) {

        User userRecord = (User) JSON.deserialize(userString, User.class);
        List<PermissionSet> ltPermissionSet = (List<PermissionSet>) JSON.deserialize(permissionSetString, List<PermissionSet>.class);
        Set<Id> setPermissonSetId = new Set<Id>();

        for(PermissionSet item : ltPermissionSet) {
            setPermissonSetId.add(item.Id);
        }

        List<PermissionSetAssignment> ltCurrentPSA = new List<PermissionSetAssignment>([SELECT Id, PermissionSetId FROM PermissionSetAssignment 
                                                                                            WHERE AssigneeId = : userRecord.Id AND PermissionSet.ProfileId = null]);
        Set<Id> setCurrentPSA = new Set<Id>();
        List<PermissionSetAssignment> ltInsertPSA = new List<PermissionSetAssignment>();
        List<PermissionSetAssignment> ltDeletePSA = new List<PermissionSetAssignment>();

        for(PermissionSetAssignment item : ltCurrentPSA) {
            if(setPermissonSetId.contains(item.PermissionSetId)) {
                setCurrentPSA.add(item.PermissionSetId);
            } else {
                ltDeletePSA.add(item);
            }
        }

        for(PermissionSet item : ltPermissionSet) {
            if(!setCurrentPSA.contains(item.Id)) {
                ltInsertPSA.add(new PermissionSetAssignment(AssigneeId = userRecord.Id, PermissionSetId = item.Id));
            }
        }

        if(ltDeletePSA.size() > 0) {
            delete ltDeletePSA;
        }

        if(ltInsertPSA.size() > 0) {
            insert ltInsertPSA;
        }

    }

    // Função para atualizar usuário
    @future
    public static void updateUserFuture(String dados) {
        User u = (User)JSON.deserialize(dados,User.class);
        update u;
    }

    @TestVisible
    private String getSandboxName() {
        if(Url.getSalesforceBaseUrl().toExternalForm().contains('comunidade')) {
            // Community User
            return Url.getSalesforceBaseUrl().toExternalForm().contains('-vivo') ?
                            '.' + Url.getSalesforceBaseUrl().toExternalForm().substringAfterLast('//').substringBefore('-') :
                            '';
        } else {
            // Internal User
            return Url.getSalesforceBaseUrl().toExternalForm().contains('--') ? 
                            '.' + Url.getSalesforceBaseUrl().toExternalForm().substringAfterLast('--').substringBefore('.') : 
                            '';
        }
    }

    private User getUserData(String userName){
        List<User> ltUser = new List<User>([SELECT Id, PartnerGroup__c FROM User WHERE username =: userName LIMIT 1]);
        return (ltUser.size() > 0 ? new User(Id=ltUser[0].Id) : new User());
    }

    @future
    public static void updatePublicGroupFuture(String userString, String roleResponse) {
        User userRecord = (User) JSON.deserialize(userString, User.class);
        String role = roleResponse.replaceAll('"','');
        List<PublicGroup__mdt> lstPublicGroup = [SELECT PartnerGroup__c, PublicGroup__c, DeveloperName FROM PublicGroup__mdt WHERE PartnerGroup__c =: role];

        Set<String> setGroupName = new Set<String>();
        Map<Id, GroupMember> mapGroupMember = new Map<Id, GroupMember>();

        for(PublicGroup__mdt publicGroup : lstPublicGroup) {
            setGroupName.add(publicGroup.PublicGroup__c);
        }

        //Busca os grupos relacionados ao metadado
        List<Group> lstGroup = [SELECT Id, DeveloperName FROM Group WHERE DeveloperName IN: setGroupName];        
        List<GroupMember> lstGroupMember = [SELECT Id, GroupId FROM GroupMember WHERE UserOrGroupID =: userRecord.Id];
    
        Set<Id> setCurrentGroupId = new Set<Id>();
        Set<Id> setGroupId = new Set<Id>();
        List<GroupMember> lstInsertGroup = new List<GroupMember>();
        List<GroupMember> lstDeleteGroup = new List<GroupMember>();
        
        for(Group grp : lstGroup) {
            setGroupId.add(grp.Id);
        }
        
        for(GroupMember groupMember : lstGroupMember) {
            if(setGroupId.contains(groupMember.GroupId)) {
                setCurrentGroupId.add(groupMember.GroupId);
            } else {
                lstDeleteGroup.add(groupMember);
            }
        }
        
        for(Group grp : lstGroup) {
            if(!setCurrentGroupId.contains(grp.Id) && userRecord.id != null) {
                GroupMember groupMember = new GroupMember();
                groupMember.GroupId = grp.id;
                groupMember.UserOrGroupId = userRecord.id;
                lstInsertGroup.add(groupMember);
            }
        }

        if(lstDeleteGroup.size() > 0) {
            delete lstDeleteGroup;
        }

        if(lstInsertGroup.size() > 0) {
            insert lstInsertGroup;
        }
    }

    //Função validadora Nivel 1
    private void fristValidateResponse(Auth.UserData data, Boolean userInternal) {
        String errorMsg = '';
        
        // LastName para contato quando parceiro
        if((String.isEmpty(data.LastName)) && (userInternal == false)) {
            errorMsg = 'Campo obrigatório de lastName não informado no response.';
        }
        // Profile
        if(data.attributeMap.get('profile_name') == null) {
            errorMsg += 'Campo obrigatório de perfil não informado no response.';
        }
        // Role
        if(data.attributeMap.get('role') == null) {
            errorMsg += 'Campo obrigatório de papel não informado no response.';
        }
        // Sub
        if(String.isEmpty(data.username)) {
            errorMsg += 'Campo obrigatório de Sub (Username) não informado no response.';
        }
        if((userInternal) && (String.isEmpty(data.email))) {
            errorMsg += 'Campo obrigatório de email para usuário interno não informado no response.';
        }

        if(String.isNotEmpty(errorMsg)) {
            throw new RegHandlerException(errorMsg + 'Acesso incorreto, por favor, entrar em contato com o CSL para regularização');
        }
    }

    //Função validadora Nivel 2
    private void secondValidateResponse(Auth.UserData data, 
                                                Boolean userInternal, 
                                                Profile userProfile, 
                                                String userLicenseProfile,
                                                String userRole, 
                                                Contact contactRecord,
                                                List<PermissionSet> ltPermissionSetSF, 
                                                List<String> ltPermissionSetResponse) 
    {
        String errorMsg = '';
        
        // Validação de Perfil 
        if(userProfile.Id == null) {
            errorMsg = 'Perfil de acesso relacionado não encontrado.';
        }
        // Validação de Papel
        if(userRole == 'null') {
            errorMsg += 'Papel informado não encontrado no SalesForce.';
        }
        // Validação usuário interno e sem licensa de perfil 'Partner Community'
        if(userInternal && userLicenseProfile == 'Partner Community') {
            errorMsg += 'Usuário interno, perfil não informado ou atribuído como Partner Community.';
        }
        // Validação usuário parceiro e com licensa de perfil 'Partner Community'
        if(!userInternal) {
            // if(contactRecord.Id == null) {
            //     errorMsg += 'Contato não encontrado.';
            // }
            if(userLicenseProfile != 'Partner Community') {
                errorMsg += 'Usuário Parceiro, perfil não informado ou atribuído diferente de Partner Community.';
            }
        }
        // Validação permissionSet base x response
        if(ltPermissionSetResponse.size() > 0 && ltPermissionSetSF.size() != ltPermissionSetResponse.size()) {
            errorMsg += 'PermissionSet informada(s) no response não corresponde com as do SalesForce.';
        }

        if(String.isNotEmpty(errorMsg)) {
            throw new RegHandlerException(errorMsg + 'Acesso incorreto, por favor, entrar em contato com o CSL para regularização');
        }
    }

    private SalesOffices__mdt getOffice(String office) {
        SalesOffices__mdt center = null;
        List<String> vetOffice = office.split('-');
        
        if (vetOffice.size() > 0) {
            office = vetOffice[0];

            List<SalesOffices__mdt> lstCenter = [SELECT Id, Office__c, Center__c, Store__c FROM SalesOffices__mdt WHERE Office__c = :office AND Active__c = true];
        
            if (lstCenter.size() > 0) {
                center = lstCenter[0];
            }            
        }

        return center;
    }
    
    private String getAdabasAssignedDocumentByAdabasCode(string varChannelName, String varSite, String varAdabas)
    {
        system.debug('OAMRegistrationHandler.getAdabasAssignedDocumentByAdabasCode varChannelName: ' + varChannelName);
        system.debug('OAMRegistrationHandler.getAdabasAssignedDocumentByAdabasCode varSite: ' + varSite);
        system.debug('OAMRegistrationHandler.getAdabasAssignedDocumentByAdabasCode varAdabas: ' + varAdabas);
        
        string queryAdabasSite;
         AdabasSite__c sobjectAdabasSite;
        
        //J110 incluir campo Status__c n consulta adabas caso necessário por conta da Carga DO Power Center      
        if(String.isNotEmpty(varChannelName) && String.isNotEmpty(varSite) && String.isNotEmpty(varAdabas))
        {
            switch on varChannelName 
            {
                when 'Call Center', 'Lojas Proprias' 
                {
                    queryAdabasSite = ' SELECT Name, AdabasCode__c, CNPJ__c FROM AdabasSite__c WHERE AdabasCode__c =: varSite';                
                }
                
                when 'Lojas Revendas'
                {                
                    queryAdabasSite = ' SELECT Name, AdabasCode__c, CNPJ__c FROM AdabasSite__c WHERE AdabasCode__c =: varAdabas';                 
                }            
            }
            
            queryAdabasSite = queryAdabasSite + ' LIMIT 1';
        }
        
        System.debug('OAMRegistrationHandler.getAdabasAssignedDocumentByAdabasCode queryAdabasSite: ' + queryAdabasSite); 
        
        if(queryAdabasSite != null)
        {             
            sobjectAdabasSite = Database.query(queryAdabasSite);            
        }
       
        system.debug('OAMRegistrationHandler.getAdabasAssignedDocumentByAdabasCode sobjectAdabasSite: ' + sobjectAdabasSite);
        
        return (sobjectAdabasSite?.CNPJ__c != null) ? sobjectAdabasSite?.CNPJ__c : '';
    }
}