force-app/main/default/objects/FlowExecutionActionHistory__c/FlowExecutionActionHistory__c.object-meta.xml
<CustomObject>
    <label>Histórico de Execução de ações</label>
    <nameField>
        <label>Step</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Execução de ações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlowExecutionActionHistory__c/fields/AdditionalInformation__c.field-meta.xml
<CustomField>
    <fullName>AdditionalInformation__c</fullName>
    <label>Informações Adicionais</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlowExecutionActionHistory__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Resposta</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlowExecutionActionHistory__c/fields/FlowExecutionStepHistory__c.field-meta.xml
<CustomField>
    <fullName>FlowExecutionStepHistory__c</fullName>
    <label>Histórico de Execução de Fluxo</label>
    <referenceTo>FlowExecutionStepHistory__c</referenceTo>
    <relationshipLabel>Históricos de Execução de ações</relationshipLabel>
    <relationshipName>FlowExecutionStepHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlowExecutionActionHistory__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlowExecutionActionHistory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <default>true</default>
                <label>M</label>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlowExecutionStepHistory__c/FlowExecutionStepHistory__c.object-meta.xml
<CustomObject>
    <label>Histórico de Execução de Fluxo</label>
    <nameField>
        <label>Step</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Execução de Fluxos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlowExecutionStepHistory__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Históricos de Execução de Fluxos</relationshipLabel>
    <relationshipName>Hist_ricos_de_Execu_o_de_Fluxos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usado para associar um pedido a um caso (bilhete)</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlowExecutionStepHistoryController.cls
public class FlowExecutionStepHistoryController {
    @AuraEnabled(cacheable=false)
    public static List<FlowExecutionStepHistory__c> getByCaseId(Id caseId) {
        return [
            select
            Id,
            Name,
            CreatedBy.Name,
            (select
                Id,
                Name__c,
                Answer__c,
                AdditionalInformation__c,
                Type__c
                from FlowExecutionStepHistories__r
                order by CreatedDate)
            from FlowExecutionStepHistory__c where CaseId__c =: caseId
            WITH SECURITY_ENFORCED
            order by CreatedDate
        ];
    }
}