force-app/main/default/objects/CaseDetail__c/CaseDetail__c.object-meta.xml
<CustomObject>
    <description>Objeto auxiliar ao objeto Caso (Case), que armazena os campos das jornadas de minhas solicitações recebidos através do fluxo do App Vivo. Projeto Minhas Solicitações PTI4728</description>
    <label>Detalhe do Caso</label>
    <nameField>
        <displayFormat>DC - {00000000}</displayFormat>
        <label>Número do Detalhe do Caso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalhes dos Casos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseDetail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Detalhes dos Casos</relationshipLabel>
    <relationshipName>CaseDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HDECaseDetailService.cls
public without sharing class HDECaseDetailService {
    public static void createCaseDetail(List<Case> ltCases) {
        List<CaseDetail__c> ltCaseDetails = new List<CaseDetail__c>();
        
        for (Case caseSource : ltCases) {
            if (caseSource.Origin == 'HDE') {
                ltCaseDetails.add(new CaseDetail__c(
                    Case__c = caseSource.Id
                ));
            }
        }

        if (ltCaseDetails.size() > 0) {
            insert ltCaseDetails;
        }
    }
}