force-app/main/default/objects/CustomerInteractionTopicTree__c/CustomerInteractionTopicTree__c.object-meta.xml
<CustomObject>
    <label>Árvore de Palitagem</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Árvore de Palitagem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/GPSFlow__c.field-meta.xml
<CustomField>
    <fullName>GPSFlow__c</fullName>
    <label>Fluxo GPS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/GPSId__c.field-meta.xml
<CustomField>
    <fullName>GPSId__c</fullName>
    <label>Id GPS</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <label>Instância</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LINHA TELEFÔNICA</fullName>
            </value>
            <value>
                <fullName>BANDA LARGA</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>CONTROLE</fullName>
            </value>
            <value>
                <fullName>PÓS-PAGO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <label>Segmento Operador</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>LOJA</fullName>
            </value>
            <value>
                <fullName>OMNICHANNEL</fullName>
            </value>
            <value>
                <fullName>OUVIDORIA</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
                <label>PÚRPURA</label>
            </value>
            <value>
                <fullName>REVENDA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>SUPORTE A LOJAS</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
            <value>
                <fullName>VIVO V</fullName>
            </value>
            <value>
                <fullName>LOJAS</fullName>
                <isActive>false</isActive>
                <label>LOJAS</label>
            </value>
            <value>
                <fullName>Purpura-OLD</fullName>
                <isActive>false</isActive>
                <label>Purpura-OLD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
                <label>Pós/Controle</label>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <label>Fixa</label>
            </value>
            <value>
                <fullName>Pre</fullName>
                <label>Pré</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Campo criado para desenvolvimento de POC</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pasta</fullName>
            </value>
            <value>
                <fullName>Palito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/VisibleTo__c.field-meta.xml
<CustomField>
    <fullName>VisibleTo__c</fullName>
    <label>Visível Para</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COMUNIDADE - PROTOCOLO DETALHE</fullName>
            </value>
            <value>
                <fullName>COMUNIDADE - RETENÇÃO</fullName>
            </value>
            <value>
                <fullName>COMUNIDADE - VENDAS</fullName>
            </value>
            <value>
                <fullName>ORG VIVO - B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerInteractionTopicTreeDAO.cls
public class CustomerInteractionTopicTreeDAO {
    public static List<CustomerInteractionTopicTree__c> getEndFlowCustomerInteractionTopicTreeById(Id serviceId) {    
        return [
            SELECT
                Id,
                Name,
                GpsId__c,
                Instance__c,
                GPSFlow__c,
				ProductType__c
            FROM
                CustomerInteractionTopicTree__c
            WHERE
            	Type__c = 'Palito'				
            AND
               	Id =: serviceId
        ];
    }
    
    public static CustomerInteractionTopicTree__c getCustomerInteractionTopicTreeToFillProdutoOutrosFixa() {    
        return [
            SELECT 
                Id 
            FROM 
                CustomerInteractionTopicTree__c 
            WHERE 
                Name = 'NDA'
            LIMIT 1
        ];
    }
    
    public static List<CustomerInteractionTopicTree__c> getServiceFlowBySegment(Set<String> setOperatorSegment, String pageReference) {    

        List<String> segments = new List<String>(setOperatorSegment);
        String query = '';
        query += 'SELECT Id, Name, GpsId__c, ProductType__c, OperatorSegment__c, Instance__c FROM CustomerInteractionTopicTree__c';        
        query += ' WHERE Active__c = true AND GpsId__c != null AND VisibleTo__c INCLUDES (\'' + pageReference + '\') ';
        
        if(!segments.isEmpty() && segments != null){
            query += ' AND OperatorSegment__c ';
            if(segments.size() > 1){
                query += 'INCLUDES (\'' + String.join(segments, '\',\'') + '\')';
            } else {
                query += 'INCLUDES (\'' + segments[0] + '\') ';
            }
		}else {
            return new List<CustomerInteractionTopicTree__c>();
        }

        query +=' ORDER BY Name';

        return Database.Query(query);

    }
}