force-app/main/default/objects/CustomerInteractionTopicTree__c/CustomerInteractionTopicTree__c.object-meta.xml
<CustomObject>
    <label>Árvore de Palitagem</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Árvore de Palitagem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/GPSFlow__c.field-meta.xml
<CustomField>
    <fullName>GPSFlow__c</fullName>
    <label>Fluxo GPS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/GPSId__c.field-meta.xml
<CustomField>
    <fullName>GPSId__c</fullName>
    <label>Id GPS</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/OmniTree__c.field-meta.xml
<CustomField>
    <fullName>OmniTree__c</fullName>
    <description>O campo será o nome do palito, e deverá aparecer para o APP.</description>
    <label>OmniTree</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/OperatorSegment__c.field-meta.xml
<CustomField>
    <fullName>OperatorSegment__c</fullName>
    <label>Segmento Operador</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>LOJA</fullName>
            </value>
            <value>
                <fullName>OMNICHANNEL</fullName>
            </value>
            <value>
                <fullName>OUVIDORIA</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>PURPURA</fullName>
                <label>PÚRPURA</label>
            </value>
            <value>
                <fullName>REVENDA</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>SUPORTE A LOJAS</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
            <value>
                <fullName>VIVO V</fullName>
            </value>
            <value>
                <fullName>LOJAS</fullName>
                <isActive>false</isActive>
                <label>LOJAS</label>
            </value>
            <value>
                <fullName>Purpura-OLD</fullName>
                <isActive>false</isActive>
                <label>Purpura-OLD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
                <label>Pós/Controle</label>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <label>Fixa</label>
            </value>
            <value>
                <fullName>Pre</fullName>
                <label>Pré</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Campo criado para desenvolvimento de POC</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pasta</fullName>
            </value>
            <value>
                <fullName>Palito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TopicTreeManagementTest.cls
@isTest
public with sharing class TopicTreeManagementTest {
    private static final String BROKEN_JWT_TOKEN = 'MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGem2z/GaUjUe/6OGfilrcdrklxa0fyMqQIbSMBjC9rr7g+2db+mC1C/pSwNEOHjnM8OcObtSeTz9khtd/jB8aFggYbnmFAJgBEvOmiPLFpaDObBKVMytSK/M8j63gmu2fGIWZAupnyCG1BKe2YOpOwG4nOwlRSqUhISUosYFotfAgMBAAE='; 
    
    @testSetup 
    static void setup(){
        insert new CustomerInteractionTopicTree__c(
            Name = 'Test With Omnitree',
            Active__c = true,
            GPSId__c = '',
            OperatorSegment__c = 'Gold',
            OmniTree__c = 'Mudança do Endereço de Instalação > Fixa > Casa',
			Type__c = 'Palito'            
        );

        insert new CustomerInteractionTopicTree__c(
            Name = 'Test With Gps Flow',
            Active__c = true,
            GPSId__c = '',
            OperatorSegment__c = 'Gold',
            GPSFlow__c = 'Mudança do Endereço de Instalação > Fixa > Casa',
			Type__c = 'Palito'            
        );
    }
    
    @isTest
    public static void getWithOmniTree(){
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();   
        request.requestUri ='/TopicTreeManagement/v1';
        request.httpMethod = 'GET';
        String authHeader = 'Bearer ' + jwt;
        request.headers.put('x-Authorization', authHeader);
        request.addParameter('omnitree','true');
        RestContext.request = request;
        RestContext.response= res;
        TopicTreeManagement.getTopicTree();
        test.stopTest();
        getTopicTreeResponseWrapper.responseSucess responseReturn = (getTopicTreeResponseWrapper.responseSucess) Json.deserialize(res.responseBody.toString(),getTopicTreeResponseWrapper.responseSucess.class);
        System.assertEquals('Test With Omnitree', responseReturn.topicTree[0].Name);
    }

    @isTest
    public static void getWithGpsFlow(){
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();   
        request.requestUri ='/TopicTreeManagement/v1';
        request.httpMethod = 'GET';
        String authHeader = 'Bearer ' + jwt;
        request.headers.put('x-Authorization', authHeader);
        request.addParameter('gpsFlow','true');
        RestContext.request = request;
        RestContext.response= res;
        TopicTreeManagement.getTopicTree();
        test.stopTest();
        getTopicTreeResponseWrapper.responseSucess responseReturn = (getTopicTreeResponseWrapper.responseSucess) Json.deserialize(res.responseBody.toString(),getTopicTreeResponseWrapper.responseSucess.class);
        System.assertEquals('Test With Gps Flow', responseReturn.topicTree[0].Name);
    }

    @isTest
    public static void getWithOmnitreeAndGpsFlow(){
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        insert new CustomerInteractionTopicTree__c(
            Name = 'Test With Gps Flow and OmniTree',
            Active__c = true,
            GPSId__c = '',
            OperatorSegment__c = 'Gold',
            GPSFlow__c = 'Teste GpsFlow',
            OmniTree__c = 'Mudança de Endereço > Fixa > Casa',
			Type__c = 'Palito'            
        );
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();   
        request.requestUri ='/TopicTreeManagement/v1';
        request.httpMethod = 'GET';
        String authHeader = 'Bearer ' + jwt;
        request.headers.put('x-Authorization', authHeader);
        request.addParameter('gpsFlow','true');
        request.addParameter('omnitree','true');
        RestContext.request = request;
        RestContext.response= res;
        TopicTreeManagement.getTopicTree();
        test.stopTest();
        getTopicTreeResponseWrapper.responseSucess responseReturn = (getTopicTreeResponseWrapper.responseSucess) Json.deserialize(res.responseBody.toString(),getTopicTreeResponseWrapper.responseSucess.class);
        System.assertEquals('Test With Gps Flow and OmniTree', responseReturn.topicTree[0].Name);
    }

    @isTest
    public static void getWithProductType(){
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        insert new CustomerInteractionTopicTree__c(
            Name = 'getWithProductType',
            Active__c = true,
            GPSId__c = '',
            OperatorSegment__c = 'Gold',
            GPSFlow__c = 'Teste GpsFlow',
            OmniTree__c = 'Mudança de Endereço > Fixa > Casa',
            ProductType__C = 'Fixed',
			Type__c = 'Palito'            
        );
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();   
        request.requestUri ='/TopicTreeManagement/v1';
        request.httpMethod = 'GET';
        String authHeader = 'Bearer ' + jwt;
        request.headers.put('x-Authorization', authHeader);
        request.addParameter('productType','fixed, mobile');
        RestContext.request = request;
        RestContext.response= res;
        TopicTreeManagement.getTopicTree();
        test.stopTest();
        getTopicTreeResponseWrapper.responseSucess responseReturn = (getTopicTreeResponseWrapper.responseSucess) Json.deserialize(res.responseBody.toString(),getTopicTreeResponseWrapper.responseSucess.class);
        System.assertEquals('getWithProductType', responseReturn.topicTree[0].Name);
    }

    @isTest
    public static void getBlank(){
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();   
        request.requestUri ='/TopicTreeManagement/v1';
        request.httpMethod = 'GET';
        String authHeader = 'Bearer ' + jwt;
        request.headers.put('x-Authorization', authHeader);
        request.addParameter('gpsFlow','true');
        request.addParameter('omnitree','true');
        RestContext.request = request;
        RestContext.response= res;
        TopicTreeManagement.getTopicTree();
        test.stopTest();
        List<getTopicTreeResponseWrapper.responseError> responseReturn = (List<getTopicTreeResponseWrapper.responseError>) Json.deserialize(res.responseBody.toString(),List<getTopicTreeResponseWrapper.responseError>.class);
        System.assertEquals('NOT_FOUND', responseReturn[0].errorCode);
    }

    @isTest
    public static void errorException(){
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createValidJWT();
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();   
        request.requestUri ='/TopicTreeManagement/v1';
        request.httpMethod = 'GET';
        String authHeader = 'Bearer ' + BROKEN_JWT_TOKEN;
        request.headers.put('x-Authorization', authHeader);
        request.addParameter('gpsFlow','true');
        request.addParameter('omnitree','true');
        RestContext.request = request;
        RestContext.response= res;
        TopicTreeManagement.getTopicTree();
        test.stopTest();
        List<getTopicTreeResponseWrapper.responseError> responseReturn = (List<getTopicTreeResponseWrapper.responseError>) Json.deserialize(res.responseBody.toString(),List<getTopicTreeResponseWrapper.responseError>.class);
        System.assertEquals('Exception', responseReturn[0].errorCode);
    }

    @isTest
    public static void errorJWT(){
        JWTUtilityTest.setPublicTestKey();
        String jwt = JWTUtilityTest.createInvalidJWT();
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();   
        request.requestUri ='/TopicTreeManagement/v1';
        request.httpMethod = 'GET';
        String authHeader = 'Bearer ' + jwt;
        request.headers.put('x-Authorization', authHeader);
        request.addParameter('gpsFlow','true');
        request.addParameter('omnitree','true');
        RestContext.request = request;
        RestContext.response= res;
        TopicTreeManagement.getTopicTree();
        test.stopTest();
        List<getTopicTreeResponseWrapper.responseError> responseReturn = (List<getTopicTreeResponseWrapper.responseError>) Json.deserialize(res.responseBody.toString(),List<getTopicTreeResponseWrapper.responseError>.class);
        System.assertEquals('Forbidden', responseReturn[0].errorCode);
    }

    @isTest
    public static void withoutJWT(){
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();   
        request.requestUri ='/TopicTreeManagement/v1';
        request.httpMethod = 'GET';
        request.addParameter('gpsFlow','true');
        request.addParameter('omnitree','true');
        RestContext.request = request;
        RestContext.response= res;
        TopicTreeManagement.getTopicTree();
        test.stopTest();
        List<getTopicTreeResponseWrapper.responseError> responseReturn = (List<getTopicTreeResponseWrapper.responseError>) Json.deserialize(res.responseBody.toString(),List<getTopicTreeResponseWrapper.responseError>.class);
        System.assertEquals('Forbidden', responseReturn[0].errorCode);
    }
    
}