force-app/main/default/objects/CustomerInteractionTopicTree__c/CustomerInteractionTopicTree__c.object-meta.xml
<CustomObject>
    <label>Árvore de Palitagem</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Árvore de Palitagem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/CaseHandling__c.field-meta.xml
<CustomField>
    <fullName>CaseHandling__c</fullName>
    <description>Campo destinado aos grupos de atendimento que podem realizar a tratativa do caso.</description>
    <label>Tratativa de Caso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo de Atendimento - Fraude</fullName>
            </value>
            <value>
                <fullName>Grupo de Atendimento - GT Unificado</fullName>
            </value>
            <value>
                <fullName>Grupo de Atendimento - Solução Online</fullName>
            </value>
            <value>
                <fullName>Grupo de Atendimento - Resgate Gravação</fullName>
            </value>
            <value>
                <fullName>Grupo de Atendimento - Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Grupo de Atend. Ajuste Saldo - Atend</fullName>
            </value>
            <value>
                <fullName>Grupo de Atend. Ajuste Saldo - Lojas</fullName>
            </value>
            <value>
                <fullName>Grupo de Atend. Contestação - Atend</fullName>
            </value>
            <value>
                <fullName>Grupo de Atend. Contestação - Lojas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/CaseOpening__c.field-meta.xml
<CustomField>
    <fullName>CaseOpening__c</fullName>
    <description>Campo destinado aos grupos de atendimento que podem realizar a abertura do caso.</description>
    <label>Abertura de Caso</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GRUPO DE ABERTURA - FRAUDE</fullName>
            </value>
            <value>
                <fullName>GRUPO DE ABERTURA - GT UNIFICADO</fullName>
            </value>
            <value>
                <fullName>GRUPO DE ABERTURA - SOLUÇÃO ONLINE</fullName>
            </value>
            <value>
                <fullName>GRUPO DE ABERTURA - RESGATE DE GRAVAÇÃO</fullName>
            </value>
            <value>
                <fullName>GRUPO DE ABERTURA - OUVIDORIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/CaseReturn__c.field-meta.xml
<CustomField>
    <fullName>CaseReturn__c</fullName>
    <description>Campo destinado aos grupos de retorno que podem realizar o retorno ao cliente e encerramento do caso.</description>
    <label>Retorno do Caso</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo de Retorno - GT Unificado/Atend</fullName>
            </value>
            <value>
                <fullName>Grupo de Retorno - Resgate de Gravação</fullName>
            </value>
            <value>
                <fullName>Grupo de Retorno - Solução Online/Atend</fullName>
            </value>
            <value>
                <fullName>Grupo de Retorno - Ouvidoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Channels__c.field-meta.xml
<CustomField>
    <fullName>Channels__c</fullName>
    <label>Canais</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LOJAS PRÓPRIAS</fullName>
            </value>
            <value>
                <fullName>LOJAS REVENDAS</fullName>
            </value>
            <value>
                <fullName>CALL CENTER</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
            <value>
                <fullName>MEU VIVO</fullName>
            </value>
            <value>
                <fullName>E-COMMERCE</fullName>
            </value>
            <value>
                <fullName>CALLCENTER</fullName>
                <isActive>false</isActive>
                <label>CALLCENTER</label>
            </value>
            <value>
                <fullName>LOJA PROPRIA</fullName>
                <isActive>false</isActive>
                <label>LOJA PROPRIA</label>
            </value>
            <value>
                <fullName>REVENDA</fullName>
                <isActive>false</isActive>
                <label>REVENDA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classificação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atendimento</fullName>
            </value>
            <value>
                <fullName>Elogio</fullName>
            </value>
            <value>
                <fullName>Incidência</fullName>
            </value>
            <value>
                <fullName>Informação</fullName>
            </value>
            <value>
                <fullName>Serviço</fullName>
            </value>
            <value>
                <fullName>Sugestão</fullName>
            </value>
            <value>
                <fullName>Reclamação</fullName>
                <isActive>false</isActive>
                <label>Reclamação</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/CustomerTypes__c.field-meta.xml
<CustomField>
    <fullName>CustomerTypes__c</fullName>
    <label>Tipos de Clientes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PROSPECT</fullName>
            </value>
            <value>
                <fullName>CLIENTE</fullName>
            </value>
            <value>
                <fullName>NÃO CLASSIFICADO</fullName>
                <isActive>false</isActive>
                <label>NÃO CLASSIFICADO</label>
            </value>
            <value>
                <fullName>PESSOA FÍSICA</fullName>
                <isActive>false</isActive>
                <label>PESSOA FÍSICA</label>
            </value>
            <value>
                <fullName>PESSOA JURÍDICA</fullName>
                <isActive>false</isActive>
                <label>PESSOA JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/FormType__c.field-meta.xml
<CustomField>
    <fullName>FormType__c</fullName>
    <description>Indica qual o Tipo de formulário a ser usado pelo palito</description>
    <label>Formulário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processo e Retorno ao Cliente</fullName>
                <default>true</default>
                <label>Processo e Retorno ao Cliente</label>
            </value>
            <value>
                <fullName>Portabilidade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/IdVivoNet__c.field-meta.xml
<CustomField>
    <fullName>IdVivoNet__c</fullName>
    <description>Field to input ID of topic on VivoNet</description>
    <label>Identificação VivoNet</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/LinesTypes__c.field-meta.xml
<CustomField>
    <fullName>LinesTypes__c</fullName>
    <label>Tipos de Linhas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NÃO CLASSIFICADO</fullName>
            </value>
            <value>
                <fullName>PÓS-PAGO GSM</fullName>
            </value>
            <value>
                <fullName>PRÉ-PAGO GSM</fullName>
            </value>
            <value>
                <fullName>CONTROLE GSM</fullName>
            </value>
            <value>
                <fullName>POS-PAGO GSM</fullName>
                <isActive>false</isActive>
                <label>POS-PAGO GSM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ParentTopicId__c.field-meta.xml
<CustomField>
    <fullName>ParentTopicId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Topic Id</description>
    <label>Palito Pai</label>
    <referenceTo>CustomerInteractionTopicTree__c</referenceTo>
    <relationshipLabel>Palitos Filhos</relationshipLabel>
    <relationshipName>ParentTopic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
                <label>Pós/Controle</label>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <label>Fixa</label>
            </value>
            <value>
                <fullName>Pre</fullName>
                <label>Pré</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/RelationshipType__c.field-meta.xml
<CustomField>
    <fullName>RelationshipType__c</fullName>
    <label>Tipo de Relacionamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automático/Manual</fullName>
                <default>true</default>
                <label>Automático/Manual</label>
            </value>
            <value>
                <fullName>Caso/Processo</fullName>
            </value>
            <value>
                <fullName>GPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Segmentations__c.field-meta.xml
<CustomField>
    <fullName>Segmentations__c</fullName>
    <label>Segmentações</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>PÚRPURA</fullName>
            </value>
            <value>
                <fullName>NÃO CLASSIFICADO</fullName>
            </value>
            <value>
                <fullName>SEM SEGMENTO</fullName>
            </value>
            <value>
                <fullName>V</fullName>
                <isActive>false</isActive>
                <label>V</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/SendSMS__c.field-meta.xml
<CustomField>
    <fullName>SendSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Envio SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/ServiceTree__c.field-meta.xml
<CustomField>
    <fullName>ServiceTree__c</fullName>
    <label>Árvore de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
                <label>Atendimento</label>
            </value>
            <value>
                <fullName>DigitalChannels</fullName>
                <label>Canais Digitais</label>
            </value>
            <value>
                <fullName>Retention</fullName>
                <label>Retenção</label>
            </value>
            <value>
                <fullName>Hybrid</fullName>
                <label>Híbrido</label>
            </value>
            <value>
                <fullName>Ombudsman</fullName>
                <label>Ouvidoria</label>
            </value>
            <value>
                <fullName>Store</fullName>
                <label>Loja</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <description>Campo SLA do palito</description>
    <label>SLA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseHandling__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 dia útil</fullName>
            </value>
            <value>
                <fullName>2 dias úteis</fullName>
            </value>
            <value>
                <fullName>5 dias úteis</fullName>
            </value>
            <value>
                <fullName>10 dias corridos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerInteractionTopicTree__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Campo criado para desenvolvimento de POC</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pasta</fullName>
            </value>
            <value>
                <fullName>Palito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TopicTree.cls
/* -------------------------------------------------------------------------
* Autor....: Guilherme Kaiser - Deloitte
* Data.....: 21/08/2023
* Objetivo.: Atualização de pastas e palitos Valentina
* US 535 - Palitagem Manual
*  -------------------------------------------------------------------------
* Data: 29/11/2023
* Modificação: Inclusão de campos bloco 9
*  -------------------------------------------------------------------------
* Data: 25/04/2024
* Modificação: Alterado para executar StaticResources
*  PALITOSLOJASRELEASEJULHO2024, 
*  -------------------------------------------------------------------------
* How to execute:

        TopicTree topic = new TopicTree('LOJA',30,0);
        topic.ExecuteTopicTree();

        TopicTree topic = new TopicTree('CALLCENTER',30,0);
        topic.ExecuteTopicTree();

        TopicTree topic = new TopicTree('PALITOSLOJASBLOCO9',30,0);
        topic.ExecuteTopicTree();

        TopicTree topic = new TopicTree('PALITOSCALLCENTERBLOCO9',30,0);
        topic.ExecuteTopicTree();

        TopicTree topic = new TopicTree('PALITOSLOJASRELEASEJULHO2024',30,0);
        topic.ExecuteTopicTree();

        TopicTree topic = new TopicTree('PALITOSCALLCENTERRELEASEJULHO2024',30,0);
        topic.ExecuteTopicTree();

        TopicTree topic = new TopicTree('PALITOSLOJASRELEASESETEMBRO2024',30,0);
        topic.ExecuteTopicTree();

        TopicTree topic = new TopicTree('PALITOSCALLCENTERRELEASESETEMBRO2024',30,0);
        topic.ExecuteTopicTree();

*/
public class TopicTree {

    @TestVisible
    private static String staticResourceLojaseRevendas                    = 'PalitosLojaseRevendas';
    private static String staticResourceCallCenter                        = 'PalitosCallCenter';
    private static String staticResourcePalitosLojasBloco9                = 'PalitosLojasBloco9';
    private static String staticResourcePalitosCallCenterBloco9           = 'PalitosCallCenterBloco9';
    private static String staticResourcePalitosLojasReleaseJulho2024      = 'PalitosLojasReleaseJulho2024';
    private static String staticResourcePalitosCallCenterReleaseJulho2024 = 'PalitosCallCenterReleaseJulho2024';    
    private static String staticResourcePalitosCallCenterReleaseJulho2024V2 = 'PalitosCallCenterReleaseJulho2024V2';
    private static String staticResourcePalitosLojasReleaseSetembro2024      = 'PalitosLojasReleaseSetembro2024';
    private static String staticResourcePalitosCallCenterReleaseSetembro2024 = 'PalitosCallCenterReleaseSetembro2024';    
    //
    Map<String, CustomerInteractionTopicTree__c> mapTopicsDedup = new Map<String, CustomerInteractionTopicTree__c>();    
	// 
    public String file;
    public Integer qtyRecords=0;
    public Integer posRecord=0;
    public Integer countRecord=0;
    public String key;
    
    public String IdLevel0;
    public String IdLevel1;
    public String IdLevel2;
    public String IdLevel3;
    public String IdLevel4;
    public String IdLevel5;
    //
    public Boolean hasLevel0=false;
    public Boolean hasLevel1=false;
    public Boolean hasLevel2=false;
    public Boolean hasLevel3=false;
    public Boolean hasLevel4=false;
    public Boolean hasLevel5=false;
    
    private static StaticResource getResourceLojaseRevendas(){    
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourceLojaseRevendas LIMIT 1];
    }    
    private static StaticResource getResourceCallCenter(){
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourceCallCenter LIMIT 1];
    }    
    private static StaticResource getResourcestaticResourcePalitosLojasBloco9(){
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourcePalitosLojasBloco9 LIMIT 1];
    }    
    private static StaticResource getResourcestaticResourcePalitosCallCenterBloco9(){
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourcePalitosCallCenterBloco9 LIMIT 1];
    }        
    private static StaticResource getResourcestaticResourcePalitosLojasReleaseJulho2024(){
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourcePalitosLojasReleaseJulho2024 LIMIT 1];
    }            
    private static StaticResource getResourcestaticResourcePalitosCallCenterReleaseJulho2024(){
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourcePalitosCallCenterReleaseJulho2024 LIMIT 1];
    } 
    private static StaticResource getResourcestaticResourcePalitosCallCenterReleaseJulho2024V2(){
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourcePalitosCallCenterReleaseJulho2024V2 LIMIT 1];
    }                
    private static StaticResource getResourcestaticResourcePalitosLojasReleaseSetembro2024(){
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourcePalitosLojasReleaseSetembro2024 LIMIT 1];
    }            
    private static StaticResource getResourcestaticResourcePalitosCallCenterReleaseSetembro2024(){
        return [SELECT ID, body FROM StaticResource WHERE Name =: staticResourcePalitosCallCenterReleaseSetembro2024 LIMIT 1];
    }    
              

	public class Topic {
		public String SEQ;
		public String ProductType;
		public String ServiceTree;
		public String Level0;
		public String Level1;
		public String Level2;
		public String Level3;
		public String Level4;
		public String Level5;
		public String Type;
		public String IdVivoNet;
		public String Active;
		public String CustomerTypes;
		public String LinesTypes;
		public String Segmentations;
		public String Channels;
		public String SendSMS;
		public String Classification;
		public String RelationshipType;
		public String CaseOpening;
		public String CaseReturn;
        public String CaseHandling;
        public String FormType;
        public String SLA;
        public String CustomerFeedback;
        public String VisibleTo;
        public String CaseStatusGenTopic;        
	}
	
	public static List<Topic> parse(String json, Integer qty, Integer pos) {
		return (List<Topic>) System.JSON.deserialize(json, List<Topic>.class);
               
/*    	Integer Count = 0;
        
    	List<Topic> lstNewTopics;
    	List<Topic> lstTopics = (List<Topic>) System.JSON.deserialize(json, List<Topic>.class);
    	system.debug('size....'+ lstTopics.Size());
        if(pos >0){Count = pos;}
        
		for(Topic obj : lstTopics) {
            Count++;
			if((Count > pos) && (Count <= (qty + pos))) {
                System.debug('Count..:'+Count);
				lstNewTopics.add(obj);
			}
	        system.debug('Count.......:'+Count);
	        system.debug('qtyRecords..:'+qty);
    	    system.debug('posRecorde..:'+pos);
		}        
        return lstNewTopics;
*/
	}    
    
    public String getId(String source, String name, String type,String idVivoNet, String classification, String sendSMS ,String productType, String serviceTree, String active, String customerTypes, String linesTypes, String segmentations, String channels, String relationshipType, String caseOpening, String caseReturn, String caseHandling, String formType, String sla, String customerFeedback, String visibleTo, String caseStatusGenTopic){
		//
        String Id=null;
        CustomerInteractionTopicTree__c[] objAuxiliar;        
        
        this.key = 'ParentTopicId__c='+source+'|name='+name+'|type__c='+type;
		system.debug('KEY.:'+this.key);
        
        //map tem a chave do registro já inserido
        if (this.mapTopicsDedup.containsKey(this.key)){
            //se encontrou o registro no map então recupera o id do map e add para fazer um upsert
            //Guarda os valores duplicados
            CustomerInteractionTopicTree__c recordAux = this.mapTopicsDedup.get(key);
            //
            Id = recordAux.Id;
            System.debug('recuperou Id no map..: '+ Id);
            //
        }else{       
            //
            System.debug('não achou Id na mapTopicsDedup para chave..: '+ this.key);
            //
            if( Limits.getQueries() < 100){
                
                if(name=='Início' && type=='Pasta' && source==null){
                	objAuxiliar = [SELECT id, ParentTopicId__c, Name, type__c from CustomerInteractionTopicTree__c where ParentTopicId__c = :source and name = :name and type__c=:type and Active__c= true];
                }else{
                	objAuxiliar = [SELECT id, ParentTopicId__c, Name, type__c from CustomerInteractionTopicTree__c where ParentTopicId__c = :source and name = :name and type__c=:type and ProductType__c= 'Pre' and ServiceTree__c = :serviceTree and Active__c= true];
                }
                Id = (objAuxiliar.size() >0) ? objAuxiliar[0].Id : null;

                if(Id!=null){
        			this.mapTopicsDedup.put(this.key, objAuxiliar[0]);
                    System.debug('Teste key..: '+ this.key);
                    System.debug('ObjAuxiliar[0] .: '+ objAuxiliar[0]);
                }else{
                    if( Limits.getQueries() < 100){
                        if(type=='Pasta'){
                            Id = insertFolder(source, name, productType, serviceTree, active, relationshipType);
                        }else{
                            Id = insertTopic (source, name, idVivoNet, classification, sendSMS, productType, serviceTree, active, customerTypes, linesTypes, segmentations, channels, relationshipType, caseOpening, caseReturn, caseHandling, formType, sla, customerFeedback, visibleTo, caseStatusGenTopic);
                        }                        
                    }else{                
                        System.debug('***** Limite de inserção.  *****'+ Limits.getQueries());
                        System.debug('***** Limite atingido. Execute novamente para inserir os demais registros *****');
                    }
                }			
            }
        }
        System.debug('source:'+ Source + ' name: '+name + ' Id: '+ Id);        
        return Id;
    }

    public String insertFolder(String parentTopic, String folderName, String productType, String serviceTree, String active, String relationshipType){
        CustomerInteractionTopicTree__c record = new CustomerInteractionTopicTree__c(Name= folderName,Type__c='Pasta', RelationshipType__c= relationshipType, Active__c= Boolean.valueOf(active), ProductType__c= productType, ServiceTree__c = serviceTree, ParentTopicId__c= parentTopic);
		Database.insert(record, false);

        this.mapTopicsDedup.put(this.key, record);
        
        String Id = record.Id;
        return Id;
    }    
    public String insertTopic(String parentTopic, String folderName, String idVivoNet, String classification, String sendSMS ,String productType, String serviceTree, String active, String customerTypes, String linesTypes, String segmentations, String channels, String relationshipType, String caseOpening, String caseReturn, String caseHandling, String formType, String sla, String customerFeedback, String visibleTo, String caseStatusGenTopic){
        CustomerInteractionTopicTree__c record = new CustomerInteractionTopicTree__c(Name= folderName,Type__c='Palito', RelationshipType__c= relationshipType, Active__c= Boolean.valueOf(active), ProductType__c= productType , ServiceTree__c = serviceTree ,ParentTopicId__c= parentTopic, idVivoNet__c = idVivoNet ,CustomerTypes__c = customerTypes, LinesTypes__c = linesTypes, Segmentations__c = segmentations, SendSMS__c = Boolean.valueOf(sendSMS), Classification__c= classification, Channels__c= channels, CaseOpening__c = caseOpening, CaseReturn__c = caseReturn, CaseHandling__c= caseHandling, FormType__c = formType, SLA__c = sla, CustomerFeedback__c = customerFeedback, VisibleTo__C = visibleTo, CaseStatusGenTopic__c = caseStatusGenTopic);
		Database.insert(record, true);
        
        system.debug('this.key insertTopic..: '+ this.key);        
        this.mapTopicsDedup.put(this.key, record);
        
        String Id = record.Id;
        return Id;
    }    
    
    public void makeMapTopicsDedup(){   
		
        String serviceTree ='';
        
    	if(this.file=='LOJA' || this.file=='PALITOSLOJASBLOCO9' || this.file=='PALITOSLOJASRELEASEJULHO2024' || this.file=='PALITOSLOJASRELEASESETEMBRO2024'){
            serviceTree = 'Store';
        }else if(this.file=='CALLCENTER' || this.file=='PALITOSCALLCENTERBLOCO9' || this.file=='PALITOSCALLCENTERRELEASEJULHO2024' || this.file=='PALITOSCALLCENTERRELEASEJULHO2024V2' || this.file=='PALITOSCALLCENTERRELEASESETEMBRO2024'){
            serviceTree = 'Service';
        }
        System.debug('--------------------------------------');
        System.debug('makeMapTopicsDedup');
        List<CustomerInteractionTopicTree__c> lstTopicsDatabase = [SELECT id, ParentTopicId__c, Name, type__c from CustomerInteractionTopicTree__c where ProductType__c= 'Pre' and ServiceTree__c = :serviceTree and Active__c= true];
        
        for(CustomerInteractionTopicTree__c topic : lstTopicsDatabase) {
        	this.key = 'ParentTopicId__c='+topic.ParentTopicId__c+'|name='+topic.name+'|type__c='+topic.type__c;
            this.mapTopicsDedup.put(key, topic);
        }
        System.debug('Total Itens Map..: '+this.mapTopicsDedup.Size());
        System.debug('--------------------------------------');            
        this.key = '';
    } 
    
    /**
	* file: {LOJA,CALLCENTER,PALITOSLOJASBLOCO9,'PALITOSLOJASBLOCO9}
    */
    public TopicTree(String File, Integer QtyRecords, Integer PosRecord) {
        this.file = File;
        this.qtyRecords = QtyRecords;
        this.posRecord  = PosRecord;
    }

    public void ExecuteTopicTree() {   
        system.debug('file........:'+this.file);
        system.debug('qtyRecords..:'+this.qtyRecords);        
        system.debug('posRecord...:'+this.posRecord);
        
        makeMapTopicsDedup();
        
        StaticResource sr;
        if(file=='LOJA'){
            sr = getResourceLojaseRevendas();
        }else if(file=='CALLCENTER'){
            sr = getResourceCallCenter();            
        }else if(file=='PALITOSLOJASBLOCO9'){
            sr = getResourcestaticResourcePalitosLojasBloco9();
        }else if(file=='PALITOSCALLCENTERBLOCO9'){
            sr = getResourcestaticResourcePalitosCallCenterBloco9();
        }else if(file=='PALITOSLOJASRELEASEJULHO2024'){
            sr = getResourcestaticResourcePalitosLojasReleaseJulho2024();
        }else if(file=='PALITOSCALLCENTERRELEASEJULHO2024'){
            sr = getResourcestaticResourcePalitosCallCenterReleaseJulho2024();
        }else if(file=='PALITOSCALLCENTERRELEASEJULHO2024V2'){
            sr = getResourcestaticResourcePalitosCallCenterReleaseJulho2024V2();    
        }else if(file=='PALITOSLOJASRELEASESETEMBRO2024'){
            sr = getResourcestaticResourcePalitosLojasReleaseSetembro2024();
        }else if(file=='PALITOSCALLCENTERRELEASESETEMBRO2024'){
            sr = getResourcestaticResourcePalitosCallCenterReleaseSetembro2024();
        }
        if(sr != null && sr.Body != null) {
            String content = sr.Body.toString();
            
            System.debug('content: '+ JSON.serializePretty(content));
            
            if(content!= null) {
                //
                List<Topic> lstTopics = parse(content, this.qtyRecords, this.posRecord);
                //
                system.debug('Qtde elementos no JSON:'+ lstTopics.Size());
				//
                for(Topic topic : (List<Topic>) lstTopics) {
                    String IdLevel1=null;
                    String IdLevel2=null;
                    String IdLevel3=null;
                    String IdLevel4=null;
                    String IdLevel5=null;
                    
                    hasLevel0=(topic.Level0!='');
                    hasLevel1=(topic.Level1!='');
                    hasLevel2=(topic.Level2!='');
                    hasLevel3=(topic.Level3!='');
                    hasLevel4=(topic.Level4!='');
                    hasLevel5=(topic.Level5!='');
                    //
                    System.debug('--------------------------------------');
                    system.debug('SEQ...:'+ topic.SEQ);
                	system.debug('itens no listTopics'+ lstTopics.get(Integer.valueOf(topic.SEQ)));
                    //
                    if(topic.Type=='Pasta'){
                        system.debug('Pasta');
                        //
                        if(hasLevel0){ /* NIVEL 0 */ 
                            IdLevel0 = getId(null, topic.Level0,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null ); 
                            //
                            if(IdLevel0!=null && hasLevel1){ /* NIVEL 1 */
                                IdLevel1 = getId(IdLevel0 , topic.Level1,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                //
                                if(IdLevel1!=null && hasLevel2){ /* NIVEL 2 */
                                    IdLevel2 = getId(IdLevel1 , topic.Level2,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                    
                                    if(IdLevel2!=null && hasLevel3){ /* NIVEL 3 */
                                        IdLevel3 = getId(IdLevel2 , topic.Level3,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                        
                                        if(IdLevel3!=null && hasLevel4){ /* NIVEL 4 */
                                            IdLevel4 = getId(IdLevel3 , topic.Level4,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                            
                                            if(IdLevel4!=null && hasLevel5){ /* NIVEL 5 */
                                                IdLevel5 = getId(IdLevel4 , topic.Level5,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                                
                                            }		
                                        }   
                                    }
                                }
                            }
                        }
                    }else if(topic.Type=='Palito'){
                        system.debug('Palito');   
                        
                        if(hasLevel0){ /* NIVEL 0 */ 
                            String IdLevel0 = getId(null, topic.Level0,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                            //
                            if(IdLevel0!=null && hasLevel1){ /* NIVEL 1 */
                                if(hasLevel2){
                                    IdLevel1 = getId(IdLevel0 , topic.Level1,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                }else{
                                    IdLevel1 = getId(IdLevel0, topic.Level1, 'Palito', topic.IdVivoNet, topic.Classification, topic.SendSMS, topic.ProductType, topic.ServiceTree, topic.Active, topic.CustomerTypes, topic.LinesTypes, topic.Segmentations, topic.Channels,topic.RelationshipType, topic.CaseOpening, topic.CaseReturn, topic.CaseHandling, topic.FormType, topic.SLA, topic.CustomerFeedback, topic.VisibleTo, topic.CaseStatusGenTopic);
                                }
                                //
                                if(IdLevel1!=null && hasLevel2){ /* NIVEL 2 */
                                    if(hasLevel3){
                                        IdLevel2 = getId(IdLevel1 , topic.Level2,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                    }else{
                                        IdLevel2 = getId(IdLevel1, topic.Level2, 'Palito', topic.IdVivoNet, topic.Classification, topic.SendSMS, topic.ProductType, topic.ServiceTree, topic.Active, topic.CustomerTypes, topic.LinesTypes, topic.Segmentations, topic.Channels,topic.RelationshipType, topic.CaseOpening, topic.CaseReturn, topic.CaseHandling, topic.FormType, topic.SLA, topic.CustomerFeedback, topic.VisibleTo, topic.CaseStatusGenTopic);
                                    }                                        
                                    //
                                    if(IdLevel2!=null && hasLevel3){ /* NIVEL 3 */
                                        if(hasLevel4){
                                            IdLevel3 = getId(IdLevel2 , topic.Level3,'Pasta',null,null,null, topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                        }else{
                                            IdLevel3 = getId(IdLevel2, topic.Level3, 'Palito', topic.IdVivoNet, topic.Classification, topic.SendSMS, topic.ProductType, topic.ServiceTree, topic.Active, topic.CustomerTypes, topic.LinesTypes, topic.Segmentations, topic.Channels,topic.RelationshipType, topic.CaseOpening, topic.CaseReturn, topic.CaseHandling, topic.FormType, topic.SLA, topic.CustomerFeedback, topic.VisibleTo, topic.CaseStatusGenTopic);
                                        }                                        
                                        //
                                        if(IdLevel3!=null && hasLevel4){ /* NIVEL 4 */                                            
                                            if(hasLevel5){
                                                IdLevel4 = getId(IdLevel3 , topic.Level4,'Pasta',null,null,null,topic.ProductType, topic.ServiceTree, topic.Active,null,null,null,null,topic.RelationshipType, null, null, null, null, null, null, null, null);
                                            }else{
                                                IdLevel4 = getId(IdLevel3, topic.Level4, 'Palito', topic.IdVivoNet, topic.Classification, topic.SendSMS, topic.ProductType, topic.ServiceTree, topic.Active, topic.CustomerTypes, topic.LinesTypes, topic.Segmentations, topic.Channels,topic.RelationshipType, topic.CaseOpening, topic.CaseReturn, topic.CaseHandling, topic.FormType, topic.SLA, topic.CustomerFeedback, topic.VisibleTo, topic.CaseStatusGenTopic);
                                            }                                        
                                            //
                                            if(IdLevel4!=null && hasLevel5){ /* NIVEL 5 */
                                                IdLevel5 = getId(IdLevel4, topic.Level5, 'Palito', topic.IdVivoNet, topic.Classification, topic.SendSMS, topic.ProductType, topic.ServiceTree, topic.Active, topic.CustomerTypes, topic.LinesTypes, topic.Segmentations, topic.Channels,topic.RelationshipType, topic.CaseOpening, topic.CaseReturn, topic.CaseHandling, topic.FormType, topic.SLA, topic.CustomerFeedback, topic.VisibleTo, topic.CaseStatusGenTopic);
                                            }                                        
                                        }		
                                    }   
                                }
                            }
                        }
                    }
                }                    
            }
        }    
    }
}