force-app/main/default/objects/DisputedInvoice__c/DisputedInvoice__c.object-meta.xml
<CustomObject>
    <label>Fatura Contestada</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faturas Contestadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedInvoice__c/fields/case__c.field-meta.xml
<CustomField>
    <fullName>case__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Faturas Contestadas</relationshipLabel>
    <relationshipName>FaturasContestadas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DisputedInvoiceControllerTest.cls
@isTest
public with sharing class DisputedInvoiceControllerTest {
    @isTest
    public static void findByCaseIdTest(){
        Case nuCase = new Case();
        insert nuCase;

        DisputedInvoice__c nuInv = new DisputedInvoice__c();
        nuInv.case__c = nuCase.Id;
        insert nuInv;

        Test.startTest();
            DisputedInvoice__c result =  DisputedInvoiceController.findByCaseId(nuCase.Id);
        Test.stopTest();

        System.assert(result != null);
    }
}