force-app/main/default/objects/DisputedInvoice__c/DisputedInvoice__c.object-meta.xml
<CustomObject>
    <label>Fatura Contestada</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faturas Contestadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DisputedInvoice__c/fields/AccountHref__c.field-meta.xml
<CustomField>
    <fullName>AccountHref__c</fullName>
    <label>AccountHref</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/adjustedPaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>adjustedPaymentAmount__c</fullName>
    <label>Valor de Pagamento Ajustado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balanço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/BillingAccountId__c.field-meta.xml
<CustomField>
    <fullName>BillingAccountId__c</fullName>
    <label>Billing Account Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/billNo__c.field-meta.xml
<CustomField>
    <fullName>billNo__c</fullName>
    <label>Número da Bill</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/billOrigin__c.field-meta.xml
<CustomField>
    <fullName>billOrigin__c</fullName>
    <label>Origem da Fatura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/case__c.field-meta.xml
<CustomField>
    <fullName>case__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Faturas Contestadas</relationshipLabel>
    <relationshipName>FaturasContestadas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/FinancialAccountId__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccountId__c</fullName>
    <label>Financial Account Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/imageNo__c.field-meta.xml
<CustomField>
    <fullName>imageNo__c</fullName>
    <label>Número da Imagem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/invoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>invoiceNumber__c</fullName>
    <label>Número da Fatura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/l9CycleCloseDate__c.field-meta.xml
<CustomField>
    <fullName>l9CycleCloseDate__c</fullName>
    <label>Data de Encerramento do Ciclo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DisputedInvoice__c/fields/l9CycleStartDate__c.field-meta.xml
<CustomField>
    <fullName>l9CycleStartDate__c</fullName>
    <label>Data de Início do Ciclo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DisputedInvoiceDAO.cls
public with sharing class DisputedInvoiceDAO {

    public static DisputedInvoice__c findByCaseId(String caseId) {

        return [ 
        SELECT
            Id,
            Name,
            Status__c,
            invoiceNumber__c,
            case__r.AccountId,
            billNo__c,
            billOrigin__c,
            imageNo__c,
            l9CycleCloseDate__c,
            l9CycleStartDate__c, 
            amount__c,
            FinancialAccountId__c,
            BillingAccountId__c,
            Balance__c,
            adjustedPaymentAmount__c,
            AccountHref__c
            from DisputedInvoice__c
        where case__c =: caseId
        Limit 1];
    }
}