force-app/main/default/objects/Asset/recordTypes/Fixa.recordType-meta.xml
<RecordType>
    <fullName>Fixa</fullName>
    <active>true</active>
    <description>Produtos contratados do tipo fixo</description>
    <label>Fixa</label>
</RecordType>

force-app/main/default/objects/Webservice__c/Webservice__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings criado para construção das APIs.</description>
    <label>Webservice</label>
</CustomObject>

force-app/main/default/objects/Webservice__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/SubscriptionKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionKey__c</fullName>
    <label>Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <label>Validade dos dados da consulta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MassiveFixedCaseRequestTest.cls
@IsTest
public class MassiveFixedCaseRequestTest {
	
	@TestSetup
	static void setup(){
        Account lAccount = DataFactory.createAccount();
        insert lAccount;

        Account lBillingAccountFixed = DataFactory.createBillingAccount(lAccount.Id, 'Fixa');
        insert lBillingAccountFixed;

        Asset asset = DataFactory.createAsset(lAccount.Id, 'Fixa');
        insert asset;

        insert new Webservice__c(
            Name = 'MassiveFixedCallout',
            Endpoint__c  = 'https://hmlapi.telefonicabigdata.com',
            SubscriptionKey__c = 'd1ca8d57a2984db88f01c9ce7b5862e2',
			Validate__c = 15
        );
        
        WebServiceTestFactory.start().authOAuthProvider().create();
    }


	@IsTest
	static void execute(){
		Map<String, object> mapResult = new Map<string, Object>();
		String requestBody;
		Asset asset = [ SELECT  Id FROM Asset LIMIT 1];
		
        Test.startTest();
			MassiveFixedCaseCallout.execute(mapResult, asset.Id);   
			requestBody = new MassiveFixedCaseRequest(asset.Id, 'MassiveFixedCallout').createRequestStructure().toJson();
		Test.stopTest();
		System.assert(mapResult != null, 'O mapa de resposta não foi preenchido');
		System.assert(!String.isBlank(requestBody) , 'O contrato de request não foi preenchido');

	}

}