force-app/main/default/objects/CanvasHybrisMigration__mdt/CanvasHybrisMigration__mdt.object-meta.xml
<CustomObject>
    <description>Metadado responsável por controle de acesso do fluxo de migração hybris.</description>
    <label>Fluxo Migração Hybris</label>
    <pluralLabel>Fluxos de Migrações Hybris</pluralLabel>
</CustomObject>

force-app/main/default/objects/CanvasHybrisMigration__mdt/fields/HasAccessToHybrisMigration__c.field-meta.xml
<CustomField>
    <fullName>HasAccessToHybrisMigration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo define se o papel possui acesso ao fluxo de migração hybris</description>
    <inlineHelpText>Marcado = Tem acesso, Desmarcado = Não tem acesso</inlineHelpText>
    <label>Tem acesso ao fluxo de migração hybris?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CanvasHybrisMigration__mdt/fields/OriginApiName__c.field-meta.xml
<CustomField>
    <fullName>OriginApiName__c</fullName>
    <description>Campo com o DeveloperName do papel do usuário interno ou PartnerGroup__c para usuários externos. Utilizado para o mapeamento &quot;De x Para&quot;.</description>
    <inlineHelpText>DeveloperName do papel do usuário interno ou PartnerGroup__c para usuários externos.</inlineHelpText>
    <label>API name origem</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CanvasHybrisMigration__mdt/fields/UserLicense__c.field-meta.xml
<CustomField>
    <fullName>UserLicense__c</fullName>
    <description>Campo para mostrar se o papel diz respeito a usuário interno ou externo.</description>
    <inlineHelpText>Tipo de licença do usuário: &quot;Salesforce&quot;, &quot;Partner Community&quot;, etc</inlineHelpText>
    <label>Licença do usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CanvasHybrisMigration__mdt/fields/UserSegment__c.field-meta.xml
<CustomField>
    <fullName>UserSegment__c</fullName>
    <description>Campo que indica o segmento de atendimento do usuário</description>
    <inlineHelpText>Segmento que o operador está atribuído (Púrpura, Gold, Platinum, Silver, V)</inlineHelpText>
    <label>Segmento do Usuário</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purpura</fullName>
                <default>true</default>
                <label>Purpura</label>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Vivo V</fullName>
            </value>
            <value>
                <fullName>Ouvidoria</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Omnichannel</fullName>
            </value>
            <value>
                <fullName>PAP</fullName>
            </value>
            <value>
                <fullName>Revenda</fullName>
            </value>
            <value>
                <fullName>Suporte a Lojas</fullName>
            </value>
            <value>
                <fullName>Televendas</fullName>
            </value>
            <value>
                <fullName>Atendimento</fullName>
            </value>
            <value>
                <fullName>Backoffice</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Retencao</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CanvasHybrisMigrationDAO.cls
public with sharing class CanvasHybrisMigrationDAO {

    public static List<CanvasHybrisMigration__mdt> getAll(String userRole){
        return[
            SELECT 
                Id,
                OriginApiName__c,
                UserLicense__c,
                UserSegment__c,
                HasAccessToHybrisMigration__c
            FROM 
                CanvasHybrisMigration__mdt
            WHERE
                OriginApiName__c = :userRole
        ];
    }
    public static CanvasHybrisMigration__mdt getAccessToCanvas(String userRole){ 

        CanvasHybrisMigration__mdt chmObject = [
            SELECT
                HasAccessToHybrisMigration__c
            FROM 
                CanvasHybrisMigration__mdt
            WHERE
                OriginApiName__c = :userRole
            LIMIT 1 
        ];

    return chmObject !=null ? chmObject : null;

    }    
}